Run the following command in the terminal:

sbatch --gpus=1 --gres=gpumem:10g --time=05:00:00 --mem-per-cpu=32g --wrap="jupyter nbconvert --to notebook --execute 02_251218_optimizing_number_of_clusters_Apertus-8B-Instruct.ipynb --inplace"

In [1]:
import os
import json
import pandas as pd

directory_path = "./251030_generated_descriptions_Apertus-8B-Instruct-2509s"
data_list = []
# Iterate through all files in the directory
for filename in os.listdir(directory_path):
    if filename.endswith('.json'):
        file_path = os.path.join(directory_path, filename)
        with open(file_path, 'r', encoding='utf-8') as file:
            try:
                data = json.load(file)
                # Ensure it's a dict with 4 key-value pairs
                if isinstance(data, dict):
                    if data["data_point"] == "":
                        print(f"Skipping {filename}, data point empty")
                    
                        continue
                    data_list.append(data)
                else:
                    print(f"Skipping {filename}")
            except json.JSONDecodeError:
                print(f"Skipping {filename}: invalid JSON format.")
                
# Convert list of dicts to DataFrame
df = pd.DataFrame(data_list)
df.tail()

,question,original_source,data_group,data_point,reference_1,reference_2,description,references
2005,What is the meaning of eco-toxicity in relatio...,CPR 2024.pdf,essential environmental characteristics,eco-toxicity,CPR 2024.pdf,BAMB 2019.pdf,Eco-toxicity refers to the harmful effects of...,[{'text': 'ANNEX II Predetermined environmenta...
2006,What is the meaning of freshwater in relation ...,CPR 2024.pdf,essential environmental characteristics,freshwater,CPR 2024.pdf,CPR 2024.pdf,(g) eutrophication aquatic freshwater; \nThis...,[{'text': 'ANNEX II Predetermined environmenta...
2007,What is the meaning of human toxicity cancerog...,CPR 2024.pdf,essential environmental characteristics,human toxicity cancerogenic,CPR 2024.pdf,BAMB 2019.pdf,"Human toxicity, cancerogenic refers to the po...",[{'text': 'ANNEX II Predetermined environmenta...
2008,What is the meaning of human toxicity non-canc...,CPR 2024.pdf,essential environmental characteristics,human toxicity non-cancerogenic,CPR 2024.pdf,BAMB 2019.pdf,Human toxicity non-cancerogenic refers to the...,[{'text': 'ANNEX II Predetermined environmenta...
2009,What is the meaning of land use related impact...,CPR 2024.pdf,essential environmental characteristics,land use related impacts,CPR 2024.pdf,Kebede 2024.pdf,Land use related impacts refer to the effects...,[{'text': 'ANNEX II Predetermined environmenta...

In [3]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import make_scorer
from sentence_transformers import SentenceTransformer


model = SentenceTransformer('./cluster/scratch/svangelova')
description_embeddings = model.encode(df["data_point"])

In [9]:
import numpy as np
import pandas as pd
import logging
from collections.abc import Iterable
from scipy.sparse import csr_matrix
from scipy.spatial.distance import squareform
from typing import Optional, Union, Tuple


def select_topic_representation(
    ctfidf_embeddings,
    embeddings,
    use_ctfidf: bool = True,
    output_ndarray: bool = False,
):
    """Select the topic representation.

    Arguments:
        ctfidf_embeddings: The c-TF-IDF embedding matrix
        embeddings: The topic embedding matrix
        use_ctfidf: Whether to use the c-TF-IDF representation. If False, topics embedding representation is used, if it
                    exists. Default is True.
        output_ndarray: Whether to convert the selected representation into ndarray
    Raises
        ValueError:
            - If no topic representation was found
            - If c-TF-IDF embeddings are not a numpy array or a scipy.sparse.csr_matrix

    Returns:
        The selected topic representation and a boolean indicating whether it is c-TF-IDF.
    """

    def to_ndarray(array: Union[np.ndarray, csr_matrix]) -> np.ndarray:
        if isinstance(array, csr_matrix):
            return array.toarray()
        return array
    if use_ctfidf:
        if ctfidf_embeddings is None:
            repr_, ctfidf_used = embeddings, False
        else:
            repr_, ctfidf_used = ctfidf_embeddings, True
    else:
        if embeddings is None:
            repr_, ctfidf_used = ctfidf_embeddings, True
        else:
            repr_, ctfidf_used = embeddings, False

    return to_ndarray(repr_) if output_ndarray else repr_, ctfidf_used


def validate_distance_matrix(X, n_samples):
    """Validate the distance matrix and convert it to a condensed distance matrix
    if necessary.

    A valid distance matrix is either a square matrix of shape (n_samples, n_samples)
    with zeros on the diagonal and non-negative values or condensed distance matrix
    of shape (n_samples * (n_samples - 1) / 2,) containing the upper triangular of the
    distance matrix.

    Arguments:
        X: Distance matrix to validate.
        n_samples: Number of samples in the dataset.

    Returns:
        X: Validated distance matrix.

    Raises:
        ValueError: If the distance matrix is not valid.
    """
    # Make sure it is the 1-D condensed distance matrix with zeros on the diagonal
    s = X.shape
    if len(s) == 1:
        # check it has correct size
        n = s[0]
        if n != (n_samples * (n_samples - 1) / 2):
            raise ValueError("The condensed distance matrix must have " "shape (n*(n-1)/2,).")
    elif len(s) == 2:
        # check it has correct size
        if (s[0] != n_samples) or (s[1] != n_samples):
            raise ValueError("The distance matrix must be of shape " "(n, n) where n is the number of samples.")
        # force zero diagonal and convert to condensed
        np.fill_diagonal(X, 0)
        X = squareform(X)
    else:
        raise ValueError(
            "The distance matrix must be either a 1-D condensed "
            "distance matrix of shape (n*(n-1)/2,) or a "
            "2-D square distance matrix of shape (n, n)."
            "where n is the number of documents."
            "Got a distance matrix of shape %s" % str(s)
        )

    # Make sure its entries are non-negative
    if np.any(X < 0):
        raise ValueError("Distance matrix cannot contain negative values.")

    return X

In [12]:
import optuna
import hdbscan
import numpy as np
from umap import UMAP
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.vectorizers import ClassTfidfTransformer
from sklearn.datasets import fetch_20newsgroups
from scipy.cluster import hierarchy as sch
from scipy.cluster.hierarchy import linkage, cophenet
from scipy.spatial.distance import pdist
from hdbscan.validity import validity_index
from sklearn.metrics.pairwise import cosine_similarity

def calculate_ccc(topic_model, docs):
    # Hierarchical topics
    linkage_function = lambda x: sch.linkage(x, "ward", optimal_ordering=True)
    _distance_function = lambda x: 1 - cosine_similarity(x)
    
    hierarchical_topics = topic_model.hierarchical_topics(docs, 
                                                          linkage_function=linkage_function, 
                                                          distance_function=_distance_function, 
                                                          use_ctfidf=True)
    
    # Select topic embeddings
    use_ctfidf = True

    # Calculate distance
    embeddings = select_topic_representation(topic_model.c_tf_idf_, topic_model.topic_embeddings_, use_ctfidf)[0][
        topic_model._outliers :
    ]
    distance_function = lambda x: validate_distance_matrix(_distance_function(x), embeddings.shape[0])
    
    dists = distance_function(embeddings)
    linkage_matrix = linkage_function(dists)

    ccc_score, _ = cophenet(linkage_matrix, dists)

    if np.isnan(ccc_score):
        return 0.0

    return ccc_score


ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

def objective(trial, docs, embeddings):
    # --- Hyperparameters to Optimize ---
    
    # UMAP Parameters
    n_neighbors = trial.suggest_int('n_neighbors', 2, 50)
    n_components = trial.suggest_int('n_components', 2, 15)
    min_dist = trial.suggest_float("min_dist", 0.0, 0.3, step=0.01)
    
    # HDBSCAN Parameters
    min_cluster_size = trial.suggest_int('min_cluster_size', 2, 50)
    min_samples = trial.suggest_int('min_samples', 1, 20)
    cluster_selection_epsilon = trial.suggest_float("cluster_selection_epsilon", 0.0, 0.3, step=0.01)
    
    # --- Model Initialization ---
    
    umap_model = UMAP(
        n_neighbors=n_neighbors,
        n_components=n_components,
        min_dist=min_dist,
        metric='cosine',
        random_state=42,
        n_jobs=1 #important for reproducability
    )

    
    hdbscan_model = hdbscan.HDBSCAN(
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        cluster_selection_epsilon=cluster_selection_epsilon,
        metric="euclidean",  
        cluster_selection_method='eom'
    )
    
    topic_model = BERTopic(
        hdbscan_model=hdbscan_model,
        vectorizer_model=CountVectorizer(stop_words='english'),
        ctfidf_model=ctfidf_model, 
        umap_model=umap_model,
        calculate_probabilities=False
        )

    topic_model.fit(docs, embeddings)

    labels = topic_model.get_document_info(docs).Topic
    mask = labels != -1
    n_clusters = len(np.unique(labels[mask]))
    emb_umap = topic_model.umap_model.embedding_
    
    emb_masked = np.ascontiguousarray(emb_umap[mask], dtype=np.float64)
    labels_masked = np.ascontiguousarray(labels[mask], dtype=np.int32)

    dbcv_score = validity_index(emb_masked, labels_masked, metric='euclidean')
    ccc_score = calculate_ccc(topic_model, docs)

    
    # logging for visibility
    print(f"Trial {trial.number}: DBCV={dbcv_score:.3f}, CCC={ccc_score:.3f}")

    # ---- Outlier ratio (fraction of points labeled -1)
    outlier_ratio =  outlier_ratio = np.mean(labels == -1)

    # Store the custom metrics in Optuna
    trial.set_user_attr("dbcv_score", dbcv_score)
    trial.set_user_attr("ccc_score", ccc_score)
    trial.set_user_attr("outlier_ratio", outlier_ratio)
    trial.set_user_attr("n_clusters", n_clusters)

    # Create directory if it doesn't exist
    os.makedirs("optuna_models/data_point_names", exist_ok=True)
    
    # Save model (safely serialization)
    model_name = f"optuna_models/data_point_names/251222_trial_{trial.number}_model"
    topic_model.save(model_name, serialization="safetensors", save_ctfidf=True)

    return ccc_score, dbcv_score

In [13]:
# 2. Run Multi-Objective Optimization
# Note: 'directions' list matches the return tuple order (DBCV, CCC)
study = optuna.create_study(directions=['maximize', 'maximize'])

study.optimize(lambda trial: objective(trial, df["data_point"], description_embeddings), n_trials=300, show_progress_bar=True)

[I 2025-12-22 19:33:23,040] A new study created in memory with name: no-name-501415c1-3b7a-4862-8ea7-463fb6560d60

  0%|          | 0/300 [00:00<?, ?it/s]

100%|██████████| 13/13 [00:00<00:00, 410.45it/s]

Trial 0: DBCV=0.185, CCC=0.710
[I 2025-12-22 19:33:33,929] Trial 0 finished with values: [0.7095179582375415, 0.18460052253707745] and parameters: {'n_neighbors': 38, 'n_components': 11, 'min_dist': 0.02, 'min_cluster_size': 44, 'min_samples': 1, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 19/19 [00:00<00:00, 388.84it/s]

Trial 1: DBCV=0.346, CCC=0.509
[I 2025-12-22 19:33:43,187] Trial 1 finished with values: [0.5090682860111985, 0.3461837711390894] and parameters: {'n_neighbors': 8, 'n_components': 10, 'min_dist': 0.0, 'min_cluster_size': 45, 'min_samples': 5, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 9/9 [00:00<00:00, 416.89it/s]

Trial 2: DBCV=0.210, CCC=0.683
[I 2025-12-22 19:33:53,694] Trial 2 finished with values: [0.6828093631559072, 0.21007075689329957] and parameters: {'n_neighbors': 25, 'n_components': 11, 'min_dist': 0.22, 'min_cluster_size': 43, 'min_samples': 13, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 29/29 [00:00<00:00, 400.53it/s]

Trial 3: DBCV=0.274, CCC=0.565
[I 2025-12-22 19:34:04,784] Trial 3 finished with values: [0.5645013842391405, 0.27398797744166214] and parameters: {'n_neighbors': 42, 'n_components': 11, 'min_dist': 0.1, 'min_cluster_size': 23, 'min_samples': 1, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 1/1 [00:00<00:00, 340.25it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 4: DBCV=0.040, CCC=0.000
[I 2025-12-22 19:34:14,413] Trial 4 finished with values: [0.0, 0.03958129686881891] and parameters: {'n_neighbors': 24, 'n_components': 2, 'min_dist': 0.04, 'min_cluster_size': 32, 'min_samples': 14, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 10/10 [00:00<00:00, 417.20it/s]

Trial 5: DBCV=0.371, CCC=0.644
[I 2025-12-22 19:34:26,050] Trial 5 finished with values: [0.6442235885036709, 0.370873687621316] and parameters: {'n_neighbors': 48, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 45, 'min_samples': 10, 'cluster_selection_epsilon': 0.01}.

  0%|          | 0/52 [00:00<?, ?it/s]
100%|██████████| 52/52 [00:00<00:00, 398.02it/s]

Trial 6: DBCV=0.657, CCC=0.377
[I 2025-12-22 19:34:36,767] Trial 6 finished with values: [0.37705320061028824, 0.6571015449833463] and parameters: {'n_neighbors': 30, 'n_components': 10, 'min_dist': 0.0, 'min_cluster_size': 12, 'min_samples': 12, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 2/2 [00:00<00:00, 376.14it/s]

Trial 7: DBCV=0.302, CCC=0.937
[I 2025-12-22 19:34:46,574] Trial 7 finished with values: [0.9366249027571225, 0.30214152049958665] and parameters: {'n_neighbors': 14, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 50, 'min_samples': 5, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 27/27 [00:00<00:00, 399.15it/s]

Trial 8: DBCV=0.508, CCC=0.583
[I 2025-12-22 19:34:57,210] Trial 8 finished with values: [0.582907491735777, 0.5082633478606688] and parameters: {'n_neighbors': 26, 'n_components': 12, 'min_dist': 0.15, 'min_cluster_size': 23, 'min_samples': 9, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 24/24 [00:00<00:00, 409.23it/s]

Trial 9: DBCV=0.167, CCC=0.557
[I 2025-12-22 19:35:07,664] Trial 9 finished with values: [0.5567175644982406, 0.16687146197747857] and parameters: {'n_neighbors': 31, 'n_components': 7, 'min_dist': 0.3, 'min_cluster_size': 27, 'min_samples': 1, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 26/26 [00:00<00:00, 406.99it/s]

Trial 10: DBCV=0.561, CCC=0.485
[I 2025-12-22 19:35:16,957] Trial 10 finished with values: [0.48481118071073975, 0.5609698508077449] and parameters: {'n_neighbors': 6, 'n_components': 13, 'min_dist': 0.12, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 234.32it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 11: DBCV=0.179, CCC=0.000
[I 2025-12-22 19:35:28,310] Trial 11 finished with values: [0.0, 0.179010762548266] and parameters: {'n_neighbors': 38, 'n_components': 12, 'min_dist': 0.15, 'min_cluster_size': 30, 'min_samples': 14, 'cluster_selection_epsilon': 0.3}.

  0%|          | 0/55 [00:00<?, ?it/s]
100%|██████████| 55/55 [00:00<00:00, 406.99it/s]

Trial 12: DBCV=0.201, CCC=0.374
[I 2025-12-22 19:35:37,654] Trial 12 finished with values: [0.37358369772011163, 0.2008909561808017] and parameters: {'n_neighbors': 12, 'n_components': 2, 'min_dist': 0.14, 'min_cluster_size': 11, 'min_samples': 1, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 37/37 [00:00<00:00, 415.59it/s]

Trial 13: DBCV=0.543, CCC=0.397
[I 2025-12-22 19:35:48,092] Trial 13 finished with values: [0.3973471088989137, 0.5434214264984435] and parameters: {'n_neighbors': 19, 'n_components': 12, 'min_dist': 0.03, 'min_cluster_size': 18, 'min_samples': 9, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 22/22 [00:00<00:00, 390.52it/s]

Trial 14: DBCV=0.408, CCC=0.544
[I 2025-12-22 19:35:58,790] Trial 14 finished with values: [0.5435041983365233, 0.40823640081110907] and parameters: {'n_neighbors': 38, 'n_components': 7, 'min_dist': 0.23, 'min_cluster_size': 24, 'min_samples': 11, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 11/11 [00:00<00:00, 424.23it/s]

Trial 15: DBCV=0.183, CCC=0.645
[I 2025-12-22 19:36:08,894] Trial 15 finished with values: [0.6447130325719805, 0.1828582841114245] and parameters: {'n_neighbors': 16, 'n_components': 12, 'min_dist': 0.27, 'min_cluster_size': 46, 'min_samples': 3, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 28/28 [00:00<00:00, 431.87it/s]

Trial 16: DBCV=0.522, CCC=0.437
[I 2025-12-22 19:36:17,199] Trial 16 finished with values: [0.4368616235741087, 0.5224917956921505] and parameters: {'n_neighbors': 3, 'n_components': 10, 'min_dist': 0.19, 'min_cluster_size': 10, 'min_samples': 20, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 20/20 [00:00<00:00, 429.10it/s]

Trial 17: DBCV=0.463, CCC=0.567
[I 2025-12-22 19:36:28,379] Trial 17 finished with values: [0.566597750359763, 0.4628475604834819] and parameters: {'n_neighbors': 44, 'n_components': 12, 'min_dist': 0.1, 'min_cluster_size': 22, 'min_samples': 14, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 28/28 [00:00<00:00, 409.95it/s]

Trial 18: DBCV=0.330, CCC=0.452
[I 2025-12-22 19:36:40,475] Trial 18 finished with values: [0.45177032344629625, 0.329701966714764] and parameters: {'n_neighbors': 48, 'n_components': 15, 'min_dist': 0.02, 'min_cluster_size': 22, 'min_samples': 1, 'cluster_selection_epsilon': 0.27}.

  0%|          | 0/52 [00:00<?, ?it/s]
100%|██████████| 52/52 [00:00<00:00, 400.89it/s]

Trial 19: DBCV=0.517, CCC=0.436
[I 2025-12-22 19:36:50,703] Trial 19 finished with values: [0.43604041143968686, 0.5165072868360912] and parameters: {'n_neighbors': 23, 'n_components': 8, 'min_dist': 0.3, 'min_cluster_size': 12, 'min_samples': 9, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 30/30 [00:00<00:00, 412.85it/s]

Trial 20: DBCV=0.546, CCC=0.497
[I 2025-12-22 19:37:01,286] Trial 20 finished with values: [0.4969005751636483, 0.5457271128974276] and parameters: {'n_neighbors': 40, 'n_components': 8, 'min_dist': 0.06, 'min_cluster_size': 13, 'min_samples': 16, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 15/15 [00:00<00:00, 387.56it/s]

Trial 21: DBCV=0.350, CCC=0.647
[I 2025-12-22 19:37:11,156] Trial 21 finished with values: [0.6471980759776347, 0.34966688029786486] and parameters: {'n_neighbors': 32, 'n_components': 4, 'min_dist': 0.04, 'min_cluster_size': 32, 'min_samples': 19, 'cluster_selection_epsilon': 0.28}.

100%|██████████| 12/12 [00:00<00:00, 382.90it/s]

Trial 22: DBCV=0.365, CCC=0.742
[I 2025-12-22 19:37:21,436] Trial 22 finished with values: [0.74173236285244, 0.3650378081900496] and parameters: {'n_neighbors': 41, 'n_components': 5, 'min_dist': 0.18, 'min_cluster_size': 37, 'min_samples': 13, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 13/13 [00:00<00:00, 421.81it/s]

Trial 23: DBCV=0.294, CCC=0.594
[I 2025-12-22 19:37:30,098] Trial 23 finished with values: [0.5935100328172753, 0.2941575271199372] and parameters: {'n_neighbors': 4, 'n_components': 12, 'min_dist': 0.03, 'min_cluster_size': 44, 'min_samples': 11, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 4/4 [00:00<00:00, 297.31it/s]

Trial 24: DBCV=-0.011, CCC=0.869
[I 2025-12-22 19:37:40,323] Trial 24 finished with values: [0.8694213079799196, -0.010711028968181262] and parameters: {'n_neighbors': 48, 'n_components': 4, 'min_dist': 0.2, 'min_cluster_size': 48, 'min_samples': 17, 'cluster_selection_epsilon': 0.04}.

  0%|          | 0/139 [00:00<?, ?it/s]
 34%|███▍      | 47/139 [00:00<00:00, 461.42it/s]
 68%|██████▊   | 94/139 [00:00<00:00, 436.01it/s]
100%|██████████| 139/139 [00:00<00:00, 421.87it/s]

Trial 25: DBCV=0.529, CCC=0.259
[I 2025-12-22 19:37:52,086] Trial 25 finished with values: [0.25851053340127944, 0.5288825158740776] and parameters: {'n_neighbors': 48, 'n_components': 6, 'min_dist': 0.17, 'min_cluster_size': 5, 'min_samples': 3, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 30/30 [00:00<00:00, 408.83it/s]

Trial 26: DBCV=0.178, CCC=0.526
[I 2025-12-22 19:38:02,604] Trial 26 finished with values: [0.52645912831722, 0.17775303800839035] and parameters: {'n_neighbors': 37, 'n_components': 8, 'min_dist': 0.25, 'min_cluster_size': 24, 'min_samples': 1, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 25/25 [00:00<00:00, 396.05it/s]

Trial 27: DBCV=0.543, CCC=0.484
[I 2025-12-22 19:38:12,541] Trial 27 finished with values: [0.4842429817862128, 0.5433830863580347] and parameters: {'n_neighbors': 31, 'n_components': 4, 'min_dist': 0.07, 'min_cluster_size': 4, 'min_samples': 20, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 33/33 [00:00<00:00, 415.01it/s]

Trial 28: DBCV=0.599, CCC=0.535
[I 2025-12-22 19:38:22,369] Trial 28 finished with values: [0.5354233726860151, 0.5989175807469301] and parameters: {'n_neighbors': 28, 'n_components': 4, 'min_dist': 0.1, 'min_cluster_size': 2, 'min_samples': 20, 'cluster_selection_epsilon': 0.1}.

  0%|          | 0/56 [00:00<?, ?it/s]
100%|██████████| 56/56 [00:00<00:00, 406.01it/s]

Trial 29: DBCV=0.619, CCC=0.414
[I 2025-12-22 19:38:32,827] Trial 29 finished with values: [0.4139396402375066, 0.6190642800001184] and parameters: {'n_neighbors': 14, 'n_components': 13, 'min_dist': 0.13, 'min_cluster_size': 9, 'min_samples': 12, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 28/28 [00:00<00:00, 407.94it/s]

Trial 30: DBCV=0.595, CCC=0.514
[I 2025-12-22 19:38:44,020] Trial 30 finished with values: [0.5143716450834392, 0.5949377285109829] and parameters: {'n_neighbors': 25, 'n_components': 15, 'min_dist': 0.12, 'min_cluster_size': 16, 'min_samples': 18, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/50 [00:00<?, ?it/s]
100%|██████████| 50/50 [00:00<00:00, 397.98it/s]

Trial 31: DBCV=0.479, CCC=0.383
[I 2025-12-22 19:38:53,941] Trial 31 finished with values: [0.3826164857659351, 0.47908445811611] and parameters: {'n_neighbors': 16, 'n_components': 8, 'min_dist': 0.25, 'min_cluster_size': 14, 'min_samples': 7, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 26/26 [00:00<00:00, 408.04it/s]

Trial 32: DBCV=0.513, CCC=0.546
[I 2025-12-22 19:39:05,337] Trial 32 finished with values: [0.5463630526322015, 0.5132199336961213] and parameters: {'n_neighbors': 48, 'n_components': 12, 'min_dist': 0.11, 'min_cluster_size': 5, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 37/37 [00:00<00:00, 417.09it/s]

Trial 33: DBCV=0.216, CCC=0.481
[I 2025-12-22 19:39:15,062] Trial 33 finished with values: [0.4808021115344886, 0.2160753673052633] and parameters: {'n_neighbors': 25, 'n_components': 3, 'min_dist': 0.24, 'min_cluster_size': 17, 'min_samples': 3, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 21/21 [00:00<00:00, 428.28it/s]

Trial 34: DBCV=0.423, CCC=0.490
[I 2025-12-22 19:39:27,151] Trial 34 finished with values: [0.48966989073197104, 0.42259603957661457] and parameters: {'n_neighbors': 48, 'n_components': 15, 'min_dist': 0.18, 'min_cluster_size': 21, 'min_samples': 14, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 16/16 [00:00<00:00, 426.31it/s]

Trial 35: DBCV=0.407, CCC=0.664
[I 2025-12-22 19:39:37,880] Trial 35 finished with values: [0.6643818047786467, 0.40734487267817315] and parameters: {'n_neighbors': 46, 'n_components': 8, 'min_dist': 0.09, 'min_cluster_size': 27, 'min_samples': 14, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 13/13 [00:00<00:00, 424.55it/s]

Trial 36: DBCV=0.355, CCC=0.677
[I 2025-12-22 19:39:49,445] Trial 36 finished with values: [0.6768767678871128, 0.354820338882532] and parameters: {'n_neighbors': 32, 'n_components': 15, 'min_dist': 0.05, 'min_cluster_size': 44, 'min_samples': 3, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 33/33 [00:00<00:00, 413.22it/s]

Trial 37: DBCV=0.268, CCC=0.459
[I 2025-12-22 19:39:59,240] Trial 37 finished with values: [0.4590028891455171, 0.26795684849616264] and parameters: {'n_neighbors': 29, 'n_components': 3, 'min_dist': 0.24, 'min_cluster_size': 19, 'min_samples': 4, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 3/3 [00:00<00:00, 242.71it/s]

Trial 38: DBCV=0.169, CCC=0.964
[I 2025-12-22 19:40:08,750] Trial 38 finished with values: [0.9644223118872992, 0.16896695242403276] and parameters: {'n_neighbors': 7, 'n_components': 11, 'min_dist': 0.29, 'min_cluster_size': 25, 'min_samples': 15, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 25/25 [00:00<00:00, 393.52it/s]

Trial 39: DBCV=0.562, CCC=0.428
[I 2025-12-22 19:40:16,773] Trial 39 finished with values: [0.4282313522417341, 0.5622086042613124] and parameters: {'n_neighbors': 3, 'n_components': 3, 'min_dist': 0.17, 'min_cluster_size': 18, 'min_samples': 19, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 14/14 [00:00<00:00, 383.11it/s]

Trial 40: DBCV=0.237, CCC=0.636
[I 2025-12-22 19:40:26,844] Trial 40 finished with values: [0.6358089515282058, 0.2366367551588023] and parameters: {'n_neighbors': 23, 'n_components': 7, 'min_dist': 0.15, 'min_cluster_size': 40, 'min_samples': 4, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 13/13 [00:00<00:00, 424.83it/s]

Trial 41: DBCV=-0.170, CCC=0.593
[I 2025-12-22 19:40:36,785] Trial 41 finished with values: [0.5925273976048965, -0.17033757196991692] and parameters: {'n_neighbors': 47, 'n_components': 2, 'min_dist': 0.17, 'min_cluster_size': 34, 'min_samples': 4, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 23/23 [00:00<00:00, 426.86it/s]

Trial 42: DBCV=0.520, CCC=0.624
[I 2025-12-22 19:40:46,975] Trial 42 finished with values: [0.6244039864544179, 0.5197554678187487] and parameters: {'n_neighbors': 37, 'n_components': 5, 'min_dist': 0.01, 'min_cluster_size': 20, 'min_samples': 19, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 35/35 [00:00<00:00, 435.53it/s]

Trial 43: DBCV=0.523, CCC=0.543
[I 2025-12-22 19:40:57,384] Trial 43 finished with values: [0.543137260391728, 0.522606232818614] and parameters: {'n_neighbors': 14, 'n_components': 14, 'min_dist': 0.26, 'min_cluster_size': 13, 'min_samples': 14, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 6/6 [00:00<00:00, 411.57it/s]

Trial 44: DBCV=0.359, CCC=0.660
[I 2025-12-22 19:41:07,286] Trial 44 finished with values: [0.6601139305582805, 0.35924976893768584] and parameters: {'n_neighbors': 8, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 14, 'min_samples': 16, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 380.44it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 45: DBCV=0.145, CCC=0.000
[I 2025-12-22 19:41:16,445] Trial 45 finished with values: [0.0, 0.1449691103545816] and parameters: {'n_neighbors': 5, 'n_components': 11, 'min_dist': 0.3, 'min_cluster_size': 50, 'min_samples': 13, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 2/2 [00:00<00:00, 357.56it/s]

Trial 46: DBCV=0.050, CCC=0.736
[I 2025-12-22 19:41:25,566] Trial 46 finished with values: [0.735556222888268, 0.050170510284338846] and parameters: {'n_neighbors': 6, 'n_components': 10, 'min_dist': 0.22, 'min_cluster_size': 45, 'min_samples': 10, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 16/16 [00:00<00:00, 422.39it/s]

Trial 47: DBCV=0.321, CCC=0.629
[I 2025-12-22 19:41:36,898] Trial 47 finished with values: [0.6290524399951449, 0.32109571712600016] and parameters: {'n_neighbors': 34, 'n_components': 14, 'min_dist': 0.19, 'min_cluster_size': 38, 'min_samples': 7, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 23/23 [00:00<00:00, 380.81it/s]

Trial 48: DBCV=0.445, CCC=0.490
[I 2025-12-22 19:41:47,374] Trial 48 finished with values: [0.49048568512067015, 0.445007029759171] and parameters: {'n_neighbors': 50, 'n_components': 5, 'min_dist': 0.27, 'min_cluster_size': 19, 'min_samples': 13, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 16/16 [00:00<00:00, 370.16it/s]

Trial 49: DBCV=0.356, CCC=0.589
[I 2025-12-22 19:41:57,552] Trial 49 finished with values: [0.5892204974396421, 0.3559386445576182] and parameters: {'n_neighbors': 25, 'n_components': 7, 'min_dist': 0.15, 'min_cluster_size': 39, 'min_samples': 3, 'cluster_selection_epsilon': 0.04}.

  0%|          | 0/73 [00:00<?, ?it/s]
100%|██████████| 73/73 [00:00<00:00, 414.50it/s]

Trial 50: DBCV=0.611, CCC=0.340
[I 2025-12-22 19:42:07,698] Trial 50 finished with values: [0.3402232039153654, 0.6107875645499025] and parameters: {'n_neighbors': 28, 'n_components': 4, 'min_dist': 0.29, 'min_cluster_size': 2, 'min_samples': 10, 'cluster_selection_epsilon': 0.09}.

  0%|          | 0/57 [00:00<?, ?it/s]
100%|██████████| 57/57 [00:00<00:00, 414.44it/s]

Trial 51: DBCV=0.646, CCC=0.404
[I 2025-12-22 19:42:18,569] Trial 51 finished with values: [0.40418035206397285, 0.646303783637518] and parameters: {'n_neighbors': 14, 'n_components': 15, 'min_dist': 0.13, 'min_cluster_size': 9, 'min_samples': 12, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 9/9 [00:00<00:00, 424.48it/s]

Trial 52: DBCV=0.210, CCC=0.683
[I 2025-12-22 19:42:28,999] Trial 52 finished with values: [0.6828093631559072, 0.21007075689329957] and parameters: {'n_neighbors': 25, 'n_components': 11, 'min_dist': 0.22, 'min_cluster_size': 43, 'min_samples': 13, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 34/34 [00:00<00:00, 416.72it/s]

Trial 53: DBCV=0.412, CCC=0.446
[I 2025-12-22 19:42:39,118] Trial 53 finished with values: [0.4462303789784046, 0.4118128698413726] and parameters: {'n_neighbors': 23, 'n_components': 8, 'min_dist': 0.3, 'min_cluster_size': 15, 'min_samples': 10, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 20/20 [00:00<00:00, 398.72it/s]

Trial 54: DBCV=0.518, CCC=0.593
[I 2025-12-22 19:42:49,740] Trial 54 finished with values: [0.5932641054448744, 0.5177222781844578] and parameters: {'n_neighbors': 37, 'n_components': 7, 'min_dist': 0.15, 'min_cluster_size': 20, 'min_samples': 18, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 13/13 [00:00<00:00, 381.49it/s]

Trial 55: DBCV=-0.170, CCC=0.593
[I 2025-12-22 19:42:59,697] Trial 55 finished with values: [0.5925273976048965, -0.17033757196991692] and parameters: {'n_neighbors': 47, 'n_components': 2, 'min_dist': 0.17, 'min_cluster_size': 34, 'min_samples': 4, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 11/11 [00:00<00:00, 425.26it/s]

Trial 56: DBCV=0.183, CCC=0.645
[I 2025-12-22 19:43:09,912] Trial 56 finished with values: [0.6447130325719805, 0.1828582841114245] and parameters: {'n_neighbors': 16, 'n_components': 12, 'min_dist': 0.27, 'min_cluster_size': 46, 'min_samples': 3, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 12/12 [00:00<00:00, 417.56it/s]

Trial 57: DBCV=0.370, CCC=0.615
[I 2025-12-22 19:43:21,934] Trial 57 finished with values: [0.6148093001256041, 0.3695429738486907] and parameters: {'n_neighbors': 48, 'n_components': 15, 'min_dist': 0.15, 'min_cluster_size': 28, 'min_samples': 17, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 11/11 [00:00<00:00, 341.70it/s]

Trial 58: DBCV=0.153, CCC=0.724
[I 2025-12-22 19:43:32,952] Trial 58 finished with values: [0.724441987656678, 0.15316254221759387] and parameters: {'n_neighbors': 50, 'n_components': 10, 'min_dist': 0.15, 'min_cluster_size': 45, 'min_samples': 3, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 29/29 [00:00<00:00, 404.48it/s]

Trial 59: DBCV=0.654, CCC=0.544
[I 2025-12-22 19:43:43,399] Trial 59 finished with values: [0.5444765106905759, 0.6540678203877881] and parameters: {'n_neighbors': 28, 'n_components': 10, 'min_dist': 0.0, 'min_cluster_size': 10, 'min_samples': 20, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 15/15 [00:00<00:00, 386.90it/s]

Trial 60: DBCV=0.212, CCC=0.601
[I 2025-12-22 19:43:53,510] Trial 60 finished with values: [0.6009635200235682, 0.21152272845562917] and parameters: {'n_neighbors': 23, 'n_components': 7, 'min_dist': 0.15, 'min_cluster_size': 40, 'min_samples': 1, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 335.54it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 61: DBCV=0.299, CCC=0.000
[I 2025-12-22 19:44:03,729] Trial 61 finished with values: [0.0, 0.29902894045249334] and parameters: {'n_neighbors': 14, 'n_components': 11, 'min_dist': 0.22, 'min_cluster_size': 50, 'min_samples': 10, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 19/19 [00:00<00:00, 429.27it/s]

Trial 62: DBCV=0.346, CCC=0.509
[I 2025-12-22 19:44:13,004] Trial 62 finished with values: [0.5090682860111985, 0.3461837711390894] and parameters: {'n_neighbors': 8, 'n_components': 10, 'min_dist': 0.0, 'min_cluster_size': 45, 'min_samples': 5, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 38/38 [00:00<00:00, 432.34it/s]

Trial 63: DBCV=0.387, CCC=0.394
[I 2025-12-22 19:44:22,363] Trial 63 finished with values: [0.3935297709722216, 0.3865674975277517] and parameters: {'n_neighbors': 6, 'n_components': 13, 'min_dist': 0.12, 'min_cluster_size': 22, 'min_samples': 1, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 370.16it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 64: DBCV=0.335, CCC=0.000
[I 2025-12-22 19:44:33,350] Trial 64 finished with values: [0.0, 0.3352218175066404] and parameters: {'n_neighbors': 46, 'n_components': 8, 'min_dist': 0.28, 'min_cluster_size': 27, 'min_samples': 13, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 2/2 [00:00<00:00, 292.27it/s]

Trial 65: DBCV=0.273, CCC=0.817
[I 2025-12-22 19:44:44,804] Trial 65 finished with values: [0.8173595913191998, 0.2730570661422186] and parameters: {'n_neighbors': 42, 'n_components': 12, 'min_dist': 0.18, 'min_cluster_size': 23, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 24/24 [00:00<00:00, 427.15it/s]

Trial 66: DBCV=0.499, CCC=0.526
[I 2025-12-22 19:44:55,876] Trial 66 finished with values: [0.5261207093588469, 0.4989480605060803] and parameters: {'n_neighbors': 44, 'n_components': 11, 'min_dist': 0.1, 'min_cluster_size': 22, 'min_samples': 14, 'cluster_selection_epsilon': 0.1}.

  0%|          | 0/54 [00:00<?, ?it/s]
100%|██████████| 54/54 [00:00<00:00, 431.76it/s]

Trial 67: DBCV=0.577, CCC=0.410
[I 2025-12-22 19:45:08,141] Trial 67 finished with values: [0.4097511710691495, 0.57687958966689] and parameters: {'n_neighbors': 48, 'n_components': 15, 'min_dist': 0.0, 'min_cluster_size': 5, 'min_samples': 12, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 12/12 [00:00<00:00, 424.05it/s]

Trial 68: DBCV=0.318, CCC=0.644
[I 2025-12-22 19:45:18,528] Trial 68 finished with values: [0.6440601162149572, 0.31781472498856983] and parameters: {'n_neighbors': 23, 'n_components': 11, 'min_dist': 0.15, 'min_cluster_size': 40, 'min_samples': 8, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 23/23 [00:00<00:00, 423.69it/s]

Trial 69: DBCV=0.489, CCC=0.448
[I 2025-12-22 19:45:28,739] Trial 69 finished with values: [0.44764975078422514, 0.4893057008936954] and parameters: {'n_neighbors': 10, 'n_components': 15, 'min_dist': 0.22, 'min_cluster_size': 23, 'min_samples': 13, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 12/12 [00:00<00:00, 376.02it/s]

Trial 70: DBCV=0.456, CCC=0.636
[I 2025-12-22 19:45:38,875] Trial 70 finished with values: [0.6360117020353931, 0.4556104463809657] and parameters: {'n_neighbors': 44, 'n_components': 4, 'min_dist': 0.1, 'min_cluster_size': 32, 'min_samples': 19, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 13/13 [00:00<00:00, 419.69it/s]

Trial 71: DBCV=0.440, CCC=0.742
[I 2025-12-22 19:45:49,152] Trial 71 finished with values: [0.7424677368568544, 0.4401651366548962] and parameters: {'n_neighbors': 28, 'n_components': 9, 'min_dist': 0.1, 'min_cluster_size': 30, 'min_samples': 20, 'cluster_selection_epsilon': 0.1}.

  0%|          | 0/48 [00:00<?, ?it/s]
100%|██████████| 48/48 [00:00<00:00, 409.81it/s]

Trial 72: DBCV=0.449, CCC=0.444
[I 2025-12-22 19:46:00,636] Trial 72 finished with values: [0.4442551027239489, 0.4494668417867851] and parameters: {'n_neighbors': 25, 'n_components': 15, 'min_dist': 0.12, 'min_cluster_size': 16, 'min_samples': 3, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 30/30 [00:00<00:00, 408.31it/s]

Trial 73: DBCV=0.436, CCC=0.493
[I 2025-12-22 19:46:10,547] Trial 73 finished with values: [0.49285463331070284, 0.43646406433886775] and parameters: {'n_neighbors': 40, 'n_components': 2, 'min_dist': 0.17, 'min_cluster_size': 13, 'min_samples': 16, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 9/9 [00:00<00:00, 418.73it/s]

Trial 74: DBCV=0.227, CCC=0.535
[I 2025-12-22 19:46:20,264] Trial 74 finished with values: [0.5349212487460857, 0.22738946663144033] and parameters: {'n_neighbors': 16, 'n_components': 7, 'min_dist': 0.27, 'min_cluster_size': 46, 'min_samples': 10, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 25/25 [00:00<00:00, 383.07it/s]

Trial 75: DBCV=0.460, CCC=0.486
[I 2025-12-22 19:46:31,800] Trial 75 finished with values: [0.4863420256224322, 0.46037227680779036] and parameters: {'n_neighbors': 32, 'n_components': 15, 'min_dist': 0.18, 'min_cluster_size': 21, 'min_samples': 11, 'cluster_selection_epsilon': 0.28}.

100%|██████████| 25/25 [00:00<00:00, 395.42it/s]

Trial 76: DBCV=0.371, CCC=0.556
[I 2025-12-22 19:46:41,825] Trial 76 finished with values: [0.5559922401964942, 0.37146604979378106] and parameters: {'n_neighbors': 26, 'n_components': 5, 'min_dist': 0.19, 'min_cluster_size': 23, 'min_samples': 9, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 23/23 [00:00<00:00, 390.66it/s]

Trial 77: DBCV=0.512, CCC=0.424
[I 2025-12-22 19:46:49,864] Trial 77 finished with values: [0.4237723027938323, 0.512137867560887] and parameters: {'n_neighbors': 3, 'n_components': 3, 'min_dist': 0.17, 'min_cluster_size': 18, 'min_samples': 19, 'cluster_selection_epsilon': 0.13}.

  0%|          | 0/42 [00:00<?, ?it/s]
100%|██████████| 42/42 [00:00<00:00, 395.20it/s]

Trial 78: DBCV=0.344, CCC=0.426
[I 2025-12-22 19:47:02,088] Trial 78 finished with values: [0.4257631935200874, 0.3443702555180435] and parameters: {'n_neighbors': 48, 'n_components': 15, 'min_dist': 0.02, 'min_cluster_size': 14, 'min_samples': 1, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 26/26 [00:00<00:00, 429.86it/s]

Trial 79: DBCV=0.502, CCC=0.574
[I 2025-12-22 19:47:12,225] Trial 79 finished with values: [0.5739305278408624, 0.5024937245407062] and parameters: {'n_neighbors': 46, 'n_components': 3, 'min_dist': 0.17, 'min_cluster_size': 5, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 1/1 [00:00<00:00, 382.48it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 80: DBCV=0.551, CCC=0.000
[I 2025-12-22 19:47:22,869] Trial 80 finished with values: [0.0, 0.5508469260253521] and parameters: {'n_neighbors': 12, 'n_components': 15, 'min_dist': 0.29, 'min_cluster_size': 40, 'min_samples': 1, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 12/12 [00:00<00:00, 417.25it/s]

Trial 81: DBCV=0.336, CCC=0.724
[I 2025-12-22 19:47:32,963] Trial 81 finished with values: [0.7241335141666517, 0.33631991947759804] and parameters: {'n_neighbors': 23, 'n_components': 8, 'min_dist': 0.03, 'min_cluster_size': 44, 'min_samples': 9, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 9/9 [00:00<00:00, 417.77it/s]

Trial 82: DBCV=0.210, CCC=0.683
[I 2025-12-22 19:47:43,444] Trial 82 finished with values: [0.6828093631559072, 0.21007075689329957] and parameters: {'n_neighbors': 25, 'n_components': 11, 'min_dist': 0.22, 'min_cluster_size': 43, 'min_samples': 13, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 10/10 [00:00<00:00, 425.91it/s]

Trial 83: DBCV=0.326, CCC=0.702
[I 2025-12-22 19:47:54,875] Trial 83 finished with values: [0.7021336872619066, 0.32562571096858123] and parameters: {'n_neighbors': 32, 'n_components': 15, 'min_dist': 0.22, 'min_cluster_size': 44, 'min_samples': 10, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 19/19 [00:00<00:00, 426.54it/s]

Trial 84: DBCV=0.451, CCC=0.544
[I 2025-12-22 19:48:05,687] Trial 84 finished with values: [0.5439626521916776, 0.4514913039054377] and parameters: {'n_neighbors': 48, 'n_components': 7, 'min_dist': 0.3, 'min_cluster_size': 21, 'min_samples': 14, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 25/25 [00:00<00:00, 427.04it/s]

Trial 85: DBCV=0.267, CCC=0.573
[I 2025-12-22 19:48:15,811] Trial 85 finished with values: [0.5726430902182468, 0.2667614266022161] and parameters: {'n_neighbors': 22, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 27, 'min_samples': 1, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 9/9 [00:00<00:00, 421.04it/s]

Trial 86: DBCV=0.371, CCC=0.722
[I 2025-12-22 19:48:26,150] Trial 86 finished with values: [0.7222399745305418, 0.3705383785534411] and parameters: {'n_neighbors': 25, 'n_components': 10, 'min_dist': 0.11, 'min_cluster_size': 39, 'min_samples': 19, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 22/22 [00:00<00:00, 389.81it/s]

Trial 87: DBCV=0.575, CCC=0.568
[I 2025-12-22 19:48:36,641] Trial 87 finished with values: [0.5678426884982593, 0.5752048568213773] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.06}.

  0%|          | 0/134 [00:00<?, ?it/s]
 35%|███▌      | 47/134 [00:00<00:00, 459.69it/s]
100%|██████████| 134/134 [00:00<00:00, 423.87it/s][A

Trial 88: DBCV=0.617, CCC=0.236
[I 2025-12-22 19:48:47,925] Trial 88 finished with values: [0.23641870644347127, 0.6170964534518034] and parameters: {'n_neighbors': 28, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 2, 'min_samples': 5, 'cluster_selection_epsilon': 0.15}.

  0%|          | 0/56 [00:00<?, ?it/s]
100%|██████████| 56/56 [00:00<00:00, 413.40it/s]

Trial 89: DBCV=0.392, CCC=0.427
[I 2025-12-22 19:49:00,009] Trial 89 finished with values: [0.42662484883931495, 0.3919197721678721] and parameters: {'n_neighbors': 48, 'n_components': 14, 'min_dist': 0.11, 'min_cluster_size': 13, 'min_samples': 2, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 33/33 [00:00<00:00, 425.77it/s]

Trial 90: DBCV=0.451, CCC=0.468
[I 2025-12-22 19:49:10,086] Trial 90 finished with values: [0.4681474759467208, 0.45069649729412103] and parameters: {'n_neighbors': 19, 'n_components': 7, 'min_dist': 0.03, 'min_cluster_size': 18, 'min_samples': 9, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 23/23 [00:00<00:00, 423.00it/s]

Trial 91: DBCV=0.371, CCC=0.509
[I 2025-12-22 19:49:19,381] Trial 91 finished with values: [0.5092256107906601, 0.3708676076292417] and parameters: {'n_neighbors': 7, 'n_components': 11, 'min_dist': 0.13, 'min_cluster_size': 25, 'min_samples': 12, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 8/8 [00:00<00:00, 421.65it/s]

Trial 92: DBCV=0.384, CCC=0.683
[I 2025-12-22 19:49:31,032] Trial 92 finished with values: [0.6832189502999511, 0.3839899742967872] and parameters: {'n_neighbors': 48, 'n_components': 14, 'min_dist': 0.1, 'min_cluster_size': 45, 'min_samples': 19, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 13/13 [00:00<00:00, 421.14it/s]

Trial 93: DBCV=0.090, CCC=0.644
[I 2025-12-22 19:49:42,553] Trial 93 finished with values: [0.6441043300335723, 0.089881110218161] and parameters: {'n_neighbors': 42, 'n_components': 14, 'min_dist': 0.13, 'min_cluster_size': 45, 'min_samples': 1, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 26/26 [00:00<00:00, 406.58it/s]

Trial 94: DBCV=0.387, CCC=0.464
[I 2025-12-22 19:49:53,705] Trial 94 finished with values: [0.463775360924988, 0.3874766555752603] and parameters: {'n_neighbors': 44, 'n_components': 11, 'min_dist': 0.02, 'min_cluster_size': 23, 'min_samples': 1, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 34/34 [00:00<00:00, 385.00it/s]

Trial 95: DBCV=0.342, CCC=0.357
[I 2025-12-22 19:50:03,282] Trial 95 finished with values: [0.3571151294406032, 0.3423488268343759] and parameters: {'n_neighbors': 8, 'n_components': 12, 'min_dist': 0.27, 'min_cluster_size': 22, 'min_samples': 3, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 27/27 [00:00<00:00, 431.06it/s]

Trial 96: DBCV=0.519, CCC=0.541
[I 2025-12-22 19:50:13,805] Trial 96 finished with values: [0.5409984399163009, 0.519238713179017] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.01, 'min_cluster_size': 16, 'min_samples': 18, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 15/15 [00:00<00:00, 424.89it/s]

Trial 97: DBCV=0.204, CCC=0.610
[I 2025-12-22 19:50:24,392] Trial 97 finished with values: [0.6097989736310742, 0.20360775492895009] and parameters: {'n_neighbors': 48, 'n_components': 6, 'min_dist': 0.15, 'min_cluster_size': 43, 'min_samples': 4, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 325.62it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 98: DBCV=-0.101, CCC=0.000
[I 2025-12-22 19:50:34,300] Trial 98 finished with values: [0.0, -0.1011650358302813] and parameters: {'n_neighbors': 34, 'n_components': 2, 'min_dist': 0.03, 'min_cluster_size': 50, 'min_samples': 7, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 19/19 [00:00<00:00, 385.90it/s]

Trial 99: DBCV=0.184, CCC=0.523
[I 2025-12-22 19:50:44,196] Trial 99 finished with values: [0.5229731989624032, 0.18444700537750613] and parameters: {'n_neighbors': 31, 'n_components': 4, 'min_dist': 0.25, 'min_cluster_size': 27, 'min_samples': 5, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 2/2 [00:00<00:00, 350.52it/s]

Trial 100: DBCV=0.302, CCC=0.937
[I 2025-12-22 19:50:53,972] Trial 100 finished with values: [0.9366249027571225, 0.30214152049958665] and parameters: {'n_neighbors': 14, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 50, 'min_samples': 5, 'cluster_selection_epsilon': 0.15}.

  0%|          | 0/62 [00:00<?, ?it/s]
100%|██████████| 62/62 [00:00<00:00, 394.53it/s]

Trial 101: DBCV=0.618, CCC=0.380
[I 2025-12-22 19:51:04,209] Trial 101 finished with values: [0.3797595501538694, 0.6177347315244276] and parameters: {'n_neighbors': 31, 'n_components': 4, 'min_dist': 0.1, 'min_cluster_size': 4, 'min_samples': 11, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 19/19 [00:00<00:00, 422.16it/s]

Trial 102: DBCV=0.581, CCC=0.497
[I 2025-12-22 19:51:12,950] Trial 102 finished with values: [0.49705265176602664, 0.5813385996805979] and parameters: {'n_neighbors': 3, 'n_components': 15, 'min_dist': 0.19, 'min_cluster_size': 18, 'min_samples': 20, 'cluster_selection_epsilon': 0.1}.

  0%|          | 0/45 [00:00<?, ?it/s]
100%|██████████| 45/45 [00:00<00:00, 427.84it/s]

Trial 103: DBCV=0.548, CCC=0.423
[I 2025-12-22 19:51:24,613] Trial 103 finished with values: [0.4229261991466323, 0.54829063310915] and parameters: {'n_neighbors': 48, 'n_components': 13, 'min_dist': 0.13, 'min_cluster_size': 9, 'min_samples': 12, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 33/33 [00:00<00:00, 406.58it/s]

Trial 104: DBCV=0.621, CCC=0.528
[I 2025-12-22 19:51:34,472] Trial 104 finished with values: [0.5279031217743726, 0.6205696144282506] and parameters: {'n_neighbors': 28, 'n_components': 4, 'min_dist': 0.0, 'min_cluster_size': 5, 'min_samples': 19, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 10/10 [00:00<00:00, 366.48it/s]

Trial 105: DBCV=0.447, CCC=0.651
[I 2025-12-22 19:51:45,533] Trial 105 finished with values: [0.6514189596713362, 0.44693018163651443] and parameters: {'n_neighbors': 42, 'n_components': 12, 'min_dist': 0.11, 'min_cluster_size': 39, 'min_samples': 19, 'cluster_selection_epsilon': 0.2}.

  0%|          | 0/134 [00:00<?, ?it/s]
 34%|███▍      | 46/134 [00:00<00:00, 458.40it/s]
100%|██████████| 134/134 [00:00<00:00, 427.85it/s][A

Trial 106: DBCV=0.617, CCC=0.236
[I 2025-12-22 19:51:56,823] Trial 106 finished with values: [0.23641870644347127, 0.6170964534518034] and parameters: {'n_neighbors': 28, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 2, 'min_samples': 5, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 10/10 [00:00<00:00, 413.60it/s]

Trial 107: DBCV=0.398, CCC=0.760
[I 2025-12-22 19:52:07,041] Trial 107 finished with values: [0.7596946770213364, 0.39801102902025287] and parameters: {'n_neighbors': 23, 'n_components': 10, 'min_dist': 0.11, 'min_cluster_size': 40, 'min_samples': 8, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 17/17 [00:00<00:00, 426.23it/s]

Trial 108: DBCV=0.398, CCC=0.708
[I 2025-12-22 19:52:17,294] Trial 108 finished with values: [0.7083232623783128, 0.3982317213042341] and parameters: {'n_neighbors': 41, 'n_components': 5, 'min_dist': 0.18, 'min_cluster_size': 23, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 1/1 [00:00<00:00, 374.56it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 109: DBCV=0.265, CCC=0.000
[I 2025-12-22 19:52:28,743] Trial 109 finished with values: [0.0, 0.26495064542931285] and parameters: {'n_neighbors': 48, 'n_components': 11, 'min_dist': 0.22, 'min_cluster_size': 40, 'min_samples': 10, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 17/17 [00:00<00:00, 374.34it/s]

Trial 110: DBCV=0.492, CCC=0.613
[I 2025-12-22 19:52:39,170] Trial 110 finished with values: [0.6127172809954027, 0.4920053094651522] and parameters: {'n_neighbors': 37, 'n_components': 8, 'min_dist': 0.15, 'min_cluster_size': 27, 'min_samples': 14, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 26/26 [00:00<00:00, 422.50it/s]

Trial 111: DBCV=0.409, CCC=0.553
[I 2025-12-22 19:52:49,746] Trial 111 finished with values: [0.552952392885106, 0.40878013788068635] and parameters: {'n_neighbors': 23, 'n_components': 11, 'min_dist': 0.03, 'min_cluster_size': 24, 'min_samples': 9, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 19/19 [00:00<00:00, 399.70it/s]

Trial 112: DBCV=0.401, CCC=0.610
[I 2025-12-22 19:53:00,144] Trial 112 finished with values: [0.6097795924155912, 0.4013846458770919] and parameters: {'n_neighbors': 46, 'n_components': 5, 'min_dist': 0.27, 'min_cluster_size': 20, 'min_samples': 14, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 16/16 [00:00<00:00, 391.33it/s]

Trial 113: DBCV=0.396, CCC=0.650
[I 2025-12-22 19:53:10,392] Trial 113 finished with values: [0.6500583046749236, 0.39621107144601103] and parameters: {'n_neighbors': 41, 'n_components': 5, 'min_dist': 0.18, 'min_cluster_size': 29, 'min_samples': 13, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 13/13 [00:00<00:00, 425.80it/s]

Trial 114: DBCV=0.402, CCC=0.513
[I 2025-12-22 19:53:19,457] Trial 114 finished with values: [0.5134000118848158, 0.40232298309603626] and parameters: {'n_neighbors': 8, 'n_components': 8, 'min_dist': 0.22, 'min_cluster_size': 44, 'min_samples': 16, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 40/40 [00:00<00:00, 423.12it/s]

Trial 115: DBCV=0.573, CCC=0.382
[I 2025-12-22 19:53:31,501] Trial 115 finished with values: [0.3823481762107582, 0.5733327810847185] and parameters: {'n_neighbors': 44, 'n_components': 15, 'min_dist': 0.1, 'min_cluster_size': 5, 'min_samples': 14, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 25/25 [00:00<00:00, 425.49it/s]

Trial 116: DBCV=0.497, CCC=0.415
[I 2025-12-22 19:53:39,602] Trial 116 finished with values: [0.41496830608971524, 0.49707994854681425] and parameters: {'n_neighbors': 3, 'n_components': 3, 'min_dist': 0.17, 'min_cluster_size': 18, 'min_samples': 19, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 25/25 [00:00<00:00, 402.12it/s]

Trial 117: DBCV=0.490, CCC=0.459
[I 2025-12-22 19:53:50,913] Trial 117 finished with values: [0.4591597374274196, 0.49007406024534444] and parameters: {'n_neighbors': 46, 'n_components': 12, 'min_dist': 0.17, 'min_cluster_size': 5, 'min_samples': 19, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 27/27 [00:00<00:00, 399.20it/s]

Trial 118: DBCV=0.500, CCC=0.498
[I 2025-12-22 19:54:02,669] Trial 118 finished with values: [0.49766756157153874, 0.5004204731396122] and parameters: {'n_neighbors': 48, 'n_components': 14, 'min_dist': 0.15, 'min_cluster_size': 13, 'min_samples': 17, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 32/32 [00:00<00:00, 421.54it/s]

Trial 119: DBCV=0.557, CCC=0.434
[I 2025-12-22 19:54:12,503] Trial 119 finished with values: [0.4343007723214853, 0.5566903885343123] and parameters: {'n_neighbors': 28, 'n_components': 4, 'min_dist': 0.22, 'min_cluster_size': 2, 'min_samples': 20, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 38/38 [00:00<00:00, 415.66it/s]

Trial 120: DBCV=0.594, CCC=0.419
[I 2025-12-22 19:54:21,961] Trial 120 finished with values: [0.4188523303400516, 0.5936917309858977] and parameters: {'n_neighbors': 10, 'n_components': 8, 'min_dist': 0.06, 'min_cluster_size': 13, 'min_samples': 16, 'cluster_selection_epsilon': 0.18}.

  0%|          | 0/56 [00:00<?, ?it/s]
100%|██████████| 56/56 [00:00<00:00, 398.73it/s]

Trial 121: DBCV=0.619, CCC=0.414
[I 2025-12-22 19:54:32,387] Trial 121 finished with values: [0.4139396402375066, 0.6190642800001184] and parameters: {'n_neighbors': 14, 'n_components': 13, 'min_dist': 0.13, 'min_cluster_size': 9, 'min_samples': 12, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 20/20 [00:00<00:00, 388.72it/s]

Trial 122: DBCV=0.529, CCC=0.628
[I 2025-12-22 19:54:42,848] Trial 122 finished with values: [0.6283564691735066, 0.5285838124974876] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.16, 'min_cluster_size': 20, 'min_samples': 18, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 15/15 [00:00<00:00, 413.42it/s]

Trial 123: DBCV=0.301, CCC=0.580
[I 2025-12-22 19:54:52,367] Trial 123 finished with values: [0.5804267541593678, 0.30140155250013934] and parameters: {'n_neighbors': 6, 'n_components': 15, 'min_dist': 0.0, 'min_cluster_size': 45, 'min_samples': 10, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 13/13 [00:00<00:00, 362.40it/s]

Trial 124: DBCV=0.506, CCC=0.555
[I 2025-12-22 19:55:00,990] Trial 124 finished with values: [0.5553750909314452, 0.5058499952545278] and parameters: {'n_neighbors': 5, 'n_components': 7, 'min_dist': 0.15, 'min_cluster_size': 45, 'min_samples': 18, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 12/12 [00:00<00:00, 376.50it/s]

Trial 125: DBCV=0.374, CCC=0.657
[I 2025-12-22 19:55:11,760] Trial 125 finished with values: [0.6567457780217064, 0.3739172203238826] and parameters: {'n_neighbors': 34, 'n_components': 11, 'min_dist': 0.08, 'min_cluster_size': 45, 'min_samples': 3, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 9/9 [00:00<00:00, 196.28it/s]

Trial 126: DBCV=0.210, CCC=0.683
[I 2025-12-22 19:55:22,245] Trial 126 finished with values: [0.6828093631559072, 0.21007075689329957] and parameters: {'n_neighbors': 25, 'n_components': 11, 'min_dist': 0.22, 'min_cluster_size': 43, 'min_samples': 13, 'cluster_selection_epsilon': 0.01}.

  0%|          | 0/37 [00:00<?, ?it/s]
100%|██████████| 37/37 [00:00<00:00, 344.18it/s]

Trial 127: DBCV=0.543, CCC=0.397
[I 2025-12-22 19:55:32,838] Trial 127 finished with values: [0.3973471088989137, 0.5434214264984435] and parameters: {'n_neighbors': 19, 'n_components': 12, 'min_dist': 0.03, 'min_cluster_size': 18, 'min_samples': 9, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 22/22 [00:00<00:00, 389.56it/s]

Trial 128: DBCV=0.517, CCC=0.590
[I 2025-12-22 19:55:43,051] Trial 128 finished with values: [0.5902535029238055, 0.5171999003316079] and parameters: {'n_neighbors': 37, 'n_components': 5, 'min_dist': 0.04, 'min_cluster_size': 23, 'min_samples': 19, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 14/14 [00:00<00:00, 419.78it/s]

Trial 129: DBCV=0.333, CCC=0.684
[I 2025-12-22 19:55:53,960] Trial 129 finished with values: [0.6838951290275614, 0.33270859867940783] and parameters: {'n_neighbors': 46, 'n_components': 10, 'min_dist': 0.07, 'min_cluster_size': 45, 'min_samples': 10, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 16/16 [00:00<00:00, 421.54it/s]

Trial 130: DBCV=0.170, CCC=0.654
[I 2025-12-22 19:56:03,782] Trial 130 finished with values: [0.6536799749473026, 0.17030100088209155] and parameters: {'n_neighbors': 23, 'n_components': 5, 'min_dist': 0.03, 'min_cluster_size': 35, 'min_samples': 9, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 13/13 [00:00<00:00, 420.01it/s]

Trial 131: DBCV=0.346, CCC=0.660
[I 2025-12-22 19:56:14,419] Trial 131 finished with values: [0.6598147723618792, 0.34599692940522225] and parameters: {'n_neighbors': 19, 'n_components': 14, 'min_dist': 0.19, 'min_cluster_size': 38, 'min_samples': 9, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 22/22 [00:00<00:00, 402.04it/s]

Trial 132: DBCV=0.575, CCC=0.568
[I 2025-12-22 19:56:25,027] Trial 132 finished with values: [0.5678426884982593, 0.5752048568213773] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 418.26it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 133: DBCV=0.421, CCC=0.000
[I 2025-12-22 19:56:34,293] Trial 133 finished with values: [0.0, 0.4214604875703543] and parameters: {'n_neighbors': 9, 'n_components': 4, 'min_dist': 0.1, 'min_cluster_size': 32, 'min_samples': 19, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 13/13 [00:00<00:00, 424.19it/s]

Trial 134: DBCV=0.390, CCC=0.674
[I 2025-12-22 19:56:44,430] Trial 134 finished with values: [0.6742056040186689, 0.39039854733563684] and parameters: {'n_neighbors': 23, 'n_components': 9, 'min_dist': 0.1, 'min_cluster_size': 30, 'min_samples': 20, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 11/11 [00:00<00:00, 418.97it/s]

Trial 135: DBCV=0.322, CCC=0.745
[I 2025-12-22 19:56:55,592] Trial 135 finished with values: [0.7451511194450574, 0.32216166024513326] and parameters: {'n_neighbors': 32, 'n_components': 14, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 10, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 28/28 [00:00<00:00, 404.31it/s]

Trial 136: DBCV=0.534, CCC=0.466
[I 2025-12-22 19:57:05,844] Trial 136 finished with values: [0.46637170535062994, 0.5342149217757973] and parameters: {'n_neighbors': 48, 'n_components': 3, 'min_dist': 0.11, 'min_cluster_size': 5, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 15/15 [00:00<00:00, 369.67it/s]

Trial 137: DBCV=0.350, CCC=0.647
[I 2025-12-22 19:57:15,726] Trial 137 finished with values: [0.6471980759776347, 0.34966688029786486] and parameters: {'n_neighbors': 32, 'n_components': 4, 'min_dist': 0.04, 'min_cluster_size': 32, 'min_samples': 19, 'cluster_selection_epsilon': 0.28}.

100%|██████████| 34/34 [00:00<00:00, 404.58it/s]

Trial 138: DBCV=0.431, CCC=0.471
[I 2025-12-22 19:57:24,693] Trial 138 finished with values: [0.47063778784820826, 0.43086564834387053] and parameters: {'n_neighbors': 6, 'n_components': 8, 'min_dist': 0.12, 'min_cluster_size': 22, 'min_samples': 5, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 8/8 [00:00<00:00, 426.68it/s]

Trial 139: DBCV=0.311, CCC=0.598
[I 2025-12-22 19:57:35,652] Trial 139 finished with values: [0.5983163901775947, 0.3114988997295434] and parameters: {'n_neighbors': 25, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 45, 'min_samples': 13, 'cluster_selection_epsilon': 0.14}.

  0%|          | 0/51 [00:00<?, ?it/s]
100%|██████████| 51/51 [00:00<00:00, 393.75it/s]

Trial 140: DBCV=0.594, CCC=0.401
[I 2025-12-22 19:57:46,817] Trial 140 finished with values: [0.400640055768213, 0.5943614625609263] and parameters: {'n_neighbors': 48, 'n_components': 10, 'min_dist': 0.0, 'min_cluster_size': 12, 'min_samples': 12, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 11/11 [00:00<00:00, 356.09it/s]

Trial 141: DBCV=0.214, CCC=0.671
[I 2025-12-22 19:57:57,311] Trial 141 finished with values: [0.6708435462666534, 0.21407668758990106] and parameters: {'n_neighbors': 25, 'n_components': 11, 'min_dist': 0.22, 'min_cluster_size': 43, 'min_samples': 10, 'cluster_selection_epsilon': 0.01}.

  0%|          | 0/57 [00:00<?, ?it/s]
100%|██████████| 57/57 [00:00<00:00, 402.41it/s]

Trial 142: DBCV=0.587, CCC=0.366
[I 2025-12-22 19:58:08,845] Trial 142 finished with values: [0.36584771733133514, 0.5870974503279919] and parameters: {'n_neighbors': 41, 'n_components': 13, 'min_dist': 0.0, 'min_cluster_size': 5, 'min_samples': 12, 'cluster_selection_epsilon': 0.19}.

  0%|          | 0/43 [00:00<?, ?it/s]
100%|██████████| 43/43 [00:00<00:00, 396.79it/s]

Trial 143: DBCV=0.561, CCC=0.406
[I 2025-12-22 19:58:18,698] Trial 143 finished with values: [0.40571177187910373, 0.5613430875376004] and parameters: {'n_neighbors': 8, 'n_components': 14, 'min_dist': 0.03, 'min_cluster_size': 18, 'min_samples': 9, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 40/40 [00:00<00:00, 416.71it/s]

Trial 144: DBCV=0.304, CCC=0.555
[I 2025-12-22 19:58:29,249] Trial 144 finished with values: [0.5554011305972428, 0.3043804917569775] and parameters: {'n_neighbors': 12, 'n_components': 15, 'min_dist': 0.29, 'min_cluster_size': 23, 'min_samples': 1, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 7/7 [00:00<00:00, 415.17it/s]

Trial 145: DBCV=0.241, CCC=0.716
[I 2025-12-22 19:58:39,485] Trial 145 finished with values: [0.7158172688194921, 0.2413237301941173] and parameters: {'n_neighbors': 25, 'n_components': 10, 'min_dist': 0.22, 'min_cluster_size': 47, 'min_samples': 19, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 20/20 [00:00<00:00, 397.12it/s]

Trial 146: DBCV=0.533, CCC=0.604
[I 2025-12-22 19:58:49,861] Trial 146 finished with values: [0.604440360060548, 0.5326897340306075] and parameters: {'n_neighbors': 28, 'n_components': 10, 'min_dist': 0.1, 'min_cluster_size': 22, 'min_samples': 20, 'cluster_selection_epsilon': 0.14}.

  0%|          | 0/53 [00:00<?, ?it/s]
100%|██████████| 53/53 [00:00<00:00, 415.95it/s]

Trial 147: DBCV=0.618, CCC=0.366
[I 2025-12-22 19:58:59,552] Trial 147 finished with values: [0.3656655663459377, 0.6181240325616587] and parameters: {'n_neighbors': 14, 'n_components': 6, 'min_dist': 0.13, 'min_cluster_size': 11, 'min_samples': 12, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 1/1 [00:00<00:00, 340.83it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 148: DBCV=0.310, CCC=0.000
[I 2025-12-22 19:59:09,523] Trial 148 finished with values: [0.0, 0.31010170242239576] and parameters: {'n_neighbors': 25, 'n_components': 3, 'min_dist': 0.22, 'min_cluster_size': 24, 'min_samples': 13, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/55 [00:00<?, ?it/s]
100%|██████████| 55/55 [00:00<00:00, 397.47it/s]

Trial 149: DBCV=0.637, CCC=0.311
[I 2025-12-22 19:59:19,657] Trial 149 finished with values: [0.3112683349531733, 0.6371044349912898] and parameters: {'n_neighbors': 30, 'n_components': 4, 'min_dist': 0.0, 'min_cluster_size': 12, 'min_samples': 12, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 28/28 [00:00<00:00, 400.28it/s]

Trial 150: DBCV=0.573, CCC=0.534
[I 2025-12-22 19:59:30,139] Trial 150 finished with values: [0.5341759510696723, 0.5732788974098224] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 16, 'min_samples': 18, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 13/13 [00:00<00:00, 423.31it/s]

Trial 151: DBCV=0.452, CCC=0.670
[I 2025-12-22 19:59:42,015] Trial 151 finished with values: [0.6704672966786476, 0.45213080905305464] and parameters: {'n_neighbors': 44, 'n_components': 15, 'min_dist': 0.1, 'min_cluster_size': 32, 'min_samples': 19, 'cluster_selection_epsilon': 0.2}.

  0%|          | 0/68 [00:00<?, ?it/s]
100%|██████████| 68/68 [00:00<00:00, 408.24it/s]

Trial 152: DBCV=0.678, CCC=0.417
[I 2025-12-22 19:59:52,325] Trial 152 finished with values: [0.41744582846433514, 0.6782928143159834] and parameters: {'n_neighbors': 14, 'n_components': 11, 'min_dist': 0.1, 'min_cluster_size': 4, 'min_samples': 11, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 30/30 [00:00<00:00, 397.64it/s]

Trial 153: DBCV=0.609, CCC=0.564
[I 2025-12-22 20:00:02,498] Trial 153 finished with values: [0.5643364437655483, 0.6089632147732432] and parameters: {'n_neighbors': 28, 'n_components': 6, 'min_dist': 0.0, 'min_cluster_size': 5, 'min_samples': 19, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 9/9 [00:00<00:00, 421.19it/s]

Trial 154: DBCV=0.361, CCC=0.773
[I 2025-12-22 20:00:12,732] Trial 154 finished with values: [0.772583328076609, 0.36138237095295506] and parameters: {'n_neighbors': 23, 'n_components': 10, 'min_dist': 0.11, 'min_cluster_size': 40, 'min_samples': 20, 'cluster_selection_epsilon': 0.04}.

  0%|          | 0/55 [00:00<?, ?it/s]
100%|██████████| 55/55 [00:00<00:00, 401.43it/s]

Trial 155: DBCV=0.619, CCC=0.417
[I 2025-12-22 20:00:22,590] Trial 155 finished with values: [0.4171375258133303, 0.6190662723946175] and parameters: {'n_neighbors': 14, 'n_components': 8, 'min_dist': 0.09, 'min_cluster_size': 11, 'min_samples': 12, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 32/32 [00:00<00:00, 414.61it/s]

Trial 156: DBCV=0.442, CCC=0.556
[I 2025-12-22 20:00:32,789] Trial 156 finished with values: [0.556002511875705, 0.4422267716041359] and parameters: {'n_neighbors': 23, 'n_components': 7, 'min_dist': 0.19, 'min_cluster_size': 18, 'min_samples': 11, 'cluster_selection_epsilon': 0.25}.

  0%|          | 0/51 [00:00<?, ?it/s]
100%|██████████| 51/51 [00:00<00:00, 393.60it/s]

Trial 157: DBCV=0.594, CCC=0.401
[I 2025-12-22 20:00:44,094] Trial 157 finished with values: [0.400640055768213, 0.5943614625609263] and parameters: {'n_neighbors': 48, 'n_components': 10, 'min_dist': 0.0, 'min_cluster_size': 12, 'min_samples': 12, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 6/6 [00:00<00:00, 330.72it/s]

Trial 158: DBCV=0.329, CCC=0.730
[I 2025-12-22 20:00:53,260] Trial 158 finished with values: [0.7302940534798705, 0.3287560804721271] and parameters: {'n_neighbors': 7, 'n_components': 11, 'min_dist': 0.29, 'min_cluster_size': 50, 'min_samples': 15, 'cluster_selection_epsilon': 0.15}.

  0%|          | 0/67 [00:00<?, ?it/s]
100%|██████████| 67/67 [00:00<00:00, 419.87it/s]

Trial 159: DBCV=0.643, CCC=0.332
[I 2025-12-22 20:01:03,450] Trial 159 finished with values: [0.33203505543624406, 0.6434309738077925] and parameters: {'n_neighbors': 30, 'n_components': 4, 'min_dist': 0.0, 'min_cluster_size': 12, 'min_samples': 10, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 17/17 [00:00<00:00, 384.84it/s]

Trial 160: DBCV=0.471, CCC=0.629
[I 2025-12-22 20:01:13,527] Trial 160 finished with values: [0.628671149884772, 0.47118373805040303] and parameters: {'n_neighbors': 42, 'n_components': 4, 'min_dist': 0.1, 'min_cluster_size': 23, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 28/28 [00:00<00:00, 401.03it/s]

Trial 161: DBCV=0.416, CCC=0.566
[I 2025-12-22 20:01:24,032] Trial 161 finished with values: [0.5664456446500618, 0.4156164163704446] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.14, 'min_cluster_size': 22, 'min_samples': 5, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 7/7 [00:00<00:00, 417.08it/s]

Trial 162: DBCV=0.364, CCC=0.737
[I 2025-12-22 20:01:34,228] Trial 162 finished with values: [0.7368583055765742, 0.36377859748361896] and parameters: {'n_neighbors': 25, 'n_components': 10, 'min_dist': 0.22, 'min_cluster_size': 47, 'min_samples': 18, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 7/7 [00:00<00:00, 341.20it/s]

Trial 163: DBCV=0.241, CCC=0.716
[I 2025-12-22 20:01:44,458] Trial 163 finished with values: [0.7158172688194921, 0.2413237301941173] and parameters: {'n_neighbors': 25, 'n_components': 10, 'min_dist': 0.22, 'min_cluster_size': 47, 'min_samples': 19, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 1/1 [00:00<00:00, 332.49it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 164: DBCV=0.217, CCC=0.000
[I 2025-12-22 20:01:54,580] Trial 164 finished with values: [0.0, 0.21749707176164546] and parameters: {'n_neighbors': 19, 'n_components': 8, 'min_dist': 0.06, 'min_cluster_size': 32, 'min_samples': 16, 'cluster_selection_epsilon': 0.18}.

  0%|          | 0/51 [00:00<?, ?it/s]
100%|██████████| 51/51 [00:00<00:00, 403.39it/s]

Trial 165: DBCV=0.594, CCC=0.401
[I 2025-12-22 20:02:05,790] Trial 165 finished with values: [0.400640055768213, 0.5943614625609263] and parameters: {'n_neighbors': 48, 'n_components': 10, 'min_dist': 0.0, 'min_cluster_size': 12, 'min_samples': 12, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 37/37 [00:00<00:00, 414.93it/s]

Trial 166: DBCV=0.558, CCC=0.466
[I 2025-12-22 20:02:16,101] Trial 166 finished with values: [0.465659207277244, 0.5584025620607889] and parameters: {'n_neighbors': 46, 'n_components': 4, 'min_dist': 0.09, 'min_cluster_size': 12, 'min_samples': 14, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 16/16 [00:00<00:00, 388.29it/s]

Trial 167: DBCV=0.360, CCC=0.665
[I 2025-12-22 20:02:26,298] Trial 167 finished with values: [0.6652539044541135, 0.36035235126360765] and parameters: {'n_neighbors': 23, 'n_components': 10, 'min_dist': 0.13, 'min_cluster_size': 40, 'min_samples': 4, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 20/20 [00:00<00:00, 428.78it/s]

Trial 168: DBCV=0.392, CCC=0.649
[I 2025-12-22 20:02:36,771] Trial 168 finished with values: [0.6491472804125527, 0.39237232637812847] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.12, 'min_cluster_size': 22, 'min_samples': 19, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 29/29 [00:00<00:00, 429.86it/s]

Trial 169: DBCV=0.344, CCC=0.566
[I 2025-12-22 20:02:48,015] Trial 169 finished with values: [0.5659954492154385, 0.3435617584030749] and parameters: {'n_neighbors': 37, 'n_components': 13, 'min_dist': 0.01, 'min_cluster_size': 23, 'min_samples': 2, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 6/6 [00:00<00:00, 420.71it/s]

Trial 170: DBCV=0.343, CCC=0.688
[I 2025-12-22 20:02:59,090] Trial 170 finished with values: [0.687647458978238, 0.34319741478576565] and parameters: {'n_neighbors': 42, 'n_components': 12, 'min_dist': 0.22, 'min_cluster_size': 47, 'min_samples': 19, 'cluster_selection_epsilon': 0.28}.

100%|██████████| 19/19 [00:00<00:00, 423.35it/s]

Trial 171: DBCV=0.425, CCC=0.606
[I 2025-12-22 20:03:08,914] Trial 171 finished with values: [0.6062882350627081, 0.42461750766487244] and parameters: {'n_neighbors': 34, 'n_components': 3, 'min_dist': 0.0, 'min_cluster_size': 22, 'min_samples': 20, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 2/2 [00:00<00:00, 230.07it/s]

Trial 172: DBCV=0.273, CCC=0.817
[I 2025-12-22 20:03:20,426] Trial 172 finished with values: [0.8173595913191998, 0.2730570661422186] and parameters: {'n_neighbors': 42, 'n_components': 12, 'min_dist': 0.18, 'min_cluster_size': 23, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 8/8 [00:00<00:00, 423.76it/s]

Trial 173: DBCV=0.334, CCC=0.662
[I 2025-12-22 20:03:31,267] Trial 173 finished with values: [0.661777076789874, 0.3338529212041036] and parameters: {'n_neighbors': 46, 'n_components': 10, 'min_dist': 0.28, 'min_cluster_size': 45, 'min_samples': 12, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 8/8 [00:00<00:00, 325.04it/s]

Trial 174: DBCV=0.382, CCC=0.691
[I 2025-12-22 20:03:41,541] Trial 174 finished with values: [0.691336736629475, 0.3822412738568663] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.15, 'min_cluster_size': 45, 'min_samples': 18, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 23/23 [00:00<00:00, 401.61it/s]

Trial 175: DBCV=0.490, CCC=0.608
[I 2025-12-22 20:03:53,003] Trial 175 finished with values: [0.6080692503505774, 0.4901698704025223] and parameters: {'n_neighbors': 46, 'n_components': 13, 'min_dist': 0.0, 'min_cluster_size': 20, 'min_samples': 20, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 7/7 [00:00<00:00, 420.18it/s]

Trial 176: DBCV=0.372, CCC=0.697
[I 2025-12-22 20:04:03,245] Trial 176 finished with values: [0.6968694944981132, 0.3719613299683981] and parameters: {'n_neighbors': 25, 'n_components': 9, 'min_dist': 0.09, 'min_cluster_size': 49, 'min_samples': 14, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 19/19 [00:00<00:00, 394.31it/s]

Trial 177: DBCV=0.401, CCC=0.610
[I 2025-12-22 20:04:13,604] Trial 177 finished with values: [0.6097795924155912, 0.4013846458770919] and parameters: {'n_neighbors': 46, 'n_components': 5, 'min_dist': 0.27, 'min_cluster_size': 20, 'min_samples': 14, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 28/28 [00:00<00:00, 397.88it/s]

Trial 178: DBCV=0.416, CCC=0.566
[I 2025-12-22 20:04:24,172] Trial 178 finished with values: [0.5664456446500618, 0.4156164163704446] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.14, 'min_cluster_size': 22, 'min_samples': 5, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 22/22 [00:00<00:00, 387.76it/s]

Trial 179: DBCV=0.442, CCC=0.495
[I 2025-12-22 20:04:34,362] Trial 179 finished with values: [0.4946993831842133, 0.4417496551885163] and parameters: {'n_neighbors': 14, 'n_components': 13, 'min_dist': 0.15, 'min_cluster_size': 27, 'min_samples': 14, 'cluster_selection_epsilon': 0.04}.

  0%|          | 0/53 [00:00<?, ?it/s]
100%|██████████| 53/53 [00:00<00:00, 398.64it/s]

Trial 180: DBCV=0.615, CCC=0.277
[I 2025-12-22 20:04:44,075] Trial 180 finished with values: [0.27675349135355815, 0.6151516178362598] and parameters: {'n_neighbors': 10, 'n_components': 10, 'min_dist': 0.07, 'min_cluster_size': 13, 'min_samples': 10, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 26/26 [00:00<00:00, 406.42it/s]

Trial 181: DBCV=0.398, CCC=0.545
[I 2025-12-22 20:04:54,236] Trial 181 finished with values: [0.5447312437213172, 0.3977596751949207] and parameters: {'n_neighbors': 30, 'n_components': 5, 'min_dist': 0.04, 'min_cluster_size': 23, 'min_samples': 12, 'cluster_selection_epsilon': 0.14}.

  0%|          | 0/70 [00:00<?, ?it/s]
100%|██████████| 70/70 [00:00<00:00, 413.23it/s]

Trial 182: DBCV=0.655, CCC=0.287
[I 2025-12-22 20:05:04,869] Trial 182 finished with values: [0.28698312933255915, 0.6553625913614343] and parameters: {'n_neighbors': 46, 'n_components': 4, 'min_dist': 0.0, 'min_cluster_size': 5, 'min_samples': 10, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 10/10 [00:00<00:00, 419.63it/s]

Trial 183: DBCV=0.202, CCC=0.701
[I 2025-12-22 20:05:15,061] Trial 183 finished with values: [0.70075329486559, 0.20219807508484078] and parameters: {'n_neighbors': 37, 'n_components': 5, 'min_dist': 0.13, 'min_cluster_size': 48, 'min_samples': 12, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 43/43 [00:00<00:00, 435.48it/s]

Trial 184: DBCV=0.611, CCC=0.450
[I 2025-12-22 20:05:25,870] Trial 184 finished with values: [0.44975043162411205, 0.6107568119322135] and parameters: {'n_neighbors': 48, 'n_components': 5, 'min_dist': 0.05, 'min_cluster_size': 12, 'min_samples': 13, 'cluster_selection_epsilon': 0.09}.

  0%|          | 0/62 [00:00<?, ?it/s]
100%|██████████| 62/62 [00:00<00:00, 431.75it/s]

Trial 185: DBCV=0.618, CCC=0.380
[I 2025-12-22 20:05:36,066] Trial 185 finished with values: [0.3797595501538694, 0.6177347315244276] and parameters: {'n_neighbors': 31, 'n_components': 4, 'min_dist': 0.1, 'min_cluster_size': 4, 'min_samples': 11, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 18/18 [00:00<00:00, 382.29it/s]

Trial 186: DBCV=0.514, CCC=0.687
[I 2025-12-22 20:05:45,993] Trial 186 finished with values: [0.6870097560144618, 0.5141110867505018] and parameters: {'n_neighbors': 34, 'n_components': 4, 'min_dist': 0.08, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 10/10 [00:00<00:00, 423.03it/s]

Trial 187: DBCV=0.370, CCC=0.657
[I 2025-12-22 20:05:56,258] Trial 187 finished with values: [0.6571018396251761, 0.3696673589260632] and parameters: {'n_neighbors': 19, 'n_components': 12, 'min_dist': 0.08, 'min_cluster_size': 45, 'min_samples': 19, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 33/33 [00:00<00:00, 406.33it/s]

Trial 188: DBCV=0.599, CCC=0.535
[I 2025-12-22 20:06:06,207] Trial 188 finished with values: [0.5354233726860151, 0.5989175807469301] and parameters: {'n_neighbors': 28, 'n_components': 4, 'min_dist': 0.1, 'min_cluster_size': 2, 'min_samples': 20, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 36/36 [00:00<00:00, 434.57it/s]

Trial 189: DBCV=0.646, CCC=0.454
[I 2025-12-22 20:06:15,968] Trial 189 finished with values: [0.45368097450324457, 0.6464827300375776] and parameters: {'n_neighbors': 10, 'n_components': 12, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 20, 'cluster_selection_epsilon': 0.1}.

  0%|          | 0/63 [00:00<?, ?it/s]
100%|██████████| 63/63 [00:00<00:00, 422.18it/s]

Trial 190: DBCV=0.635, CCC=0.317
[I 2025-12-22 20:06:26,951] Trial 190 finished with values: [0.31725904404059496, 0.6349180169686107] and parameters: {'n_neighbors': 23, 'n_components': 13, 'min_dist': 0.13, 'min_cluster_size': 4, 'min_samples': 12, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 21/21 [00:00<00:00, 400.94it/s]

Trial 191: DBCV=0.565, CCC=0.640
[I 2025-12-22 20:06:37,580] Trial 191 finished with values: [0.639544468619351, 0.5648551157567135] and parameters: {'n_neighbors': 39, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 22/22 [00:00<00:00, 403.58it/s]

Trial 192: DBCV=0.487, CCC=0.520
[I 2025-12-22 20:06:47,812] Trial 192 finished with values: [0.5203369735931661, 0.48680080854761637] and parameters: {'n_neighbors': 48, 'n_components': 4, 'min_dist': 0.2, 'min_cluster_size': 16, 'min_samples': 18, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 12/12 [00:00<00:00, 371.30it/s]

Trial 193: DBCV=0.348, CCC=0.695
[I 2025-12-22 20:06:57,761] Trial 193 finished with values: [0.6945244339506447, 0.34772096517437223] and parameters: {'n_neighbors': 41, 'n_components': 3, 'min_dist': 0.18, 'min_cluster_size': 36, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

  0%|          | 0/95 [00:00<?, ?it/s]
 47%|████▋     | 45/95 [00:00<00:00, 443.86it/s]
100%|██████████| 95/95 [00:00<00:00, 418.60it/s]

Trial 194: DBCV=0.553, CCC=0.301
[I 2025-12-22 20:07:08,396] Trial 194 finished with values: [0.30089894288816466, 0.5533558386168699] and parameters: {'n_neighbors': 14, 'n_components': 11, 'min_dist': 0.08, 'min_cluster_size': 9, 'min_samples': 3, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 7/7 [00:00<00:00, 412.39it/s]

Trial 195: DBCV=0.355, CCC=0.717
[I 2025-12-22 20:07:18,656] Trial 195 finished with values: [0.7169168917318761, 0.3548935319475567] and parameters: {'n_neighbors': 23, 'n_components': 10, 'min_dist': 0.1, 'min_cluster_size': 48, 'min_samples': 20, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 20/20 [00:00<00:00, 418.07it/s]

Trial 196: DBCV=0.458, CCC=0.549
[I 2025-12-22 20:07:28,829] Trial 196 finished with values: [0.5488292528138383, 0.4581233649720172] and parameters: {'n_neighbors': 23, 'n_components': 9, 'min_dist': 0.1, 'min_cluster_size': 30, 'min_samples': 13, 'cluster_selection_epsilon': 0.24}.

  0%|          | 0/90 [00:00<?, ?it/s]
 50%|█████     | 45/90 [00:00<00:00, 441.28it/s]
100%|██████████| 90/90 [00:00<00:00, 415.95it/s]

Trial 197: DBCV=0.554, CCC=0.321
[I 2025-12-22 20:07:39,626] Trial 197 finished with values: [0.32129531461902944, 0.5544373968516983] and parameters: {'n_neighbors': 37, 'n_components': 5, 'min_dist': 0.04, 'min_cluster_size': 5, 'min_samples': 4, 'cluster_selection_epsilon': 0.29}.

  0%|          | 0/47 [00:00<?, ?it/s]
100%|██████████| 47/47 [00:00<00:00, 398.53it/s]

Trial 198: DBCV=0.592, CCC=0.349
[I 2025-12-22 20:07:48,142] Trial 198 finished with values: [0.3491434900129541, 0.5924533883264695] and parameters: {'n_neighbors': 3, 'n_components': 10, 'min_dist': 0.0, 'min_cluster_size': 18, 'min_samples': 4, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 9/9 [00:00<00:00, 417.62it/s]

Trial 199: DBCV=0.049, CCC=0.674
[I 2025-12-22 20:07:58,603] Trial 199 finished with values: [0.6743129561761361, 0.048790539059139874] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.15, 'min_cluster_size': 45, 'min_samples': 3, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 22/22 [00:00<00:00, 402.64it/s]

Trial 200: DBCV=0.575, CCC=0.568
[I 2025-12-22 20:08:09,181] Trial 200 finished with values: [0.5678426884982593, 0.5752048568213773] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.0}.

  0%|          | 0/50 [00:00<?, ?it/s]
100%|██████████| 50/50 [00:00<00:00, 410.09it/s]

Trial 201: DBCV=0.601, CCC=0.386
[I 2025-12-22 20:08:19,412] Trial 201 finished with values: [0.3864531957155523, 0.6012312611457252] and parameters: {'n_neighbors': 23, 'n_components': 8, 'min_dist': 0.11, 'min_cluster_size': 11, 'min_samples': 12, 'cluster_selection_epsilon': 0.25}.

  0%|          | 0/57 [00:00<?, ?it/s]
100%|██████████| 57/57 [00:00<00:00, 418.38it/s]

Trial 202: DBCV=0.549, CCC=0.417
[I 2025-12-22 20:08:29,791] Trial 202 finished with values: [0.4169536770884364, 0.5487085095092922] and parameters: {'n_neighbors': 23, 'n_components': 7, 'min_dist': 0.26, 'min_cluster_size': 11, 'min_samples': 9, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 1/1 [00:00<00:00, 329.20it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 203: DBCV=0.210, CCC=0.000
[I 2025-12-22 20:08:39,516] Trial 203 finished with values: [0.0, 0.20997738526772067] and parameters: {'n_neighbors': 10, 'n_components': 9, 'min_dist': 0.18, 'min_cluster_size': 30, 'min_samples': 20, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 17/17 [00:00<00:00, 419.38it/s]

Trial 204: DBCV=0.525, CCC=0.687
[I 2025-12-22 20:08:50,274] Trial 204 finished with values: [0.6873463576052914, 0.5253004792016508] and parameters: {'n_neighbors': 28, 'n_components': 12, 'min_dist': 0.08, 'min_cluster_size': 25, 'min_samples': 20, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 7/7 [00:00<00:00, 418.52it/s]

Trial 205: DBCV=0.339, CCC=0.552
[I 2025-12-22 20:09:00,792] Trial 205 finished with values: [0.5521211775926175, 0.3393354611166579] and parameters: {'n_neighbors': 28, 'n_components': 11, 'min_dist': 0.29, 'min_cluster_size': 50, 'min_samples': 15, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 26/26 [00:00<00:00, 423.72it/s]

Trial 206: DBCV=0.649, CCC=0.379
[I 2025-12-22 20:09:09,616] Trial 206 finished with values: [0.3788008963915517, 0.6487891247182752] and parameters: {'n_neighbors': 3, 'n_components': 15, 'min_dist': 0.1, 'min_cluster_size': 18, 'min_samples': 20, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 29/29 [00:00<00:00, 433.91it/s]

Trial 207: DBCV=0.500, CCC=0.462
[I 2025-12-22 20:09:21,261] Trial 207 finished with values: [0.46185816929582113, 0.49959757790985265] and parameters: {'n_neighbors': 46, 'n_components': 14, 'min_dist': 0.18, 'min_cluster_size': 5, 'min_samples': 17, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 23/23 [00:00<00:00, 404.24it/s]

Trial 208: DBCV=0.472, CCC=0.505
[I 2025-12-22 20:09:31,407] Trial 208 finished with values: [0.5054505398083895, 0.47241175631305515] and parameters: {'n_neighbors': 34, 'n_components': 5, 'min_dist': 0.01, 'min_cluster_size': 20, 'min_samples': 18, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 20/20 [00:00<00:00, 394.54it/s]

Trial 209: DBCV=0.512, CCC=0.575
[I 2025-12-22 20:09:42,040] Trial 209 finished with values: [0.5753412388291986, 0.5122048687008133] and parameters: {'n_neighbors': 39, 'n_components': 7, 'min_dist': 0.0, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 8/8 [00:00<00:00, 413.43it/s]

Trial 210: DBCV=0.327, CCC=0.720
[I 2025-12-22 20:09:52,199] Trial 210 finished with values: [0.7198309966247858, 0.32724434157058463] and parameters: {'n_neighbors': 23, 'n_components': 10, 'min_dist': 0.11, 'min_cluster_size': 48, 'min_samples': 8, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/43 [00:00<?, ?it/s]
100%|██████████| 43/43 [00:00<00:00, 405.47it/s]

Trial 211: DBCV=0.611, CCC=0.450
[I 2025-12-22 20:10:02,753] Trial 211 finished with values: [0.44975043162411205, 0.6107568119322135] and parameters: {'n_neighbors': 48, 'n_components': 5, 'min_dist': 0.05, 'min_cluster_size': 12, 'min_samples': 13, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 3/3 [00:00<00:00, 156.77it/s]

Trial 212: DBCV=-0.155, CCC=0.992
[I 2025-12-22 20:10:12,826] Trial 212 finished with values: [0.992244475854761, -0.1553117145124827] and parameters: {'n_neighbors': 34, 'n_components': 4, 'min_dist': 0.13, 'min_cluster_size': 48, 'min_samples': 17, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 36/36 [00:00<00:00, 430.30it/s]

Trial 213: DBCV=0.595, CCC=0.375
[I 2025-12-22 20:10:21,027] Trial 213 finished with values: [0.3746844254517546, 0.5952208894044515] and parameters: {'n_neighbors': 3, 'n_components': 5, 'min_dist': 0.01, 'min_cluster_size': 20, 'min_samples': 19, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 40/40 [00:00<00:00, 417.10it/s]

Trial 214: DBCV=0.528, CCC=0.351
[I 2025-12-22 20:10:29,856] Trial 214 finished with values: [0.35061587466638505, 0.5284384067521234] and parameters: {'n_neighbors': 3, 'n_components': 15, 'min_dist': 0.19, 'min_cluster_size': 18, 'min_samples': 6, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 7/7 [00:00<00:00, 419.13it/s]

Trial 215: DBCV=0.372, CCC=0.697
[I 2025-12-22 20:10:40,102] Trial 215 finished with values: [0.6968694944981132, 0.3719613299683981] and parameters: {'n_neighbors': 25, 'n_components': 9, 'min_dist': 0.09, 'min_cluster_size': 49, 'min_samples': 14, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 16/16 [00:00<00:00, 377.27it/s]

Trial 216: DBCV=0.501, CCC=0.653
[I 2025-12-22 20:10:49,891] Trial 216 finished with values: [0.6534716042596098, 0.5009864678631667] and parameters: {'n_neighbors': 30, 'n_components': 4, 'min_dist': 0.18, 'min_cluster_size': 23, 'min_samples': 19, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 18/18 [00:00<00:00, 424.22it/s]

Trial 217: DBCV=0.378, CCC=0.609
[I 2025-12-22 20:11:00,783] Trial 217 finished with values: [0.6089462511763374, 0.3784194902245961] and parameters: {'n_neighbors': 28, 'n_components': 10, 'min_dist': 0.11, 'min_cluster_size': 30, 'min_samples': 16, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 13/13 [00:00<00:00, 419.54it/s]

Trial 218: DBCV=0.532, CCC=0.709
[I 2025-12-22 20:11:11,105] Trial 218 finished with values: [0.7087970796357072, 0.5323747933299404] and parameters: {'n_neighbors': 28, 'n_components': 9, 'min_dist': 0.14, 'min_cluster_size': 30, 'min_samples': 20, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 18/18 [00:00<00:00, 391.18it/s]

Trial 219: DBCV=0.435, CCC=0.643
[I 2025-12-22 20:11:20,861] Trial 219 finished with values: [0.6425857700782241, 0.4348549811064045] and parameters: {'n_neighbors': 25, 'n_components': 4, 'min_dist': 0.11, 'min_cluster_size': 23, 'min_samples': 19, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 21/21 [00:00<00:00, 385.15it/s]

Trial 220: DBCV=0.565, CCC=0.640
[I 2025-12-22 20:11:31,614] Trial 220 finished with values: [0.639544468619351, 0.5648551157567135] and parameters: {'n_neighbors': 39, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 8/8 [00:00<00:00, 409.73it/s]

Trial 221: DBCV=0.391, CCC=0.666
[I 2025-12-22 20:11:42,740] Trial 221 finished with values: [0.6658138804200454, 0.3908944698746203] and parameters: {'n_neighbors': 42, 'n_components': 11, 'min_dist': 0.01, 'min_cluster_size': 50, 'min_samples': 15, 'cluster_selection_epsilon': 0.15}.

  0%|          | 0/76 [00:00<?, ?it/s]
100%|██████████| 76/76 [00:00<00:00, 414.69it/s]

Trial 222: DBCV=0.637, CCC=0.286
[I 2025-12-22 20:11:53,389] Trial 222 finished with values: [0.28569704946895086, 0.6369977927497036] and parameters: {'n_neighbors': 28, 'n_components': 6, 'min_dist': 0.1, 'min_cluster_size': 5, 'min_samples': 9, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 34/34 [00:00<00:00, 416.70it/s]

Trial 223: DBCV=0.527, CCC=0.508
[I 2025-12-22 20:12:02,708] Trial 223 finished with values: [0.5077217185594439, 0.5268483058385321] and parameters: {'n_neighbors': 7, 'n_components': 11, 'min_dist': 0.01, 'min_cluster_size': 20, 'min_samples': 15, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 13/13 [00:00<00:00, 377.21it/s]

Trial 224: DBCV=0.345, CCC=0.684
[I 2025-12-22 20:12:12,766] Trial 224 finished with values: [0.6841537980625908, 0.3452743534905994] and parameters: {'n_neighbors': 34, 'n_components': 5, 'min_dist': 0.08, 'min_cluster_size': 37, 'min_samples': 13, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 16/16 [00:00<00:00, 429.72it/s]

Trial 225: DBCV=0.425, CCC=0.544
[I 2025-12-22 20:12:22,981] Trial 225 finished with values: [0.5443154003235994, 0.4248453133395124] and parameters: {'n_neighbors': 41, 'n_components': 5, 'min_dist': 0.29, 'min_cluster_size': 23, 'min_samples': 15, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 31/31 [00:00<00:00, 407.41it/s]

Trial 226: DBCV=0.609, CCC=0.398
[I 2025-12-22 20:12:31,607] Trial 226 finished with values: [0.3979269826774238, 0.6085902746491095] and parameters: {'n_neighbors': 3, 'n_components': 12, 'min_dist': 0.08, 'min_cluster_size': 18, 'min_samples': 20, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 27/27 [00:00<00:00, 403.27it/s]

Trial 227: DBCV=0.576, CCC=0.565
[I 2025-12-22 20:12:42,024] Trial 227 finished with values: [0.5648514649576315, 0.5755312526855586] and parameters: {'n_neighbors': 30, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 12, 'min_samples': 18, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 328.22it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 228: DBCV=0.151, CCC=0.000
[I 2025-12-22 20:12:51,968] Trial 228 finished with values: [0.0, 0.15052405786244802] and parameters: {'n_neighbors': 14, 'n_components': 7, 'min_dist': 0.09, 'min_cluster_size': 49, 'min_samples': 14, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 21/21 [00:00<00:00, 426.46it/s]

Trial 229: DBCV=0.447, CCC=0.608
[I 2025-12-22 20:13:03,188] Trial 229 finished with values: [0.6079766639901268, 0.44712882736860915] and parameters: {'n_neighbors': 42, 'n_components': 12, 'min_dist': 0.05, 'min_cluster_size': 23, 'min_samples': 13, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 20/20 [00:00<00:00, 398.20it/s]

Trial 230: DBCV=0.533, CCC=0.604
[I 2025-12-22 20:13:13,638] Trial 230 finished with values: [0.604440360060548, 0.5326897340306075] and parameters: {'n_neighbors': 28, 'n_components': 10, 'min_dist': 0.1, 'min_cluster_size': 22, 'min_samples': 20, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 1/1 [00:00<00:00, 322.07it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 231: DBCV=0.018, CCC=0.000
[I 2025-12-22 20:13:25,423] Trial 231 finished with values: [0.0, 0.018296327373053263] and parameters: {'n_neighbors': 42, 'n_components': 13, 'min_dist': 0.14, 'min_cluster_size': 50, 'min_samples': 7, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 21/21 [00:00<00:00, 426.96it/s]

Trial 232: DBCV=0.567, CCC=0.483
[I 2025-12-22 20:13:33,730] Trial 232 finished with values: [0.48289165472849405, 0.5669073273286481] and parameters: {'n_neighbors': 3, 'n_components': 11, 'min_dist': 0.19, 'min_cluster_size': 22, 'min_samples': 20, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 24/24 [00:00<00:00, 428.81it/s]

Trial 233: DBCV=0.277, CCC=0.583
[I 2025-12-22 20:13:44,759] Trial 233 finished with values: [0.5833362144812022, 0.27718075039311457] and parameters: {'n_neighbors': 48, 'n_components': 10, 'min_dist': 0.05, 'min_cluster_size': 20, 'min_samples': 13, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 12/12 [00:00<00:00, 428.81it/s]

Trial 234: DBCV=0.309, CCC=0.449
[I 2025-12-22 20:13:53,916] Trial 234 finished with values: [0.44946514677763216, 0.3093059416294611] and parameters: {'n_neighbors': 7, 'n_components': 11, 'min_dist': 0.09, 'min_cluster_size': 50, 'min_samples': 14, 'cluster_selection_epsilon': 0.0}.

  0%|          | 0/60 [00:00<?, ?it/s]
100%|██████████| 60/60 [00:00<00:00, 403.83it/s]

Trial 235: DBCV=0.634, CCC=0.309
[I 2025-12-22 20:14:04,408] Trial 235 finished with values: [0.309360349040225, 0.6337142133753413] and parameters: {'n_neighbors': 46, 'n_components': 4, 'min_dist': 0.0, 'min_cluster_size': 12, 'min_samples': 10, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 20/20 [00:00<00:00, 284.23it/s]

Trial 236: DBCV=0.450, CCC=0.615
[I 2025-12-22 20:14:14,686] Trial 236 finished with values: [0.6152897462266459, 0.45009550740031545] and parameters: {'n_neighbors': 33, 'n_components': 5, 'min_dist': 0.1, 'min_cluster_size': 23, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 23/23 [00:00<00:00, 407.52it/s]

Trial 237: DBCV=0.639, CCC=0.562
[I 2025-12-22 20:14:26,010] Trial 237 finished with values: [0.5621177815883566, 0.6393512115404026] and parameters: {'n_neighbors': 28, 'n_components': 15, 'min_dist': 0.0, 'min_cluster_size': 16, 'min_samples': 20, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 19/19 [00:00<00:00, 381.70it/s]

Trial 238: DBCV=0.581, CCC=0.497
[I 2025-12-22 20:14:34,664] Trial 238 finished with values: [0.49705265176602664, 0.5813385996805979] and parameters: {'n_neighbors': 3, 'n_components': 15, 'min_dist': 0.19, 'min_cluster_size': 20, 'min_samples': 20, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 23/23 [00:00<00:00, 393.30it/s]

Trial 239: DBCV=0.496, CCC=0.498
[I 2025-12-22 20:14:45,183] Trial 239 finished with values: [0.49784240166492205, 0.49616078140248093] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 20, 'min_samples': 19, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 16/16 [00:00<00:00, 371.84it/s]

Trial 240: DBCV=0.408, CCC=0.733
[I 2025-12-22 20:14:55,756] Trial 240 finished with values: [0.7331776631128152, 0.40821242604100577] and parameters: {'n_neighbors': 42, 'n_components': 8, 'min_dist': 0.09, 'min_cluster_size': 27, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 18/18 [00:00<00:00, 426.68it/s]

Trial 241: DBCV=0.503, CCC=0.620
[I 2025-12-22 20:15:06,085] Trial 241 finished with values: [0.6204578652537466, 0.5029388316650429] and parameters: {'n_neighbors': 25, 'n_components': 10, 'min_dist': 0.15, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 10/10 [00:00<00:00, 316.39it/s]

Trial 242: DBCV=0.255, CCC=0.713
[I 2025-12-22 20:15:16,149] Trial 242 finished with values: [0.7129670602982394, 0.25481319487748416] and parameters: {'n_neighbors': 44, 'n_components': 4, 'min_dist': 0.07, 'min_cluster_size': 44, 'min_samples': 20, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 22/22 [00:00<00:00, 399.54it/s]

Trial 243: DBCV=0.579, CCC=0.595
[I 2025-12-22 20:15:26,930] Trial 243 finished with values: [0.5947983478689394, 0.5790289615442378] and parameters: {'n_neighbors': 41, 'n_components': 10, 'min_dist': 0.0, 'min_cluster_size': 23, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 27/27 [00:00<00:00, 391.39it/s]

Trial 244: DBCV=0.596, CCC=0.449
[I 2025-12-22 20:15:38,845] Trial 244 finished with values: [0.44861144379968326, 0.5956295063407151] and parameters: {'n_neighbors': 39, 'n_components': 15, 'min_dist': 0.03, 'min_cluster_size': 16, 'min_samples': 18, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 29/29 [00:00<00:00, 336.36it/s]

Trial 245: DBCV=0.590, CCC=0.421
[I 2025-12-22 20:15:49,162] Trial 245 finished with values: [0.42051645642382496, 0.5902856805798604] and parameters: {'n_neighbors': 37, 'n_components': 5, 'min_dist': 0.01, 'min_cluster_size': 20, 'min_samples': 18, 'cluster_selection_epsilon': 0.06}.

  0%|          | 0/61 [00:00<?, ?it/s]
100%|██████████| 61/61 [00:00<00:00, 423.06it/s]

Trial 246: DBCV=0.593, CCC=0.371
[I 2025-12-22 20:15:59,663] Trial 246 finished with values: [0.37075749927485935, 0.593263261156566] and parameters: {'n_neighbors': 46, 'n_components': 4, 'min_dist': 0.11, 'min_cluster_size': 5, 'min_samples': 10, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 2/2 [00:00<00:00, 177.16it/s]

Trial 247: DBCV=0.133, CCC=0.852
[I 2025-12-22 20:16:10,252] Trial 247 finished with values: [0.8523827741968857, 0.13289504000187055] and parameters: {'n_neighbors': 14, 'n_components': 14, 'min_dist': 0.26, 'min_cluster_size': 13, 'min_samples': 19, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 27/27 [00:00<00:00, 431.10it/s]

Trial 248: DBCV=0.452, CCC=0.518
[I 2025-12-22 20:16:20,778] Trial 248 finished with values: [0.5182836480777032, 0.4516504686654411] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 20, 'min_samples': 8, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 15/15 [00:00<00:00, 379.25it/s]

Trial 249: DBCV=0.359, CCC=0.679
[I 2025-12-22 20:16:31,610] Trial 249 finished with values: [0.6785225014287003, 0.3594213424596064] and parameters: {'n_neighbors': 46, 'n_components': 7, 'min_dist': 0.0, 'min_cluster_size': 45, 'min_samples': 10, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 5/5 [00:00<00:00, 282.82it/s]

Trial 250: DBCV=-0.048, CCC=0.884
[I 2025-12-22 20:16:41,786] Trial 250 finished with values: [0.8835861813073081, -0.04777152402600421] and parameters: {'n_neighbors': 48, 'n_components': 4, 'min_dist': 0.2, 'min_cluster_size': 48, 'min_samples': 20, 'cluster_selection_epsilon': 0.15}.

  0%|          | 0/50 [00:00<?, ?it/s]
100%|██████████| 50/50 [00:00<00:00, 402.25it/s]

Trial 251: DBCV=0.554, CCC=0.305
[I 2025-12-22 20:16:51,405] Trial 251 finished with values: [0.3054082516162606, 0.553764349864215] and parameters: {'n_neighbors': 10, 'n_components': 6, 'min_dist': 0.18, 'min_cluster_size': 14, 'min_samples': 6, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 28/28 [00:00<00:00, 397.74it/s]

Trial 252: DBCV=0.559, CCC=0.582
[I 2025-12-22 20:17:00,889] Trial 252 finished with values: [0.5818258339385828, 0.5585239402562193] and parameters: {'n_neighbors': 14, 'n_components': 5, 'min_dist': 0.13, 'min_cluster_size': 20, 'min_samples': 19, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 29/29 [00:00<00:00, 399.84it/s]

Trial 253: DBCV=0.597, CCC=0.591
[I 2025-12-22 20:17:10,745] Trial 253 finished with values: [0.5907395311528456, 0.5968143827096142] and parameters: {'n_neighbors': 28, 'n_components': 4, 'min_dist': 0.1, 'min_cluster_size': 6, 'min_samples': 20, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 12/12 [00:00<00:00, 321.13it/s]

Trial 254: DBCV=0.392, CCC=0.662
[I 2025-12-22 20:17:21,520] Trial 254 finished with values: [0.6620880384007609, 0.3924944660671077] and parameters: {'n_neighbors': 39, 'n_components': 10, 'min_dist': 0.08, 'min_cluster_size': 39, 'min_samples': 18, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 8/8 [00:00<00:00, 416.23it/s]

Trial 255: DBCV=0.281, CCC=0.623
[I 2025-12-22 20:17:31,878] Trial 255 finished with values: [0.623073888026724, 0.28096395701981836] and parameters: {'n_neighbors': 28, 'n_components': 10, 'min_dist': 0.1, 'min_cluster_size': 48, 'min_samples': 20, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 15/15 [00:00<00:00, 422.68it/s]

Trial 256: DBCV=0.288, CCC=0.611
[I 2025-12-22 20:17:42,219] Trial 256 finished with values: [0.6111479879126576, 0.28828005270280205] and parameters: {'n_neighbors': 35, 'n_components': 8, 'min_dist': 0.0, 'min_cluster_size': 42, 'min_samples': 3, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 30/30 [00:00<00:00, 378.06it/s]

Trial 257: DBCV=0.490, CCC=0.554
[I 2025-12-22 20:17:52,714] Trial 257 finished with values: [0.5539179684827499, 0.49043730587873247] and parameters: {'n_neighbors': 14, 'n_components': 14, 'min_dist': 0.08, 'min_cluster_size': 16, 'min_samples': 18, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 23/23 [00:00<00:00, 392.10it/s]

Trial 258: DBCV=0.496, CCC=0.498
[I 2025-12-22 20:18:03,229] Trial 258 finished with values: [0.49784240166492205, 0.49616078140248093] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 22, 'min_samples': 19, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 33/33 [00:00<00:00, 406.52it/s]

Trial 259: DBCV=0.599, CCC=0.535
[I 2025-12-22 20:18:13,206] Trial 259 finished with values: [0.5354233726860151, 0.5989175807469301] and parameters: {'n_neighbors': 28, 'n_components': 4, 'min_dist': 0.1, 'min_cluster_size': 2, 'min_samples': 20, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 21/21 [00:00<00:00, 400.96it/s]

Trial 260: DBCV=0.565, CCC=0.640
[I 2025-12-22 20:18:23,845] Trial 260 finished with values: [0.639544468619351, 0.5648551157567135] and parameters: {'n_neighbors': 39, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 16/16 [00:00<00:00, 426.88it/s]

Trial 261: DBCV=0.484, CCC=0.668
[I 2025-12-22 20:18:33,750] Trial 261 finished with values: [0.6679462023038819, 0.48430658561681195] and parameters: {'n_neighbors': 28, 'n_components': 5, 'min_dist': 0.1, 'min_cluster_size': 22, 'min_samples': 20, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 22/22 [00:00<00:00, 387.67it/s]

Trial 262: DBCV=0.556, CCC=0.625
[I 2025-12-22 20:18:44,315] Trial 262 finished with values: [0.62523497056499, 0.5558610322980752] and parameters: {'n_neighbors': 28, 'n_components': 10, 'min_dist': 0.1, 'min_cluster_size': 16, 'min_samples': 20, 'cluster_selection_epsilon': 0.1}.

  0%|          | 0/57 [00:00<?, ?it/s]
100%|██████████| 57/57 [00:00<00:00, 395.77it/s]

Trial 263: DBCV=0.605, CCC=0.303
[I 2025-12-22 20:18:54,996] Trial 263 finished with values: [0.30252547059879004, 0.6046208254149379] and parameters: {'n_neighbors': 14, 'n_components': 14, 'min_dist': 0.08, 'min_cluster_size': 13, 'min_samples': 9, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 21/21 [00:00<00:00, 402.14it/s]

Trial 264: DBCV=0.294, CCC=0.634
[I 2025-12-22 20:19:05,559] Trial 264 finished with values: [0.6337349414213638, 0.2935411020678331] and parameters: {'n_neighbors': 48, 'n_components': 5, 'min_dist': 0.11, 'min_cluster_size': 23, 'min_samples': 13, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 34/34 [00:00<00:00, 410.53it/s]

Trial 265: DBCV=0.595, CCC=0.436
[I 2025-12-22 20:19:14,369] Trial 265 finished with values: [0.4357327762162174, 0.594920147965466] and parameters: {'n_neighbors': 8, 'n_components': 3, 'min_dist': 0.2, 'min_cluster_size': 2, 'min_samples': 20, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 1/1 [00:00<00:00, 174.22it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 266: DBCV=0.264, CCC=0.000
[I 2025-12-22 20:19:24,607] Trial 266 finished with values: [0.0, 0.2635793043639817] and parameters: {'n_neighbors': 14, 'n_components': 10, 'min_dist': 0.09, 'min_cluster_size': 40, 'min_samples': 19, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 8/8 [00:00<00:00, 417.41it/s]

Trial 267: DBCV=0.113, CCC=0.729
[I 2025-12-22 20:19:34,809] Trial 267 finished with values: [0.7289625826937396, 0.11274229401861248] and parameters: {'n_neighbors': 25, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 47, 'min_samples': 5, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 29/29 [00:00<00:00, 432.39it/s]

Trial 268: DBCV=0.260, CCC=0.416
[I 2025-12-22 20:19:44,181] Trial 268 finished with values: [0.41573835934617454, 0.2603524333158017] and parameters: {'n_neighbors': 14, 'n_components': 4, 'min_dist': 0.1, 'min_cluster_size': 33, 'min_samples': 2, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 22/22 [00:00<00:00, 402.47it/s]

Trial 269: DBCV=0.577, CCC=0.627
[I 2025-12-22 20:19:55,493] Trial 269 finished with values: [0.6273835166894628, 0.5766839890316099] and parameters: {'n_neighbors': 28, 'n_components': 15, 'min_dist': 0.12, 'min_cluster_size': 16, 'min_samples': 19, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 31/31 [00:00<00:00, 415.30it/s]

Trial 270: DBCV=0.529, CCC=0.528
[I 2025-12-22 20:20:05,912] Trial 270 finished with values: [0.5275884655240202, 0.5287707949901855] and parameters: {'n_neighbors': 46, 'n_components': 4, 'min_dist': 0.08, 'min_cluster_size': 5, 'min_samples': 18, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 29/29 [00:00<00:00, 402.09it/s]

Trial 271: DBCV=0.612, CCC=0.463
[I 2025-12-22 20:20:16,707] Trial 271 finished with values: [0.4629522669394137, 0.6116942542356554] and parameters: {'n_neighbors': 41, 'n_components': 10, 'min_dist': 0.0, 'min_cluster_size': 16, 'min_samples': 18, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 11/11 [00:00<00:00, 370.82it/s]

Trial 272: DBCV=0.444, CCC=0.715
[I 2025-12-22 20:20:27,132] Trial 272 finished with values: [0.7154678541854812, 0.44400345900415916] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.11, 'min_cluster_size': 37, 'min_samples': 18, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 8/8 [00:00<00:00, 424.59it/s]

Trial 273: DBCV=0.314, CCC=0.615
[I 2025-12-22 20:20:37,747] Trial 273 finished with values: [0.6153128343253716, 0.3138640633881305] and parameters: {'n_neighbors': 46, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 50, 'min_samples': 5, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 8/8 [00:00<00:00, 195.80it/s]

Trial 274: DBCV=0.464, CCC=0.694
[I 2025-12-22 20:20:49,057] Trial 274 finished with values: [0.6936850979708296, 0.46373559750361953] and parameters: {'n_neighbors': 48, 'n_components': 12, 'min_dist': 0.08, 'min_cluster_size': 48, 'min_samples': 17, 'cluster_selection_epsilon': 0.14}.

  0%|          | 0/54 [00:00<?, ?it/s]
100%|██████████| 54/54 [00:00<00:00, 410.90it/s]

Trial 275: DBCV=0.551, CCC=0.403
[I 2025-12-22 20:21:00,463] Trial 275 finished with values: [0.40265265113881554, 0.5513883503115256] and parameters: {'n_neighbors': 48, 'n_components': 11, 'min_dist': 0.1, 'min_cluster_size': 12, 'min_samples': 8, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 9/9 [00:00<00:00, 414.95it/s]

Trial 276: DBCV=0.310, CCC=0.664
[I 2025-12-22 20:21:10,819] Trial 276 finished with values: [0.6643934444521632, 0.31043093765402185] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.08, 'min_cluster_size': 50, 'min_samples': 5, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 19/19 [00:00<00:00, 394.29it/s]

Trial 277: DBCV=0.553, CCC=0.618
[I 2025-12-22 20:21:21,452] Trial 277 finished with values: [0.6184272363828384, 0.5525232625667857] and parameters: {'n_neighbors': 41, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 22, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 6/6 [00:00<00:00, 416.94it/s]

Trial 278: DBCV=0.356, CCC=0.688
[I 2025-12-22 20:21:32,509] Trial 278 finished with values: [0.6878190854936821, 0.3559444952475467] and parameters: {'n_neighbors': 42, 'n_components': 12, 'min_dist': 0.16, 'min_cluster_size': 49, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 13/13 [00:00<00:00, 423.33it/s]

Trial 279: DBCV=0.393, CCC=0.541
[I 2025-12-22 20:21:43,797] Trial 279 finished with values: [0.5405348430353066, 0.39258229907908504] and parameters: {'n_neighbors': 48, 'n_components': 12, 'min_dist': 0.26, 'min_cluster_size': 25, 'min_samples': 20, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 22/22 [00:00<00:00, 391.42it/s]

Trial 280: DBCV=0.573, CCC=0.599
[I 2025-12-22 20:21:53,641] Trial 280 finished with values: [0.5985592233614005, 0.5734783801471534] and parameters: {'n_neighbors': 28, 'n_components': 4, 'min_dist': 0.1, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 19/19 [00:00<00:00, 424.76it/s]

Trial 281: DBCV=0.484, CCC=0.441
[I 2025-12-22 20:22:02,596] Trial 281 finished with values: [0.44134867084589663, 0.48444920605164793] and parameters: {'n_neighbors': 4, 'n_components': 15, 'min_dist': 0.01, 'min_cluster_size': 37, 'min_samples': 10, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 21/21 [00:00<00:00, 388.00it/s]

Trial 282: DBCV=0.384, CCC=0.589
[I 2025-12-22 20:22:13,117] Trial 282 finished with values: [0.589373064793465, 0.38431713610615126] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.0, 'min_cluster_size': 22, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 23/23 [00:00<00:00, 404.84it/s]

Trial 283: DBCV=0.400, CCC=0.581
[I 2025-12-22 20:22:24,332] Trial 283 finished with values: [0.5807563258949169, 0.40021093349054826] and parameters: {'n_neighbors': 25, 'n_components': 15, 'min_dist': 0.12, 'min_cluster_size': 16, 'min_samples': 19, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/43 [00:00<?, ?it/s]
100%|██████████| 43/43 [00:00<00:00, 407.45it/s]

Trial 284: DBCV=0.642, CCC=0.383
[I 2025-12-22 20:22:35,631] Trial 284 finished with values: [0.38274746797426157, 0.6421664615463265] and parameters: {'n_neighbors': 42, 'n_components': 12, 'min_dist': 0.05, 'min_cluster_size': 12, 'min_samples': 13, 'cluster_selection_epsilon': 0.11}.

  0%|          | 0/51 [00:00<?, ?it/s]
100%|██████████| 51/51 [00:00<00:00, 426.64it/s]

Trial 285: DBCV=0.558, CCC=0.407
[I 2025-12-22 20:22:46,423] Trial 285 finished with values: [0.4069744764418765, 0.5575643045509007] and parameters: {'n_neighbors': 14, 'n_components': 15, 'min_dist': 0.19, 'min_cluster_size': 9, 'min_samples': 12, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 2/2 [00:00<00:00, 351.55it/s]

Trial 286: DBCV=-0.325, CCC=0.941
[I 2025-12-22 20:22:56,946] Trial 286 finished with values: [0.9413982427444122, -0.3251317501690425] and parameters: {'n_neighbors': 28, 'n_components': 7, 'min_dist': 0.14, 'min_cluster_size': 30, 'min_samples': 20, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 15/15 [00:00<00:00, 424.95it/s]

Trial 287: DBCV=0.423, CCC=0.612
[I 2025-12-22 20:23:07,088] Trial 287 finished with values: [0.6119742786636349, 0.4233620938056933] and parameters: {'n_neighbors': 28, 'n_components': 8, 'min_dist': 0.1, 'min_cluster_size': 30, 'min_samples': 19, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 19/19 [00:00<00:00, 395.12it/s]

Trial 288: DBCV=0.536, CCC=0.591
[I 2025-12-22 20:23:17,853] Trial 288 finished with values: [0.5911059172524554, 0.5363156087110077] and parameters: {'n_neighbors': 41, 'n_components': 10, 'min_dist': 0.1, 'min_cluster_size': 23, 'min_samples': 19, 'cluster_selection_epsilon': 0.26}.

  0%|          | 0/237 [00:00<?, ?it/s]
 22%|██▏       | 52/237 [00:00<00:00, 512.75it/s]
 44%|████▍     | 104/237 [00:00<00:00, 480.61it/s]
 65%|██████▍   | 153/237 [00:00<00:00, 461.88it/s]
100%|██████████| 237/237 [00:00<00:00, 443.06it/s]

Trial 289: DBCV=0.559, CCC=0.216
[I 2025-12-22 20:23:30,948] Trial 289 finished with values: [0.21615709804346117, 0.5587548298910829] and parameters: {'n_neighbors': 30, 'n_components': 7, 'min_dist': 0.28, 'min_cluster_size': 2, 'min_samples': 2, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 2/2 [00:00<00:00, 380.83it/s]

Trial 290: DBCV=0.133, CCC=0.852
[I 2025-12-22 20:23:41,538] Trial 290 finished with values: [0.8523827741968857, 0.13289504000187055] and parameters: {'n_neighbors': 14, 'n_components': 14, 'min_dist': 0.26, 'min_cluster_size': 23, 'min_samples': 19, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 7/7 [00:00<00:00, 411.69it/s]

Trial 291: DBCV=0.420, CCC=0.722
[I 2025-12-22 20:23:52,265] Trial 291 finished with values: [0.7224470088387408, 0.42015008752837957] and parameters: {'n_neighbors': 48, 'n_components': 8, 'min_dist': 0.18, 'min_cluster_size': 50, 'min_samples': 17, 'cluster_selection_epsilon': 0.04}.

  0%|          | 0/68 [00:00<?, ?it/s]
100%|██████████| 68/68 [00:00<00:00, 412.48it/s]

Trial 292: DBCV=0.634, CCC=0.330
[I 2025-12-22 20:24:02,258] Trial 292 finished with values: [0.3303016178443976, 0.6337455124264559] and parameters: {'n_neighbors': 12, 'n_components': 10, 'min_dist': 0.1, 'min_cluster_size': 4, 'min_samples': 11, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 33/33 [00:00<00:00, 409.70it/s]

Trial 293: DBCV=0.601, CCC=0.391
[I 2025-12-22 20:24:13,125] Trial 293 finished with values: [0.39054648309206436, 0.601474713221764] and parameters: {'n_neighbors': 45, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 2, 'min_samples': 19, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 38/38 [00:00<00:00, 418.22it/s]

Trial 294: DBCV=0.503, CCC=0.441
[I 2025-12-22 20:24:23,811] Trial 294 finished with values: [0.44091133452251263, 0.5030594549295541] and parameters: {'n_neighbors': 30, 'n_components': 10, 'min_dist': 0.18, 'min_cluster_size': 12, 'min_samples': 12, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 12/12 [00:00<00:00, 425.60it/s]

Trial 295: DBCV=0.318, CCC=0.682
[I 2025-12-22 20:24:35,243] Trial 295 finished with values: [0.6822126524343648, 0.31774962611070257] and parameters: {'n_neighbors': 41, 'n_components': 14, 'min_dist': 0.26, 'min_cluster_size': 37, 'min_samples': 13, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 24/24 [00:00<00:00, 422.23it/s]

Trial 296: DBCV=0.508, CCC=0.514
[I 2025-12-22 20:24:45,722] Trial 296 finished with values: [0.5139568690419164, 0.5083244839856095] and parameters: {'n_neighbors': 28, 'n_components': 10, 'min_dist': 0.05, 'min_cluster_size': 22, 'min_samples': 14, 'cluster_selection_epsilon': 0.26}.

  0%|          | 0/58 [00:00<?, ?it/s]
100%|██████████| 58/58 [00:00<00:00, 417.55it/s]

Trial 297: DBCV=0.627, CCC=0.409
[I 2025-12-22 20:24:55,749] Trial 297 finished with values: [0.40860027669707527, 0.6268518171601862] and parameters: {'n_neighbors': 14, 'n_components': 9, 'min_dist': 0.05, 'min_cluster_size': 12, 'min_samples': 12, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 1/1 [00:00<00:00, 379.20it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 298: DBCV=-0.282, CCC=0.000
[I 2025-12-22 20:25:06,345] Trial 298 finished with values: [0.0, -0.2819845838539694] and parameters: {'n_neighbors': 48, 'n_components': 4, 'min_dist': 0.2, 'min_cluster_size': 40, 'min_samples': 15, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 17/17 [00:00<00:00, 429.75it/s]

Trial 299: DBCV=0.445, CCC=0.556
[I 2025-12-22 20:25:17,103] Trial 299 finished with values: [0.5561362438069936, 0.44502473835631495] and parameters: {'n_neighbors': 34, 'n_components': 11, 'min_dist': 0.29, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.24}.

In [14]:
df_descriptions = study.trials_dataframe()
df_descriptions.head()

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_cluster_selection_epsilon,params_min_cluster_size,params_min_dist,params_min_samples,params_n_components,params_n_neighbors,user_attrs_ccc_score,user_attrs_dbcv_score,user_attrs_n_clusters,user_attrs_outlier_ratio,system_attrs_NSGAIISampler:generation,state
0,0,0.709518,0.184601,2025-12-22 19:33:23.052038,2025-12-22 19:33:33.929302,0 days 00:00:10.877264,0.10,44,0.02,1,11,38,0.709518,0.184601,14,0.218408,0,COMPLETE
1,1,0.509068,0.346184,2025-12-22 19:33:33.931281,2025-12-22 19:33:43.187271,0 days 00:00:09.255990,0.26,45,0.00,5,10,8,0.509068,0.346184,20,0.203980,0,COMPLETE
2,2,0.682809,0.210071,2025-12-22 19:33:43.189230,2025-12-22 19:33:53.694016,0 days 00:00:10.504786,0.01,43,0.22,13,11,25,0.682809,0.210071,10,0.299502,0,COMPLETE
3,3,0.564501,0.273988,2025-12-22 19:33:53.695705,2025-12-22 19:34:04.784886,0 days 00:00:11.089181,0.26,23,0.10,1,11,42,0.564501,0.273988,30,0.185572,0,COMPLETE
4,4,0.000000,0.039581,2025-12-22 19:34:04.786701,2025-12-22 19:34:14.413644,0 days 00:00:09.626943,0.03,32,0.04,14,2,24,0.000000,0.039581,2,0.044279,0,COMPLETE

In [15]:
import joblib
# Save to a file
joblib.dump(study, "02_251222_multi_clusterdata_descriptions_data_points.pkl")

['02_251222_multi_clusterdata_descriptions_data_points.pkl']

In [16]:
df_descriptions.to_csv("02_251222_multi_clusterdata_descriptions_data_points.csv", index=False)

In [17]:
import optuna.visualization as vis

fig = vis.plot_pareto_front(
    study,
    target_names=["CCC Score", "Number of Clusters"], # Names for Obj 0 and Obj 1
    include_dominated_trials=True  # Set to True to see all points, not just the best frontier
)

fig.update_layout(width=600, height=500)
fig.show()