Run the following command in the terminal:

sbatch --gpus=1 --gres=gpumem:10g --time=05:00:00 --mem-per-cpu=32g --wrap="jupyter nbconvert --to notebook --execute 02_251218_optimizing_number_of_clusters_Apertus-8B-Instruct.ipynb --inplace"

In [1]:
import os
import json
import pandas as pd

directory_path = "./251030_generated_descriptions_Apertus-8B-Instruct-2509s"
data_list = []
# Iterate through all files in the directory
for filename in os.listdir(directory_path):
    if filename.endswith('.json'):
        file_path = os.path.join(directory_path, filename)
        with open(file_path, 'r', encoding='utf-8') as file:
            try:
                data = json.load(file)
                # Ensure it's a dict with 4 key-value pairs
                if isinstance(data, dict):
                    if data["data_point"] == "":
                        print(f"Skipping {filename}, data point empty")
                    
                        continue
                    data_list.append(data)
                else:
                    print(f"Skipping {filename}")
            except json.JSONDecodeError:
                print(f"Skipping {filename}: invalid JSON format.")
                
# Convert list of dicts to DataFrame
df = pd.DataFrame(data_list)
df.tail()

,question,original_source,data_group,data_point,reference_1,reference_2,description,references
2005,What is the meaning of eco-toxicity in relatio...,CPR 2024.pdf,essential environmental characteristics,eco-toxicity,CPR 2024.pdf,BAMB 2019.pdf,Eco-toxicity refers to the harmful effects of...,[{'text': 'ANNEX II Predetermined environmenta...
2006,What is the meaning of freshwater in relation ...,CPR 2024.pdf,essential environmental characteristics,freshwater,CPR 2024.pdf,CPR 2024.pdf,(g) eutrophication aquatic freshwater; \nThis...,[{'text': 'ANNEX II Predetermined environmenta...
2007,What is the meaning of human toxicity cancerog...,CPR 2024.pdf,essential environmental characteristics,human toxicity cancerogenic,CPR 2024.pdf,BAMB 2019.pdf,"Human toxicity, cancerogenic refers to the po...",[{'text': 'ANNEX II Predetermined environmenta...
2008,What is the meaning of human toxicity non-canc...,CPR 2024.pdf,essential environmental characteristics,human toxicity non-cancerogenic,CPR 2024.pdf,BAMB 2019.pdf,Human toxicity non-cancerogenic refers to the...,[{'text': 'ANNEX II Predetermined environmenta...
2009,What is the meaning of land use related impact...,CPR 2024.pdf,essential environmental characteristics,land use related impacts,CPR 2024.pdf,Kebede 2024.pdf,Land use related impacts refer to the effects...,[{'text': 'ANNEX II Predetermined environmenta...

In [2]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import make_scorer
from sentence_transformers import SentenceTransformer


model = SentenceTransformer('./cluster/scratch/svangelova')
description_embeddings = model.encode(df["description"])

In [3]:
import numpy as np
import pandas as pd
import logging
from collections.abc import Iterable
from scipy.sparse import csr_matrix
from scipy.spatial.distance import squareform
from typing import Optional, Union, Tuple


def select_topic_representation(
    ctfidf_embeddings,
    embeddings,
    use_ctfidf: bool = True,
    output_ndarray: bool = False,
):
    """Select the topic representation.

    Arguments:
        ctfidf_embeddings: The c-TF-IDF embedding matrix
        embeddings: The topic embedding matrix
        use_ctfidf: Whether to use the c-TF-IDF representation. If False, topics embedding representation is used, if it
                    exists. Default is True.
        output_ndarray: Whether to convert the selected representation into ndarray
    Raises
        ValueError:
            - If no topic representation was found
            - If c-TF-IDF embeddings are not a numpy array or a scipy.sparse.csr_matrix

    Returns:
        The selected topic representation and a boolean indicating whether it is c-TF-IDF.
    """

    def to_ndarray(array: Union[np.ndarray, csr_matrix]) -> np.ndarray:
        if isinstance(array, csr_matrix):
            return array.toarray()
        return array
    if use_ctfidf:
        if ctfidf_embeddings is None:
            repr_, ctfidf_used = embeddings, False
        else:
            repr_, ctfidf_used = ctfidf_embeddings, True
    else:
        if embeddings is None:
            repr_, ctfidf_used = ctfidf_embeddings, True
        else:
            repr_, ctfidf_used = embeddings, False

    return to_ndarray(repr_) if output_ndarray else repr_, ctfidf_used


def validate_distance_matrix(X, n_samples):
    """Validate the distance matrix and convert it to a condensed distance matrix
    if necessary.

    A valid distance matrix is either a square matrix of shape (n_samples, n_samples)
    with zeros on the diagonal and non-negative values or condensed distance matrix
    of shape (n_samples * (n_samples - 1) / 2,) containing the upper triangular of the
    distance matrix.

    Arguments:
        X: Distance matrix to validate.
        n_samples: Number of samples in the dataset.

    Returns:
        X: Validated distance matrix.

    Raises:
        ValueError: If the distance matrix is not valid.
    """
    # Make sure it is the 1-D condensed distance matrix with zeros on the diagonal
    s = X.shape
    if len(s) == 1:
        # check it has correct size
        n = s[0]
        if n != (n_samples * (n_samples - 1) / 2):
            raise ValueError("The condensed distance matrix must have " "shape (n*(n-1)/2,).")
    elif len(s) == 2:
        # check it has correct size
        if (s[0] != n_samples) or (s[1] != n_samples):
            raise ValueError("The distance matrix must be of shape " "(n, n) where n is the number of samples.")
        # force zero diagonal and convert to condensed
        np.fill_diagonal(X, 0)
        X = squareform(X)
    else:
        raise ValueError(
            "The distance matrix must be either a 1-D condensed "
            "distance matrix of shape (n*(n-1)/2,) or a "
            "2-D square distance matrix of shape (n, n)."
            "where n is the number of documents."
            "Got a distance matrix of shape %s" % str(s)
        )

    # Make sure its entries are non-negative
    if np.any(X < 0):
        raise ValueError("Distance matrix cannot contain negative values.")

    return X

In [8]:
import optuna
import hdbscan
import numpy as np
from umap import UMAP
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.vectorizers import ClassTfidfTransformer
from sklearn.datasets import fetch_20newsgroups
from scipy.cluster import hierarchy as sch
from scipy.cluster.hierarchy import linkage, cophenet
from scipy.spatial.distance import pdist
from hdbscan.validity import validity_index
from sklearn.metrics.pairwise import cosine_similarity

def calculate_ccc(topic_model, docs):
    # Hierarchical topics
    linkage_function = lambda x: sch.linkage(x, "ward", optimal_ordering=True)
    _distance_function = lambda x: 1 - cosine_similarity(x)
    
    hierarchical_topics = topic_model.hierarchical_topics(docs, 
                                                          linkage_function=linkage_function, 
                                                          distance_function=_distance_function, 
                                                          use_ctfidf=True)
    
    # Select topic embeddings
    use_ctfidf = True

    # Calculate distance
    embeddings = select_topic_representation(topic_model.c_tf_idf_, topic_model.topic_embeddings_, use_ctfidf)[0][
        topic_model._outliers :
    ]
    distance_function = lambda x: validate_distance_matrix(_distance_function(x), embeddings.shape[0])
    
    dists = distance_function(embeddings)
    linkage_matrix = linkage_function(dists)

    ccc_score, _ = cophenet(linkage_matrix, dists)

    if np.isnan(ccc_score):
        return 0.0

    return ccc_score


ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

def objective(trial, docs, embeddings):
    # --- Hyperparameters to Optimize ---
    
    # UMAP Parameters
    n_neighbors = trial.suggest_int('n_neighbors', 2, 50)
    n_components = trial.suggest_int('n_components', 2, 15)
    min_dist = trial.suggest_float("min_dist", 0.0, 0.3, step=0.01)
    
    # HDBSCAN Parameters
    min_cluster_size = trial.suggest_int('min_cluster_size', 2, 50)
    min_samples = trial.suggest_int('min_samples', 1, 20)
    cluster_selection_epsilon = trial.suggest_float("cluster_selection_epsilon", 0.0, 0.3, step=0.01)
    
    # --- Model Initialization ---
    
    umap_model = UMAP(
        n_neighbors=n_neighbors,
        n_components=n_components,
        min_dist=min_dist,
        metric='cosine',
        random_state=42,
        n_jobs=1 #important for reproducability
    )

    
    hdbscan_model = hdbscan.HDBSCAN(
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        cluster_selection_epsilon=cluster_selection_epsilon,
        metric="euclidean",  
        cluster_selection_method='eom'
    )
    
    topic_model = BERTopic(
        hdbscan_model=hdbscan_model,
        vectorizer_model=CountVectorizer(stop_words='english'),
        ctfidf_model=ctfidf_model, 
        umap_model=umap_model,
        calculate_probabilities=False
        )

    topic_model.fit(docs, embeddings)

    labels = topic_model.get_document_info(docs).Topic
    mask = labels != -1
    n_clusters = len(np.unique(labels[mask]))
    emb_umap = topic_model.umap_model.embedding_
    
    emb_masked = np.ascontiguousarray(emb_umap[mask], dtype=np.float64)
    labels_masked = np.ascontiguousarray(labels[mask], dtype=np.int32)

    dbcv_score = validity_index(emb_masked, labels_masked, metric='euclidean')
    ccc_score = calculate_ccc(topic_model, docs)

    
    # logging for visibility
    print(f"Trial {trial.number}: DBCV={dbcv_score:.3f}, CCC={ccc_score:.3f}")

    # ---- Outlier ratio (fraction of points labeled -1)
    outlier_ratio =  outlier_ratio = np.mean(labels == -1)

    # Store the custom metrics in Optuna
    trial.set_user_attr("dbcv_score", dbcv_score)
    trial.set_user_attr("ccc_score", ccc_score)
    trial.set_user_attr("outlier_ratio", outlier_ratio)
    trial.set_user_attr("n_clusters", n_clusters)

    # Create directory if it doesn't exist
    os.makedirs("optuna_models/Apertus-8B-instruct", exist_ok=True)
    
    # Save model (safely serialization)
    model_name = f"optuna_models/Apertus-8B-instruct/251222_trial_{trial.number}_model"
    topic_model.save(model_name, serialization="safetensors", save_ctfidf=True)

    return ccc_score, dbcv_score

In [9]:
# 2. Run Multi-Objective Optimization
# Note: 'directions' list matches the return tuple order (DBCV, CCC)
study = optuna.create_study(directions=['maximize', 'maximize'])

study.optimize(lambda trial: objective(trial, df["description"], description_embeddings), n_trials=300, show_progress_bar=True)

[I 2025-12-22 19:33:44,280] A new study created in memory with name: no-name-ee791afb-3802-4157-a215-287d452fe15f

  0%|          | 0/300 [00:00<?, ?it/s]

100%|██████████| 1/1 [00:00<00:00, 223.42it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 0: DBCV=0.186, CCC=0.000
[I 2025-12-22 19:33:53,110] Trial 0 finished with values: [0.0, 0.18559021401486864] and parameters: {'n_neighbors': 4, 'n_components': 6, 'min_dist': 0.21, 'min_cluster_size': 27, 'min_samples': 19, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 1/1 [00:00<00:00, 297.98it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 1: DBCV=0.075, CCC=0.000
[I 2025-12-22 19:34:03,460] Trial 1 finished with values: [0.0, 0.0749195372067271] and parameters: {'n_neighbors': 29, 'n_components': 3, 'min_dist': 0.13, 'min_cluster_size': 7, 'min_samples': 16, 'cluster_selection_epsilon': 0.11}.

  0%|          | 0/58 [00:00<?, ?it/s]
100%|██████████| 58/58 [00:00<00:00, 385.78it/s]

Trial 2: DBCV=0.447, CCC=0.505
[I 2025-12-22 19:34:14,282] Trial 2 finished with values: [0.5048492381458858, 0.4473800532614568] and parameters: {'n_neighbors': 34, 'n_components': 5, 'min_dist': 0.15, 'min_cluster_size': 9, 'min_samples': 5, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 1/1 [00:00<00:00, 332.70it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 3: DBCV=0.381, CCC=0.000
[I 2025-12-22 19:34:24,578] Trial 3 finished with values: [0.0, 0.3811650556636976] and parameters: {'n_neighbors': 16, 'n_components': 9, 'min_dist': 0.27, 'min_cluster_size': 12, 'min_samples': 20, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 8/8 [00:00<00:00, 393.06it/s]

Trial 4: DBCV=0.456, CCC=0.662
[I 2025-12-22 19:34:34,955] Trial 4 finished with values: [0.6615692198325055, 0.45587889612521737] and parameters: {'n_neighbors': 19, 'n_components': 11, 'min_dist': 0.16, 'min_cluster_size': 45, 'min_samples': 20, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 281.10it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 5: DBCV=0.210, CCC=0.000
[I 2025-12-22 19:34:44,571] Trial 5 finished with values: [0.0, 0.20961226614456432] and parameters: {'n_neighbors': 16, 'n_components': 2, 'min_dist': 0.14, 'min_cluster_size': 20, 'min_samples': 7, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 22/22 [00:00<00:00, 382.11it/s]

Trial 6: DBCV=0.468, CCC=0.441
[I 2025-12-22 19:34:55,345] Trial 6 finished with values: [0.4408734121922265, 0.46815374442170105] and parameters: {'n_neighbors': 44, 'n_components': 5, 'min_dist': 0.16, 'min_cluster_size': 15, 'min_samples': 16, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 6/6 [00:00<00:00, 369.02it/s]

Trial 7: DBCV=-0.263, CCC=0.601
[I 2025-12-22 19:35:05,969] Trial 7 finished with values: [0.6011493492725489, -0.26343372388858033] and parameters: {'n_neighbors': 49, 'n_components': 3, 'min_dist': 0.07, 'min_cluster_size': 35, 'min_samples': 2, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 11/11 [00:00<00:00, 345.11it/s]

Trial 8: DBCV=0.258, CCC=0.715
[I 2025-12-22 19:35:15,343] Trial 8 finished with values: [0.7153180981838287, 0.2580960340375874] and parameters: {'n_neighbors': 5, 'n_components': 15, 'min_dist': 0.03, 'min_cluster_size': 31, 'min_samples': 17, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/48 [00:00<?, ?it/s]
100%|██████████| 48/48 [00:00<00:00, 380.28it/s]

Trial 9: DBCV=0.527, CCC=0.500
[I 2025-12-22 19:35:26,886] Trial 9 finished with values: [0.5000866339256793, 0.5270623144907954] and parameters: {'n_neighbors': 30, 'n_components': 13, 'min_dist': 0.16, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 28/28 [00:00<00:00, 383.99it/s]

Trial 10: DBCV=0.426, CCC=0.536
[I 2025-12-22 19:35:36,737] Trial 10 finished with values: [0.536450637869346, 0.42628884877810036] and parameters: {'n_neighbors': 20, 'n_components': 4, 'min_dist': 0.13, 'min_cluster_size': 13, 'min_samples': 14, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 1/1 [00:00<00:00, 279.14it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 11: DBCV=0.497, CCC=0.000
[I 2025-12-22 19:35:46,797] Trial 11 finished with values: [0.0, 0.49696988448183704] and parameters: {'n_neighbors': 9, 'n_components': 13, 'min_dist': 0.21, 'min_cluster_size': 22, 'min_samples': 6, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 23/23 [00:00<00:00, 388.08it/s]

Trial 12: DBCV=0.564, CCC=0.523
[I 2025-12-22 19:35:57,168] Trial 12 finished with values: [0.5230784160506533, 0.5639580958603511] and parameters: {'n_neighbors': 37, 'n_components': 4, 'min_dist': 0.12, 'min_cluster_size': 15, 'min_samples': 19, 'cluster_selection_epsilon': 0.08}.

  0%|          | 0/47 [00:00<?, ?it/s]
100%|██████████| 47/47 [00:00<00:00, 380.18it/s]

Trial 13: DBCV=0.531, CCC=0.532
[I 2025-12-22 19:36:08,229] Trial 13 finished with values: [0.532463046139648, 0.531057766307713] and parameters: {'n_neighbors': 46, 'n_components': 5, 'min_dist': 0.02, 'min_cluster_size': 10, 'min_samples': 7, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 24/24 [00:00<00:00, 388.02it/s]

Trial 14: DBCV=0.496, CCC=0.526
[I 2025-12-22 19:36:19,621] Trial 14 finished with values: [0.5261417365271361, 0.4962999168438142] and parameters: {'n_neighbors': 48, 'n_components': 10, 'min_dist': 0.14, 'min_cluster_size': 11, 'min_samples': 15, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 7/7 [00:00<00:00, 368.39it/s]

Trial 15: DBCV=-0.202, CCC=0.743
[I 2025-12-22 19:36:27,809] Trial 15 finished with values: [0.7431288335438276, -0.20169284721687875] and parameters: {'n_neighbors': 3, 'n_components': 2, 'min_dist': 0.15, 'min_cluster_size': 29, 'min_samples': 19, 'cluster_selection_epsilon': 0.05}.

  0%|          | 0/72 [00:00<?, ?it/s]
100%|██████████| 72/72 [00:00<00:00, 393.55it/s]

Trial 16: DBCV=0.452, CCC=0.451
[I 2025-12-22 19:36:37,989] Trial 16 finished with values: [0.45096684070924076, 0.4521485482047187] and parameters: {'n_neighbors': 11, 'n_components': 9, 'min_dist': 0.06, 'min_cluster_size': 9, 'min_samples': 2, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 25/25 [00:00<00:00, 379.12it/s]

Trial 17: DBCV=0.410, CCC=0.534
[I 2025-12-22 19:36:48,270] Trial 17 finished with values: [0.5342299680155633, 0.41043806212285777] and parameters: {'n_neighbors': 26, 'n_components': 5, 'min_dist': 0.07, 'min_cluster_size': 26, 'min_samples': 7, 'cluster_selection_epsilon': 0.05}.

  0%|          | 0/43 [00:00<?, ?it/s]
100%|██████████| 43/43 [00:00<00:00, 383.74it/s]

Trial 18: DBCV=0.501, CCC=0.562
[I 2025-12-22 19:36:59,465] Trial 18 finished with values: [0.5624512640600788, 0.5008238825419792] and parameters: {'n_neighbors': 29, 'n_components': 12, 'min_dist': 0.3, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 16/16 [00:00<00:00, 363.95it/s]

Trial 19: DBCV=0.246, CCC=0.542
[I 2025-12-22 19:37:09,623] Trial 19 finished with values: [0.5424265991126687, 0.24601308007339673] and parameters: {'n_neighbors': 20, 'n_components': 8, 'min_dist': 0.01, 'min_cluster_size': 38, 'min_samples': 3, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 10/10 [00:00<00:00, 351.06it/s]

Trial 20: DBCV=0.444, CCC=0.648
[I 2025-12-22 19:37:20,512] Trial 20 finished with values: [0.6478801143856457, 0.4443592433901595] and parameters: {'n_neighbors': 21, 'n_components': 14, 'min_dist': 0.28, 'min_cluster_size': 36, 'min_samples': 12, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 9/9 [00:00<00:00, 316.97it/s]

Trial 21: DBCV=0.098, CCC=0.595
[I 2025-12-22 19:37:31,580] Trial 21 finished with values: [0.5948512818460733, 0.09792691468511203] and parameters: {'n_neighbors': 49, 'n_components': 8, 'min_dist': 0.15, 'min_cluster_size': 44, 'min_samples': 8, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 17/17 [00:00<00:00, 371.21it/s]

Trial 22: DBCV=0.547, CCC=0.525
[I 2025-12-22 19:37:42,350] Trial 22 finished with values: [0.5254606951100163, 0.5469160963227295] and parameters: {'n_neighbors': 28, 'n_components': 6, 'min_dist': 0.24, 'min_cluster_size': 20, 'min_samples': 18, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 20/20 [00:00<00:00, 370.43it/s]

Trial 23: DBCV=0.354, CCC=0.504
[I 2025-12-22 19:37:51,337] Trial 23 finished with values: [0.5039378274097296, 0.3536777556808779] and parameters: {'n_neighbors': 5, 'n_components': 11, 'min_dist': 0.01, 'min_cluster_size': 32, 'min_samples': 5, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 1/1 [00:00<00:00, 276.12it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 24: DBCV=0.458, CCC=0.000
[I 2025-12-22 19:38:02,149] Trial 24 finished with values: [0.0, 0.4575388842805368] and parameters: {'n_neighbors': 13, 'n_components': 14, 'min_dist': 0.15, 'min_cluster_size': 20, 'min_samples': 13, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 13/13 [00:00<00:00, 386.46it/s]

Trial 25: DBCV=0.291, CCC=0.739
[I 2025-12-22 19:38:10,590] Trial 25 finished with values: [0.7385446574399419, 0.2909002508711009] and parameters: {'n_neighbors': 3, 'n_components': 7, 'min_dist': 0.22, 'min_cluster_size': 31, 'min_samples': 6, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 11/11 [00:00<00:00, 350.55it/s]

Trial 26: DBCV=0.373, CCC=0.590
[I 2025-12-22 19:38:21,227] Trial 26 finished with values: [0.5899927887273024, 0.372602143923889] and parameters: {'n_neighbors': 29, 'n_components': 9, 'min_dist': 0.19, 'min_cluster_size': 46, 'min_samples': 7, 'cluster_selection_epsilon': 0.3}.

  0%|          | 0/74 [00:00<?, ?it/s]
100%|██████████| 74/74 [00:00<00:00, 393.66it/s]

Trial 27: DBCV=0.540, CCC=0.404
[I 2025-12-22 19:38:32,344] Trial 27 finished with values: [0.4042716956477628, 0.5401194270252598] and parameters: {'n_neighbors': 33, 'n_components': 8, 'min_dist': 0.2, 'min_cluster_size': 3, 'min_samples': 6, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 34/34 [00:00<00:00, 395.35it/s]

Trial 28: DBCV=0.525, CCC=0.495
[I 2025-12-22 19:38:42,947] Trial 28 finished with values: [0.49452915121926144, 0.5253033435210585] and parameters: {'n_neighbors': 18, 'n_components': 12, 'min_dist': 0.21, 'min_cluster_size': 14, 'min_samples': 10, 'cluster_selection_epsilon': 0.23}.

  0%|          | 0/43 [00:00<?, ?it/s]
100%|██████████| 43/43 [00:00<00:00, 377.30it/s]

Trial 29: DBCV=0.572, CCC=0.454
[I 2025-12-22 19:38:54,343] Trial 29 finished with values: [0.45416973813167294, 0.5717063493099729] and parameters: {'n_neighbors': 24, 'n_components': 14, 'min_dist': 0.24, 'min_cluster_size': 2, 'min_samples': 12, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 15/15 [00:00<00:00, 362.91it/s]

Trial 30: DBCV=-0.169, CCC=0.706
[I 2025-12-22 19:39:03,808] Trial 30 finished with values: [0.7057085978293881, -0.16949365878078881] and parameters: {'n_neighbors': 17, 'n_components': 2, 'min_dist': 0.18, 'min_cluster_size': 35, 'min_samples': 3, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 11/11 [00:00<00:00, 394.98it/s]

Trial 31: DBCV=0.388, CCC=0.606
[I 2025-12-22 19:39:13,957] Trial 31 finished with values: [0.6055239692611966, 0.38832626558280486] and parameters: {'n_neighbors': 17, 'n_components': 10, 'min_dist': 0.08, 'min_cluster_size': 43, 'min_samples': 8, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 37/37 [00:00<00:00, 400.23it/s]

Trial 32: DBCV=0.596, CCC=0.572
[I 2025-12-22 19:39:24,596] Trial 32 finished with values: [0.5723468729934691, 0.5955733762055279] and parameters: {'n_neighbors': 14, 'n_components': 14, 'min_dist': 0.11, 'min_cluster_size': 15, 'min_samples': 11, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 16/16 [00:00<00:00, 403.97it/s]

Trial 33: DBCV=0.434, CCC=0.526
[I 2025-12-22 19:39:35,921] Trial 33 finished with values: [0.5259694449899543, 0.43415377218452683] and parameters: {'n_neighbors': 39, 'n_components': 11, 'min_dist': 0.3, 'min_cluster_size': 19, 'min_samples': 10, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 9/9 [00:00<00:00, 312.92it/s]

Trial 34: DBCV=0.279, CCC=0.561
[I 2025-12-22 19:39:45,829] Trial 34 finished with values: [0.561226693193829, 0.27925286720971243] and parameters: {'n_neighbors': 22, 'n_components': 4, 'min_dist': 0.26, 'min_cluster_size': 48, 'min_samples': 13, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 1/1 [00:00<00:00, 280.42it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 35: DBCV=0.281, CCC=0.000
[I 2025-12-22 19:39:56,153] Trial 35 finished with values: [0.0, 0.281157936500344] and parameters: {'n_neighbors': 15, 'n_components': 10, 'min_dist': 0.28, 'min_cluster_size': 14, 'min_samples': 18, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 2/2 [00:00<00:00, 251.93it/s]

Trial 36: DBCV=0.008, CCC=0.527
[I 2025-12-22 19:40:06,599] Trial 36 finished with values: [0.5270732650363787, 0.008238181798765096] and parameters: {'n_neighbors': 22, 'n_components': 6, 'min_dist': 0.16, 'min_cluster_size': 28, 'min_samples': 14, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 7/7 [00:00<00:00, 297.35it/s]

Trial 37: DBCV=0.356, CCC=0.685
[I 2025-12-22 19:40:16,552] Trial 37 finished with values: [0.6853372997879558, 0.3560676234122057] and parameters: {'n_neighbors': 14, 'n_components': 10, 'min_dist': 0.16, 'min_cluster_size': 42, 'min_samples': 15, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 18/18 [00:00<00:00, 375.56it/s]

Trial 38: DBCV=0.450, CCC=0.469
[I 2025-12-22 19:40:27,266] Trial 38 finished with values: [0.4694714350861973, 0.45006967083306065] and parameters: {'n_neighbors': 30, 'n_components': 9, 'min_dist': 0.28, 'min_cluster_size': 19, 'min_samples': 11, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 22/22 [00:00<00:00, 376.06it/s]

Trial 39: DBCV=0.367, CCC=0.500
[I 2025-12-22 19:40:35,873] Trial 39 finished with values: [0.500408778842024, 0.36665183241937527] and parameters: {'n_neighbors': 5, 'n_components': 3, 'min_dist': 0.03, 'min_cluster_size': 29, 'min_samples': 10, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 185.52it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 40: DBCV=-0.541, CCC=0.000
[I 2025-12-22 19:40:46,581] Trial 40 finished with values: [0.0, -0.5413488547627011] and parameters: {'n_neighbors': 49, 'n_components': 2, 'min_dist': 0.23, 'min_cluster_size': 15, 'min_samples': 19, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 10/10 [00:00<00:00, 394.36it/s]

Trial 41: DBCV=0.299, CCC=0.544
[I 2025-12-22 19:40:57,465] Trial 41 finished with values: [0.543547693364829, 0.2990346001695888] and parameters: {'n_neighbors': 26, 'n_components': 11, 'min_dist': 0.26, 'min_cluster_size': 36, 'min_samples': 12, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 10/10 [00:00<00:00, 399.64it/s]

Trial 42: DBCV=0.363, CCC=0.533
[I 2025-12-22 19:41:08,969] Trial 42 finished with values: [0.5334995683881455, 0.36293494431886564] and parameters: {'n_neighbors': 35, 'n_components': 13, 'min_dist': 0.19, 'min_cluster_size': 46, 'min_samples': 9, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 9/9 [00:00<00:00, 390.97it/s]

Trial 43: DBCV=0.375, CCC=0.547
[I 2025-12-22 19:41:18,931] Trial 43 finished with values: [0.5472622015732428, 0.37508836048103994] and parameters: {'n_neighbors': 12, 'n_components': 11, 'min_dist': 0.1, 'min_cluster_size': 43, 'min_samples': 17, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 1/1 [00:00<00:00, 153.86it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 44: DBCV=0.570, CCC=0.000
[I 2025-12-22 19:41:31,260] Trial 44 finished with values: [0.0, 0.570061590128716] and parameters: {'n_neighbors': 33, 'n_components': 15, 'min_dist': 0.1, 'min_cluster_size': 24, 'min_samples': 20, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 9/9 [00:00<00:00, 390.53it/s]

Trial 45: DBCV=-0.019, CCC=0.669
[I 2025-12-22 19:41:42,152] Trial 45 finished with values: [0.6691394170724777, -0.018617670294512133] and parameters: {'n_neighbors': 49, 'n_components': 5, 'min_dist': 0.15, 'min_cluster_size': 43, 'min_samples': 3, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 13/13 [00:00<00:00, 349.46it/s]

Trial 46: DBCV=0.371, CCC=0.651
[I 2025-12-22 19:41:53,040] Trial 46 finished with values: [0.6512554706489265, 0.37063990411204395] and parameters: {'n_neighbors': 32, 'n_components': 10, 'min_dist': 0.24, 'min_cluster_size': 31, 'min_samples': 16, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 12/12 [00:00<00:00, 396.01it/s]

Trial 47: DBCV=0.320, CCC=0.660
[I 2025-12-22 19:42:04,144] Trial 47 finished with values: [0.6595016152024057, 0.3195176713264663] and parameters: {'n_neighbors': 37, 'n_components': 10, 'min_dist': 0.17, 'min_cluster_size': 34, 'min_samples': 7, 'cluster_selection_epsilon': 0.12}.

  0%|          | 0/60 [00:00<?, ?it/s]
100%|██████████| 60/60 [00:00<00:00, 389.23it/s]

Trial 48: DBCV=0.516, CCC=0.492
[I 2025-12-22 19:42:17,157] Trial 48 finished with values: [0.4923610648971712, 0.5159246173782334] and parameters: {'n_neighbors': 46, 'n_components': 14, 'min_dist': 0.08, 'min_cluster_size': 5, 'min_samples': 7, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 12/12 [00:00<00:00, 341.41it/s]

Trial 49: DBCV=0.233, CCC=0.551
[I 2025-12-22 19:42:29,269] Trial 49 finished with values: [0.5514179871068917, 0.23259937126918837] and parameters: {'n_neighbors': 36, 'n_components': 15, 'min_dist': 0.0, 'min_cluster_size': 40, 'min_samples': 2, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 9/9 [00:00<00:00, 314.30it/s]

Trial 50: DBCV=0.443, CCC=0.703
[I 2025-12-22 19:42:40,128] Trial 50 finished with values: [0.7027472863466906, 0.4434095685445095] and parameters: {'n_neighbors': 32, 'n_components': 10, 'min_dist': 0.28, 'min_cluster_size': 36, 'min_samples': 11, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 22/22 [00:00<00:00, 411.87it/s]

Trial 51: DBCV=0.472, CCC=0.561
[I 2025-12-22 19:42:51,303] Trial 51 finished with values: [0.560661661618068, 0.4721834726313562] and parameters: {'n_neighbors': 44, 'n_components': 9, 'min_dist': 0.16, 'min_cluster_size': 9, 'min_samples': 16, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 9/9 [00:00<00:00, 341.41it/s]

Trial 52: DBCV=0.464, CCC=0.765
[I 2025-12-22 19:43:02,006] Trial 52 finished with values: [0.7651339660701999, 0.4636635736183961] and parameters: {'n_neighbors': 33, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 144.96it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 53: DBCV=0.451, CCC=0.000
[I 2025-12-22 19:43:11,175] Trial 53 finished with values: [0.0, 0.4506323940191908] and parameters: {'n_neighbors': 4, 'n_components': 14, 'min_dist': 0.21, 'min_cluster_size': 27, 'min_samples': 16, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 30/30 [00:00<00:00, 391.88it/s]

Trial 54: DBCV=0.532, CCC=0.525
[I 2025-12-22 19:43:21,279] Trial 54 finished with values: [0.5247161496696444, 0.5316250405146961] and parameters: {'n_neighbors': 15, 'n_components': 10, 'min_dist': 0.3, 'min_cluster_size': 14, 'min_samples': 13, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 38/38 [00:00<00:00, 412.85it/s]

Trial 55: DBCV=0.492, CCC=0.490
[I 2025-12-22 19:43:33,043] Trial 55 finished with values: [0.48971093330482174, 0.49223252996828043] and parameters: {'n_neighbors': 39, 'n_components': 13, 'min_dist': 0.16, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 281.67it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 56: DBCV=0.228, CCC=0.000
[I 2025-12-22 19:43:43,666] Trial 56 finished with values: [0.0, 0.2278137564205566] and parameters: {'n_neighbors': 28, 'n_components': 5, 'min_dist': 0.16, 'min_cluster_size': 18, 'min_samples': 18, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 28/28 [00:00<00:00, 385.82it/s]

Trial 57: DBCV=0.133, CCC=0.494
[I 2025-12-22 19:43:55,836] Trial 57 finished with values: [0.49431907337238734, 0.1329059026534906] and parameters: {'n_neighbors': 36, 'n_components': 15, 'min_dist': 0.28, 'min_cluster_size': 19, 'min_samples': 2, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 19/19 [00:00<00:00, 403.05it/s]

Trial 58: DBCV=0.460, CCC=0.465
[I 2025-12-22 19:44:07,259] Trial 58 finished with values: [0.46467271803921695, 0.46015361751656503] and parameters: {'n_neighbors': 28, 'n_components': 14, 'min_dist': 0.28, 'min_cluster_size': 20, 'min_samples': 12, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 39/39 [00:00<00:00, 397.94it/s]

Trial 59: DBCV=0.589, CCC=0.557
[I 2025-12-22 19:44:18,371] Trial 59 finished with values: [0.5565077959560998, 0.5888999237236128] and parameters: {'n_neighbors': 21, 'n_components': 14, 'min_dist': 0.28, 'min_cluster_size': 5, 'min_samples': 12, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 2/2 [00:00<00:00, 312.44it/s]

Trial 60: DBCV=0.288, CCC=0.531
[I 2025-12-22 19:44:29,536] Trial 60 finished with values: [0.5306038662835868, 0.28766494791668423] and parameters: {'n_neighbors': 26, 'n_components': 11, 'min_dist': 0.07, 'min_cluster_size': 26, 'min_samples': 7, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 7/7 [00:00<00:00, 291.53it/s]

Trial 61: DBCV=-0.202, CCC=0.743
[I 2025-12-22 19:44:37,781] Trial 61 finished with values: [0.7431288335438276, -0.20169284721687875] and parameters: {'n_neighbors': 3, 'n_components': 2, 'min_dist': 0.15, 'min_cluster_size': 29, 'min_samples': 19, 'cluster_selection_epsilon': 0.27}.

  0%|          | 0/47 [00:00<?, ?it/s]
100%|██████████| 47/47 [00:00<00:00, 386.05it/s]

Trial 62: DBCV=0.566, CCC=0.526
[I 2025-12-22 19:44:48,487] Trial 62 finished with values: [0.5263354266537066, 0.5662923957576478] and parameters: {'n_neighbors': 19, 'n_components': 11, 'min_dist': 0.06, 'min_cluster_size': 9, 'min_samples': 10, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 16/16 [00:00<00:00, 378.01it/s]

Trial 63: DBCV=0.441, CCC=0.500
[I 2025-12-22 19:45:00,006] Trial 63 finished with values: [0.4997520570759488, 0.4412887886684526] and parameters: {'n_neighbors': 36, 'n_components': 13, 'min_dist': 0.21, 'min_cluster_size': 29, 'min_samples': 11, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 281.27it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 64: DBCV=0.381, CCC=0.000
[I 2025-12-22 19:45:10,368] Trial 64 finished with values: [0.0, 0.3811650556636976] and parameters: {'n_neighbors': 16, 'n_components': 9, 'min_dist': 0.27, 'min_cluster_size': 12, 'min_samples': 20, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 28/28 [00:00<00:00, 392.33it/s]

Trial 65: DBCV=0.549, CCC=0.484
[I 2025-12-22 19:45:19,671] Trial 65 finished with values: [0.4837914441814195, 0.5488010733477932] and parameters: {'n_neighbors': 8, 'n_components': 8, 'min_dist': 0.04, 'min_cluster_size': 15, 'min_samples': 18, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 16/16 [00:00<00:00, 361.94it/s]

Trial 66: DBCV=0.252, CCC=0.577
[I 2025-12-22 19:45:30,662] Trial 66 finished with values: [0.5770568095065823, 0.25228248821822874] and parameters: {'n_neighbors': 17, 'n_components': 15, 'min_dist': 0.08, 'min_cluster_size': 40, 'min_samples': 2, 'cluster_selection_epsilon': 0.27}.

  0%|          | 0/41 [00:00<?, ?it/s]
100%|██████████| 41/41 [00:00<00:00, 396.14it/s]

Trial 67: DBCV=0.548, CCC=0.480
[I 2025-12-22 19:45:40,472] Trial 67 finished with values: [0.480368851364801, 0.5477973555842907] and parameters: {'n_neighbors': 18, 'n_components': 4, 'min_dist': 0.24, 'min_cluster_size': 2, 'min_samples': 14, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 15/15 [00:00<00:00, 375.14it/s]

Trial 68: DBCV=0.429, CCC=0.553
[I 2025-12-22 19:45:50,601] Trial 68 finished with values: [0.5530622116376169, 0.42897204900562924] and parameters: {'n_neighbors': 29, 'n_components': 4, 'min_dist': 0.3, 'min_cluster_size': 15, 'min_samples': 19, 'cluster_selection_epsilon': 0.02}.

  0%|          | 0/65 [00:00<?, ?it/s]
100%|██████████| 65/65 [00:00<00:00, 397.34it/s]

Trial 69: DBCV=0.480, CCC=0.438
[I 2025-12-22 19:46:00,797] Trial 69 finished with values: [0.4378481406587557, 0.47998017043800334] and parameters: {'n_neighbors': 20, 'n_components': 4, 'min_dist': 0.2, 'min_cluster_size': 8, 'min_samples': 6, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 15/15 [00:00<00:00, 366.60it/s]

Trial 70: DBCV=0.485, CCC=0.504
[I 2025-12-22 19:46:12,736] Trial 70 finished with values: [0.5037836498221884, 0.4852178098831506] and parameters: {'n_neighbors': 33, 'n_components': 15, 'min_dist': 0.3, 'min_cluster_size': 24, 'min_samples': 12, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 11/11 [00:00<00:00, 338.84it/s]

Trial 71: DBCV=0.357, CCC=0.593
[I 2025-12-22 19:46:22,500] Trial 71 finished with values: [0.5928500876680118, 0.357494370090232] and parameters: {'n_neighbors': 20, 'n_components': 4, 'min_dist': 0.29, 'min_cluster_size': 34, 'min_samples': 14, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 11/11 [00:00<00:00, 354.67it/s]

Trial 72: DBCV=0.144, CCC=0.555
[I 2025-12-22 19:46:31,957] Trial 72 finished with values: [0.5551748359714375, 0.14360657050293796] and parameters: {'n_neighbors': 11, 'n_components': 6, 'min_dist': 0.19, 'min_cluster_size': 46, 'min_samples': 2, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 39/39 [00:00<00:00, 407.66it/s]

Trial 73: DBCV=0.445, CCC=0.611
[I 2025-12-22 19:46:42,886] Trial 73 finished with values: [0.6113505360868056, 0.44505410281878854] and parameters: {'n_neighbors': 40, 'n_components': 6, 'min_dist': 0.28, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 12/12 [00:00<00:00, 348.34it/s]

Trial 74: DBCV=0.371, CCC=0.599
[I 2025-12-22 19:46:53,542] Trial 74 finished with values: [0.599241227910995, 0.3708195433032895] and parameters: {'n_neighbors': 29, 'n_components': 9, 'min_dist': 0.18, 'min_cluster_size': 46, 'min_samples': 7, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 1/1 [00:00<00:00, 283.13it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 75: DBCV=-0.517, CCC=0.000
[I 2025-12-22 19:47:03,284] Trial 75 finished with values: [0.0, -0.5165040047530661] and parameters: {'n_neighbors': 17, 'n_components': 2, 'min_dist': 0.24, 'min_cluster_size': 31, 'min_samples': 3, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 8/8 [00:00<00:00, 375.88it/s]

Trial 76: DBCV=0.278, CCC=0.788
[I 2025-12-22 19:47:13,654] Trial 76 finished with values: [0.7881636856223962, 0.27811618780993924] and parameters: {'n_neighbors': 16, 'n_components': 12, 'min_dist': 0.26, 'min_cluster_size': 48, 'min_samples': 5, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 35/35 [00:00<00:00, 400.71it/s]

Trial 77: DBCV=0.487, CCC=0.575
[I 2025-12-22 19:47:23,941] Trial 77 finished with values: [0.5753527272186464, 0.48711754123670997] and parameters: {'n_neighbors': 29, 'n_components': 4, 'min_dist': 0.12, 'min_cluster_size': 15, 'min_samples': 7, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 27/27 [00:00<00:00, 392.13it/s]

Trial 78: DBCV=0.368, CCC=0.585
[I 2025-12-22 19:47:35,784] Trial 78 finished with values: [0.5845894532966945, 0.3681792086352534] and parameters: {'n_neighbors': 37, 'n_components': 14, 'min_dist': 0.17, 'min_cluster_size': 19, 'min_samples': 5, 'cluster_selection_epsilon': 0.28}.

100%|██████████| 1/1 [00:00<00:00, 281.99it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 79: DBCV=-0.231, CCC=0.000
[I 2025-12-22 19:47:45,333] Trial 79 finished with values: [0.0, -0.23102547798992176] and parameters: {'n_neighbors': 14, 'n_components': 2, 'min_dist': 0.16, 'min_cluster_size': 29, 'min_samples': 15, 'cluster_selection_epsilon': 0.1}.

  0%|          | 0/47 [00:00<?, ?it/s]
100%|██████████| 47/47 [00:00<00:00, 385.91it/s]

Trial 80: DBCV=0.520, CCC=0.448
[I 2025-12-22 19:47:56,100] Trial 80 finished with values: [0.44835362693390546, 0.5198717537149493] and parameters: {'n_neighbors': 29, 'n_components': 6, 'min_dist': 0.02, 'min_cluster_size': 3, 'min_samples': 8, 'cluster_selection_epsilon': 0.27}.

  0%|          | 0/72 [00:00<?, ?it/s]
100%|██████████| 72/72 [00:00<00:00, 394.96it/s]

Trial 81: DBCV=0.468, CCC=0.488
[I 2025-12-22 19:48:06,278] Trial 81 finished with values: [0.4875380723180545, 0.4675031107666852] and parameters: {'n_neighbors': 11, 'n_components': 9, 'min_dist': 0.02, 'min_cluster_size': 9, 'min_samples': 2, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 35/35 [00:00<00:00, 398.38it/s]

Trial 82: DBCV=0.500, CCC=0.518
[I 2025-12-22 19:48:17,399] Trial 82 finished with values: [0.5181434333476989, 0.5000654937245776] and parameters: {'n_neighbors': 30, 'n_components': 11, 'min_dist': 0.16, 'min_cluster_size': 13, 'min_samples': 8, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 9/9 [00:00<00:00, 333.98it/s]

Trial 83: DBCV=0.262, CCC=0.761
[I 2025-12-22 19:48:28,366] Trial 83 finished with values: [0.7610308023865128, 0.26197980611807475] and parameters: {'n_neighbors': 35, 'n_components': 10, 'min_dist': 0.19, 'min_cluster_size': 46, 'min_samples': 7, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 37/37 [00:00<00:00, 416.49it/s]

Trial 84: DBCV=0.474, CCC=0.554
[I 2025-12-22 19:48:39,580] Trial 84 finished with values: [0.5543214690957241, 0.4739947980125955] and parameters: {'n_neighbors': 41, 'n_components': 9, 'min_dist': 0.27, 'min_cluster_size': 12, 'min_samples': 5, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 8/8 [00:00<00:00, 304.00it/s]

Trial 85: DBCV=0.312, CCC=0.668
[I 2025-12-22 19:48:50,466] Trial 85 finished with values: [0.6684550290276815, 0.3122813876246584] and parameters: {'n_neighbors': 35, 'n_components': 7, 'min_dist': 0.06, 'min_cluster_size': 50, 'min_samples': 9, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 33/33 [00:00<00:00, 400.01it/s]

Trial 86: DBCV=0.436, CCC=0.559
[I 2025-12-22 19:49:01,098] Trial 86 finished with values: [0.5589374241679469, 0.43586848631833514] and parameters: {'n_neighbors': 43, 'n_components': 4, 'min_dist': 0.14, 'min_cluster_size': 15, 'min_samples': 7, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 1/1 [00:00<00:00, 312.33it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 87: DBCV=0.722, CCC=0.000
[I 2025-12-22 19:49:12,745] Trial 87 finished with values: [0.0, 0.7222644434555083] and parameters: {'n_neighbors': 22, 'n_components': 15, 'min_dist': 0.07, 'min_cluster_size': 28, 'min_samples': 14, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 27/27 [00:00<00:00, 393.62it/s]

Trial 88: DBCV=0.407, CCC=0.593
[I 2025-12-22 19:49:23,544] Trial 88 finished with values: [0.5927398383099158, 0.4068853213687336] and parameters: {'n_neighbors': 29, 'n_components': 9, 'min_dist': 0.01, 'min_cluster_size': 23, 'min_samples': 5, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 1/1 [00:00<00:00, 190.44it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 89: DBCV=0.528, CCC=0.000
[I 2025-12-22 19:49:34,355] Trial 89 finished with values: [0.0, 0.5279977955901544] and parameters: {'n_neighbors': 18, 'n_components': 12, 'min_dist': 0.21, 'min_cluster_size': 20, 'min_samples': 10, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 11/11 [00:00<00:00, 395.37it/s]

Trial 90: DBCV=0.386, CCC=0.659
[I 2025-12-22 19:49:44,192] Trial 90 finished with values: [0.659065834870385, 0.38580327432647715] and parameters: {'n_neighbors': 24, 'n_components': 3, 'min_dist': 0.07, 'min_cluster_size': 35, 'min_samples': 20, 'cluster_selection_epsilon': 0.2}.

  0%|          | 0/52 [00:00<?, ?it/s]
100%|██████████| 52/52 [00:00<00:00, 403.05it/s]

Trial 91: DBCV=0.455, CCC=0.542
[I 2025-12-22 19:49:54,924] Trial 91 finished with values: [0.5421643076500666, 0.45520471480491764] and parameters: {'n_neighbors': 34, 'n_components': 5, 'min_dist': 0.22, 'min_cluster_size': 9, 'min_samples': 6, 'cluster_selection_epsilon': 0.2}.

  0%|          | 0/40 [00:00<?, ?it/s]
100%|██████████| 40/40 [00:00<00:00, 389.16it/s]

Trial 92: DBCV=0.562, CCC=0.561
[I 2025-12-22 19:50:06,073] Trial 92 finished with values: [0.5609168461857184, 0.562326013588096] and parameters: {'n_neighbors': 21, 'n_components': 14, 'min_dist': 0.08, 'min_cluster_size': 5, 'min_samples': 12, 'cluster_selection_epsilon': 0.18}.

  0%|          | 0/46 [00:00<?, ?it/s]
100%|██████████| 46/46 [00:00<00:00, 388.11it/s]

Trial 93: DBCV=0.483, CCC=0.459
[I 2025-12-22 19:50:17,152] Trial 93 finished with values: [0.4585137565590003, 0.48260869784471083] and parameters: {'n_neighbors': 46, 'n_components': 5, 'min_dist': 0.04, 'min_cluster_size': 9, 'min_samples': 7, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 9/9 [00:00<00:00, 390.12it/s]

Trial 94: DBCV=0.322, CCC=0.599
[I 2025-12-22 19:50:28,692] Trial 94 finished with values: [0.5993314659865142, 0.32167701476621297] and parameters: {'n_neighbors': 37, 'n_components': 13, 'min_dist': 0.17, 'min_cluster_size': 45, 'min_samples': 11, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 9/9 [00:00<00:00, 336.79it/s]

Trial 95: DBCV=0.318, CCC=0.601
[I 2025-12-22 19:50:39,999] Trial 95 finished with values: [0.6010861390772165, 0.3184800722081878] and parameters: {'n_neighbors': 30, 'n_components': 13, 'min_dist': 0.16, 'min_cluster_size': 43, 'min_samples': 8, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 33/33 [00:00<00:00, 400.98it/s]

Trial 96: DBCV=0.455, CCC=0.579
[I 2025-12-22 19:50:50,864] Trial 96 finished with values: [0.5789652465166713, 0.4546449857163049] and parameters: {'n_neighbors': 46, 'n_components': 5, 'min_dist': 0.21, 'min_cluster_size': 10, 'min_samples': 10, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 18/18 [00:00<00:00, 382.89it/s]

Trial 97: DBCV=0.268, CCC=0.551
[I 2025-12-22 19:51:01,372] Trial 97 finished with values: [0.5513383456763585, 0.2678192114131118] and parameters: {'n_neighbors': 29, 'n_components': 6, 'min_dist': 0.3, 'min_cluster_size': 28, 'min_samples': 4, 'cluster_selection_epsilon': 0.29}.

  0%|          | 0/49 [00:00<?, ?it/s]
100%|██████████| 49/49 [00:00<00:00, 384.30it/s]

Trial 98: DBCV=0.606, CCC=0.467
[I 2025-12-22 19:51:11,756] Trial 98 finished with values: [0.46699543073100763, 0.605599234350829] and parameters: {'n_neighbors': 24, 'n_components': 5, 'min_dist': 0.16, 'min_cluster_size': 2, 'min_samples': 12, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 5/5 [00:00<00:00, 374.54it/s]

Trial 99: DBCV=0.280, CCC=0.904
[I 2025-12-22 19:51:22,515] Trial 99 finished with values: [0.9042562279521016, 0.2796650659962502] and parameters: {'n_neighbors': 26, 'n_components': 11, 'min_dist': 0.26, 'min_cluster_size': 44, 'min_samples': 20, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 14/14 [00:00<00:00, 343.78it/s]

Trial 100: DBCV=0.265, CCC=0.498
[I 2025-12-22 19:51:32,968] Trial 100 finished with values: [0.4980843336579481, 0.26528428472939697] and parameters: {'n_neighbors': 29, 'n_components': 6, 'min_dist': 0.28, 'min_cluster_size': 28, 'min_samples': 8, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 23/23 [00:00<00:00, 372.59it/s]

Trial 101: DBCV=0.580, CCC=0.542
[I 2025-12-22 19:51:44,866] Trial 101 finished with values: [0.5422626257541614, 0.5802487086198811] and parameters: {'n_neighbors': 32, 'n_components': 15, 'min_dist': 0.02, 'min_cluster_size': 10, 'min_samples': 20, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 1/1 [00:00<00:00, 285.39it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 102: DBCV=0.181, CCC=0.000
[I 2025-12-22 19:51:54,481] Trial 102 finished with values: [0.0, 0.18130417688797323] and parameters: {'n_neighbors': 5, 'n_components': 15, 'min_dist': 0.19, 'min_cluster_size': 31, 'min_samples': 17, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 17/17 [00:00<00:00, 401.82it/s]

Trial 103: DBCV=0.394, CCC=0.557
[I 2025-12-22 19:52:05,710] Trial 103 finished with values: [0.5568823396087726, 0.39444652036775446] and parameters: {'n_neighbors': 33, 'n_components': 12, 'min_dist': 0.28, 'min_cluster_size': 7, 'min_samples': 20, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 11/11 [00:00<00:00, 348.61it/s]

Trial 104: DBCV=0.295, CCC=0.615
[I 2025-12-22 19:52:16,192] Trial 104 finished with values: [0.6148668554341127, 0.2950133917918726] and parameters: {'n_neighbors': 19, 'n_components': 11, 'min_dist': 0.02, 'min_cluster_size': 45, 'min_samples': 7, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 13/13 [00:00<00:00, 358.86it/s]

Trial 105: DBCV=0.332, CCC=0.635
[I 2025-12-22 19:52:24,668] Trial 105 finished with values: [0.634650824300597, 0.3320086823030186] and parameters: {'n_neighbors': 3, 'n_components': 7, 'min_dist': 0.04, 'min_cluster_size': 31, 'min_samples': 9, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 10/10 [00:00<00:00, 333.98it/s]

Trial 106: DBCV=0.337, CCC=0.763
[I 2025-12-22 19:52:35,293] Trial 106 finished with values: [0.7626522893966474, 0.3366706324360851] and parameters: {'n_neighbors': 16, 'n_components': 14, 'min_dist': 0.07, 'min_cluster_size': 46, 'min_samples': 11, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 1/1 [00:00<00:00, 288.31it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 107: DBCV=-0.187, CCC=0.000
[I 2025-12-22 19:52:45,093] Trial 107 finished with values: [0.0, -0.18715834376576268] and parameters: {'n_neighbors': 18, 'n_components': 2, 'min_dist': 0.15, 'min_cluster_size': 2, 'min_samples': 14, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 342.06it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 108: DBCV=-0.188, CCC=0.000
[I 2025-12-22 19:52:56,015] Trial 108 finished with values: [0.0, -0.1875467273824029] and parameters: {'n_neighbors': 46, 'n_components': 3, 'min_dist': 0.07, 'min_cluster_size': 29, 'min_samples': 19, 'cluster_selection_epsilon': 0.05}.

  0%|          | 0/62 [00:00<?, ?it/s]
100%|██████████| 62/62 [00:00<00:00, 393.00it/s]

Trial 109: DBCV=0.585, CCC=0.469
[I 2025-12-22 19:53:06,801] Trial 109 finished with values: [0.46895085165466016, 0.5849338605285299] and parameters: {'n_neighbors': 17, 'n_components': 12, 'min_dist': 0.08, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 1/1 [00:00<00:00, 290.00it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 110: DBCV=0.441, CCC=0.000
[I 2025-12-22 19:53:18,109] Trial 110 finished with values: [0.0, 0.44102596102207003] and parameters: {'n_neighbors': 21, 'n_components': 14, 'min_dist': 0.28, 'min_cluster_size': 5, 'min_samples': 18, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 36/36 [00:00<00:00, 401.30it/s]

Trial 111: DBCV=0.515, CCC=0.475
[I 2025-12-22 19:53:28,874] Trial 111 finished with values: [0.4751074907086835, 0.5153285218005889] and parameters: {'n_neighbors': 21, 'n_components': 12, 'min_dist': 0.28, 'min_cluster_size': 5, 'min_samples': 12, 'cluster_selection_epsilon': 0.17}.

  0%|          | 0/52 [00:00<?, ?it/s]
100%|██████████| 52/52 [00:00<00:00, 391.30it/s]

Trial 112: DBCV=0.260, CCC=0.510
[I 2025-12-22 19:53:39,630] Trial 112 finished with values: [0.5101679378040872, 0.25998283683405143] and parameters: {'n_neighbors': 2, 'n_components': 14, 'min_dist': 0.24, 'min_cluster_size': 2, 'min_samples': 12, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 9/9 [00:00<00:00, 345.61it/s]

Trial 113: DBCV=0.391, CCC=0.716
[I 2025-12-22 19:53:50,520] Trial 113 finished with values: [0.7161194732505827, 0.3905717404799279] and parameters: {'n_neighbors': 40, 'n_components': 8, 'min_dist': 0.16, 'min_cluster_size': 46, 'min_samples': 20, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 1/1 [00:00<00:00, 313.99it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 114: DBCV=-0.106, CCC=0.000
[I 2025-12-22 19:54:00,807] Trial 114 finished with values: [0.0, -0.1055147102762858] and parameters: {'n_neighbors': 16, 'n_components': 10, 'min_dist': 0.26, 'min_cluster_size': 48, 'min_samples': 3, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 38/38 [00:00<00:00, 402.63it/s]

Trial 115: DBCV=0.610, CCC=0.529
[I 2025-12-22 19:54:12,862] Trial 115 finished with values: [0.5285684286020654, 0.6104903457750196] and parameters: {'n_neighbors': 33, 'n_components': 15, 'min_dist': 0.1, 'min_cluster_size': 5, 'min_samples': 12, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 29/29 [00:00<00:00, 395.28it/s]

Trial 116: DBCV=0.434, CCC=0.596
[I 2025-12-22 19:54:23,564] Trial 116 finished with values: [0.5959657156508937, 0.4344475427449879] and parameters: {'n_neighbors': 43, 'n_components': 4, 'min_dist': 0.14, 'min_cluster_size': 15, 'min_samples': 10, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 18/18 [00:00<00:00, 379.57it/s]

Trial 117: DBCV=0.395, CCC=0.603
[I 2025-12-22 19:54:33,417] Trial 117 finished with values: [0.6032883457242519, 0.3945515614399348] and parameters: {'n_neighbors': 28, 'n_components': 2, 'min_dist': 0.24, 'min_cluster_size': 20, 'min_samples': 18, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 8/8 [00:00<00:00, 386.83it/s]

Trial 118: DBCV=0.403, CCC=0.626
[I 2025-12-22 19:54:44,366] Trial 118 finished with values: [0.6261727111232066, 0.4031686569399006] and parameters: {'n_neighbors': 21, 'n_components': 14, 'min_dist': 0.06, 'min_cluster_size': 50, 'min_samples': 9, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 30/30 [00:00<00:00, 397.04it/s]

Trial 119: DBCV=0.532, CCC=0.525
[I 2025-12-22 19:54:54,469] Trial 119 finished with values: [0.5247161496696444, 0.5316250405146961] and parameters: {'n_neighbors': 15, 'n_components': 10, 'min_dist': 0.3, 'min_cluster_size': 14, 'min_samples': 13, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 35/35 [00:00<00:00, 395.99it/s]

Trial 120: DBCV=0.435, CCC=0.563
[I 2025-12-22 19:55:05,439] Trial 120 finished with values: [0.5628492259831048, 0.4353480113713846] and parameters: {'n_neighbors': 49, 'n_components': 5, 'min_dist': 0.15, 'min_cluster_size': 13, 'min_samples': 7, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 11/11 [00:00<00:00, 361.24it/s]

Trial 121: DBCV=0.386, CCC=0.659
[I 2025-12-22 19:55:15,284] Trial 121 finished with values: [0.659065834870385, 0.38580327432647715] and parameters: {'n_neighbors': 24, 'n_components': 3, 'min_dist': 0.07, 'min_cluster_size': 35, 'min_samples': 20, 'cluster_selection_epsilon': 0.2}.

  0%|          | 0/75 [00:00<?, ?it/s]
100%|██████████| 75/75 [00:00<00:00, 400.29it/s]

Trial 122: DBCV=0.529, CCC=0.429
[I 2025-12-22 19:55:25,869] Trial 122 finished with values: [0.42891056449855997, 0.5290677107776219] and parameters: {'n_neighbors': 22, 'n_components': 5, 'min_dist': 0.07, 'min_cluster_size': 7, 'min_samples': 6, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 16/16 [00:00<00:00, 350.20it/s]

Trial 123: DBCV=0.557, CCC=0.576
[I 2025-12-22 19:55:34,585] Trial 123 finished with values: [0.5763533130788159, 0.5565817871151993] and parameters: {'n_neighbors': 3, 'n_components': 14, 'min_dist': 0.14, 'min_cluster_size': 29, 'min_samples': 19, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 11/11 [00:00<00:00, 353.26it/s]

Trial 124: DBCV=0.391, CCC=0.598
[I 2025-12-22 19:55:46,110] Trial 124 finished with values: [0.598031344179431, 0.390579867544756] and parameters: {'n_neighbors': 32, 'n_components': 14, 'min_dist': 0.28, 'min_cluster_size': 36, 'min_samples': 12, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 6/6 [00:00<00:00, 305.78it/s]

Trial 125: DBCV=-0.263, CCC=0.601
[I 2025-12-22 19:55:56,755] Trial 125 finished with values: [0.6011493492725489, -0.26343372388858033] and parameters: {'n_neighbors': 49, 'n_components': 3, 'min_dist': 0.07, 'min_cluster_size': 35, 'min_samples': 2, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 14/14 [00:00<00:00, 369.43it/s]

Trial 126: DBCV=0.201, CCC=0.662
[I 2025-12-22 19:56:07,788] Trial 126 finished with values: [0.6623594861708914, 0.2012375073795216] and parameters: {'n_neighbors': 40, 'n_components': 9, 'min_dist': 0.18, 'min_cluster_size': 35, 'min_samples': 3, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 27/27 [00:00<00:00, 389.63it/s]

Trial 127: DBCV=0.407, CCC=0.593
[I 2025-12-22 19:56:18,589] Trial 127 finished with values: [0.5927398383099158, 0.4068853213687336] and parameters: {'n_neighbors': 29, 'n_components': 9, 'min_dist': 0.01, 'min_cluster_size': 23, 'min_samples': 5, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 8/8 [00:00<00:00, 387.25it/s]

Trial 128: DBCV=0.316, CCC=0.667
[I 2025-12-22 19:56:29,600] Trial 128 finished with values: [0.66724655512339, 0.31550825835799884] and parameters: {'n_neighbors': 39, 'n_components': 9, 'min_dist': 0.16, 'min_cluster_size': 46, 'min_samples': 15, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 12/12 [00:00<00:00, 398.41it/s]

Trial 129: DBCV=0.371, CCC=0.599
[I 2025-12-22 19:56:40,246] Trial 129 finished with values: [0.599241227910995, 0.3708195433032895] and parameters: {'n_neighbors': 29, 'n_components': 9, 'min_dist': 0.18, 'min_cluster_size': 46, 'min_samples': 7, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 9/9 [00:00<00:00, 305.34it/s]

Trial 130: DBCV=0.438, CCC=0.565
[I 2025-12-22 19:56:50,907] Trial 130 finished with values: [0.5651605007017317, 0.437807295460863] and parameters: {'n_neighbors': 29, 'n_components': 9, 'min_dist': 0.28, 'min_cluster_size': 46, 'min_samples': 15, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 10/10 [00:00<00:00, 348.28it/s]

Trial 131: DBCV=0.384, CCC=0.535
[I 2025-12-22 19:57:01,843] Trial 131 finished with values: [0.5347173282089377, 0.3835510206328851] and parameters: {'n_neighbors': 35, 'n_components': 10, 'min_dist': 0.19, 'min_cluster_size': 46, 'min_samples': 12, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 30/30 [00:00<00:00, 395.72it/s]

Trial 132: DBCV=0.326, CCC=0.550
[I 2025-12-22 19:57:12,492] Trial 132 finished with values: [0.5504296397869706, 0.3262368063252952] and parameters: {'n_neighbors': 43, 'n_components': 4, 'min_dist': 0.2, 'min_cluster_size': 15, 'min_samples': 7, 'cluster_selection_epsilon': 0.08}.

  0%|          | 0/56 [00:00<?, ?it/s]
100%|██████████| 56/56 [00:00<00:00, 385.62it/s]

Trial 133: DBCV=0.490, CCC=0.504
[I 2025-12-22 19:57:23,639] Trial 133 finished with values: [0.5035365755689886, 0.489746923509344] and parameters: {'n_neighbors': 49, 'n_components': 5, 'min_dist': 0.15, 'min_cluster_size': 5, 'min_samples': 7, 'cluster_selection_epsilon': 0.18}.

  0%|          | 0/59 [00:00<?, ?it/s]
100%|██████████| 59/59 [00:00<00:00, 403.30it/s]

Trial 134: DBCV=0.545, CCC=0.505
[I 2025-12-22 19:57:33,827] Trial 134 finished with values: [0.5049173952890157, 0.5452782873213986] and parameters: {'n_neighbors': 18, 'n_components': 5, 'min_dist': 0.02, 'min_cluster_size': 12, 'min_samples': 7, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 11/11 [00:00<00:00, 340.08it/s]

Trial 135: DBCV=0.457, CCC=0.585
[I 2025-12-22 19:57:44,986] Trial 135 finished with values: [0.5854207309622605, 0.4569026191201279] and parameters: {'n_neighbors': 37, 'n_components': 10, 'min_dist': 0.17, 'min_cluster_size': 34, 'min_samples': 17, 'cluster_selection_epsilon': 0.12}.

  0%|          | 0/45 [00:00<?, ?it/s]
100%|██████████| 45/45 [00:00<00:00, 394.24it/s]

Trial 136: DBCV=0.500, CCC=0.557
[I 2025-12-22 19:57:56,354] Trial 136 finished with values: [0.5570149747180204, 0.4998301181771822] and parameters: {'n_neighbors': 29, 'n_components': 11, 'min_dist': 0.3, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 12/12 [00:00<00:00, 355.74it/s]

Trial 137: DBCV=0.413, CCC=0.581
[I 2025-12-22 19:58:06,623] Trial 137 finished with values: [0.580605562270089, 0.4131265699469392] and parameters: {'n_neighbors': 24, 'n_components': 6, 'min_dist': 0.14, 'min_cluster_size': 35, 'min_samples': 12, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 10/10 [00:00<00:00, 345.39it/s]

Trial 138: DBCV=0.393, CCC=0.637
[I 2025-12-22 19:58:16,790] Trial 138 finished with values: [0.6368041998033352, 0.39293461372191757] and parameters: {'n_neighbors': 19, 'n_components': 7, 'min_dist': 0.06, 'min_cluster_size': 50, 'min_samples': 9, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 9/9 [00:00<00:00, 392.77it/s]

Trial 139: DBCV=0.433, CCC=0.610
[I 2025-12-22 19:58:28,150] Trial 139 finished with values: [0.610424631959284, 0.43271272167654407] and parameters: {'n_neighbors': 44, 'n_components': 11, 'min_dist': 0.16, 'min_cluster_size': 45, 'min_samples': 10, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 31/31 [00:00<00:00, 395.57it/s]

Trial 140: DBCV=0.544, CCC=0.527
[I 2025-12-22 19:58:37,420] Trial 140 finished with values: [0.526531354165393, 0.5444058733214676] and parameters: {'n_neighbors': 8, 'n_components': 8, 'min_dist': 0.08, 'min_cluster_size': 5, 'min_samples': 18, 'cluster_selection_epsilon': 0.18}.

  0%|          | 0/46 [00:00<?, ?it/s]
100%|██████████| 46/46 [00:00<00:00, 384.39it/s]

Trial 141: DBCV=0.488, CCC=0.562
[I 2025-12-22 19:58:47,923] Trial 141 finished with values: [0.5617562447452618, 0.4877967769538112] and parameters: {'n_neighbors': 26, 'n_components': 6, 'min_dist': 0.28, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 26/26 [00:00<00:00, 410.04it/s]

Trial 142: DBCV=0.522, CCC=0.527
[I 2025-12-22 19:58:57,190] Trial 142 finished with values: [0.5274383995862756, 0.521633919325055] and parameters: {'n_neighbors': 8, 'n_components': 8, 'min_dist': 0.12, 'min_cluster_size': 15, 'min_samples': 18, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 9/9 [00:00<00:00, 341.53it/s]

Trial 143: DBCV=0.462, CCC=0.534
[I 2025-12-22 19:59:07,830] Trial 143 finished with values: [0.5338364814059936, 0.46185667472655967] and parameters: {'n_neighbors': 29, 'n_components': 9, 'min_dist': 0.26, 'min_cluster_size': 46, 'min_samples': 18, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 11/11 [00:00<00:00, 352.77it/s]

Trial 144: DBCV=0.303, CCC=0.592
[I 2025-12-22 19:59:17,612] Trial 144 finished with values: [0.5915776711391005, 0.30322114704181263] and parameters: {'n_neighbors': 24, 'n_components': 3, 'min_dist': 0.22, 'min_cluster_size': 35, 'min_samples': 20, 'cluster_selection_epsilon': 0.2}.

  0%|          | 0/45 [00:00<?, ?it/s]
100%|██████████| 45/45 [00:00<00:00, 373.83it/s]

Trial 145: DBCV=0.380, CCC=0.572
[I 2025-12-22 19:59:28,426] Trial 145 finished with values: [0.5717590455170156, 0.37961971953352025] and parameters: {'n_neighbors': 37, 'n_components': 5, 'min_dist': 0.21, 'min_cluster_size': 10, 'min_samples': 7, 'cluster_selection_epsilon': 0.12}.

  0%|          | 0/51 [00:00<?, ?it/s]
100%|██████████| 51/51 [00:00<00:00, 390.61it/s]

Trial 146: DBCV=0.544, CCC=0.446
[I 2025-12-22 19:59:39,628] Trial 146 finished with values: [0.4464168508670367, 0.5438198352282405] and parameters: {'n_neighbors': 21, 'n_components': 14, 'min_dist': 0.28, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 12/12 [00:00<00:00, 402.35it/s]

Trial 147: DBCV=0.208, CCC=0.569
[I 2025-12-22 19:59:50,974] Trial 147 finished with values: [0.568919261684991, 0.2081554444323431] and parameters: {'n_neighbors': 46, 'n_components': 10, 'min_dist': 0.21, 'min_cluster_size': 34, 'min_samples': 7, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 10/10 [00:00<00:00, 393.74it/s]

Trial 148: DBCV=0.029, CCC=0.690
[I 2025-12-22 20:00:01,236] Trial 148 finished with values: [0.6895693180740232, 0.028586326635032397] and parameters: {'n_neighbors': 29, 'n_components': 4, 'min_dist': 0.19, 'min_cluster_size': 46, 'min_samples': 7, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 11/11 [00:00<00:00, 350.52it/s]

Trial 149: DBCV=0.450, CCC=0.597
[I 2025-12-22 20:00:11,693] Trial 149 finished with values: [0.5967058816557781, 0.4496083403797438] and parameters: {'n_neighbors': 24, 'n_components': 7, 'min_dist': 0.07, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 9/9 [00:00<00:00, 382.10it/s]

Trial 150: DBCV=0.354, CCC=0.589
[I 2025-12-22 20:00:22,085] Trial 150 finished with values: [0.5887129496988615, 0.3538863365714572] and parameters: {'n_neighbors': 16, 'n_components': 12, 'min_dist': 0.12, 'min_cluster_size': 48, 'min_samples': 5, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 33/33 [00:00<00:00, 399.73it/s]

Trial 151: DBCV=0.643, CCC=0.596
[I 2025-12-22 20:00:33,147] Trial 151 finished with values: [0.5957543654022747, 0.6426613562361088] and parameters: {'n_neighbors': 21, 'n_components': 14, 'min_dist': 0.06, 'min_cluster_size': 5, 'min_samples': 18, 'cluster_selection_epsilon': 0.02}.

  0%|          | 0/45 [00:00<?, ?it/s]
100%|██████████| 45/45 [00:00<00:00, 406.27it/s]

Trial 152: DBCV=0.591, CCC=0.475
[I 2025-12-22 20:00:41,719] Trial 152 finished with values: [0.47485343016043285, 0.5907741544212138] and parameters: {'n_neighbors': 3, 'n_components': 5, 'min_dist': 0.15, 'min_cluster_size': 2, 'min_samples': 12, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 13/13 [00:00<00:00, 357.64it/s]

Trial 153: DBCV=0.506, CCC=0.659
[I 2025-12-22 20:00:52,168] Trial 153 finished with values: [0.6586069370716308, 0.505925213163921] and parameters: {'n_neighbors': 22, 'n_components': 10, 'min_dist': 0.0, 'min_cluster_size': 34, 'min_samples': 17, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 7/7 [00:00<00:00, 384.74it/s]

Trial 154: DBCV=0.165, CCC=0.547
[I 2025-12-22 20:01:02,660] Trial 154 finished with values: [0.546913190965859, 0.16481504194953983] and parameters: {'n_neighbors': 20, 'n_components': 11, 'min_dist': 0.28, 'min_cluster_size': 44, 'min_samples': 20, 'cluster_selection_epsilon': 0.07}.

  0%|          | 0/40 [00:00<?, ?it/s]
100%|██████████| 40/40 [00:00<00:00, 392.13it/s]

Trial 155: DBCV=0.414, CCC=0.510
[I 2025-12-22 20:01:13,223] Trial 155 finished with values: [0.5102955367507064, 0.4140979120766384] and parameters: {'n_neighbors': 33, 'n_components': 5, 'min_dist': 0.21, 'min_cluster_size': 5, 'min_samples': 10, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 9/9 [00:00<00:00, 387.58it/s]

Trial 156: DBCV=0.408, CCC=0.578
[I 2025-12-22 20:01:25,504] Trial 156 finished with values: [0.5779856347039802, 0.40788532844378367] and parameters: {'n_neighbors': 44, 'n_components': 15, 'min_dist': 0.1, 'min_cluster_size': 45, 'min_samples': 12, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 35/35 [00:00<00:00, 402.10it/s]

Trial 157: DBCV=0.514, CCC=0.556
[I 2025-12-22 20:01:36,725] Trial 157 finished with values: [0.5560479833042865, 0.5140890147581184] and parameters: {'n_neighbors': 29, 'n_components': 12, 'min_dist': 0.3, 'min_cluster_size': 7, 'min_samples': 10, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 13/13 [00:00<00:00, 363.98it/s]

Trial 158: DBCV=0.371, CCC=0.651
[I 2025-12-22 20:01:47,634] Trial 158 finished with values: [0.6512554706489265, 0.37063990411204395] and parameters: {'n_neighbors': 32, 'n_components': 10, 'min_dist': 0.24, 'min_cluster_size': 31, 'min_samples': 16, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 11/11 [00:00<00:00, 392.47it/s]

Trial 159: DBCV=0.264, CCC=0.621
[I 2025-12-22 20:01:58,232] Trial 159 finished with values: [0.6211912593754179, 0.26417005321331133] and parameters: {'n_neighbors': 43, 'n_components': 4, 'min_dist': 0.14, 'min_cluster_size': 41, 'min_samples': 10, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 10/10 [00:00<00:00, 344.70it/s]

Trial 160: DBCV=0.481, CCC=0.784
[I 2025-12-22 20:02:08,678] Trial 160 finished with values: [0.7838584490389228, 0.4812148141321031] and parameters: {'n_neighbors': 21, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.02}.

  0%|          | 0/129 [00:00<?, ?it/s]
 33%|███▎      | 42/129 [00:00<00:00, 414.82it/s]
 65%|██████▌   | 84/129 [00:00<00:00, 406.47it/s]
100%|██████████| 129/129 [00:00<00:00, 402.15it/s]

Trial 161: DBCV=0.625, CCC=0.445
[I 2025-12-22 20:02:18,933] Trial 161 finished with values: [0.4450263394060793, 0.6245526227675591] and parameters: {'n_neighbors': 12, 'n_components': 2, 'min_dist': 0.15, 'min_cluster_size': 2, 'min_samples': 5, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 8/8 [00:00<00:00, 316.85it/s]

Trial 162: DBCV=0.257, CCC=0.527
[I 2025-12-22 20:02:29,859] Trial 162 finished with values: [0.5267541309792683, 0.25677908817445205] and parameters: {'n_neighbors': 40, 'n_components': 8, 'min_dist': 0.08, 'min_cluster_size': 46, 'min_samples': 20, 'cluster_selection_epsilon': 0.18}.

  0%|          | 0/53 [00:00<?, ?it/s]
100%|██████████| 53/53 [00:00<00:00, 390.70it/s]

Trial 163: DBCV=0.549, CCC=0.512
[I 2025-12-22 20:02:40,843] Trial 163 finished with values: [0.5116136092469755, 0.5493689513334035] and parameters: {'n_neighbors': 17, 'n_components': 14, 'min_dist': 0.08, 'min_cluster_size': 10, 'min_samples': 8, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 18/18 [00:00<00:00, 364.41it/s]

Trial 164: DBCV=0.401, CCC=0.545
[I 2025-12-22 20:02:52,416] Trial 164 finished with values: [0.5450961025811615, 0.4007124502546161] and parameters: {'n_neighbors': 44, 'n_components': 11, 'min_dist': 0.28, 'min_cluster_size': 20, 'min_samples': 12, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 16/16 [00:00<00:00, 405.12it/s]

Trial 165: DBCV=0.400, CCC=0.559
[I 2025-12-22 20:03:02,622] Trial 165 finished with values: [0.5589597435342653, 0.4000762239100271] and parameters: {'n_neighbors': 24, 'n_components': 5, 'min_dist': 0.24, 'min_cluster_size': 20, 'min_samples': 12, 'cluster_selection_epsilon': 0.15}.

  0%|          | 0/42 [00:00<?, ?it/s]
100%|██████████| 42/42 [00:00<00:00, 392.87it/s]

Trial 166: DBCV=0.448, CCC=0.511
[I 2025-12-22 20:03:11,819] Trial 166 finished with values: [0.5106766833955482, 0.44765263397155153] and parameters: {'n_neighbors': 8, 'n_components': 4, 'min_dist': 0.08, 'min_cluster_size': 15, 'min_samples': 7, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 12/12 [00:00<00:00, 396.09it/s]

Trial 167: DBCV=0.201, CCC=0.595
[I 2025-12-22 20:03:22,802] Trial 167 finished with values: [0.5948955866008524, 0.20134353975644728] and parameters: {'n_neighbors': 35, 'n_components': 7, 'min_dist': 0.0, 'min_cluster_size': 50, 'min_samples': 4, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 22/22 [00:00<00:00, 374.88it/s]

Trial 168: DBCV=0.533, CCC=0.591
[I 2025-12-22 20:03:33,744] Trial 168 finished with values: [0.5914731559210538, 0.5334522718212686] and parameters: {'n_neighbors': 40, 'n_components': 6, 'min_dist': 0.15, 'min_cluster_size': 7, 'min_samples': 19, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 36/36 [00:00<00:00, 396.55it/s]

Trial 169: DBCV=0.598, CCC=0.590
[I 2025-12-22 20:03:43,294] Trial 169 finished with values: [0.5895555105755645, 0.5978651484408115] and parameters: {'n_neighbors': 17, 'n_components': 2, 'min_dist': 0.0, 'min_cluster_size': 14, 'min_samples': 16, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 11/11 [00:00<00:00, 355.32it/s]

Trial 170: DBCV=0.442, CCC=0.621
[I 2025-12-22 20:03:55,190] Trial 170 finished with values: [0.6207405823638821, 0.44176661124634076] and parameters: {'n_neighbors': 39, 'n_components': 14, 'min_dist': 0.16, 'min_cluster_size': 36, 'min_samples': 15, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 22/22 [00:00<00:00, 386.83it/s]

Trial 171: DBCV=0.569, CCC=0.500
[I 2025-12-22 20:04:06,254] Trial 171 finished with values: [0.49984944283932997, 0.5685644339985079] and parameters: {'n_neighbors': 29, 'n_components': 11, 'min_dist': 0.15, 'min_cluster_size': 6, 'min_samples': 19, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 25/25 [00:00<00:00, 390.77it/s]

Trial 172: DBCV=0.542, CCC=0.515
[I 2025-12-22 20:04:17,259] Trial 172 finished with values: [0.5150009225827129, 0.5422968114788163] and parameters: {'n_neighbors': 29, 'n_components': 11, 'min_dist': 0.16, 'min_cluster_size': 7, 'min_samples': 17, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 1/1 [00:00<00:00, 275.51it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 173: DBCV=0.368, CCC=0.000
[I 2025-12-22 20:04:29,072] Trial 173 finished with values: [0.0, 0.36792849619835954] and parameters: {'n_neighbors': 44, 'n_components': 11, 'min_dist': 0.04, 'min_cluster_size': 9, 'min_samples': 16, 'cluster_selection_epsilon': 0.2}.

  0%|          | 0/60 [00:00<?, ?it/s]
100%|██████████| 60/60 [00:00<00:00, 383.05it/s]

Trial 174: DBCV=0.581, CCC=0.516
[I 2025-12-22 20:04:39,533] Trial 174 finished with values: [0.5157520254690443, 0.5809180928205893] and parameters: {'n_neighbors': 29, 'n_components': 4, 'min_dist': 0.02, 'min_cluster_size': 10, 'min_samples': 7, 'cluster_selection_epsilon': 0.08}.

  0%|          | 0/64 [00:00<?, ?it/s]
100%|██████████| 64/64 [00:00<00:00, 395.50it/s]

Trial 175: DBCV=0.541, CCC=0.541
[I 2025-12-22 20:04:51,079] Trial 175 finished with values: [0.5413840658599801, 0.5409692248736642] and parameters: {'n_neighbors': 46, 'n_components': 8, 'min_dist': 0.08, 'min_cluster_size': 5, 'min_samples': 7, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 21/21 [00:00<00:00, 384.48it/s]

Trial 176: DBCV=0.450, CCC=0.554
[I 2025-12-22 20:05:01,588] Trial 176 finished with values: [0.5539147741274575, 0.4498929351153714] and parameters: {'n_neighbors': 26, 'n_components': 6, 'min_dist': 0.28, 'min_cluster_size': 25, 'min_samples': 8, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 10/10 [00:00<00:00, 345.85it/s]

Trial 177: DBCV=0.378, CCC=0.638
[I 2025-12-22 20:05:12,222] Trial 177 finished with values: [0.6378385539186774, 0.3777039379640892] and parameters: {'n_neighbors': 26, 'n_components': 10, 'min_dist': 0.28, 'min_cluster_size': 36, 'min_samples': 8, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 16/16 [00:00<00:00, 371.71it/s]

Trial 178: DBCV=0.435, CCC=0.641
[I 2025-12-22 20:05:23,798] Trial 178 finished with values: [0.6407552346941817, 0.43520963465672546] and parameters: {'n_neighbors': 26, 'n_components': 15, 'min_dist': 0.07, 'min_cluster_size': 35, 'min_samples': 8, 'cluster_selection_epsilon': 0.2}.

  0%|          | 0/46 [00:00<?, ?it/s]
100%|██████████| 46/46 [00:00<00:00, 391.98it/s]

Trial 179: DBCV=0.541, CCC=0.528
[I 2025-12-22 20:05:35,539] Trial 179 finished with values: [0.5277046204595867, 0.5408666399756175] and parameters: {'n_neighbors': 40, 'n_components': 12, 'min_dist': 0.16, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.2}.

  0%|          | 0/49 [00:00<?, ?it/s]
100%|██████████| 49/49 [00:00<00:00, 379.27it/s]

Trial 180: DBCV=0.546, CCC=0.511
[I 2025-12-22 20:05:46,813] Trial 180 finished with values: [0.5110372386377257, 0.545962362479682] and parameters: {'n_neighbors': 21, 'n_components': 14, 'min_dist': 0.08, 'min_cluster_size': 5, 'min_samples': 11, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 8/8 [00:00<00:00, 392.85it/s]

Trial 181: DBCV=0.456, CCC=0.662
[I 2025-12-22 20:05:57,261] Trial 181 finished with values: [0.6615692198325055, 0.45587889612521737] and parameters: {'n_neighbors': 19, 'n_components': 11, 'min_dist': 0.16, 'min_cluster_size': 45, 'min_samples': 20, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 16/16 [00:00<00:00, 390.56it/s]

Trial 182: DBCV=0.279, CCC=0.575
[I 2025-12-22 20:06:05,621] Trial 182 finished with values: [0.5752733590870877, 0.27905960609812286] and parameters: {'n_neighbors': 3, 'n_components': 3, 'min_dist': 0.14, 'min_cluster_size': 29, 'min_samples': 6, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 16/16 [00:00<00:00, 396.39it/s]

Trial 183: DBCV=0.453, CCC=0.671
[I 2025-12-22 20:06:13,983] Trial 183 finished with values: [0.6708344194224585, 0.45267024739943196] and parameters: {'n_neighbors': 3, 'n_components': 6, 'min_dist': 0.21, 'min_cluster_size': 10, 'min_samples': 19, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 10/10 [00:00<00:00, 390.43it/s]

Trial 184: DBCV=0.403, CCC=0.675
[I 2025-12-22 20:06:24,852] Trial 184 finished with values: [0.675411128019961, 0.4034553239009394] and parameters: {'n_neighbors': 27, 'n_components': 11, 'min_dist': 0.06, 'min_cluster_size': 48, 'min_samples': 10, 'cluster_selection_epsilon': 0.02}.

  0%|          | 0/46 [00:00<?, ?it/s]
100%|██████████| 46/46 [00:00<00:00, 381.48it/s]

Trial 185: DBCV=0.566, CCC=0.502
[I 2025-12-22 20:06:35,607] Trial 185 finished with values: [0.5015626393112494, 0.5656796477937347] and parameters: {'n_neighbors': 24, 'n_components': 7, 'min_dist': 0.07, 'min_cluster_size': 10, 'min_samples': 10, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/43 [00:00<?, ?it/s]
100%|██████████| 43/43 [00:00<00:00, 390.39it/s]

Trial 186: DBCV=0.469, CCC=0.559
[I 2025-12-22 20:06:46,178] Trial 186 finished with values: [0.5591690266936277, 0.46867656401780305] and parameters: {'n_neighbors': 26, 'n_components': 6, 'min_dist': 0.24, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 10/10 [00:00<00:00, 390.29it/s]

Trial 187: DBCV=0.231, CCC=0.729
[I 2025-12-22 20:06:54,658] Trial 187 finished with values: [0.729073895665228, 0.23109584690765156] and parameters: {'n_neighbors': 3, 'n_components': 10, 'min_dist': 0.19, 'min_cluster_size': 29, 'min_samples': 19, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 314.39it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 188: DBCV=0.051, CCC=0.000
[I 2025-12-22 20:07:05,014] Trial 188 finished with values: [0.0, 0.0510620318174694] and parameters: {'n_neighbors': 19, 'n_components': 6, 'min_dist': 0.27, 'min_cluster_size': 12, 'min_samples': 8, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 1/1 [00:00<00:00, 282.27it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 189: DBCV=-0.190, CCC=0.000
[I 2025-12-22 20:07:16,009] Trial 189 finished with values: [0.0, -0.19039736118388606] and parameters: {'n_neighbors': 24, 'n_components': 11, 'min_dist': 0.06, 'min_cluster_size': 42, 'min_samples': 10, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 35/35 [00:00<00:00, 392.01it/s]

Trial 190: DBCV=0.487, CCC=0.575
[I 2025-12-22 20:07:26,316] Trial 190 finished with values: [0.5753527272186464, 0.48711754123670997] and parameters: {'n_neighbors': 29, 'n_components': 4, 'min_dist': 0.12, 'min_cluster_size': 15, 'min_samples': 7, 'cluster_selection_epsilon': 0.17}.

  0%|          | 0/47 [00:00<?, ?it/s]
100%|██████████| 47/47 [00:00<00:00, 389.07it/s]

Trial 191: DBCV=0.484, CCC=0.501
[I 2025-12-22 20:07:37,379] Trial 191 finished with values: [0.5014321218000108, 0.4836012343296392] and parameters: {'n_neighbors': 26, 'n_components': 11, 'min_dist': 0.3, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 219.39it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 192: DBCV=0.217, CCC=0.000
[I 2025-12-22 20:07:49,006] Trial 192 finished with values: [0.0, 0.21714491703016275] and parameters: {'n_neighbors': 44, 'n_components': 10, 'min_dist': 0.16, 'min_cluster_size': 9, 'min_samples': 6, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 23/23 [00:00<00:00, 390.09it/s]

Trial 193: DBCV=0.508, CCC=0.500
[I 2025-12-22 20:07:59,273] Trial 193 finished with values: [0.4995105320525634, 0.5075220787060833] and parameters: {'n_neighbors': 32, 'n_components': 4, 'min_dist': 0.14, 'min_cluster_size': 15, 'min_samples': 17, 'cluster_selection_epsilon': 0.0}.

  0%|          | 0/60 [00:00<?, ?it/s]
100%|██████████| 60/60 [00:00<00:00, 396.13it/s]

Trial 194: DBCV=0.569, CCC=0.498
[I 2025-12-22 20:08:10,470] Trial 194 finished with values: [0.49777497886597, 0.5689514443447342] and parameters: {'n_neighbors': 24, 'n_components': 12, 'min_dist': 0.07, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 18/18 [00:00<00:00, 376.77it/s]

Trial 195: DBCV=0.497, CCC=0.555
[I 2025-12-22 20:08:21,433] Trial 195 finished with values: [0.5550259142262818, 0.4971578700298803] and parameters: {'n_neighbors': 29, 'n_components': 11, 'min_dist': 0.17, 'min_cluster_size': 24, 'min_samples': 17, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 10/10 [00:00<00:00, 348.82it/s]

Trial 196: DBCV=0.428, CCC=0.572
[I 2025-12-22 20:08:32,063] Trial 196 finished with values: [0.571898127173857, 0.4279012881301131] and parameters: {'n_neighbors': 29, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 46, 'min_samples': 20, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 11/11 [00:00<00:00, 355.26it/s]

Trial 197: DBCV=0.396, CCC=0.612
[I 2025-12-22 20:08:43,130] Trial 197 finished with values: [0.6122100866151039, 0.39595120694194896] and parameters: {'n_neighbors': 32, 'n_components': 11, 'min_dist': 0.16, 'min_cluster_size': 41, 'min_samples': 13, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 34/34 [00:00<00:00, 397.19it/s]

Trial 198: DBCV=0.546, CCC=0.539
[I 2025-12-22 20:08:53,074] Trial 198 finished with values: [0.5393908551634182, 0.5455059913275561] and parameters: {'n_neighbors': 14, 'n_components': 7, 'min_dist': 0.11, 'min_cluster_size': 15, 'min_samples': 11, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 320.40it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 199: DBCV=0.566, CCC=0.000
[I 2025-12-22 20:09:04,109] Trial 199 finished with values: [0.0, 0.5664356248488147] and parameters: {'n_neighbors': 16, 'n_components': 14, 'min_dist': 0.14, 'min_cluster_size': 29, 'min_samples': 5, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 40/40 [00:00<00:00, 403.73it/s]

Trial 200: DBCV=0.514, CCC=0.546
[I 2025-12-22 20:09:14,786] Trial 200 finished with values: [0.5456870980201354, 0.5141950142391782] and parameters: {'n_neighbors': 23, 'n_components': 10, 'min_dist': 0.0, 'min_cluster_size': 15, 'min_samples': 7, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 35/35 [00:00<00:00, 399.87it/s]

Trial 201: DBCV=0.450, CCC=0.579
[I 2025-12-22 20:09:25,124] Trial 201 finished with values: [0.5792963138784719, 0.44973410790033286] and parameters: {'n_neighbors': 31, 'n_components': 4, 'min_dist': 0.07, 'min_cluster_size': 15, 'min_samples': 7, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 312.24it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 202: DBCV=0.484, CCC=0.000
[I 2025-12-22 20:09:36,033] Trial 202 finished with values: [0.0, 0.48351690141785136] and parameters: {'n_neighbors': 24, 'n_components': 10, 'min_dist': 0.09, 'min_cluster_size': 15, 'min_samples': 20, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 8/8 [00:00<00:00, 389.68it/s]

Trial 203: DBCV=0.410, CCC=0.568
[I 2025-12-22 20:09:47,055] Trial 203 finished with values: [0.5679144490102804, 0.4102080183038138] and parameters: {'n_neighbors': 37, 'n_components': 10, 'min_dist': 0.17, 'min_cluster_size': 48, 'min_samples': 15, 'cluster_selection_epsilon': 0.12}.

  0%|          | 0/55 [00:00<?, ?it/s]
100%|██████████| 55/55 [00:00<00:00, 380.36it/s]

Trial 204: DBCV=0.555, CCC=0.508
[I 2025-12-22 20:09:59,246] Trial 204 finished with values: [0.5083627743373611, 0.5552487862265302] and parameters: {'n_neighbors': 32, 'n_components': 15, 'min_dist': 0.08, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 11/11 [00:00<00:00, 335.51it/s]

Trial 205: DBCV=0.514, CCC=0.617
[I 2025-12-22 20:10:09,923] Trial 205 finished with values: [0.616731769091116, 0.5142781374548332] and parameters: {'n_neighbors': 21, 'n_components': 12, 'min_dist': 0.1, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.02}.

  0%|          | 0/47 [00:00<?, ?it/s]
100%|██████████| 47/47 [00:00<00:00, 377.38it/s]

Trial 206: DBCV=0.555, CCC=0.563
[I 2025-12-22 20:10:21,395] Trial 206 finished with values: [0.5632093620531294, 0.5546831420126829] and parameters: {'n_neighbors': 35, 'n_components': 11, 'min_dist': 0.07, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.08}.

  0%|          | 0/42 [00:00<?, ?it/s]
100%|██████████| 42/42 [00:00<00:00, 393.37it/s]

Trial 207: DBCV=0.446, CCC=0.547
[I 2025-12-22 20:10:32,673] Trial 207 finished with values: [0.547324663617111, 0.44626205415091774] and parameters: {'n_neighbors': 29, 'n_components': 12, 'min_dist': 0.28, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 24/24 [00:00<00:00, 390.94it/s]

Trial 208: DBCV=0.502, CCC=0.557
[I 2025-12-22 20:10:44,444] Trial 208 finished with values: [0.5566398361107378, 0.5019062214140237] and parameters: {'n_neighbors': 37, 'n_components': 14, 'min_dist': 0.23, 'min_cluster_size': 5, 'min_samples': 18, 'cluster_selection_epsilon': 0.02}.

  0%|          | 0/61 [00:00<?, ?it/s]
100%|██████████| 61/61 [00:00<00:00, 392.90it/s]

Trial 209: DBCV=0.573, CCC=0.496
[I 2025-12-22 20:10:55,870] Trial 209 finished with values: [0.4964291581361059, 0.5734498787169657] and parameters: {'n_neighbors': 29, 'n_components': 12, 'min_dist': 0.08, 'min_cluster_size': 7, 'min_samples': 8, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 18/18 [00:00<00:00, 376.19it/s]

Trial 210: DBCV=0.425, CCC=0.585
[I 2025-12-22 20:11:06,472] Trial 210 finished with values: [0.5853731912377659, 0.4250994104768871] and parameters: {'n_neighbors': 33, 'n_components': 6, 'min_dist': 0.1, 'min_cluster_size': 17, 'min_samples': 20, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 1/1 [00:00<00:00, 314.96it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 211: DBCV=0.278, CCC=0.000
[I 2025-12-22 20:11:17,617] Trial 211 finished with values: [0.0, 0.27805327195744534] and parameters: {'n_neighbors': 33, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 11, 'min_samples': 20, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 321.01it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 212: DBCV=0.587, CCC=0.000
[I 2025-12-22 20:11:28,068] Trial 212 finished with values: [0.0, 0.5866575996722003] and parameters: {'n_neighbors': 18, 'n_components': 7, 'min_dist': 0.07, 'min_cluster_size': 3, 'min_samples': 20, 'cluster_selection_epsilon': 0.24}.

  0%|          | 0/79 [00:00<?, ?it/s]
100%|██████████| 79/79 [00:00<00:00, 401.48it/s]

Trial 213: DBCV=0.625, CCC=0.483
[I 2025-12-22 20:11:38,151] Trial 213 finished with values: [0.4828732226411968, 0.6248338516246869] and parameters: {'n_neighbors': 12, 'n_components': 8, 'min_dist': 0.08, 'min_cluster_size': 2, 'min_samples': 8, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 13/13 [00:00<00:00, 392.26it/s]

Trial 214: DBCV=0.291, CCC=0.739
[I 2025-12-22 20:11:46,544] Trial 214 finished with values: [0.7385446574399419, 0.2909002508711009] and parameters: {'n_neighbors': 3, 'n_components': 7, 'min_dist': 0.22, 'min_cluster_size': 31, 'min_samples': 6, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 10/10 [00:00<00:00, 396.93it/s]

Trial 215: DBCV=0.337, CCC=0.763
[I 2025-12-22 20:11:57,155] Trial 215 finished with values: [0.7626522893966474, 0.3366706324360851] and parameters: {'n_neighbors': 16, 'n_components': 14, 'min_dist': 0.07, 'min_cluster_size': 46, 'min_samples': 11, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 1/1 [00:00<00:00, 282.01it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 216: DBCV=-0.238, CCC=0.000
[I 2025-12-22 20:12:07,664] Trial 216 finished with values: [0.0, -0.23768597733711683] and parameters: {'n_neighbors': 40, 'n_components': 2, 'min_dist': 0.16, 'min_cluster_size': 24, 'min_samples': 19, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 16/16 [00:00<00:00, 403.32it/s]

Trial 217: DBCV=0.453, CCC=0.671
[I 2025-12-22 20:12:15,985] Trial 217 finished with values: [0.6708344194224585, 0.45267024739943196] and parameters: {'n_neighbors': 3, 'n_components': 6, 'min_dist': 0.21, 'min_cluster_size': 10, 'min_samples': 19, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 267.78it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 218: DBCV=0.325, CCC=0.000
[I 2025-12-22 20:12:28,857] Trial 218 finished with values: [0.0, 0.3249974348060385] and parameters: {'n_neighbors': 48, 'n_components': 15, 'min_dist': 0.07, 'min_cluster_size': 28, 'min_samples': 9, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 37/37 [00:00<00:00, 398.61it/s]

Trial 219: DBCV=0.576, CCC=0.557
[I 2025-12-22 20:12:39,702] Trial 219 finished with values: [0.5573747372871997, 0.5758883533963419] and parameters: {'n_neighbors': 29, 'n_components': 9, 'min_dist': 0.1, 'min_cluster_size': 5, 'min_samples': 12, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 12/12 [00:00<00:00, 401.51it/s]

Trial 220: DBCV=0.322, CCC=0.612
[I 2025-12-22 20:12:50,757] Trial 220 finished with values: [0.6118488352425224, 0.3215343252173545] and parameters: {'n_neighbors': 37, 'n_components': 10, 'min_dist': 0.21, 'min_cluster_size': 34, 'min_samples': 7, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 7/7 [00:00<00:00, 390.75it/s]

Trial 221: DBCV=0.441, CCC=0.636
[I 2025-12-22 20:13:00,965] Trial 221 finished with values: [0.6364276389276513, 0.44089161853856557] and parameters: {'n_neighbors': 16, 'n_components': 12, 'min_dist': 0.26, 'min_cluster_size': 48, 'min_samples': 18, 'cluster_selection_epsilon': 0.17}.

  0%|          | 0/58 [00:00<?, ?it/s]
100%|██████████| 58/58 [00:00<00:00, 391.00it/s]

Trial 222: DBCV=0.561, CCC=0.533
[I 2025-12-22 20:13:13,027] Trial 222 finished with values: [0.5326130462249056, 0.5607481544844898] and parameters: {'n_neighbors': 37, 'n_components': 14, 'min_dist': 0.17, 'min_cluster_size': 5, 'min_samples': 7, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 9/9 [00:00<00:00, 342.30it/s]

Trial 223: DBCV=0.464, CCC=0.765
[I 2025-12-22 20:13:23,741] Trial 223 finished with values: [0.7651339660701999, 0.4636635736183961] and parameters: {'n_neighbors': 33, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.01}.

  0%|          | 0/60 [00:00<?, ?it/s]
100%|██████████| 60/60 [00:00<00:00, 399.54it/s]

Trial 224: DBCV=0.505, CCC=0.459
[I 2025-12-22 20:13:34,852] Trial 224 finished with values: [0.45882408255014245, 0.5050881853947324] and parameters: {'n_neighbors': 33, 'n_components': 7, 'min_dist': 0.16, 'min_cluster_size': 2, 'min_samples': 8, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 39/39 [00:00<00:00, 401.63it/s]

Trial 225: DBCV=0.537, CCC=0.488
[I 2025-12-22 20:13:45,745] Trial 225 finished with values: [0.487913928701546, 0.5370668308251428] and parameters: {'n_neighbors': 37, 'n_components': 6, 'min_dist': 0.06, 'min_cluster_size': 7, 'min_samples': 9, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 8/8 [00:00<00:00, 389.22it/s]

Trial 226: DBCV=0.400, CCC=0.787
[I 2025-12-22 20:13:56,485] Trial 226 finished with values: [0.7868392241518704, 0.4004117639134096] and parameters: {'n_neighbors': 26, 'n_components': 11, 'min_dist': 0.17, 'min_cluster_size': 44, 'min_samples': 20, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 38/38 [00:00<00:00, 392.78it/s]

Trial 227: DBCV=0.471, CCC=0.542
[I 2025-12-22 20:14:06,659] Trial 227 finished with values: [0.541673690850467, 0.4708817193801472] and parameters: {'n_neighbors': 26, 'n_components': 4, 'min_dist': 0.07, 'min_cluster_size': 15, 'min_samples': 7, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 7/7 [00:00<00:00, 373.80it/s]

Trial 228: DBCV=-0.202, CCC=0.743
[I 2025-12-22 20:14:14,887] Trial 228 finished with values: [0.7431288335438276, -0.20169284721687875] and parameters: {'n_neighbors': 3, 'n_components': 2, 'min_dist': 0.15, 'min_cluster_size': 29, 'min_samples': 19, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 10/10 [00:00<00:00, 392.89it/s]

Trial 229: DBCV=0.339, CCC=0.646
[I 2025-12-22 20:14:25,257] Trial 229 finished with values: [0.6458523465987211, 0.3393065092427524] and parameters: {'n_neighbors': 24, 'n_components': 7, 'min_dist': 0.23, 'min_cluster_size': 42, 'min_samples': 7, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 286.44it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 230: DBCV=0.585, CCC=0.000
[I 2025-12-22 20:14:36,044] Trial 230 finished with values: [0.0, 0.5851597571221557] and parameters: {'n_neighbors': 17, 'n_components': 12, 'min_dist': 0.21, 'min_cluster_size': 29, 'min_samples': 8, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 31/31 [00:00<00:00, 395.65it/s]

Trial 231: DBCV=0.402, CCC=0.632
[I 2025-12-22 20:14:45,961] Trial 231 finished with values: [0.6316074645301606, 0.4022920290064594] and parameters: {'n_neighbors': 21, 'n_components': 4, 'min_dist': 0.16, 'min_cluster_size': 19, 'min_samples': 7, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 1/1 [00:00<00:00, 282.41it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 232: DBCV=0.297, CCC=0.000
[I 2025-12-22 20:14:56,003] Trial 232 finished with values: [0.0, 0.2966065104323678] and parameters: {'n_neighbors': 19, 'n_components': 4, 'min_dist': 0.16, 'min_cluster_size': 15, 'min_samples': 11, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 4/4 [00:00<00:00, 273.64it/s]

Trial 233: DBCV=-0.182, CCC=0.751
[I 2025-12-22 20:15:04,218] Trial 233 finished with values: [0.7513680487505832, -0.18238210631671817] and parameters: {'n_neighbors': 3, 'n_components': 2, 'min_dist': 0.15, 'min_cluster_size': 44, 'min_samples': 20, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 9/9 [00:00<00:00, 321.54it/s]

Trial 234: DBCV=0.423, CCC=0.843
[I 2025-12-22 20:15:12,570] Trial 234 finished with values: [0.8430994821900948, 0.42287635892620734] and parameters: {'n_neighbors': 3, 'n_components': 10, 'min_dist': 0.28, 'min_cluster_size': 34, 'min_samples': 17, 'cluster_selection_epsilon': 0.23}.

  0%|          | 0/80 [00:00<?, ?it/s]
100%|██████████| 80/80 [00:00<00:00, 405.16it/s]

Trial 235: DBCV=0.469, CCC=0.483
[I 2025-12-22 20:15:23,926] Trial 235 finished with values: [0.48307341569840456, 0.4686634013699835] and parameters: {'n_neighbors': 46, 'n_components': 5, 'min_dist': 0.02, 'min_cluster_size': 7, 'min_samples': 3, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 10/10 [00:00<00:00, 346.47it/s]

Trial 236: DBCV=0.397, CCC=0.525
[I 2025-12-22 20:15:34,163] Trial 236 finished with values: [0.5247201897680326, 0.397489020758082] and parameters: {'n_neighbors': 21, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 42, 'min_samples': 12, 'cluster_selection_epsilon': 0.23}.

  0%|          | 0/45 [00:00<?, ?it/s]
100%|██████████| 45/45 [00:00<00:00, 402.54it/s]

Trial 237: DBCV=0.591, CCC=0.475
[I 2025-12-22 20:15:42,692] Trial 237 finished with values: [0.47485343016043285, 0.5907741544212138] and parameters: {'n_neighbors': 3, 'n_components': 5, 'min_dist': 0.15, 'min_cluster_size': 2, 'min_samples': 12, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 6/6 [00:00<00:00, 387.10it/s]

Trial 238: DBCV=0.440, CCC=0.604
[I 2025-12-22 20:15:53,691] Trial 238 finished with values: [0.6038079644388268, 0.4402639575160738] and parameters: {'n_neighbors': 35, 'n_components': 10, 'min_dist': 0.16, 'min_cluster_size': 45, 'min_samples': 20, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 10/10 [00:00<00:00, 351.80it/s]

Trial 239: DBCV=0.551, CCC=0.617
[I 2025-12-22 20:16:04,543] Trial 239 finished with values: [0.616636009063641, 0.5505843894563716] and parameters: {'n_neighbors': 26, 'n_components': 12, 'min_dist': 0.07, 'min_cluster_size': 44, 'min_samples': 20, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 34/34 [00:00<00:00, 397.46it/s]

Trial 240: DBCV=0.605, CCC=0.535
[I 2025-12-22 20:16:15,364] Trial 240 finished with values: [0.5354927610158396, 0.6045540901637433] and parameters: {'n_neighbors': 14, 'n_components': 15, 'min_dist': 0.11, 'min_cluster_size': 15, 'min_samples': 11, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 11/11 [00:00<00:00, 357.20it/s]

Trial 241: DBCV=0.448, CCC=0.591
[I 2025-12-22 20:16:25,477] Trial 241 finished with values: [0.5906326710913484, 0.4481190503219602] and parameters: {'n_neighbors': 22, 'n_components': 6, 'min_dist': 0.24, 'min_cluster_size': 34, 'min_samples': 17, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 16/16 [00:00<00:00, 378.86it/s]

Trial 242: DBCV=0.123, CCC=0.460
[I 2025-12-22 20:16:33,690] Trial 242 finished with values: [0.46005519498583947, 0.12277190888197367] and parameters: {'n_neighbors': 3, 'n_components': 2, 'min_dist': 0.15, 'min_cluster_size': 28, 'min_samples': 14, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 22/22 [00:00<00:00, 413.98it/s]

Trial 243: DBCV=0.534, CCC=0.565
[I 2025-12-22 20:16:44,700] Trial 243 finished with values: [0.5654734093375454, 0.5336924575686712] and parameters: {'n_neighbors': 47, 'n_components': 6, 'min_dist': 0.21, 'min_cluster_size': 7, 'min_samples': 19, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 14/14 [00:00<00:00, 368.84it/s]

Trial 244: DBCV=0.450, CCC=0.538
[I 2025-12-22 20:16:55,792] Trial 244 finished with values: [0.5382590653016245, 0.4502021442429334] and parameters: {'n_neighbors': 37, 'n_components': 10, 'min_dist': 0.02, 'min_cluster_size': 34, 'min_samples': 7, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 8/8 [00:00<00:00, 393.46it/s]

Trial 245: DBCV=0.456, CCC=0.662
[I 2025-12-22 20:17:06,131] Trial 245 finished with values: [0.6615692198325055, 0.45587889612521737] and parameters: {'n_neighbors': 19, 'n_components': 11, 'min_dist': 0.16, 'min_cluster_size': 45, 'min_samples': 20, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 11/11 [00:00<00:00, 356.16it/s]

Trial 246: DBCV=0.349, CCC=0.608
[I 2025-12-22 20:17:16,091] Trial 246 finished with values: [0.6079766652815966, 0.3489021938897257] and parameters: {'n_neighbors': 27, 'n_components': 3, 'min_dist': 0.06, 'min_cluster_size': 48, 'min_samples': 10, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 8/8 [00:00<00:00, 339.41it/s]

Trial 247: DBCV=0.456, CCC=0.662
[I 2025-12-22 20:17:26,448] Trial 247 finished with values: [0.6615692198325055, 0.45587889612521737] and parameters: {'n_neighbors': 19, 'n_components': 11, 'min_dist': 0.16, 'min_cluster_size': 45, 'min_samples': 20, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 7/7 [00:00<00:00, 326.72it/s]

Trial 248: DBCV=0.434, CCC=0.623
[I 2025-12-22 20:17:37,136] Trial 248 finished with values: [0.6226580383199599, 0.4335338188331695] and parameters: {'n_neighbors': 33, 'n_components': 7, 'min_dist': 0.26, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 6/6 [00:00<00:00, 386.51it/s]

Trial 249: DBCV=0.548, CCC=0.775
[I 2025-12-22 20:17:47,844] Trial 249 finished with values: [0.7745255243899936, 0.548326854927421] and parameters: {'n_neighbors': 32, 'n_components': 10, 'min_dist': 0.28, 'min_cluster_size': 46, 'min_samples': 20, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 9/9 [00:00<00:00, 398.21it/s]

Trial 250: DBCV=0.339, CCC=0.733
[I 2025-12-22 20:17:58,414] Trial 250 finished with values: [0.733248306437641, 0.3386574704837484] and parameters: {'n_neighbors': 21, 'n_components': 12, 'min_dist': 0.17, 'min_cluster_size': 44, 'min_samples': 20, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 35/35 [00:00<00:00, 391.37it/s]

Trial 251: DBCV=0.437, CCC=0.627
[I 2025-12-22 20:18:08,706] Trial 251 finished with values: [0.6271360318076168, 0.43711483706322835] and parameters: {'n_neighbors': 29, 'n_components': 4, 'min_dist': 0.11, 'min_cluster_size': 15, 'min_samples': 7, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 17/17 [00:00<00:00, 357.43it/s]

Trial 252: DBCV=0.067, CCC=0.447
[I 2025-12-22 20:18:16,989] Trial 252 finished with values: [0.44736042824499556, 0.06708710277077135] and parameters: {'n_neighbors': 3, 'n_components': 3, 'min_dist': 0.22, 'min_cluster_size': 31, 'min_samples': 6, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 12/12 [00:00<00:00, 360.74it/s]

Trial 253: DBCV=0.442, CCC=0.672
[I 2025-12-22 20:18:27,518] Trial 253 finished with values: [0.6716337326350152, 0.44197036842971155] and parameters: {'n_neighbors': 37, 'n_components': 5, 'min_dist': 0.17, 'min_cluster_size': 34, 'min_samples': 16, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 9/9 [00:00<00:00, 394.18it/s]

Trial 254: DBCV=0.423, CCC=0.843
[I 2025-12-22 20:18:35,914] Trial 254 finished with values: [0.8430994821900948, 0.42287635892620734] and parameters: {'n_neighbors': 3, 'n_components': 10, 'min_dist': 0.28, 'min_cluster_size': 34, 'min_samples': 17, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 36/36 [00:00<00:00, 393.08it/s]

Trial 255: DBCV=0.578, CCC=0.526
[I 2025-12-22 20:18:45,981] Trial 255 finished with values: [0.5264244595000632, 0.5778487890481404] and parameters: {'n_neighbors': 14, 'n_components': 10, 'min_dist': 0.11, 'min_cluster_size': 15, 'min_samples': 11, 'cluster_selection_epsilon': 0.23}.

  0%|          | 0/104 [00:00<?, ?it/s]
 40%|████      | 42/104 [00:00<00:00, 417.16it/s]
100%|██████████| 104/104 [00:00<00:00, 393.82it/s][A

Trial 256: DBCV=0.574, CCC=0.457
[I 2025-12-22 20:18:56,523] Trial 256 finished with values: [0.4570440421831215, 0.5737920269365306] and parameters: {'n_neighbors': 12, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 5, 'min_samples': 5, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 9/9 [00:00<00:00, 326.87it/s]

Trial 257: DBCV=0.391, CCC=0.716
[I 2025-12-22 20:19:07,405] Trial 257 finished with values: [0.7161194732505827, 0.3905717404799279] and parameters: {'n_neighbors': 40, 'n_components': 8, 'min_dist': 0.16, 'min_cluster_size': 46, 'min_samples': 20, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 37/37 [00:00<00:00, 410.97it/s]

Trial 258: DBCV=0.590, CCC=0.480
[I 2025-12-22 20:19:15,933] Trial 258 finished with values: [0.47954178212539156, 0.5903216628858361] and parameters: {'n_neighbors': 3, 'n_components': 6, 'min_dist': 0.07, 'min_cluster_size': 10, 'min_samples': 14, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 8/8 [00:00<00:00, 391.11it/s]

Trial 259: DBCV=0.358, CCC=0.747
[I 2025-12-22 20:19:25,602] Trial 259 finished with values: [0.7471612495217542, 0.3584783784366957] and parameters: {'n_neighbors': 14, 'n_components': 6, 'min_dist': 0.21, 'min_cluster_size': 40, 'min_samples': 19, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 13/13 [00:00<00:00, 368.38it/s]

Trial 260: DBCV=0.408, CCC=0.591
[I 2025-12-22 20:19:36,564] Trial 260 finished with values: [0.5914281854892185, 0.4081794464560281] and parameters: {'n_neighbors': 35, 'n_components': 10, 'min_dist': 0.22, 'min_cluster_size': 31, 'min_samples': 7, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 256.20it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 261: DBCV=0.268, CCC=0.000
[I 2025-12-22 20:19:46,282] Trial 261 finished with values: [0.0, 0.2682878988926316] and parameters: {'n_neighbors': 16, 'n_components': 2, 'min_dist': 0.07, 'min_cluster_size': 28, 'min_samples': 14, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 1/1 [00:00<00:00, 313.41it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 262: DBCV=0.333, CCC=0.000
[I 2025-12-22 20:19:56,513] Trial 262 finished with values: [0.0, 0.33342381172520164] and parameters: {'n_neighbors': 17, 'n_components': 6, 'min_dist': 0.21, 'min_cluster_size': 14, 'min_samples': 19, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 13/13 [00:00<00:00, 400.76it/s]

Trial 263: DBCV=0.277, CCC=0.617
[I 2025-12-22 20:20:07,213] Trial 263 finished with values: [0.6173123263752829, 0.277449301336272] and parameters: {'n_neighbors': 14, 'n_components': 15, 'min_dist': 0.11, 'min_cluster_size': 42, 'min_samples': 2, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 9/9 [00:00<00:00, 392.06it/s]

Trial 264: DBCV=0.407, CCC=0.780
[I 2025-12-22 20:20:17,721] Trial 264 finished with values: [0.7802797850424544, 0.40676164326821845] and parameters: {'n_neighbors': 21, 'n_components': 11, 'min_dist': 0.1, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 12/12 [00:00<00:00, 344.98it/s]

Trial 265: DBCV=0.357, CCC=0.639
[I 2025-12-22 20:20:26,793] Trial 265 finished with values: [0.6386426173453656, 0.35720875112387807] and parameters: {'n_neighbors': 12, 'n_components': 2, 'min_dist': 0.15, 'min_cluster_size': 44, 'min_samples': 19, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 9/9 [00:00<00:00, 345.07it/s]

Trial 266: DBCV=0.423, CCC=0.843
[I 2025-12-22 20:20:35,137] Trial 266 finished with values: [0.8430994821900948, 0.42287635892620734] and parameters: {'n_neighbors': 3, 'n_components': 10, 'min_dist': 0.28, 'min_cluster_size': 34, 'min_samples': 17, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 10/10 [00:00<00:00, 391.97it/s]

Trial 267: DBCV=0.219, CCC=0.600
[I 2025-12-22 20:20:43,729] Trial 267 finished with values: [0.6001356400129768, 0.21865410394531143] and parameters: {'n_neighbors': 3, 'n_components': 12, 'min_dist': 0.22, 'min_cluster_size': 48, 'min_samples': 5, 'cluster_selection_epsilon': 0.01}.

  0%|          | 0/71 [00:00<?, ?it/s]
100%|██████████| 71/71 [00:00<00:00, 400.94it/s]

Trial 268: DBCV=0.484, CCC=0.492
[I 2025-12-22 20:20:54,623] Trial 268 finished with values: [0.49164654814909664, 0.48413937679180113] and parameters: {'n_neighbors': 24, 'n_components': 7, 'min_dist': 0.15, 'min_cluster_size': 6, 'min_samples': 6, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 9/9 [00:00<00:00, 344.39it/s]

Trial 269: DBCV=0.391, CCC=0.716
[I 2025-12-22 20:21:05,397] Trial 269 finished with values: [0.7161194732505827, 0.3905717404799279] and parameters: {'n_neighbors': 40, 'n_components': 8, 'min_dist': 0.16, 'min_cluster_size': 46, 'min_samples': 20, 'cluster_selection_epsilon': 0.3}.

  0%|          | 0/41 [00:00<?, ?it/s]
100%|██████████| 41/41 [00:00<00:00, 396.01it/s]

Trial 270: DBCV=0.550, CCC=0.488
[I 2025-12-22 20:21:15,515] Trial 270 finished with values: [0.48763736183132095, 0.5495572910537475] and parameters: {'n_neighbors': 21, 'n_components': 5, 'min_dist': 0.21, 'min_cluster_size': 10, 'min_samples': 10, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 11/11 [00:00<00:00, 401.03it/s]

Trial 271: DBCV=0.450, CCC=0.750
[I 2025-12-22 20:21:25,933] Trial 271 finished with values: [0.7501344796818455, 0.4495570449027355] and parameters: {'n_neighbors': 19, 'n_components': 11, 'min_dist': 0.07, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.3}.

  0%|          | 0/41 [00:00<?, ?it/s]
100%|██████████| 41/41 [00:00<00:00, 397.72it/s]

Trial 272: DBCV=0.601, CCC=0.530
[I 2025-12-22 20:21:36,395] Trial 272 finished with values: [0.5300612508483336, 0.6012050755162357] and parameters: {'n_neighbors': 28, 'n_components': 5, 'min_dist': 0.14, 'min_cluster_size': 2, 'min_samples': 12, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 9/9 [00:00<00:00, 341.83it/s]

Trial 273: DBCV=0.464, CCC=0.765
[I 2025-12-22 20:21:47,130] Trial 273 finished with values: [0.7651339660701999, 0.4636635736183961] and parameters: {'n_neighbors': 33, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 35/35 [00:00<00:00, 401.17it/s]

Trial 274: DBCV=0.486, CCC=0.519
[I 2025-12-22 20:21:57,878] Trial 274 finished with values: [0.5192094722056773, 0.48645383196060776] and parameters: {'n_neighbors': 14, 'n_components': 15, 'min_dist': 0.28, 'min_cluster_size': 15, 'min_samples': 8, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 34/34 [00:00<00:00, 401.26it/s]

Trial 275: DBCV=0.585, CCC=0.583
[I 2025-12-22 20:22:08,817] Trial 275 finished with values: [0.5830317298702979, 0.5849463990648851] and parameters: {'n_neighbors': 33, 'n_components': 9, 'min_dist': 0.1, 'min_cluster_size': 8, 'min_samples': 12, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 38/38 [00:00<00:00, 418.24it/s]

Trial 276: DBCV=0.528, CCC=0.551
[I 2025-12-22 20:22:19,937] Trial 276 finished with values: [0.5506661988138948, 0.5275942845805217] and parameters: {'n_neighbors': 21, 'n_components': 14, 'min_dist': 0.07, 'min_cluster_size': 9, 'min_samples': 12, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 16/16 [00:00<00:00, 401.87it/s]

Trial 277: DBCV=0.542, CCC=0.586
[I 2025-12-22 20:22:28,664] Trial 277 finished with values: [0.5858657066542258, 0.5420018458929696] and parameters: {'n_neighbors': 3, 'n_components': 14, 'min_dist': 0.14, 'min_cluster_size': 29, 'min_samples': 18, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 39/39 [00:00<00:00, 401.88it/s]

Trial 278: DBCV=0.514, CCC=0.534
[I 2025-12-22 20:22:38,582] Trial 278 finished with values: [0.5343371604509738, 0.5143520818337323] and parameters: {'n_neighbors': 14, 'n_components': 8, 'min_dist': 0.08, 'min_cluster_size': 15, 'min_samples': 10, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 8/8 [00:00<00:00, 334.81it/s]

Trial 279: DBCV=0.400, CCC=0.787
[I 2025-12-22 20:22:49,387] Trial 279 finished with values: [0.7868392241518704, 0.4004117639134096] and parameters: {'n_neighbors': 26, 'n_components': 11, 'min_dist': 0.17, 'min_cluster_size': 48, 'min_samples': 20, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 16/16 [00:00<00:00, 404.97it/s]

Trial 280: DBCV=0.521, CCC=0.460
[I 2025-12-22 20:23:00,219] Trial 280 finished with values: [0.4601029046641378, 0.5210873235412216] and parameters: {'n_neighbors': 32, 'n_components': 10, 'min_dist': 0.28, 'min_cluster_size': 10, 'min_samples': 20, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 12/12 [00:00<00:00, 359.21it/s]

Trial 281: DBCV=0.519, CCC=0.692
[I 2025-12-22 20:23:11,044] Trial 281 finished with values: [0.691615307014054, 0.5189529560700888] and parameters: {'n_neighbors': 32, 'n_components': 10, 'min_dist': 0.07, 'min_cluster_size': 36, 'min_samples': 20, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 7/7 [00:00<00:00, 385.01it/s]

Trial 282: DBCV=0.194, CCC=0.705
[I 2025-12-22 20:23:19,368] Trial 282 finished with values: [0.7048341366960525, 0.1944923501121019] and parameters: {'n_neighbors': 3, 'n_components': 7, 'min_dist': 0.22, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 10/10 [00:00<00:00, 352.26it/s]

Trial 283: DBCV=0.400, CCC=0.740
[I 2025-12-22 20:23:29,952] Trial 283 finished with values: [0.7399306197493062, 0.400420159834884] and parameters: {'n_neighbors': 33, 'n_components': 8, 'min_dist': 0.1, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 1/1 [00:00<00:00, 197.30it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 284: DBCV=0.722, CCC=0.000
[I 2025-12-22 20:23:41,583] Trial 284 finished with values: [0.0, 0.7222644434555083] and parameters: {'n_neighbors': 22, 'n_components': 15, 'min_dist': 0.07, 'min_cluster_size': 28, 'min_samples': 14, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 40/40 [00:00<00:00, 403.73it/s]

Trial 285: DBCV=0.560, CCC=0.501
[I 2025-12-22 20:23:52,937] Trial 285 finished with values: [0.5006486547254484, 0.5604844273279124] and parameters: {'n_neighbors': 21, 'n_components': 14, 'min_dist': 0.06, 'min_cluster_size': 5, 'min_samples': 12, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 12/12 [00:00<00:00, 391.59it/s]

Trial 286: DBCV=0.266, CCC=0.749
[I 2025-12-22 20:24:03,599] Trial 286 finished with values: [0.7493345929189971, 0.2663646988479081] and parameters: {'n_neighbors': 16, 'n_components': 14, 'min_dist': 0.07, 'min_cluster_size': 46, 'min_samples': 5, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 1/1 [00:00<00:00, 221.67it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 287: DBCV=0.547, CCC=0.000
[I 2025-12-22 20:24:14,462] Trial 287 finished with values: [0.0, 0.5472905163211301] and parameters: {'n_neighbors': 19, 'n_components': 11, 'min_dist': 0.2, 'min_cluster_size': 15, 'min_samples': 20, 'cluster_selection_epsilon': 0.14}.

100%|██████████| 11/11 [00:00<00:00, 336.28it/s]

Trial 288: DBCV=0.392, CCC=0.654
[I 2025-12-22 20:24:25,188] Trial 288 finished with values: [0.653630437228993, 0.39174870369065184] and parameters: {'n_neighbors': 32, 'n_components': 7, 'min_dist': 0.07, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 24/24 [00:00<00:00, 381.62it/s]

Trial 289: DBCV=0.377, CCC=0.608
[I 2025-12-22 20:24:36,039] Trial 289 finished with values: [0.6078904484409218, 0.3772717785898057] and parameters: {'n_neighbors': 33, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 23, 'min_samples': 11, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 13/13 [00:00<00:00, 392.73it/s]

Trial 290: DBCV=0.346, CCC=0.623
[I 2025-12-22 20:24:46,467] Trial 290 finished with values: [0.6225420965527672, 0.34602963113340396] and parameters: {'n_neighbors': 16, 'n_components': 12, 'min_dist': 0.02, 'min_cluster_size': 46, 'min_samples': 3, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 13/13 [00:00<00:00, 341.48it/s]

Trial 291: DBCV=0.226, CCC=0.598
[I 2025-12-22 20:24:57,723] Trial 291 finished with values: [0.5978903940846856, 0.2256520308436389] and parameters: {'n_neighbors': 49, 'n_components': 7, 'min_dist': 0.22, 'min_cluster_size': 31, 'min_samples': 6, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 8/8 [00:00<00:00, 386.69it/s]

Trial 292: DBCV=0.413, CCC=0.702
[I 2025-12-22 20:25:07,486] Trial 292 finished with values: [0.7019220856456718, 0.41274826670439346] and parameters: {'n_neighbors': 12, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 42, 'min_samples': 20, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 8/8 [00:00<00:00, 391.53it/s]

Trial 293: DBCV=0.456, CCC=0.662
[I 2025-12-22 20:25:17,834] Trial 293 finished with values: [0.6615692198325055, 0.45587889612521737] and parameters: {'n_neighbors': 19, 'n_components': 11, 'min_dist': 0.16, 'min_cluster_size': 45, 'min_samples': 20, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 318.60it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 294: DBCV=0.082, CCC=0.000
[I 2025-12-22 20:25:27,737] Trial 294 finished with values: [0.0, 0.0823804048044593] and parameters: {'n_neighbors': 11, 'n_components': 7, 'min_dist': 0.22, 'min_cluster_size': 31, 'min_samples': 5, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 11/11 [00:00<00:00, 356.81it/s]

Trial 295: DBCV=0.526, CCC=0.676
[I 2025-12-22 20:25:38,201] Trial 295 finished with values: [0.6762360541512881, 0.5257212169943858] and parameters: {'n_neighbors': 26, 'n_components': 7, 'min_dist': 0.07, 'min_cluster_size': 44, 'min_samples': 20, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 28/28 [00:00<00:00, 394.26it/s]

Trial 296: DBCV=0.560, CCC=0.552
[I 2025-12-22 20:25:49,559] Trial 296 finished with values: [0.5517872084847074, 0.5599236548291638] and parameters: {'n_neighbors': 26, 'n_components': 14, 'min_dist': 0.1, 'min_cluster_size': 5, 'min_samples': 18, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 12/12 [00:00<00:00, 359.47it/s]

Trial 297: DBCV=0.279, CCC=0.621
[I 2025-12-22 20:25:59,950] Trial 297 finished with values: [0.6213302672031319, 0.27934209658922804] and parameters: {'n_neighbors': 22, 'n_components': 10, 'min_dist': 0.17, 'min_cluster_size': 34, 'min_samples': 17, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/55 [00:00<?, ?it/s]
100%|██████████| 55/55 [00:00<00:00, 378.51it/s]

Trial 298: DBCV=0.545, CCC=0.513
[I 2025-12-22 20:26:11,144] Trial 298 finished with values: [0.5133896272498831, 0.5449432357145753] and parameters: {'n_neighbors': 33, 'n_components': 10, 'min_dist': 0.08, 'min_cluster_size': 5, 'min_samples': 8, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 12/12 [00:00<00:00, 338.08it/s]

Trial 299: DBCV=0.504, CCC=0.642
[I 2025-12-22 20:26:19,450] Trial 299 finished with values: [0.6423006433507419, 0.5042779369786854] and parameters: {'n_neighbors': 3, 'n_components': 5, 'min_dist': 0.15, 'min_cluster_size': 34, 'min_samples': 17, 'cluster_selection_epsilon': 0.24}.

In [10]:
df_descriptions = study.trials_dataframe()
df_descriptions.head()

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_cluster_selection_epsilon,params_min_cluster_size,params_min_dist,params_min_samples,params_n_components,params_n_neighbors,user_attrs_ccc_score,user_attrs_dbcv_score,user_attrs_n_clusters,user_attrs_outlier_ratio,system_attrs_NSGAIISampler:generation,state
0,0,0.000000,0.185590,2025-12-22 19:33:44.291858,2025-12-22 19:33:53.110316,0 days 00:00:08.818458,0.02,27,0.21,19,6,4,0.000000,0.185590,2,0.018408,0,COMPLETE
1,1,0.000000,0.074920,2025-12-22 19:33:53.111950,2025-12-22 19:34:03.460243,0 days 00:00:10.348293,0.11,7,0.13,16,3,29,0.000000,0.074920,2,0.002488,0,COMPLETE
2,2,0.504849,0.447380,2025-12-22 19:34:03.461990,2025-12-22 19:34:14.282728,0 days 00:00:10.820738,0.20,9,0.15,5,5,34,0.504849,0.447380,59,0.329353,0,COMPLETE
3,3,0.000000,0.381165,2025-12-22 19:34:14.284346,2025-12-22 19:34:24.578156,0 days 00:00:10.293810,0.15,12,0.27,20,9,16,0.000000,0.381165,2,0.016418,0,COMPLETE
4,4,0.661569,0.455879,2025-12-22 19:34:24.579683,2025-12-22 19:34:34.955836,0 days 00:00:10.376153,0.15,45,0.16,20,11,19,0.661569,0.455879,9,0.415423,0,COMPLETE

In [11]:
import joblib
# Save to a file
joblib.dump(study, "02_251222_multi_clusterdata_descriptions_Apertus-8B-Instruct.pkl")

['02_251222_multi_clusterdata_descriptions_Apertus-8B-Instruct.pkl']

In [12]:
df_descriptions.to_csv("02_251222_multi_clusterdata_descriptions_Apertus-8B-Instruct.csv", index=False)

In [13]:
import optuna.visualization as vis

fig = vis.plot_pareto_front(
    study,
    target_names=["CCC Score", "Number of Clusters"], # Names for Obj 0 and Obj 1
    include_dominated_trials=True  # Set to True to see all points, not just the best frontier
)

fig.update_layout(width=600, height=500)
fig.show()