Run the following command in the terminal:

sbatch --gpus=1 --gres=gpumem:10g --time=05:00:00 --mem-per-cpu=32g --wrap="jupyter nbconvert --to notebook --execute 02_251218_optimizing_number_of_clusters_Apertus-8B-Instruct.ipynb --inplace"

In [2]:
import os
import json
import pandas as pd

directory_path = "./251029_generated_descriptions_Phi-4-mini-instruct"
data_list = []
# Iterate through all files in the directory
for filename in os.listdir(directory_path):
    if filename.endswith('.json'):
        file_path = os.path.join(directory_path, filename)
        with open(file_path, 'r', encoding='utf-8') as file:
            try:
                data = json.load(file)
                # Ensure it's a dict with 4 key-value pairs
                if isinstance(data, dict):
                    if data["data_point"] == "":
                        print(f"Skipping {filename}, data point empty")
                    
                        continue
                    data_list.append(data)
                else:
                    print(f"Skipping {filename}")
            except json.JSONDecodeError:
                print(f"Skipping {filename}: invalid JSON format.")
                
# Convert list of dicts to DataFrame
df = pd.DataFrame(data_list)
df.tail()

,question,original_source,data_group,data_point,reference_1,reference_2,description,references
2005,What is the meaning of eco-toxicity in relatio...,CPR 2024.pdf,essential environmental characteristics,eco-toxicity,CPR 2024.pdf,Circularise 2025.pdf,Eco-toxicity refers to the potential harm caus...,[{'text': 'ANNEX II Predeter mined environment...
2006,What is the meaning of freshwater in relation ...,CPR 2024.pdf,essential environmental characteristics,freshwater,CPR 2024.pdf,Circularise 2025.pdf,"Freshwater refers to water bodies like rivers,...",[{'text': 'ANNEX II Predeter mined environment...
2007,What is the meaning of human toxicity cancerog...,CPR 2024.pdf,essential environmental characteristics,human toxicity cancerogenic,CPR 2024.pdf,Circularise 2025.pdf,Human toxicity cancerogenic refers to substanc...,[{'text': 'ANNEX II Predeter mined environment...
2008,What is the meaning of human toxicity non-canc...,CPR 2024.pdf,essential environmental characteristics,human toxicity non-cancerogenic,CPR 2024.pdf,Circularise 2025.pdf,Human toxicity non-cancerogenic refers to subs...,[{'text': 'ANNEX II Predeter mined environment...
2009,What is the meaning of land use related impact...,CPR 2024.pdf,essential environmental characteristics,land use related impacts,CPR 2024.pdf,Kebede 2024.pdf,Land use related impacts refer to the environ...,[{'text': 'ANNEX II Predeter mined environment...

In [3]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import make_scorer
from sentence_transformers import SentenceTransformer


model = SentenceTransformer('./cluster/scratch/svangelova')
description_embeddings = model.encode(df["description"])

In [4]:
import numpy as np
import pandas as pd
import logging
from collections.abc import Iterable
from scipy.sparse import csr_matrix
from scipy.spatial.distance import squareform
from typing import Optional, Union, Tuple


def select_topic_representation(
    ctfidf_embeddings,
    embeddings,
    use_ctfidf: bool = True,
    output_ndarray: bool = False,
):
    """Select the topic representation.

    Arguments:
        ctfidf_embeddings: The c-TF-IDF embedding matrix
        embeddings: The topic embedding matrix
        use_ctfidf: Whether to use the c-TF-IDF representation. If False, topics embedding representation is used, if it
                    exists. Default is True.
        output_ndarray: Whether to convert the selected representation into ndarray
    Raises
        ValueError:
            - If no topic representation was found
            - If c-TF-IDF embeddings are not a numpy array or a scipy.sparse.csr_matrix

    Returns:
        The selected topic representation and a boolean indicating whether it is c-TF-IDF.
    """

    def to_ndarray(array: Union[np.ndarray, csr_matrix]) -> np.ndarray:
        if isinstance(array, csr_matrix):
            return array.toarray()
        return array
    if use_ctfidf:
        if ctfidf_embeddings is None:
            repr_, ctfidf_used = embeddings, False
        else:
            repr_, ctfidf_used = ctfidf_embeddings, True
    else:
        if embeddings is None:
            repr_, ctfidf_used = ctfidf_embeddings, True
        else:
            repr_, ctfidf_used = embeddings, False

    return to_ndarray(repr_) if output_ndarray else repr_, ctfidf_used


def validate_distance_matrix(X, n_samples):
    """Validate the distance matrix and convert it to a condensed distance matrix
    if necessary.

    A valid distance matrix is either a square matrix of shape (n_samples, n_samples)
    with zeros on the diagonal and non-negative values or condensed distance matrix
    of shape (n_samples * (n_samples - 1) / 2,) containing the upper triangular of the
    distance matrix.

    Arguments:
        X: Distance matrix to validate.
        n_samples: Number of samples in the dataset.

    Returns:
        X: Validated distance matrix.

    Raises:
        ValueError: If the distance matrix is not valid.
    """
    # Make sure it is the 1-D condensed distance matrix with zeros on the diagonal
    s = X.shape
    if len(s) == 1:
        # check it has correct size
        n = s[0]
        if n != (n_samples * (n_samples - 1) / 2):
            raise ValueError("The condensed distance matrix must have " "shape (n*(n-1)/2,).")
    elif len(s) == 2:
        # check it has correct size
        if (s[0] != n_samples) or (s[1] != n_samples):
            raise ValueError("The distance matrix must be of shape " "(n, n) where n is the number of samples.")
        # force zero diagonal and convert to condensed
        np.fill_diagonal(X, 0)
        X = squareform(X)
    else:
        raise ValueError(
            "The distance matrix must be either a 1-D condensed "
            "distance matrix of shape (n*(n-1)/2,) or a "
            "2-D square distance matrix of shape (n, n)."
            "where n is the number of documents."
            "Got a distance matrix of shape %s" % str(s)
        )

    # Make sure its entries are non-negative
    if np.any(X < 0):
        raise ValueError("Distance matrix cannot contain negative values.")

    return X

In [5]:
import optuna
import hdbscan
import numpy as np
from umap import UMAP
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.vectorizers import ClassTfidfTransformer
from sklearn.datasets import fetch_20newsgroups
from scipy.cluster import hierarchy as sch
from scipy.cluster.hierarchy import linkage, cophenet
from scipy.spatial.distance import pdist
from hdbscan.validity import validity_index
from sklearn.metrics.pairwise import cosine_similarity

def calculate_ccc(topic_model, docs):
    # Hierarchical topics
    linkage_function = lambda x: sch.linkage(x, "ward", optimal_ordering=True)
    _distance_function = lambda x: 1 - cosine_similarity(x)
    
    hierarchical_topics = topic_model.hierarchical_topics(docs, 
                                                          linkage_function=linkage_function, 
                                                          distance_function=_distance_function, 
                                                          use_ctfidf=True)
    
    # Select topic embeddings
    use_ctfidf = True

    # Calculate distance
    embeddings = select_topic_representation(topic_model.c_tf_idf_, topic_model.topic_embeddings_, use_ctfidf)[0][
        topic_model._outliers :
    ]
    distance_function = lambda x: validate_distance_matrix(_distance_function(x), embeddings.shape[0])
    
    dists = distance_function(embeddings)
    linkage_matrix = linkage_function(dists)

    ccc_score, _ = cophenet(linkage_matrix, dists)

    if np.isnan(ccc_score):
        return 0.0

    return ccc_score


ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

def objective(trial, docs, embeddings):
    # --- Hyperparameters to Optimize ---
    
    # UMAP Parameters
    n_neighbors = trial.suggest_int('n_neighbors', 2, 50)
    n_components = trial.suggest_int('n_components', 2, 15)
    min_dist = trial.suggest_float("min_dist", 0.0, 0.3, step=0.01)
    
    # HDBSCAN Parameters
    min_cluster_size = trial.suggest_int('min_cluster_size', 2, 50)
    min_samples = trial.suggest_int('min_samples', 1, 20)
    cluster_selection_epsilon = trial.suggest_float("cluster_selection_epsilon", 0.0, 0.3, step=0.01)
    
    # --- Model Initialization ---
    
    umap_model = UMAP(
        n_neighbors=n_neighbors,
        n_components=n_components,
        min_dist=min_dist,
        metric='cosine',
        random_state=42,
        n_jobs=1 #important for reproducability
    )

    
    hdbscan_model = hdbscan.HDBSCAN(
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        cluster_selection_epsilon=cluster_selection_epsilon,
        metric="euclidean",  
        cluster_selection_method='eom'
    )
    
    topic_model = BERTopic(
        hdbscan_model=hdbscan_model,
        vectorizer_model=CountVectorizer(stop_words='english'),
        ctfidf_model=ctfidf_model, 
        umap_model=umap_model,
        calculate_probabilities=False
        )

    topic_model.fit(docs, embeddings)

    labels = topic_model.get_document_info(docs).Topic
    mask = labels != -1
    n_clusters = len(np.unique(labels[mask]))
    emb_umap = topic_model.umap_model.embedding_
    
    emb_masked = np.ascontiguousarray(emb_umap[mask], dtype=np.float64)
    labels_masked = np.ascontiguousarray(labels[mask], dtype=np.int32)

    dbcv_score = validity_index(emb_masked, labels_masked, metric='euclidean')
    ccc_score = calculate_ccc(topic_model, docs)

    
    # logging for visibility
    print(f"Trial {trial.number}: DBCV={dbcv_score:.3f}, CCC={ccc_score:.3f}")

    # ---- Outlier ratio (fraction of points labeled -1)
    outlier_ratio =  outlier_ratio = np.mean(labels == -1)

    # Store the custom metrics in Optuna
    trial.set_user_attr("dbcv_score", dbcv_score)
    trial.set_user_attr("ccc_score", ccc_score)
    trial.set_user_attr("outlier_ratio", outlier_ratio)
    trial.set_user_attr("n_clusters", n_clusters)

    # Create directory if it doesn't exist
    os.makedirs("optuna_models/Phi-4-mini-instruct", exist_ok=True)
    
    # Save model (safely serialization)
    model_name = f"optuna_models/Phi-4-mini-instruct/251222_trial_{trial.number}_model"
    topic_model.save(model_name, serialization="safetensors", save_ctfidf=True)

    return ccc_score, dbcv_score

In [6]:
# 2. Run Multi-Objective Optimization
# Note: 'directions' list matches the return tuple order (DBCV, CCC)
study = optuna.create_study(directions=['maximize', 'maximize'])

study.optimize(lambda trial: objective(trial, df["description"], description_embeddings), n_trials=300, show_progress_bar=True)

[I 2025-12-22 19:37:54,251] A new study created in memory with name: no-name-9f755e7c-9a28-461b-a2eb-a3e4ec93b7a1

  0%|          | 0/300 [00:00<?, ?it/s]

100%|██████████| 1/1 [00:00<00:00, 257.89it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 0: DBCV=0.866, CCC=0.000
[I 2025-12-22 19:38:11,138] Trial 0 finished with values: [0.0, 0.8657794485696572] and parameters: {'n_neighbors': 18, 'n_components': 7, 'min_dist': 0.19, 'min_cluster_size': 41, 'min_samples': 3, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 292.80it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 1: DBCV=0.839, CCC=0.000
[I 2025-12-22 19:38:20,830] Trial 1 finished with values: [0.0, 0.8385386708203247] and parameters: {'n_neighbors': 17, 'n_components': 2, 'min_dist': 0.14, 'min_cluster_size': 42, 'min_samples': 7, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 298.95it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 2: DBCV=0.933, CCC=0.000
[I 2025-12-22 19:38:32,132] Trial 2 finished with values: [0.0, 0.9333010088546118] and parameters: {'n_neighbors': 30, 'n_components': 11, 'min_dist': 0.08, 'min_cluster_size': 49, 'min_samples': 2, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 1/1 [00:00<00:00, 295.54it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 3: DBCV=0.936, CCC=0.000
[I 2025-12-22 19:38:43,534] Trial 3 finished with values: [0.0, 0.9356713888044967] and parameters: {'n_neighbors': 41, 'n_components': 9, 'min_dist': 0.11, 'min_cluster_size': 39, 'min_samples': 17, 'cluster_selection_epsilon': 0.05}.

  0%|          | 0/113 [00:00<?, ?it/s]
 35%|███▌      | 40/113 [00:00<00:00, 392.80it/s]
100%|██████████| 113/113 [00:00<00:00, 382.55it/s][A

Trial 4: DBCV=0.433, CCC=0.416
[I 2025-12-22 19:38:54,600] Trial 4 finished with values: [0.41577729911722056, 0.43280753374745246] and parameters: {'n_neighbors': 17, 'n_components': 8, 'min_dist': 0.2, 'min_cluster_size': 5, 'min_samples': 2, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 18/18 [00:00<00:00, 394.10it/s]

Trial 5: DBCV=0.432, CCC=0.488
[I 2025-12-22 19:39:03,115] Trial 5 finished with values: [0.4884920987248704, 0.43228391409623673] and parameters: {'n_neighbors': 4, 'n_components': 2, 'min_dist': 0.08, 'min_cluster_size': 42, 'min_samples': 8, 'cluster_selection_epsilon': 0.06}.

  0%|          | 0/61 [00:00<?, ?it/s]
100%|██████████| 61/61 [00:00<00:00, 381.34it/s]

Trial 6: DBCV=0.562, CCC=0.493
[I 2025-12-22 19:39:13,728] Trial 6 finished with values: [0.49344021468132293, 0.5620662679798908] and parameters: {'n_neighbors': 17, 'n_components': 10, 'min_dist': 0.18, 'min_cluster_size': 7, 'min_samples': 6, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 1/1 [00:00<00:00, 308.43it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 7: DBCV=0.929, CCC=0.000
[I 2025-12-22 19:39:25,319] Trial 7 finished with values: [0.0, 0.9288973539992814] and parameters: {'n_neighbors': 21, 'n_components': 15, 'min_dist': 0.15, 'min_cluster_size': 27, 'min_samples': 19, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 1/1 [00:00<00:00, 323.88it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 8: DBCV=0.904, CCC=0.000
[I 2025-12-22 19:39:35,692] Trial 8 finished with values: [0.0, 0.9043432271117015] and parameters: {'n_neighbors': 10, 'n_components': 14, 'min_dist': 0.29, 'min_cluster_size': 18, 'min_samples': 3, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 1/1 [00:00<00:00, 271.81it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 9: DBCV=0.924, CCC=0.000
[I 2025-12-22 19:39:46,933] Trial 9 finished with values: [0.0, 0.924402453319039] and parameters: {'n_neighbors': 45, 'n_components': 6, 'min_dist': 0.13, 'min_cluster_size': 14, 'min_samples': 12, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 307.23it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 10: DBCV=0.912, CCC=0.000
[I 2025-12-22 19:39:57,541] Trial 10 finished with values: [0.0, 0.9120787747822362] and parameters: {'n_neighbors': 11, 'n_components': 15, 'min_dist': 0.25, 'min_cluster_size': 45, 'min_samples': 3, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 1/1 [00:00<00:00, 273.40it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 11: DBCV=0.870, CCC=0.000
[I 2025-12-22 19:40:07,826] Trial 11 finished with values: [0.0, 0.8696550636546037] and parameters: {'n_neighbors': 12, 'n_components': 11, 'min_dist': 0.07, 'min_cluster_size': 30, 'min_samples': 13, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 1/1 [00:00<00:00, 307.25it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 12: DBCV=0.921, CCC=0.000
[I 2025-12-22 19:40:17,952] Trial 12 finished with values: [0.0, 0.9214493100889963] and parameters: {'n_neighbors': 19, 'n_components': 4, 'min_dist': 0.07, 'min_cluster_size': 44, 'min_samples': 17, 'cluster_selection_epsilon': 0.18}.

  0%|          | 0/176 [00:00<?, ?it/s]
 23%|██▎       | 41/176 [00:00<00:00, 405.82it/s]
 47%|████▋     | 82/176 [00:00<00:00, 407.72it/s]
 70%|██████▉   | 123/176 [00:00<00:00, 397.69it/s]
100%|██████████| 176/176 [00:00<00:00, 388.71it/s]

Trial 13: DBCV=0.461, CCC=0.406
[I 2025-12-22 19:40:29,576] Trial 13 finished with values: [0.4062332203327433, 0.4612868148385734] and parameters: {'n_neighbors': 12, 'n_components': 8, 'min_dist': 0.2, 'min_cluster_size': 4, 'min_samples': 1, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 16/16 [00:00<00:00, 348.43it/s]

Trial 14: DBCV=0.450, CCC=0.552
[I 2025-12-22 19:40:39,177] Trial 14 finished with values: [0.5518630494758067, 0.44957832963367783] and parameters: {'n_neighbors': 11, 'n_components': 6, 'min_dist': 0.02, 'min_cluster_size': 35, 'min_samples': 13, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 1/1 [00:00<00:00, 304.51it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 15: DBCV=0.617, CCC=0.000
[I 2025-12-22 19:40:48,768] Trial 15 finished with values: [0.0, 0.6172745714739403] and parameters: {'n_neighbors': 15, 'n_components': 2, 'min_dist': 0.23, 'min_cluster_size': 45, 'min_samples': 13, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 24/24 [00:00<00:00, 379.93it/s]

Trial 16: DBCV=0.477, CCC=0.597
[I 2025-12-22 19:40:59,094] Trial 16 finished with values: [0.5967375673761549, 0.47672476222099114] and parameters: {'n_neighbors': 20, 'n_components': 8, 'min_dist': 0.08, 'min_cluster_size': 23, 'min_samples': 6, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 1/1 [00:00<00:00, 306.67it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 17: DBCV=0.920, CCC=0.000
[I 2025-12-22 19:41:10,318] Trial 17 finished with values: [0.0, 0.9200128311169226] and parameters: {'n_neighbors': 20, 'n_components': 14, 'min_dist': 0.24, 'min_cluster_size': 30, 'min_samples': 1, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 29/29 [00:00<00:00, 403.51it/s]

Trial 18: DBCV=0.558, CCC=0.560
[I 2025-12-22 19:41:22,321] Trial 18 finished with values: [0.5603245957612385, 0.5579983661128216] and parameters: {'n_neighbors': 39, 'n_components': 14, 'min_dist': 0.02, 'min_cluster_size': 15, 'min_samples': 10, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 1/1 [00:00<00:00, 272.73it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 19: DBCV=0.926, CCC=0.000
[I 2025-12-22 19:41:33,291] Trial 19 finished with values: [0.0, 0.9263569421495155] and parameters: {'n_neighbors': 48, 'n_components': 4, 'min_dist': 0.04, 'min_cluster_size': 19, 'min_samples': 12, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 276.40it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 20: DBCV=0.954, CCC=0.000
[I 2025-12-22 19:41:44,708] Trial 20 finished with values: [0.0, 0.9540132557823671] and parameters: {'n_neighbors': 38, 'n_components': 10, 'min_dist': 0.03, 'min_cluster_size': 6, 'min_samples': 12, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 273.64it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 21: DBCV=0.873, CCC=0.000
[I 2025-12-22 19:41:54,802] Trial 21 finished with values: [0.0, 0.8726739865699998] and parameters: {'n_neighbors': 7, 'n_components': 15, 'min_dist': 0.3, 'min_cluster_size': 24, 'min_samples': 5, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 1/1 [00:00<00:00, 273.74it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 22: DBCV=0.915, CCC=0.000
[I 2025-12-22 19:42:04,999] Trial 22 finished with values: [0.0, 0.9149145065446769] and parameters: {'n_neighbors': 13, 'n_components': 10, 'min_dist': 0.14, 'min_cluster_size': 35, 'min_samples': 16, 'cluster_selection_epsilon': 0.12}.

  0%|          | 0/59 [00:00<?, ?it/s]
100%|██████████| 59/59 [00:00<00:00, 379.54it/s]

Trial 23: DBCV=0.262, CCC=0.601
[I 2025-12-22 19:42:15,713] Trial 23 finished with values: [0.6005565166797271, 0.26228002204945433] and parameters: {'n_neighbors': 2, 'n_components': 7, 'min_dist': 0.23, 'min_cluster_size': 7, 'min_samples': 10, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 281.82it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 24: DBCV=0.929, CCC=0.000
[I 2025-12-22 19:42:27,171] Trial 24 finished with values: [0.0, 0.9290003211698098] and parameters: {'n_neighbors': 23, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 44, 'min_samples': 6, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 274.46it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 25: DBCV=0.932, CCC=0.000
[I 2025-12-22 19:42:39,012] Trial 25 finished with values: [0.0, 0.9316759739631] and parameters: {'n_neighbors': 25, 'n_components': 15, 'min_dist': 0.03, 'min_cluster_size': 27, 'min_samples': 18, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 328.14it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 26: DBCV=0.928, CCC=0.000
[I 2025-12-22 19:42:51,753] Trial 26 finished with values: [0.0, 0.9276102200953105] and parameters: {'n_neighbors': 46, 'n_components': 15, 'min_dist': 0.29, 'min_cluster_size': 50, 'min_samples': 3, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 1/1 [00:00<00:00, 300.39it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 27: DBCV=0.942, CCC=0.000
[I 2025-12-22 19:43:04,347] Trial 27 finished with values: [0.0, 0.9418248429617044] and parameters: {'n_neighbors': 41, 'n_components': 15, 'min_dist': 0.21, 'min_cluster_size': 37, 'min_samples': 14, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 14/14 [00:00<00:00, 385.72it/s]

Trial 28: DBCV=0.369, CCC=0.712
[I 2025-12-22 19:43:15,657] Trial 28 finished with values: [0.7118200729689322, 0.36890800980345645] and parameters: {'n_neighbors': 34, 'n_components': 11, 'min_dist': 0.0, 'min_cluster_size': 41, 'min_samples': 2, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 277.03it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 29: DBCV=0.098, CCC=0.000
[I 2025-12-22 19:43:26,552] Trial 29 finished with values: [0.0, 0.09788997758462187] and parameters: {'n_neighbors': 2, 'n_components': 12, 'min_dist': 0.02, 'min_cluster_size': 47, 'min_samples': 19, 'cluster_selection_epsilon': 0.14}.

  0%|          | 0/109 [00:00<?, ?it/s]
 38%|███▊      | 41/109 [00:00<00:00, 404.83it/s]
100%|██████████| 109/109 [00:00<00:00, 393.90it/s][A

Trial 30: DBCV=0.523, CCC=0.445
[I 2025-12-22 19:43:36,267] Trial 30 finished with values: [0.4447874069755406, 0.5228231201736075] and parameters: {'n_neighbors': 4, 'n_components': 10, 'min_dist': 0.09, 'min_cluster_size': 8, 'min_samples': 2, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 275.94it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 31: DBCV=0.888, CCC=0.000
[I 2025-12-22 19:43:46,216] Trial 31 finished with values: [0.0, 0.8876628085492843] and parameters: {'n_neighbors': 11, 'n_components': 7, 'min_dist': 0.23, 'min_cluster_size': 40, 'min_samples': 11, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 1/1 [00:00<00:00, 308.25it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 32: DBCV=0.937, CCC=0.000
[I 2025-12-22 19:43:57,797] Trial 32 finished with values: [0.0, 0.937158471597484] and parameters: {'n_neighbors': 45, 'n_components': 9, 'min_dist': 0.22, 'min_cluster_size': 42, 'min_samples': 17, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 1/1 [00:00<00:00, 275.81it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 33: DBCV=0.918, CCC=0.000
[I 2025-12-22 19:44:09,625] Trial 33 finished with values: [0.0, 0.9184645144322869] and parameters: {'n_neighbors': 24, 'n_components': 15, 'min_dist': 0.21, 'min_cluster_size': 47, 'min_samples': 6, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 274.25it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 34: DBCV=0.931, CCC=0.000
[I 2025-12-22 19:44:21,197] Trial 34 finished with values: [0.0, 0.9312846563079682] and parameters: {'n_neighbors': 49, 'n_components': 8, 'min_dist': 0.15, 'min_cluster_size': 45, 'min_samples': 14, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 1/1 [00:00<00:00, 309.31it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 35: DBCV=0.890, CCC=0.000
[I 2025-12-22 19:44:32,702] Trial 35 finished with values: [0.0, 0.8897718324856352] and parameters: {'n_neighbors': 42, 'n_components': 7, 'min_dist': 0.25, 'min_cluster_size': 12, 'min_samples': 9, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 1/1 [00:00<00:00, 300.11it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 36: DBCV=0.889, CCC=0.000
[I 2025-12-22 19:44:43,117] Trial 36 finished with values: [0.0, 0.8890330689442698] and parameters: {'n_neighbors': 14, 'n_components': 9, 'min_dist': 0.26, 'min_cluster_size': 7, 'min_samples': 13, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 241.45it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 37: DBCV=0.771, CCC=0.000
[I 2025-12-22 19:44:53,634] Trial 37 finished with values: [0.0, 0.770733983969518] and parameters: {'n_neighbors': 38, 'n_components': 2, 'min_dist': 0.24, 'min_cluster_size': 25, 'min_samples': 19, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 28/28 [00:00<00:00, 382.65it/s]

Trial 38: DBCV=0.417, CCC=0.569
[I 2025-12-22 19:45:01,981] Trial 38 finished with values: [0.5694097828819327, 0.41747725775749095] and parameters: {'n_neighbors': 3, 'n_components': 3, 'min_dist': 0.03, 'min_cluster_size': 29, 'min_samples': 3, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 237.93it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 39: DBCV=0.943, CCC=0.000
[I 2025-12-22 19:45:14,858] Trial 39 finished with values: [0.0, 0.943049936266981] and parameters: {'n_neighbors': 50, 'n_components': 15, 'min_dist': 0.2, 'min_cluster_size': 38, 'min_samples': 7, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 13/13 [00:00<00:00, 381.04it/s]

Trial 40: DBCV=0.454, CCC=0.720
[I 2025-12-22 19:45:24,640] Trial 40 finished with values: [0.720409578964507, 0.4539538642456041] and parameters: {'n_neighbors': 11, 'n_components': 9, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 9, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 297.60it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 41: DBCV=0.923, CCC=0.000
[I 2025-12-22 19:45:36,161] Trial 41 finished with values: [0.0, 0.9230763404513168] and parameters: {'n_neighbors': 31, 'n_components': 12, 'min_dist': 0.3, 'min_cluster_size': 13, 'min_samples': 11, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 1/1 [00:00<00:00, 299.57it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 42: DBCV=0.144, CCC=0.000
[I 2025-12-22 19:45:45,706] Trial 42 finished with values: [0.0, 0.1439059924008982] and parameters: {'n_neighbors': 5, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 29, 'min_samples': 9, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 269.82it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 43: DBCV=0.916, CCC=0.000
[I 2025-12-22 19:45:56,201] Trial 43 finished with values: [0.0, 0.9158857507979137] and parameters: {'n_neighbors': 18, 'n_components': 9, 'min_dist': 0.12, 'min_cluster_size': 45, 'min_samples': 4, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 300.60it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 44: DBCV=0.934, CCC=0.000
[I 2025-12-22 19:46:07,972] Trial 44 finished with values: [0.0, 0.9344926568511195] and parameters: {'n_neighbors': 50, 'n_components': 9, 'min_dist': 0.21, 'min_cluster_size': 34, 'min_samples': 4, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 302.44it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 45: DBCV=0.956, CCC=0.000
[I 2025-12-22 19:46:20,164] Trial 45 finished with values: [0.0, 0.9564235348936171] and parameters: {'n_neighbors': 44, 'n_components': 13, 'min_dist': 0.1, 'min_cluster_size': 46, 'min_samples': 9, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 275.29it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 46: DBCV=0.082, CCC=0.000
[I 2025-12-22 19:46:29,219] Trial 46 finished with values: [0.0, 0.08163880675181115] and parameters: {'n_neighbors': 5, 'n_components': 8, 'min_dist': 0.17, 'min_cluster_size': 25, 'min_samples': 18, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 1/1 [00:00<00:00, 275.61it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 47: DBCV=0.951, CCC=0.000
[I 2025-12-22 19:46:40,643] Trial 47 finished with values: [0.0, 0.9514127244684338] and parameters: {'n_neighbors': 42, 'n_components': 7, 'min_dist': 0.04, 'min_cluster_size': 44, 'min_samples': 7, 'cluster_selection_epsilon': 0.3}.

  0%|          | 0/39 [00:00<?, ?it/s]
100%|██████████| 39/39 [00:00<00:00, 379.97it/s]

Trial 48: DBCV=0.505, CCC=0.571
[I 2025-12-22 19:46:50,847] Trial 48 finished with values: [0.5711463561937529, 0.505486379209699] and parameters: {'n_neighbors': 29, 'n_components': 2, 'min_dist': 0.12, 'min_cluster_size': 15, 'min_samples': 6, 'cluster_selection_epsilon': 0.01}.

  0%|          | 0/45 [00:00<?, ?it/s]
100%|██████████| 45/45 [00:00<00:00, 391.37it/s]

Trial 49: DBCV=0.589, CCC=0.494
[I 2025-12-22 19:47:01,808] Trial 49 finished with values: [0.49400920705216333, 0.5893082118936978] and parameters: {'n_neighbors': 28, 'n_components': 7, 'min_dist': 0.05, 'min_cluster_size': 8, 'min_samples': 7, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 12/12 [00:00<00:00, 385.67it/s]

Trial 50: DBCV=0.468, CCC=0.738
[I 2025-12-22 19:47:12,255] Trial 50 finished with values: [0.7380691583634187, 0.46770836070392247] and parameters: {'n_neighbors': 11, 'n_components': 15, 'min_dist': 0.02, 'min_cluster_size': 37, 'min_samples': 13, 'cluster_selection_epsilon': 0.15}.

  0%|          | 0/52 [00:00<?, ?it/s]
100%|██████████| 52/52 [00:00<00:00, 375.65it/s]

Trial 51: DBCV=0.347, CCC=0.483
[I 2025-12-22 19:47:22,183] Trial 51 finished with values: [0.4828315465824895, 0.34687756097793665] and parameters: {'n_neighbors': 11, 'n_components': 6, 'min_dist': 0.2, 'min_cluster_size': 13, 'min_samples': 1, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 1/1 [00:00<00:00, 192.60it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 52: DBCV=0.920, CCC=0.000
[I 2025-12-22 19:47:33,937] Trial 52 finished with values: [0.0, 0.919888042637802] and parameters: {'n_neighbors': 49, 'n_components': 10, 'min_dist': 0.27, 'min_cluster_size': 6, 'min_samples': 18, 'cluster_selection_epsilon': 0.19}.

  0%|          | 0/464 [00:00<?, ?it/s]
  9%|▊         | 40/464 [00:00<00:01, 393.64it/s]
 17%|█▋        | 80/464 [00:00<00:00, 385.65it/s]
 26%|██▌       | 119/464 [00:00<00:00, 383.62it/s]
 34%|███▍      | 158/464 [00:00<00:00, 381.88it/s]
 42%|████▏     | 197/464 [00:00<00:00, 383.44it/s]
 51%|█████     | 237/464 [00:00<00:00, 388.16it/s]
 59%|█████▉    | 276/464 [00:00<00:00, 386.07it/s]
 68%|██████▊   | 315/464 [00:00<00:00, 382.76it/s]
 76%|███████▋  | 354/464 [00:00<00:00, 377.99it/s]
 84%|████████▍ | 392/464 [00:01<00:00, 374.06it/s]
100%|██████████| 464/464 [00:01<00:00, 376.55it/s]

Trial 53: DBCV=0.531, CCC=0.304
[I 2025-12-22 19:47:53,171] Trial 53 finished with values: [0.30397315022166865, 0.530798959991751] and parameters: {'n_neighbors': 12, 'n_components': 10, 'min_dist': 0.09, 'min_cluster_size': 2, 'min_samples': 1, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 279.47it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 54: DBCV=0.881, CCC=0.000
[I 2025-12-22 19:48:02,994] Trial 54 finished with values: [0.0, 0.8810700336147885] and parameters: {'n_neighbors': 11, 'n_components': 6, 'min_dist': 0.13, 'min_cluster_size': 45, 'min_samples': 2, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 1/1 [00:00<00:00, 279.69it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 55: DBCV=0.939, CCC=0.000
[I 2025-12-22 19:48:15,562] Trial 55 finished with values: [0.0, 0.9394783390233334] and parameters: {'n_neighbors': 41, 'n_components': 15, 'min_dist': 0.24, 'min_cluster_size': 39, 'min_samples': 3, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 1/1 [00:00<00:00, 309.31it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 56: DBCV=0.880, CCC=0.000
[I 2025-12-22 19:48:26,137] Trial 56 finished with values: [0.0, 0.8798876237769941] and parameters: {'n_neighbors': 19, 'n_components': 9, 'min_dist': 0.07, 'min_cluster_size': 44, 'min_samples': 17, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 215.56it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 57: DBCV=0.952, CCC=0.000
[I 2025-12-22 19:48:38,775] Trial 57 finished with values: [0.0, 0.9518553120215876] and parameters: {'n_neighbors': 41, 'n_components': 15, 'min_dist': 0.13, 'min_cluster_size': 45, 'min_samples': 14, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 18/18 [00:00<00:00, 362.34it/s]

Trial 58: DBCV=0.447, CCC=0.607
[I 2025-12-22 19:48:49,047] Trial 58 finished with values: [0.6069065499650095, 0.44679103946715715] and parameters: {'n_neighbors': 25, 'n_components': 5, 'min_dist': 0.03, 'min_cluster_size': 27, 'min_samples': 6, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 1/1 [00:00<00:00, 282.52it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 59: DBCV=0.115, CCC=0.000
[I 2025-12-22 19:48:59,439] Trial 59 finished with values: [0.0, 0.11506240569344678] and parameters: {'n_neighbors': 2, 'n_components': 9, 'min_dist': 0.11, 'min_cluster_size': 39, 'min_samples': 11, 'cluster_selection_epsilon': 0.06}.

  0%|          | 0/50 [00:00<?, ?it/s]
100%|██████████| 50/50 [00:00<00:00, 392.94it/s]

Trial 60: DBCV=0.475, CCC=0.512
[I 2025-12-22 19:49:10,490] Trial 60 finished with values: [0.5115386471338103, 0.47511794845726407] and parameters: {'n_neighbors': 29, 'n_components': 7, 'min_dist': 0.12, 'min_cluster_size': 8, 'min_samples': 6, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 308.43it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 61: DBCV=0.883, CCC=0.000
[I 2025-12-22 19:49:21,486] Trial 61 finished with values: [0.0, 0.8829741470416222] and parameters: {'n_neighbors': 28, 'n_components': 7, 'min_dist': 0.3, 'min_cluster_size': 15, 'min_samples': 7, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 309.98it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 62: DBCV=0.947, CCC=0.000
[I 2025-12-22 19:49:34,370] Trial 62 finished with values: [0.0, 0.9471518690978744] and parameters: {'n_neighbors': 50, 'n_components': 15, 'min_dist': 0.14, 'min_cluster_size': 38, 'min_samples': 3, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 246.23it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 63: DBCV=0.906, CCC=0.000
[I 2025-12-22 19:49:45,935] Trial 63 finished with values: [0.0, 0.9064232925409602] and parameters: {'n_neighbors': 25, 'n_components': 14, 'min_dist': 0.29, 'min_cluster_size': 50, 'min_samples': 18, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 1/1 [00:00<00:00, 306.78it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 64: DBCV=0.866, CCC=0.000
[I 2025-12-22 19:49:56,422] Trial 64 finished with values: [0.0, 0.8657794485696572] and parameters: {'n_neighbors': 18, 'n_components': 7, 'min_dist': 0.19, 'min_cluster_size': 41, 'min_samples': 3, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 271.18it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 65: DBCV=0.021, CCC=0.000
[I 2025-12-22 19:50:05,043] Trial 65 finished with values: [0.0, 0.020984436956885375] and parameters: {'n_neighbors': 4, 'n_components': 2, 'min_dist': 0.3, 'min_cluster_size': 42, 'min_samples': 7, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 274.71it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 66: DBCV=0.860, CCC=0.000
[I 2025-12-22 19:50:15,128] Trial 66 finished with values: [0.0, 0.8598464457248463] and parameters: {'n_neighbors': 13, 'n_components': 7, 'min_dist': 0.23, 'min_cluster_size': 7, 'min_samples': 16, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 1/1 [00:00<00:00, 274.08it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 67: DBCV=0.866, CCC=0.000
[I 2025-12-22 19:50:24,907] Trial 67 finished with values: [0.0, 0.865728547591548] and parameters: {'n_neighbors': 11, 'n_components': 6, 'min_dist': 0.22, 'min_cluster_size': 35, 'min_samples': 13, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 1/1 [00:00<00:00, 295.58it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 68: DBCV=0.919, CCC=0.000
[I 2025-12-22 19:50:36,403] Trial 68 finished with values: [0.0, 0.9194886657373401] and parameters: {'n_neighbors': 34, 'n_components': 11, 'min_dist': 0.21, 'min_cluster_size': 41, 'min_samples': 2, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 306.53it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 69: DBCV=0.944, CCC=0.000
[I 2025-12-22 19:50:48,392] Trial 69 finished with values: [0.0, 0.9436317481244901] and parameters: {'n_neighbors': 45, 'n_components': 12, 'min_dist': 0.13, 'min_cluster_size': 14, 'min_samples': 12, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 1/1 [00:00<00:00, 307.95it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 70: DBCV=0.011, CCC=0.000
[I 2025-12-22 19:50:58,810] Trial 70 finished with values: [0.0, 0.010681020737657223] and parameters: {'n_neighbors': 2, 'n_components': 7, 'min_dist': 0.03, 'min_cluster_size': 27, 'min_samples': 10, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 308.18it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 71: DBCV=0.617, CCC=0.000
[I 2025-12-22 19:51:08,448] Trial 71 finished with values: [0.0, 0.6172745714739403] and parameters: {'n_neighbors': 15, 'n_components': 2, 'min_dist': 0.23, 'min_cluster_size': 50, 'min_samples': 13, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 308.40it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 72: DBCV=0.931, CCC=0.000
[I 2025-12-22 19:51:20,971] Trial 72 finished with values: [0.0, 0.9309007548251071] and parameters: {'n_neighbors': 39, 'n_components': 15, 'min_dist': 0.29, 'min_cluster_size': 27, 'min_samples': 18, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 1/1 [00:00<00:00, 307.05it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 73: DBCV=0.954, CCC=0.000
[I 2025-12-22 19:51:33,015] Trial 73 finished with values: [0.0, 0.9541478530523735] and parameters: {'n_neighbors': 41, 'n_components': 13, 'min_dist': 0.11, 'min_cluster_size': 46, 'min_samples': 9, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 222.88it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 74: DBCV=0.936, CCC=0.000
[I 2025-12-22 19:51:44,440] Trial 74 finished with values: [0.0, 0.9363630033062381] and parameters: {'n_neighbors': 31, 'n_components': 11, 'min_dist': 0.08, 'min_cluster_size': 40, 'min_samples': 9, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 19/19 [00:00<00:00, 364.01it/s]

Trial 75: DBCV=0.351, CCC=0.544
[I 2025-12-22 19:51:54,505] Trial 75 finished with values: [0.5438836365808732, 0.35058649844059264] and parameters: {'n_neighbors': 15, 'n_components': 8, 'min_dist': 0.0, 'min_cluster_size': 41, 'min_samples': 2, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 1/1 [00:00<00:00, 278.38it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 76: DBCV=0.922, CCC=0.000
[I 2025-12-22 19:52:06,156] Trial 76 finished with values: [0.0, 0.9219152867691185] and parameters: {'n_neighbors': 45, 'n_components': 10, 'min_dist': 0.22, 'min_cluster_size': 42, 'min_samples': 17, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 270.22it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 77: DBCV=0.938, CCC=0.000
[I 2025-12-22 19:52:17,834] Trial 77 finished with values: [0.0, 0.9383737078419182] and parameters: {'n_neighbors': 24, 'n_components': 14, 'min_dist': 0.02, 'min_cluster_size': 44, 'min_samples': 6, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 1/1 [00:00<00:00, 307.32it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 78: DBCV=0.934, CCC=0.000
[I 2025-12-22 19:52:29,595] Trial 78 finished with values: [0.0, 0.9344739035787165] and parameters: {'n_neighbors': 22, 'n_components': 15, 'min_dist': 0.2, 'min_cluster_size': 38, 'min_samples': 3, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 10/10 [00:00<00:00, 368.97it/s]

Trial 79: DBCV=0.471, CCC=0.778
[I 2025-12-22 19:52:39,676] Trial 79 finished with values: [0.7779458300109655, 0.4712823716967355] and parameters: {'n_neighbors': 11, 'n_components': 13, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 14, 'cluster_selection_epsilon': 0.27}.

  0%|          | 0/104 [00:00<?, ?it/s]
 38%|███▊      | 40/104 [00:00<00:00, 397.00it/s]
100%|██████████| 104/104 [00:00<00:00, 381.93it/s][A

Trial 80: DBCV=0.565, CCC=0.434
[I 2025-12-22 19:52:50,911] Trial 80 finished with values: [0.4342330815748235, 0.5649475767556706] and parameters: {'n_neighbors': 18, 'n_components': 10, 'min_dist': 0.03, 'min_cluster_size': 6, 'min_samples': 3, 'cluster_selection_epsilon': 0.04}.

  0%|          | 0/88 [00:00<?, ?it/s]
 47%|████▋     | 41/88 [00:00<00:00, 405.62it/s]
100%|██████████| 88/88 [00:00<00:00, 396.87it/s]

Trial 81: DBCV=0.412, CCC=0.393
[I 2025-12-22 19:53:02,366] Trial 81 finished with values: [0.3933928330143787, 0.41209024130512123] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.2, 'min_cluster_size': 5, 'min_samples': 2, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 293.06it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 82: DBCV=0.877, CCC=0.000
[I 2025-12-22 19:53:12,429] Trial 82 finished with values: [0.0, 0.8766999463962335] and parameters: {'n_neighbors': 21, 'n_components': 3, 'min_dist': 0.09, 'min_cluster_size': 8, 'min_samples': 14, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 1/1 [00:00<00:00, 275.47it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 83: DBCV=0.931, CCC=0.000
[I 2025-12-22 19:53:23,941] Trial 83 finished with values: [0.0, 0.9312846563079682] and parameters: {'n_neighbors': 49, 'n_components': 8, 'min_dist': 0.15, 'min_cluster_size': 30, 'min_samples': 1, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 1/1 [00:00<00:00, 300.62it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 84: DBCV=0.786, CCC=0.000
[I 2025-12-22 19:53:33,574] Trial 84 finished with values: [0.0, 0.7856976534064822] and parameters: {'n_neighbors': 15, 'n_components': 2, 'min_dist': 0.1, 'min_cluster_size': 3, 'min_samples': 14, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 36/36 [00:00<00:00, 388.07it/s]

Trial 85: DBCV=0.449, CCC=0.510
[I 2025-12-22 19:53:43,994] Trial 85 finished with values: [0.5100327706789677, 0.4486750725326001] and parameters: {'n_neighbors': 10, 'n_components': 14, 'min_dist': 0.13, 'min_cluster_size': 18, 'min_samples': 3, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 1/1 [00:00<00:00, 271.99it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 86: DBCV=0.890, CCC=0.000
[I 2025-12-22 19:53:54,546] Trial 86 finished with values: [0.0, 0.8903254161343792] and parameters: {'n_neighbors': 10, 'n_components': 15, 'min_dist': 0.29, 'min_cluster_size': 47, 'min_samples': 3, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 1/1 [00:00<00:00, 276.85it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 87: DBCV=0.841, CCC=0.000
[I 2025-12-22 19:54:04,561] Trial 87 finished with values: [0.0, 0.8410257416051373] and parameters: {'n_neighbors': 16, 'n_components': 5, 'min_dist': 0.22, 'min_cluster_size': 8, 'min_samples': 17, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 1/1 [00:00<00:00, 277.84it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 88: DBCV=0.914, CCC=0.000
[I 2025-12-22 19:54:15,603] Trial 88 finished with values: [0.0, 0.9139072582251275] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.2, 'min_cluster_size': 5, 'min_samples': 9, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 1/1 [00:00<00:00, 274.53it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 89: DBCV=0.911, CCC=0.000
[I 2025-12-22 19:54:27,170] Trial 89 finished with values: [0.0, 0.9108273196353927] and parameters: {'n_neighbors': 20, 'n_components': 15, 'min_dist': 0.3, 'min_cluster_size': 24, 'min_samples': 7, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 1/1 [00:00<00:00, 278.80it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 90: DBCV=0.911, CCC=0.000
[I 2025-12-22 19:54:37,341] Trial 90 finished with values: [0.0, 0.9109429340928468] and parameters: {'n_neighbors': 13, 'n_components': 10, 'min_dist': 0.28, 'min_cluster_size': 35, 'min_samples': 17, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 1/1 [00:00<00:00, 303.94it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 91: DBCV=0.947, CCC=0.000
[I 2025-12-22 19:54:49,500] Trial 91 finished with values: [0.0, 0.9474303745706942] and parameters: {'n_neighbors': 45, 'n_components': 13, 'min_dist': 0.1, 'min_cluster_size': 14, 'min_samples': 9, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 311.87it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 92: DBCV=0.919, CCC=0.000
[I 2025-12-22 19:55:00,975] Trial 92 finished with values: [0.0, 0.9193291527900823] and parameters: {'n_neighbors': 38, 'n_components': 10, 'min_dist': 0.23, 'min_cluster_size': 7, 'min_samples': 12, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 307.64it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 93: DBCV=0.937, CCC=0.000
[I 2025-12-22 19:55:12,829] Trial 93 finished with values: [0.0, 0.9368628465330058] and parameters: {'n_neighbors': 50, 'n_components': 10, 'min_dist': 0.2, 'min_cluster_size': 38, 'min_samples': 7, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 300.49it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 94: DBCV=0.930, CCC=0.000
[I 2025-12-22 19:55:24,633] Trial 94 finished with values: [0.0, 0.9300128934994405] and parameters: {'n_neighbors': 25, 'n_components': 15, 'min_dist': 0.08, 'min_cluster_size': 27, 'min_samples': 8, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 272.84it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 95: DBCV=0.917, CCC=0.000
[I 2025-12-22 19:55:35,695] Trial 95 finished with values: [0.0, 0.9171536780880003] and parameters: {'n_neighbors': 50, 'n_components': 4, 'min_dist': 0.04, 'min_cluster_size': 45, 'min_samples': 12, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 1/1 [00:00<00:00, 276.67it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 96: DBCV=0.951, CCC=0.000
[I 2025-12-22 19:55:47,971] Trial 96 finished with values: [0.0, 0.9505574432717591] and parameters: {'n_neighbors': 34, 'n_components': 15, 'min_dist': 0.0, 'min_cluster_size': 41, 'min_samples': 13, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 25/25 [00:00<00:00, 392.47it/s]

Trial 97: DBCV=0.430, CCC=0.617
[I 2025-12-22 19:55:58,665] Trial 97 finished with values: [0.6169556765287157, 0.4298831383048053] and parameters: {'n_neighbors': 25, 'n_components': 9, 'min_dist': 0.03, 'min_cluster_size': 27, 'min_samples': 4, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 274.35it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 98: DBCV=0.928, CCC=0.000
[I 2025-12-22 19:56:09,678] Trial 98 finished with values: [0.0, 0.9275490726913176] and parameters: {'n_neighbors': 19, 'n_components': 13, 'min_dist': 0.11, 'min_cluster_size': 44, 'min_samples': 17, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 1/1 [00:00<00:00, 308.27it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 99: DBCV=0.960, CCC=0.000
[I 2025-12-22 19:56:21,130] Trial 99 finished with values: [0.0, 0.9596949607130412] and parameters: {'n_neighbors': 42, 'n_components': 9, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 12, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 192.07it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 100: DBCV=0.957, CCC=0.000
[I 2025-12-22 19:56:33,482] Trial 100 finished with values: [0.0, 0.9568795510053003] and parameters: {'n_neighbors': 44, 'n_components': 14, 'min_dist': 0.02, 'min_cluster_size': 38, 'min_samples': 10, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 25/25 [00:00<00:00, 399.36it/s]

Trial 101: DBCV=0.407, CCC=0.607
[I 2025-12-22 19:56:43,181] Trial 101 finished with values: [0.6066033318526146, 0.4068062338206209] and parameters: {'n_neighbors': 8, 'n_components': 12, 'min_dist': 0.12, 'min_cluster_size': 24, 'min_samples': 6, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 279.55it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 102: DBCV=0.849, CCC=0.000
[I 2025-12-22 19:56:53,787] Trial 102 finished with values: [0.0, 0.8491240987044023] and parameters: {'n_neighbors': 43, 'n_components': 2, 'min_dist': 0.1, 'min_cluster_size': 44, 'min_samples': 7, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 33/33 [00:00<00:00, 388.67it/s]

Trial 103: DBCV=0.606, CCC=0.449
[I 2025-12-22 19:57:02,253] Trial 103 finished with values: [0.4493329924546756, 0.6057209871030077] and parameters: {'n_neighbors': 4, 'n_components': 2, 'min_dist': 0.08, 'min_cluster_size': 7, 'min_samples': 18, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 306.00it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 104: DBCV=0.908, CCC=0.000
[I 2025-12-22 19:57:13,262] Trial 104 finished with values: [0.0, 0.908205624808672] and parameters: {'n_neighbors': 29, 'n_components': 7, 'min_dist': 0.12, 'min_cluster_size': 15, 'min_samples': 6, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 16/16 [00:00<00:00, 380.19it/s]

Trial 105: DBCV=0.343, CCC=0.559
[I 2025-12-22 19:57:23,525] Trial 105 finished with values: [0.5585739478192844, 0.3425838244301324] and parameters: {'n_neighbors': 25, 'n_components': 5, 'min_dist': 0.03, 'min_cluster_size': 33, 'min_samples': 4, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 1/1 [00:00<00:00, 307.88it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 106: DBCV=0.961, CCC=0.000
[I 2025-12-22 19:57:36,082] Trial 106 finished with values: [0.0, 0.9607601227823008] and parameters: {'n_neighbors': 39, 'n_components': 15, 'min_dist': 0.02, 'min_cluster_size': 39, 'min_samples': 10, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 1/1 [00:00<00:00, 301.40it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 107: DBCV=0.937, CCC=0.000
[I 2025-12-22 19:57:47,921] Trial 107 finished with values: [0.0, 0.9368628465330058] and parameters: {'n_neighbors': 50, 'n_components': 10, 'min_dist': 0.2, 'min_cluster_size': 46, 'min_samples': 9, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 10/10 [00:00<00:00, 332.48it/s]

Trial 108: DBCV=0.155, CCC=0.787
[I 2025-12-22 19:57:59,811] Trial 108 finished with values: [0.7868195496117706, 0.1546586744141496] and parameters: {'n_neighbors': 50, 'n_components': 11, 'min_dist': 0.0, 'min_cluster_size': 41, 'min_samples': 2, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 17/17 [00:00<00:00, 394.60it/s]

Trial 109: DBCV=0.535, CCC=0.654
[I 2025-12-22 19:58:10,404] Trial 109 finished with values: [0.6544728289619575, 0.5353431301385002] and parameters: {'n_neighbors': 25, 'n_components': 7, 'min_dist': 0.04, 'min_cluster_size': 27, 'min_samples': 18, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 13/13 [00:00<00:00, 384.93it/s]

Trial 110: DBCV=0.189, CCC=0.699
[I 2025-12-22 19:58:21,156] Trial 110 finished with values: [0.6993512819596597, 0.1885449549465247] and parameters: {'n_neighbors': 39, 'n_components': 5, 'min_dist': 0.02, 'min_cluster_size': 39, 'min_samples': 3, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 1/1 [00:00<00:00, 171.14it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 111: DBCV=0.952, CCC=0.000
[I 2025-12-22 19:58:33,758] Trial 111 finished with values: [0.0, 0.9518553120215876] and parameters: {'n_neighbors': 41, 'n_components': 15, 'min_dist': 0.13, 'min_cluster_size': 45, 'min_samples': 3, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 302.90it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 112: DBCV=0.924, CCC=0.000
[I 2025-12-22 19:58:44,209] Trial 112 finished with values: [0.0, 0.9243180762872736] and parameters: {'n_neighbors': 20, 'n_components': 8, 'min_dist': 0.11, 'min_cluster_size': 23, 'min_samples': 9, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 18/18 [00:00<00:00, 364.80it/s]

Trial 113: DBCV=0.427, CCC=0.453
[I 2025-12-22 19:58:55,370] Trial 113 finished with values: [0.45312579627257893, 0.4271524810225655] and parameters: {'n_neighbors': 18, 'n_components': 15, 'min_dist': 0.02, 'min_cluster_size': 37, 'min_samples': 3, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 331.57it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 114: DBCV=0.952, CCC=0.000
[I 2025-12-22 19:59:07,321] Trial 114 finished with values: [0.0, 0.9518334248573788] and parameters: {'n_neighbors': 44, 'n_components': 12, 'min_dist': 0.1, 'min_cluster_size': 36, 'min_samples': 9, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 301.79it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 115: DBCV=0.924, CCC=0.000
[I 2025-12-22 19:59:17,736] Trial 115 finished with values: [0.0, 0.9243180762872736] and parameters: {'n_neighbors': 20, 'n_components': 8, 'min_dist': 0.11, 'min_cluster_size': 23, 'min_samples': 9, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 1/1 [00:00<00:00, 272.43it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 116: DBCV=0.914, CCC=0.000
[I 2025-12-22 19:59:28,834] Trial 116 finished with values: [0.0, 0.9139072582251275] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.2, 'min_cluster_size': 5, 'min_samples': 20, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 1/1 [00:00<00:00, 309.15it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 117: DBCV=0.952, CCC=0.000
[I 2025-12-22 19:59:41,000] Trial 117 finished with values: [0.0, 0.9516382994613205] and parameters: {'n_neighbors': 46, 'n_components': 13, 'min_dist': 0.1, 'min_cluster_size': 46, 'min_samples': 7, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 34/34 [00:00<00:00, 403.28it/s]

Trial 118: DBCV=0.532, CCC=0.583
[I 2025-12-22 19:59:52,080] Trial 118 finished with values: [0.5827077155352901, 0.5317841945689682] and parameters: {'n_neighbors': 23, 'n_components': 12, 'min_dist': 0.05, 'min_cluster_size': 14, 'min_samples': 7, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 290.93it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 119: DBCV=0.862, CCC=0.000
[I 2025-12-22 20:00:02,454] Trial 119 finished with values: [0.0, 0.8616362982764754] and parameters: {'n_neighbors': 11, 'n_components': 13, 'min_dist': 0.1, 'min_cluster_size': 37, 'min_samples': 7, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 155.70it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 120: DBCV=0.934, CCC=0.000
[I 2025-12-22 20:00:14,209] Trial 120 finished with values: [0.0, 0.9344926568511195] and parameters: {'n_neighbors': 50, 'n_components': 9, 'min_dist': 0.21, 'min_cluster_size': 39, 'min_samples': 4, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 278.99it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 121: DBCV=0.941, CCC=0.000
[I 2025-12-22 20:00:25,167] Trial 121 finished with values: [0.0, 0.9409843546352202] and parameters: {'n_neighbors': 22, 'n_components': 11, 'min_dist': 0.08, 'min_cluster_size': 42, 'min_samples': 2, 'cluster_selection_epsilon': 0.16}.

  0%|          | 0/49 [00:00<?, ?it/s]
100%|██████████| 49/49 [00:00<00:00, 368.72it/s]

Trial 122: DBCV=0.253, CCC=0.443
[I 2025-12-22 20:00:36,007] Trial 122 finished with values: [0.4430167022930893, 0.25299559793255566] and parameters: {'n_neighbors': 29, 'n_components': 6, 'min_dist': 0.12, 'min_cluster_size': 8, 'min_samples': 1, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 316.67it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 123: DBCV=0.880, CCC=0.000
[I 2025-12-22 20:00:45,823] Trial 123 finished with values: [0.0, 0.8797514597746144] and parameters: {'n_neighbors': 11, 'n_components': 6, 'min_dist': 0.15, 'min_cluster_size': 35, 'min_samples': 13, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 1/1 [00:00<00:00, 274.05it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 124: DBCV=0.945, CCC=0.000
[I 2025-12-22 20:00:57,917] Trial 124 finished with values: [0.0, 0.9452658501833496] and parameters: {'n_neighbors': 50, 'n_components': 12, 'min_dist': 0.15, 'min_cluster_size': 38, 'min_samples': 7, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 15/15 [00:00<00:00, 384.90it/s]

Trial 125: DBCV=0.417, CCC=0.553
[I 2025-12-22 20:01:10,578] Trial 125 finished with values: [0.5526107983073305, 0.41677879018019504] and parameters: {'n_neighbors': 50, 'n_components': 15, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 3, 'cluster_selection_epsilon': 0.01}.

  0%|          | 0/99 [00:00<?, ?it/s]
 41%|████▏     | 41/99 [00:00<00:00, 407.83it/s]
100%|██████████| 99/99 [00:00<00:00, 385.37it/s]

Trial 126: DBCV=0.529, CCC=0.453
[I 2025-12-22 20:01:21,624] Trial 126 finished with values: [0.4530174742672757, 0.5287692137132812] and parameters: {'n_neighbors': 18, 'n_components': 7, 'min_dist': 0.03, 'min_cluster_size': 6, 'min_samples': 3, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 271.48it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 127: DBCV=0.933, CCC=0.000
[I 2025-12-22 20:01:32,642] Trial 127 finished with values: [0.0, 0.9327511615982212] and parameters: {'n_neighbors': 26, 'n_components': 10, 'min_dist': 0.13, 'min_cluster_size': 6, 'min_samples': 14, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 297.26it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 128: DBCV=0.935, CCC=0.000
[I 2025-12-22 20:01:44,689] Trial 128 finished with values: [0.0, 0.9346504804988058] and parameters: {'n_neighbors': 34, 'n_components': 14, 'min_dist': 0.18, 'min_cluster_size': 7, 'min_samples': 6, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 1/1 [00:00<00:00, 310.51it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 129: DBCV=0.933, CCC=0.000
[I 2025-12-22 20:01:57,093] Trial 129 finished with values: [0.0, 0.9332319946474712] and parameters: {'n_neighbors': 50, 'n_components': 13, 'min_dist': 0.2, 'min_cluster_size': 14, 'min_samples': 7, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 311.47it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 130: DBCV=0.887, CCC=0.000
[I 2025-12-22 20:02:08,345] Trial 130 finished with values: [0.0, 0.8871074351810507] and parameters: {'n_neighbors': 39, 'n_components': 8, 'min_dist': 0.29, 'min_cluster_size': 45, 'min_samples': 18, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 1/1 [00:00<00:00, 274.93it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 131: DBCV=0.946, CCC=0.000
[I 2025-12-22 20:02:20,087] Trial 131 finished with values: [0.0, 0.9456573637895768] and parameters: {'n_neighbors': 31, 'n_components': 13, 'min_dist': 0.08, 'min_cluster_size': 40, 'min_samples': 6, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 1/1 [00:00<00:00, 307.16it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 132: DBCV=0.938, CCC=0.000
[I 2025-12-22 20:02:31,616] Trial 132 finished with values: [0.0, 0.9383737078419182] and parameters: {'n_neighbors': 24, 'n_components': 14, 'min_dist': 0.02, 'min_cluster_size': 44, 'min_samples': 6, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 1/1 [00:00<00:00, 302.68it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 133: DBCV=0.921, CCC=0.000
[I 2025-12-22 20:02:42,897] Trial 133 finished with values: [0.0, 0.9206832144061808] and parameters: {'n_neighbors': 34, 'n_components': 9, 'min_dist': 0.19, 'min_cluster_size': 38, 'min_samples': 2, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 35/35 [00:00<00:00, 387.89it/s]

Trial 134: DBCV=0.329, CCC=0.553
[I 2025-12-22 20:02:52,973] Trial 134 finished with values: [0.5531212082930141, 0.32879839379920217] and parameters: {'n_neighbors': 12, 'n_components': 10, 'min_dist': 0.09, 'min_cluster_size': 20, 'min_samples': 1, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 274.39it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 135: DBCV=0.917, CCC=0.000
[I 2025-12-22 20:03:03,965] Trial 135 finished with values: [0.0, 0.9168811917079506] and parameters: {'n_neighbors': 28, 'n_components': 7, 'min_dist': 0.14, 'min_cluster_size': 27, 'min_samples': 5, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 13/13 [00:00<00:00, 386.36it/s]

Trial 136: DBCV=0.503, CCC=0.585
[I 2025-12-22 20:03:13,178] Trial 136 finished with values: [0.5848334521503741, 0.5032357937412164] and parameters: {'n_neighbors': 4, 'n_components': 15, 'min_dist': 0.01, 'min_cluster_size': 42, 'min_samples': 14, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 1/1 [00:00<00:00, 300.30it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 137: DBCV=0.958, CCC=0.000
[I 2025-12-22 20:03:24,463] Trial 137 finished with values: [0.0, 0.9577789552701905] and parameters: {'n_neighbors': 41, 'n_components': 8, 'min_dist': 0.03, 'min_cluster_size': 6, 'min_samples': 14, 'cluster_selection_epsilon': 0.04}.

  0%|          | 0/92 [00:00<?, ?it/s]
 43%|████▎     | 40/92 [00:00<00:00, 398.38it/s]
100%|██████████| 92/92 [00:00<00:00, 380.38it/s]

Trial 138: DBCV=0.629, CCC=0.505
[I 2025-12-22 20:03:33,521] Trial 138 finished with values: [0.5045972478229982, 0.6287443581619275] and parameters: {'n_neighbors': 4, 'n_components': 2, 'min_dist': 0.08, 'min_cluster_size': 2, 'min_samples': 8, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 277.97it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 139: DBCV=0.932, CCC=0.000
[I 2025-12-22 20:03:45,012] Trial 139 finished with values: [0.0, 0.9317530375677862] and parameters: {'n_neighbors': 49, 'n_components': 8, 'min_dist': 0.08, 'min_cluster_size': 45, 'min_samples': 14, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 1/1 [00:00<00:00, 184.15it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 140: DBCV=0.940, CCC=0.000
[I 2025-12-22 20:03:57,788] Trial 140 finished with values: [0.0, 0.9400148129545808] and parameters: {'n_neighbors': 46, 'n_components': 15, 'min_dist': 0.24, 'min_cluster_size': 8, 'min_samples': 3, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 276.03it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 141: DBCV=0.931, CCC=0.000
[I 2025-12-22 20:04:09,385] Trial 141 finished with values: [0.0, 0.9312846563079682] and parameters: {'n_neighbors': 49, 'n_components': 8, 'min_dist': 0.15, 'min_cluster_size': 30, 'min_samples': 1, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 1/1 [00:00<00:00, 319.71it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 142: DBCV=0.951, CCC=0.000
[I 2025-12-22 20:04:21,712] Trial 142 finished with values: [0.0, 0.9505574432717591] and parameters: {'n_neighbors': 34, 'n_components': 15, 'min_dist': 0.0, 'min_cluster_size': 41, 'min_samples': 13, 'cluster_selection_epsilon': 0.29}.

  0%|          | 0/59 [00:00<?, ?it/s]
100%|██████████| 59/59 [00:00<00:00, 380.98it/s]

Trial 143: DBCV=0.596, CCC=0.526
[I 2025-12-22 20:04:32,987] Trial 143 finished with values: [0.5264307938068824, 0.5962282101082851] and parameters: {'n_neighbors': 28, 'n_components': 7, 'min_dist': 0.03, 'min_cluster_size': 6, 'min_samples': 7, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 12/12 [00:00<00:00, 383.03it/s]

Trial 144: DBCV=0.324, CCC=0.755
[I 2025-12-22 20:04:43,879] Trial 144 finished with values: [0.7548697486594634, 0.3240071393708278] and parameters: {'n_neighbors': 25, 'n_components': 9, 'min_dist': 0.02, 'min_cluster_size': 37, 'min_samples': 4, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 308.81it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 145: DBCV=0.937, CCC=0.000
[I 2025-12-22 20:04:55,552] Trial 145 finished with values: [0.0, 0.937158471597484] and parameters: {'n_neighbors': 45, 'n_components': 9, 'min_dist': 0.22, 'min_cluster_size': 42, 'min_samples': 9, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 273.74it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 146: DBCV=0.915, CCC=0.000
[I 2025-12-22 20:05:06,655] Trial 146 finished with values: [0.0, 0.9154452079271918] and parameters: {'n_neighbors': 24, 'n_components': 11, 'min_dist': 0.19, 'min_cluster_size': 34, 'min_samples': 10, 'cluster_selection_epsilon': 0.3}.

  0%|          | 0/47 [00:00<?, ?it/s]
100%|██████████| 47/47 [00:00<00:00, 378.14it/s]

Trial 147: DBCV=0.292, CCC=0.477
[I 2025-12-22 20:05:17,629] Trial 147 finished with values: [0.47748820778827017, 0.29224202672844884] and parameters: {'n_neighbors': 2, 'n_components': 15, 'min_dist': 0.23, 'min_cluster_size': 7, 'min_samples': 10, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 276.18it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 148: DBCV=0.942, CCC=0.000
[I 2025-12-22 20:05:29,138] Trial 148 finished with values: [0.0, 0.9419400488455735] and parameters: {'n_neighbors': 44, 'n_components': 7, 'min_dist': 0.05, 'min_cluster_size': 14, 'min_samples': 9, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 21/21 [00:00<00:00, 359.06it/s]

Trial 149: DBCV=0.428, CCC=0.556
[I 2025-12-22 20:05:37,886] Trial 149 finished with values: [0.5559024766296448, 0.427734792357207] and parameters: {'n_neighbors': 4, 'n_components': 8, 'min_dist': 0.08, 'min_cluster_size': 30, 'min_samples': 6, 'cluster_selection_epsilon': 0.22}.

  0%|          | 0/74 [00:00<?, ?it/s]
100%|██████████| 74/74 [00:00<00:00, 397.77it/s]

Trial 150: DBCV=0.364, CCC=0.503
[I 2025-12-22 20:05:49,396] Trial 150 finished with values: [0.5028928147851429, 0.3640203637123829] and parameters: {'n_neighbors': 32, 'n_components': 10, 'min_dist': 0.09, 'min_cluster_size': 8, 'min_samples': 2, 'cluster_selection_epsilon': 0.05}.

  0%|          | 0/78 [00:00<?, ?it/s]
100%|██████████| 78/78 [00:00<00:00, 392.38it/s]

Trial 151: DBCV=0.584, CCC=0.430
[I 2025-12-22 20:06:01,281] Trial 151 finished with values: [0.4299486054161633, 0.5841478952484531] and parameters: {'n_neighbors': 28, 'n_components': 13, 'min_dist': 0.02, 'min_cluster_size': 6, 'min_samples': 4, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 276.14it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 152: DBCV=0.950, CCC=0.000
[I 2025-12-22 20:06:13,017] Trial 152 finished with values: [0.0, 0.9496610871586029] and parameters: {'n_neighbors': 50, 'n_components': 9, 'min_dist': 0.02, 'min_cluster_size': 44, 'min_samples': 10, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 1/1 [00:00<00:00, 271.48it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 153: DBCV=0.841, CCC=0.000
[I 2025-12-22 20:06:23,372] Trial 153 finished with values: [0.0, 0.840790841356208] and parameters: {'n_neighbors': 34, 'n_components': 2, 'min_dist': 0.08, 'min_cluster_size': 45, 'min_samples': 14, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 29/29 [00:00<00:00, 374.66it/s]

Trial 154: DBCV=0.449, CCC=0.573
[I 2025-12-22 20:06:32,007] Trial 154 finished with values: [0.5731610197950009, 0.4490343123375771] and parameters: {'n_neighbors': 3, 'n_components': 9, 'min_dist': 0.03, 'min_cluster_size': 29, 'min_samples': 3, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 274.12it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 155: DBCV=0.866, CCC=0.000
[I 2025-12-22 20:06:42,224] Trial 155 finished with values: [0.0, 0.8655106420743851] and parameters: {'n_neighbors': 11, 'n_components': 12, 'min_dist': 0.02, 'min_cluster_size': 41, 'min_samples': 18, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 1/1 [00:00<00:00, 308.04it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 156: DBCV=0.829, CCC=0.000
[I 2025-12-22 20:06:52,339] Trial 156 finished with values: [0.0, 0.8292827731557507] and parameters: {'n_neighbors': 25, 'n_components': 2, 'min_dist': 0.19, 'min_cluster_size': 49, 'min_samples': 6, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 276.45it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 157: DBCV=0.927, CCC=0.000
[I 2025-12-22 20:07:02,821] Trial 157 finished with values: [0.0, 0.9267993925738661] and parameters: {'n_neighbors': 25, 'n_components': 5, 'min_dist': 0.03, 'min_cluster_size': 27, 'min_samples': 18, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 302.38it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 158: DBCV=0.880, CCC=0.000
[I 2025-12-22 20:07:13,604] Trial 158 finished with values: [0.0, 0.8800275482623294] and parameters: {'n_neighbors': 11, 'n_components': 15, 'min_dist': 0.08, 'min_cluster_size': 38, 'min_samples': 10, 'cluster_selection_epsilon': 0.18}.

  0%|          | 0/92 [00:00<?, ?it/s]
 43%|████▎     | 40/92 [00:00<00:00, 399.01it/s]
100%|██████████| 92/92 [00:00<00:00, 395.13it/s]

Trial 159: DBCV=0.629, CCC=0.505
[I 2025-12-22 20:07:22,675] Trial 159 finished with values: [0.5045972478229982, 0.6287443581619275] and parameters: {'n_neighbors': 4, 'n_components': 2, 'min_dist': 0.08, 'min_cluster_size': 2, 'min_samples': 8, 'cluster_selection_epsilon': 0.06}.

  0%|          | 0/84 [00:00<?, ?it/s]
 49%|████▉     | 41/84 [00:00<00:00, 403.09it/s]
100%|██████████| 84/84 [00:00<00:00, 385.66it/s]

Trial 160: DBCV=0.522, CCC=0.476
[I 2025-12-22 20:07:33,660] Trial 160 finished with values: [0.4762567746188041, 0.5221182281409521] and parameters: {'n_neighbors': 18, 'n_components': 10, 'min_dist': 0.03, 'min_cluster_size': 7, 'min_samples': 3, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 218.93it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 161: DBCV=0.899, CCC=0.000
[I 2025-12-22 20:07:44,135] Trial 161 finished with values: [0.0, 0.8989390755976814] and parameters: {'n_neighbors': 20, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 14, 'min_samples': 7, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 1/1 [00:00<00:00, 307.46it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 162: DBCV=0.940, CCC=0.000
[I 2025-12-22 20:07:54,983] Trial 162 finished with values: [0.0, 0.9399265830437442] and parameters: {'n_neighbors': 25, 'n_components': 9, 'min_dist': 0.03, 'min_cluster_size': 27, 'min_samples': 12, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 226.34it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 163: DBCV=0.842, CCC=0.000
[I 2025-12-22 20:08:05,371] Trial 163 finished with values: [0.0, 0.8418518239711235] and parameters: {'n_neighbors': 11, 'n_components': 13, 'min_dist': 0.26, 'min_cluster_size': 44, 'min_samples': 14, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 11/11 [00:00<00:00, 335.85it/s]

Trial 164: DBCV=0.418, CCC=0.792
[I 2025-12-22 20:08:15,019] Trial 164 finished with values: [0.791863727695756, 0.41846178704522274] and parameters: {'n_neighbors': 11, 'n_components': 6, 'min_dist': 0.01, 'min_cluster_size': 47, 'min_samples': 9, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 15/15 [00:00<00:00, 356.01it/s]

Trial 165: DBCV=0.404, CCC=0.583
[I 2025-12-22 20:08:25,637] Trial 165 finished with values: [0.5834724203825358, 0.403795025210427] and parameters: {'n_neighbors': 11, 'n_components': 15, 'min_dist': 0.05, 'min_cluster_size': 37, 'min_samples': 7, 'cluster_selection_epsilon': 0.25}.

  0%|          | 0/66 [00:00<?, ?it/s]
100%|██████████| 66/66 [00:00<00:00, 385.26it/s]

Trial 166: DBCV=0.318, CCC=0.417
[I 2025-12-22 20:08:37,160] Trial 166 finished with values: [0.41676234128209, 0.31814771644603873] and parameters: {'n_neighbors': 41, 'n_components': 8, 'min_dist': 0.08, 'min_cluster_size': 6, 'min_samples': 1, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 1/1 [00:00<00:00, 276.27it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 167: DBCV=0.934, CCC=0.000
[I 2025-12-22 20:08:48,319] Trial 167 finished with values: [0.0, 0.9335808481715061] and parameters: {'n_neighbors': 23, 'n_components': 12, 'min_dist': 0.05, 'min_cluster_size': 49, 'min_samples': 6, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 1/1 [00:00<00:00, 267.03it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 168: DBCV=0.954, CCC=0.000
[I 2025-12-22 20:08:59,569] Trial 168 finished with values: [0.0, 0.9535686274819887] and parameters: {'n_neighbors': 34, 'n_components': 9, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 9, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 24/24 [00:00<00:00, 375.73it/s]

Trial 169: DBCV=0.340, CCC=0.542
[I 2025-12-22 20:09:09,901] Trial 169 finished with values: [0.5417105153207663, 0.3400511400930783] and parameters: {'n_neighbors': 25, 'n_components': 5, 'min_dist': 0.0, 'min_cluster_size': 28, 'min_samples': 4, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 13/13 [00:00<00:00, 339.44it/s]

Trial 170: DBCV=0.189, CCC=0.699
[I 2025-12-22 20:09:20,736] Trial 170 finished with values: [0.6993512819596597, 0.1885449549465247] and parameters: {'n_neighbors': 39, 'n_components': 5, 'min_dist': 0.02, 'min_cluster_size': 39, 'min_samples': 3, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/83 [00:00<?, ?it/s]
 49%|████▉     | 41/83 [00:00<00:00, 406.53it/s]
100%|██████████| 83/83 [00:00<00:00, 378.92it/s]

Trial 171: DBCV=0.500, CCC=0.381
[I 2025-12-22 20:09:32,046] Trial 171 finished with values: [0.3805015590539586, 0.5003083495481926] and parameters: {'n_neighbors': 26, 'n_components': 9, 'min_dist': 0.01, 'min_cluster_size': 6, 'min_samples': 3, 'cluster_selection_epsilon': 0.15}.

  0%|          | 0/61 [00:00<?, ?it/s]
100%|██████████| 61/61 [00:00<00:00, 393.04it/s]

Trial 172: DBCV=0.312, CCC=0.477
[I 2025-12-22 20:09:42,673] Trial 172 finished with values: [0.4769248686391772, 0.3124958953300115] and parameters: {'n_neighbors': 2, 'n_components': 5, 'min_dist': 0.23, 'min_cluster_size': 7, 'min_samples': 10, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 10/10 [00:00<00:00, 336.04it/s]

Trial 173: DBCV=0.522, CCC=0.782
[I 2025-12-22 20:09:52,834] Trial 173 finished with values: [0.7818647936093674, 0.5220573858196715] and parameters: {'n_neighbors': 11, 'n_components': 13, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 16, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 15/15 [00:00<00:00, 349.31it/s]

Trial 174: DBCV=0.426, CCC=0.638
[I 2025-12-22 20:10:03,436] Trial 174 finished with values: [0.6377476864643571, 0.4259839380121326] and parameters: {'n_neighbors': 12, 'n_components': 15, 'min_dist': 0.02, 'min_cluster_size': 44, 'min_samples': 2, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 28/28 [00:00<00:00, 381.12it/s]

Trial 175: DBCV=0.282, CCC=0.661
[I 2025-12-22 20:10:13,488] Trial 175 finished with values: [0.6607671291954919, 0.2824283670629834] and parameters: {'n_neighbors': 15, 'n_components': 8, 'min_dist': 0.08, 'min_cluster_size': 29, 'min_samples': 2, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 10/10 [00:00<00:00, 336.61it/s]

Trial 176: DBCV=0.390, CCC=0.833
[I 2025-12-22 20:10:24,339] Trial 176 finished with values: [0.8334635592975936, 0.389969409454274] and parameters: {'n_neighbors': 20, 'n_components': 13, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 14, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 12/12 [00:00<00:00, 323.19it/s]

Trial 177: DBCV=0.464, CCC=0.719
[I 2025-12-22 20:10:34,784] Trial 177 finished with values: [0.718731562734517, 0.46359198765563026] and parameters: {'n_neighbors': 11, 'n_components': 15, 'min_dist': 0.01, 'min_cluster_size': 37, 'min_samples': 9, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 13/13 [00:00<00:00, 379.21it/s]

Trial 178: DBCV=0.349, CCC=0.522
[I 2025-12-22 20:10:43,503] Trial 178 finished with values: [0.5218805123847496, 0.34946223676411936] and parameters: {'n_neighbors': 4, 'n_components': 10, 'min_dist': 0.01, 'min_cluster_size': 45, 'min_samples': 2, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 2/2 [00:00<00:00, 356.42it/s]

Trial 179: DBCV=0.021, CCC=0.638
[I 2025-12-22 20:10:52,781] Trial 179 finished with values: [0.6383430407142474, 0.021126695735345424] and parameters: {'n_neighbors': 2, 'n_components': 5, 'min_dist': 0.03, 'min_cluster_size': 46, 'min_samples': 13, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 19/19 [00:00<00:00, 349.80it/s]

Trial 180: DBCV=0.261, CCC=0.556
[I 2025-12-22 20:11:01,056] Trial 180 finished with values: [0.5563864161495823, 0.2610990545678644] and parameters: {'n_neighbors': 3, 'n_components': 3, 'min_dist': 0.0, 'min_cluster_size': 41, 'min_samples': 2, 'cluster_selection_epsilon': 0.25}.

  0%|          | 0/41 [00:00<?, ?it/s]
100%|██████████| 41/41 [00:00<00:00, 383.75it/s]

Trial 181: DBCV=0.346, CCC=0.537
[I 2025-12-22 20:11:12,330] Trial 181 finished with values: [0.5368555232361055, 0.3464708623684452] and parameters: {'n_neighbors': 39, 'n_components': 7, 'min_dist': 0.03, 'min_cluster_size': 15, 'min_samples': 3, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 1/1 [00:00<00:00, 305.40it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 182: DBCV=0.956, CCC=0.000
[I 2025-12-22 20:11:25,176] Trial 182 finished with values: [0.0, 0.9563618566756488] and parameters: {'n_neighbors': 50, 'n_components': 15, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 18, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 34/34 [00:00<00:00, 390.25it/s]

Trial 183: DBCV=0.567, CCC=0.494
[I 2025-12-22 20:11:35,643] Trial 183 finished with values: [0.4938951888054322, 0.566649344196373] and parameters: {'n_neighbors': 38, 'n_components': 3, 'min_dist': 0.01, 'min_cluster_size': 6, 'min_samples': 14, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 17/17 [00:00<00:00, 389.01it/s]

Trial 184: DBCV=0.293, CCC=0.798
[I 2025-12-22 20:11:46,149] Trial 184 finished with values: [0.7979147509055905, 0.2934478209733887] and parameters: {'n_neighbors': 24, 'n_components': 6, 'min_dist': 0.02, 'min_cluster_size': 35, 'min_samples': 3, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 37/37 [00:00<00:00, 405.87it/s]

Trial 185: DBCV=0.594, CCC=0.506
[I 2025-12-22 20:11:57,758] Trial 185 finished with values: [0.5055823529651813, 0.5943023847982882] and parameters: {'n_neighbors': 38, 'n_components': 11, 'min_dist': 0.0, 'min_cluster_size': 6, 'min_samples': 12, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 16/16 [00:00<00:00, 394.02it/s]

Trial 186: DBCV=0.343, CCC=0.453
[I 2025-12-22 20:12:08,655] Trial 186 finished with values: [0.4528018327524996, 0.3427551516608007] and parameters: {'n_neighbors': 25, 'n_components': 11, 'min_dist': 0.03, 'min_cluster_size': 33, 'min_samples': 4, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 1/1 [00:00<00:00, 292.98it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 187: DBCV=0.921, CCC=0.000
[I 2025-12-22 20:12:18,847] Trial 187 finished with values: [0.0, 0.920882594519228] and parameters: {'n_neighbors': 12, 'n_components': 10, 'min_dist': 0.09, 'min_cluster_size': 39, 'min_samples': 5, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 13/13 [00:00<00:00, 385.50it/s]

Trial 188: DBCV=0.349, CCC=0.703
[I 2025-12-22 20:12:28,703] Trial 188 finished with values: [0.7029381203988777, 0.34934919373865975] and parameters: {'n_neighbors': 15, 'n_components': 5, 'min_dist': 0.0, 'min_cluster_size': 41, 'min_samples': 8, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 1/1 [00:00<00:00, 293.62it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 189: DBCV=0.931, CCC=0.000
[I 2025-12-22 20:12:39,615] Trial 189 finished with values: [0.0, 0.9309217215354607] and parameters: {'n_neighbors': 25, 'n_components': 9, 'min_dist': 0.06, 'min_cluster_size': 37, 'min_samples': 18, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 230.52it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 190: DBCV=0.948, CCC=0.000
[I 2025-12-22 20:12:51,391] Trial 190 finished with values: [0.0, 0.9477621310160333] and parameters: {'n_neighbors': 36, 'n_components': 12, 'min_dist': 0.11, 'min_cluster_size': 15, 'min_samples': 9, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 1/1 [00:00<00:00, 305.42it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 191: DBCV=0.952, CCC=0.000
[I 2025-12-22 20:13:03,876] Trial 191 finished with values: [0.0, 0.9523671741285675] and parameters: {'n_neighbors': 39, 'n_components': 15, 'min_dist': 0.12, 'min_cluster_size': 39, 'min_samples': 2, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 1/1 [00:00<00:00, 198.34it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 192: DBCV=0.955, CCC=0.000
[I 2025-12-22 20:13:15,507] Trial 192 finished with values: [0.0, 0.9551851042592296] and parameters: {'n_neighbors': 34, 'n_components': 12, 'min_dist': 0.05, 'min_cluster_size': 22, 'min_samples': 7, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 273.33it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 193: DBCV=0.951, CCC=0.000
[I 2025-12-22 20:13:27,796] Trial 193 finished with values: [0.0, 0.9505574432717591] and parameters: {'n_neighbors': 34, 'n_components': 15, 'min_dist': 0.0, 'min_cluster_size': 37, 'min_samples': 11, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 27/27 [00:00<00:00, 379.74it/s]

Trial 194: DBCV=0.379, CCC=0.530
[I 2025-12-22 20:13:36,435] Trial 194 finished with values: [0.5297113599964848, 0.3789767178391632] and parameters: {'n_neighbors': 4, 'n_components': 5, 'min_dist': 0.09, 'min_cluster_size': 26, 'min_samples': 2, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 276.27it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 195: DBCV=0.947, CCC=0.000
[I 2025-12-22 20:13:48,201] Trial 195 finished with values: [0.0, 0.9467780894430755] and parameters: {'n_neighbors': 29, 'n_components': 14, 'min_dist': 0.07, 'min_cluster_size': 15, 'min_samples': 10, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 186.20it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 196: DBCV=0.958, CCC=0.000
[I 2025-12-22 20:13:59,434] Trial 196 finished with values: [0.0, 0.9577789552701905] and parameters: {'n_neighbors': 41, 'n_components': 8, 'min_dist': 0.03, 'min_cluster_size': 6, 'min_samples': 14, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 200.24it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 197: DBCV=0.755, CCC=0.000
[I 2025-12-22 20:14:08,751] Trial 197 finished with values: [0.0, 0.7546619470713172] and parameters: {'n_neighbors': 11, 'n_components': 2, 'min_dist': 0.03, 'min_cluster_size': 44, 'min_samples': 14, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 140.47it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 198: DBCV=0.952, CCC=0.000
[I 2025-12-22 20:14:21,333] Trial 198 finished with values: [0.0, 0.9518553120215876] and parameters: {'n_neighbors': 41, 'n_components': 15, 'min_dist': 0.13, 'min_cluster_size': 45, 'min_samples': 3, 'cluster_selection_epsilon': 0.28}.

100%|██████████| 1/1 [00:00<00:00, 188.03it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 199: DBCV=0.950, CCC=0.000
[I 2025-12-22 20:14:32,444] Trial 199 finished with values: [0.0, 0.9500728098515961] and parameters: {'n_neighbors': 32, 'n_components': 9, 'min_dist': 0.01, 'min_cluster_size': 6, 'min_samples': 14, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 18/18 [00:00<00:00, 363.02it/s]

Trial 200: DBCV=0.341, CCC=0.668
[I 2025-12-22 20:14:43,138] Trial 200 finished with values: [0.6683672912188031, 0.3405896531330556] and parameters: {'n_neighbors': 18, 'n_components': 11, 'min_dist': 0.03, 'min_cluster_size': 38, 'min_samples': 3, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 273.35it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 201: DBCV=0.955, CCC=0.000
[I 2025-12-22 20:14:54,902] Trial 201 finished with values: [0.0, 0.9552717697816613] and parameters: {'n_neighbors': 39, 'n_components': 11, 'min_dist': 0.02, 'min_cluster_size': 15, 'min_samples': 10, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 273.37it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 202: DBCV=0.837, CCC=0.000
[I 2025-12-22 20:15:05,449] Trial 202 finished with values: [0.0, 0.837310187160872] and parameters: {'n_neighbors': 41, 'n_components': 2, 'min_dist': 0.03, 'min_cluster_size': 50, 'min_samples': 18, 'cluster_selection_epsilon': 0.06}.

  0%|          | 0/146 [00:00<?, ?it/s]
 27%|██▋       | 40/146 [00:00<00:00, 398.66it/s]
 55%|█████▍    | 80/146 [00:00<00:00, 392.25it/s]
100%|██████████| 146/146 [00:00<00:00, 385.15it/s]

Trial 203: DBCV=0.638, CCC=0.471
[I 2025-12-22 20:15:16,014] Trial 203 finished with values: [0.47093846388427335, 0.638234441599475] and parameters: {'n_neighbors': 11, 'n_components': 2, 'min_dist': 0.01, 'min_cluster_size': 2, 'min_samples': 4, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 9/9 [00:00<00:00, 326.44it/s]

Trial 204: DBCV=0.363, CCC=0.915
[I 2025-12-22 20:15:24,930] Trial 204 finished with values: [0.9153236705480157, 0.36278672798404327] and parameters: {'n_neighbors': 4, 'n_components': 11, 'min_dist': 0.03, 'min_cluster_size': 42, 'min_samples': 14, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 280.01it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 205: DBCV=0.960, CCC=0.000
[I 2025-12-22 20:15:37,545] Trial 205 finished with values: [0.0, 0.9597176320525546] and parameters: {'n_neighbors': 42, 'n_components': 15, 'min_dist': 0.01, 'min_cluster_size': 7, 'min_samples': 13, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 271.76it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 206: DBCV=0.955, CCC=0.000
[I 2025-12-22 20:15:49,645] Trial 206 finished with values: [0.0, 0.955388958637048] and parameters: {'n_neighbors': 37, 'n_components': 14, 'min_dist': 0.05, 'min_cluster_size': 8, 'min_samples': 14, 'cluster_selection_epsilon': 0.27}.

  0%|          | 0/40 [00:00<?, ?it/s]
100%|██████████| 40/40 [00:00<00:00, 383.15it/s]

Trial 207: DBCV=0.572, CCC=0.565
[I 2025-12-22 20:15:59,755] Trial 207 finished with values: [0.5652233039769948, 0.5720315648075057] and parameters: {'n_neighbors': 11, 'n_components': 11, 'min_dist': 0.0, 'min_cluster_size': 7, 'min_samples': 12, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 1/1 [00:00<00:00, 272.25it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 208: DBCV=0.940, CCC=0.000
[I 2025-12-22 20:16:10,957] Trial 208 finished with values: [0.0, 0.9396509324401247] and parameters: {'n_neighbors': 41, 'n_components': 6, 'min_dist': 0.01, 'min_cluster_size': 38, 'min_samples': 14, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 2/2 [00:00<00:00, 321.14it/s]

Trial 209: DBCV=0.873, CCC=0.999
[I 2025-12-22 20:16:21,435] Trial 209 finished with values: [0.9987710624958149, 0.8729843668230245] and parameters: {'n_neighbors': 39, 'n_components': 2, 'min_dist': 0.02, 'min_cluster_size': 39, 'min_samples': 6, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 22/22 [00:00<00:00, 360.98it/s]

Trial 210: DBCV=0.440, CCC=0.593
[I 2025-12-22 20:16:31,425] Trial 210 finished with values: [0.5925010810557473, 0.439630313499011] and parameters: {'n_neighbors': 28, 'n_components': 2, 'min_dist': 0.01, 'min_cluster_size': 8, 'min_samples': 14, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 20/20 [00:00<00:00, 366.80it/s]

Trial 211: DBCV=0.549, CCC=0.525
[I 2025-12-22 20:16:42,200] Trial 211 finished with values: [0.5253183089192248, 0.5485463183107477] and parameters: {'n_neighbors': 28, 'n_components': 7, 'min_dist': 0.01, 'min_cluster_size': 27, 'min_samples': 11, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 274.86it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 212: DBCV=0.943, CCC=0.000
[I 2025-12-22 20:16:53,612] Trial 212 finished with values: [0.0, 0.9433672130574361] and parameters: {'n_neighbors': 50, 'n_components': 6, 'min_dist': 0.02, 'min_cluster_size': 44, 'min_samples': 13, 'cluster_selection_epsilon': 0.3}.

  0%|          | 0/60 [00:00<?, ?it/s]
100%|██████████| 60/60 [00:00<00:00, 397.77it/s]

Trial 213: DBCV=0.457, CCC=0.541
[I 2025-12-22 20:17:04,350] Trial 213 finished with values: [0.5405670510723494, 0.45714296789588543] and parameters: {'n_neighbors': 38, 'n_components': 3, 'min_dist': 0.08, 'min_cluster_size': 2, 'min_samples': 8, 'cluster_selection_epsilon': 0.06}.

  0%|          | 0/46 [00:00<?, ?it/s]
100%|██████████| 46/46 [00:00<00:00, 370.13it/s]

Trial 214: DBCV=0.442, CCC=0.588
[I 2025-12-22 20:17:15,883] Trial 214 finished with values: [0.5884733944431401, 0.44165618389905226] and parameters: {'n_neighbors': 34, 'n_components': 11, 'min_dist': 0.01, 'min_cluster_size': 12, 'min_samples': 3, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 14/14 [00:00<00:00, 338.18it/s]

Trial 215: DBCV=0.386, CCC=0.673
[I 2025-12-22 20:17:25,107] Trial 215 finished with values: [0.6730859033627951, 0.38594495567384873] and parameters: {'n_neighbors': 4, 'n_components': 15, 'min_dist': 0.08, 'min_cluster_size': 37, 'min_samples': 18, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 283.42it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 216: DBCV=0.946, CCC=0.000
[I 2025-12-22 20:17:36,523] Trial 216 finished with values: [0.0, 0.9455402690821982] and parameters: {'n_neighbors': 41, 'n_components': 9, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 6, 'cluster_selection_epsilon': 0.27}.

  0%|          | 0/66 [00:00<?, ?it/s]
100%|██████████| 66/66 [00:00<00:00, 385.40it/s]

Trial 217: DBCV=0.531, CCC=0.418
[I 2025-12-22 20:17:47,714] Trial 217 finished with values: [0.41799298237536003, 0.5309291611125722] and parameters: {'n_neighbors': 33, 'n_components': 8, 'min_dist': 0.12, 'min_cluster_size': 2, 'min_samples': 6, 'cluster_selection_epsilon': 0.22}.

  0%|          | 0/84 [00:00<?, ?it/s]
 49%|████▉     | 41/84 [00:00<00:00, 404.44it/s]
100%|██████████| 84/84 [00:00<00:00, 379.64it/s]

Trial 218: DBCV=0.522, CCC=0.476
[I 2025-12-22 20:17:58,697] Trial 218 finished with values: [0.4762567746188041, 0.5221182281409521] and parameters: {'n_neighbors': 18, 'n_components': 10, 'min_dist': 0.03, 'min_cluster_size': 7, 'min_samples': 3, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 183.90it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 219: DBCV=0.880, CCC=0.000
[I 2025-12-22 20:18:08,611] Trial 219 finished with values: [0.0, 0.8801527173182279] and parameters: {'n_neighbors': 11, 'n_components': 8, 'min_dist': 0.24, 'min_cluster_size': 37, 'min_samples': 9, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 27/27 [00:00<00:00, 380.35it/s]

Trial 220: DBCV=0.415, CCC=0.439
[I 2025-12-22 20:18:19,930] Trial 220 finished with values: [0.43923183383580294, 0.4145771401171801] and parameters: {'n_neighbors': 44, 'n_components': 7, 'min_dist': 0.05, 'min_cluster_size': 8, 'min_samples': 7, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 19/19 [00:00<00:00, 393.82it/s]

Trial 221: DBCV=0.573, CCC=0.680
[I 2025-12-22 20:18:30,633] Trial 221 finished with values: [0.6798123926988822, 0.5727769049293332] and parameters: {'n_neighbors': 20, 'n_components': 11, 'min_dist': 0.01, 'min_cluster_size': 23, 'min_samples': 12, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 1/1 [00:00<00:00, 273.05it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 222: DBCV=0.939, CCC=0.000
[I 2025-12-22 20:18:41,582] Trial 222 finished with values: [0.0, 0.9392777295437386] and parameters: {'n_neighbors': 29, 'n_components': 7, 'min_dist': 0.02, 'min_cluster_size': 37, 'min_samples': 13, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 188.30it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 223: DBCV=0.954, CCC=0.000
[I 2025-12-22 20:18:53,705] Trial 223 finished with values: [0.0, 0.9542331040143126] and parameters: {'n_neighbors': 44, 'n_components': 13, 'min_dist': 0.08, 'min_cluster_size': 2, 'min_samples': 9, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 272.89it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 224: DBCV=0.960, CCC=0.000
[I 2025-12-22 20:19:05,798] Trial 224 finished with values: [0.0, 0.9597487301694927] and parameters: {'n_neighbors': 41, 'n_components': 13, 'min_dist': 0.0, 'min_cluster_size': 6, 'min_samples': 12, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 16/16 [00:00<00:00, 395.76it/s]

Trial 225: DBCV=0.485, CCC=0.709
[I 2025-12-22 20:19:15,682] Trial 225 finished with values: [0.7087617032478093, 0.48539376308030463] and parameters: {'n_neighbors': 7, 'n_components': 15, 'min_dist': 0.08, 'min_cluster_size': 37, 'min_samples': 13, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 227.00it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 226: DBCV=0.961, CCC=0.000
[I 2025-12-22 20:19:28,153] Trial 226 finished with values: [0.0, 0.9607601227823008] and parameters: {'n_neighbors': 39, 'n_components': 15, 'min_dist': 0.02, 'min_cluster_size': 39, 'min_samples': 10, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 270.46it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 227: DBCV=0.913, CCC=0.000
[I 2025-12-22 20:19:38,853] Trial 227 finished with values: [0.0, 0.9132287179111603] and parameters: {'n_neighbors': 39, 'n_components': 3, 'min_dist': 0.02, 'min_cluster_size': 39, 'min_samples': 10, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 10/10 [00:00<00:00, 342.20it/s]

Trial 228: DBCV=0.403, CCC=0.800
[I 2025-12-22 20:19:49,687] Trial 228 finished with values: [0.8004255978764746, 0.40297797655277473] and parameters: {'n_neighbors': 14, 'n_components': 15, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 18, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 33/33 [00:00<00:00, 383.90it/s]

Trial 229: DBCV=0.506, CCC=0.572
[I 2025-12-22 20:19:59,383] Trial 229 finished with values: [0.5721835698389173, 0.5057443183787198] and parameters: {'n_neighbors': 11, 'n_components': 6, 'min_dist': 0.01, 'min_cluster_size': 19, 'min_samples': 9, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 203.62it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 230: DBCV=0.941, CCC=0.000
[I 2025-12-22 20:20:10,497] Trial 230 finished with values: [0.0, 0.9407171904496779] and parameters: {'n_neighbors': 32, 'n_components': 7, 'min_dist': 0.05, 'min_cluster_size': 42, 'min_samples': 14, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 1/1 [00:00<00:00, 214.00it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 231: DBCV=0.949, CCC=0.000
[I 2025-12-22 20:20:21,444] Trial 231 finished with values: [0.0, 0.9485796768015835] and parameters: {'n_neighbors': 34, 'n_components': 6, 'min_dist': 0.01, 'min_cluster_size': 47, 'min_samples': 9, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 29/29 [00:00<00:00, 383.97it/s]

Trial 232: DBCV=0.395, CCC=0.485
[I 2025-12-22 20:20:31,113] Trial 232 finished with values: [0.4853626286459307, 0.3954265702821404] and parameters: {'n_neighbors': 11, 'n_components': 6, 'min_dist': 0.01, 'min_cluster_size': 29, 'min_samples': 3, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 10/10 [00:00<00:00, 378.63it/s]

Trial 233: DBCV=0.283, CCC=0.736
[I 2025-12-22 20:20:42,873] Trial 233 finished with values: [0.7356631726345623, 0.2828829503525667] and parameters: {'n_neighbors': 50, 'n_components': 11, 'min_dist': 0.0, 'min_cluster_size': 48, 'min_samples': 2, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 24/24 [00:00<00:00, 376.22it/s]

Trial 234: DBCV=0.404, CCC=0.707
[I 2025-12-22 20:20:52,337] Trial 234 finished with values: [0.7069114717961725, 0.4039064864077942] and parameters: {'n_neighbors': 8, 'n_components': 7, 'min_dist': 0.02, 'min_cluster_size': 32, 'min_samples': 4, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 29/29 [00:00<00:00, 403.21it/s]

Trial 235: DBCV=0.558, CCC=0.560
[I 2025-12-22 20:21:04,314] Trial 235 finished with values: [0.5603245957612385, 0.5579983661128216] and parameters: {'n_neighbors': 39, 'n_components': 14, 'min_dist': 0.02, 'min_cluster_size': 15, 'min_samples': 10, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 35/35 [00:00<00:00, 404.98it/s]

Trial 236: DBCV=0.602, CCC=0.587
[I 2025-12-22 20:21:14,679] Trial 236 finished with values: [0.5869339828043042, 0.6015514077019403] and parameters: {'n_neighbors': 18, 'n_components': 7, 'min_dist': 0.03, 'min_cluster_size': 6, 'min_samples': 12, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 281.40it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 237: DBCV=0.922, CCC=0.000
[I 2025-12-22 20:21:26,491] Trial 237 finished with values: [0.0, 0.9219950974157888] and parameters: {'n_neighbors': 23, 'n_components': 15, 'min_dist': 0.15, 'min_cluster_size': 44, 'min_samples': 7, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 17/17 [00:00<00:00, 348.30it/s]

Trial 238: DBCV=0.372, CCC=0.642
[I 2025-12-22 20:21:37,165] Trial 238 finished with values: [0.6424582650526862, 0.37187701049638144] and parameters: {'n_neighbors': 25, 'n_components': 9, 'min_dist': 0.03, 'min_cluster_size': 27, 'min_samples': 6, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 27/27 [00:00<00:00, 401.48it/s]

Trial 239: DBCV=0.482, CCC=0.458
[I 2025-12-22 20:21:49,921] Trial 239 finished with values: [0.4583824117384195, 0.4817449756825224] and parameters: {'n_neighbors': 50, 'n_components': 15, 'min_dist': 0.01, 'min_cluster_size': 9, 'min_samples': 9, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 159.36it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 240: DBCV=0.906, CCC=0.000
[I 2025-12-22 20:22:00,967] Trial 240 finished with values: [0.0, 0.9060386884315913] and parameters: {'n_neighbors': 42, 'n_components': 5, 'min_dist': 0.11, 'min_cluster_size': 16, 'min_samples': 6, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 1/1 [00:00<00:00, 304.82it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 241: DBCV=0.930, CCC=0.000
[I 2025-12-22 20:22:12,373] Trial 241 finished with values: [0.0, 0.9300509232526999] and parameters: {'n_neighbors': 42, 'n_components': 7, 'min_dist': 0.12, 'min_cluster_size': 44, 'min_samples': 12, 'cluster_selection_epsilon': 0.25}.

  0%|          | 0/57 [00:00<?, ?it/s]
100%|██████████| 57/57 [00:00<00:00, 404.49it/s]

Trial 242: DBCV=0.543, CCC=0.446
[I 2025-12-22 20:22:24,149] Trial 242 finished with values: [0.446100447358833, 0.5429280225026941] and parameters: {'n_neighbors': 28, 'n_components': 14, 'min_dist': 0.02, 'min_cluster_size': 8, 'min_samples': 7, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 35/35 [00:00<00:00, 384.51it/s]

Trial 243: DBCV=0.579, CCC=0.590
[I 2025-12-22 20:22:35,299] Trial 243 finished with values: [0.5899108163959266, 0.5786324413590913] and parameters: {'n_neighbors': 41, 'n_components': 8, 'min_dist': 0.01, 'min_cluster_size': 6, 'min_samples': 13, 'cluster_selection_epsilon': 0.16}.

  0%|          | 0/61 [00:00<?, ?it/s]
100%|██████████| 61/61 [00:00<00:00, 382.96it/s]

Trial 244: DBCV=0.562, CCC=0.493
[I 2025-12-22 20:22:45,890] Trial 244 finished with values: [0.49344021468132293, 0.5620662679798908] and parameters: {'n_neighbors': 17, 'n_components': 10, 'min_dist': 0.18, 'min_cluster_size': 7, 'min_samples': 6, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 1/1 [00:00<00:00, 294.83it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 245: DBCV=0.935, CCC=0.000
[I 2025-12-22 20:22:57,480] Trial 245 finished with values: [0.0, 0.9353385083504302] and parameters: {'n_neighbors': 29, 'n_components': 13, 'min_dist': 0.12, 'min_cluster_size': 44, 'min_samples': 14, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 10/10 [00:00<00:00, 375.24it/s]

Trial 246: DBCV=0.471, CCC=0.778
[I 2025-12-22 20:23:07,621] Trial 246 finished with values: [0.7779458300109655, 0.4712823716967355] and parameters: {'n_neighbors': 11, 'n_components': 13, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 14, 'cluster_selection_epsilon': 0.24}.

  0%|          | 0/107 [00:00<?, ?it/s]
 38%|███▊      | 41/107 [00:00<00:00, 406.42it/s]
100%|██████████| 107/107 [00:00<00:00, 385.76it/s][A

Trial 247: DBCV=0.433, CCC=0.437
[I 2025-12-22 20:23:18,396] Trial 247 finished with values: [0.43689831217550446, 0.43315839235336845] and parameters: {'n_neighbors': 12, 'n_components': 10, 'min_dist': 0.25, 'min_cluster_size': 6, 'min_samples': 1, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 275.58it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 248: DBCV=0.956, CCC=0.000
[I 2025-12-22 20:23:30,413] Trial 248 finished with values: [0.0, 0.9564483541343427] and parameters: {'n_neighbors': 44, 'n_components': 12, 'min_dist': 0.05, 'min_cluster_size': 38, 'min_samples': 10, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 26/26 [00:00<00:00, 379.79it/s]

Trial 249: DBCV=0.496, CCC=0.602
[I 2025-12-22 20:23:39,212] Trial 249 finished with values: [0.601682670109952, 0.49574932164446844] and parameters: {'n_neighbors': 4, 'n_components': 7, 'min_dist': 0.08, 'min_cluster_size': 20, 'min_samples': 8, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 285.09it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 250: DBCV=0.884, CCC=0.000
[I 2025-12-22 20:23:49,137] Trial 250 finished with values: [0.0, 0.8835536571762134] and parameters: {'n_neighbors': 11, 'n_components': 7, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 14, 'cluster_selection_epsilon': 0.27}.

  0%|          | 0/87 [00:00<?, ?it/s]
 47%|████▋     | 41/87 [00:00<00:00, 404.89it/s]
100%|██████████| 87/87 [00:00<00:00, 386.35it/s]

Trial 251: DBCV=0.612, CCC=0.432
[I 2025-12-22 20:23:58,184] Trial 251 finished with values: [0.432205432169679, 0.6115728077051173] and parameters: {'n_neighbors': 4, 'n_components': 2, 'min_dist': 0.12, 'min_cluster_size': 2, 'min_samples': 8, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 299.46it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 252: DBCV=0.952, CCC=0.000
[I 2025-12-22 20:24:09,769] Trial 252 finished with values: [0.0, 0.9521392361662038] and parameters: {'n_neighbors': 28, 'n_components': 13, 'min_dist': 0.03, 'min_cluster_size': 44, 'min_samples': 7, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 2/2 [00:00<00:00, 289.02it/s]

Trial 253: DBCV=0.924, CCC=0.999
[I 2025-12-22 20:24:21,018] Trial 253 finished with values: [0.9989156913790005, 0.9235197333096083] and parameters: {'n_neighbors': 50, 'n_components': 5, 'min_dist': 0.01, 'min_cluster_size': 6, 'min_samples': 18, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 20/20 [00:00<00:00, 369.57it/s]

Trial 254: DBCV=0.469, CCC=0.648
[I 2025-12-22 20:24:29,811] Trial 254 finished with values: [0.6476814023775623, 0.4686076051461972] and parameters: {'n_neighbors': 4, 'n_components': 7, 'min_dist': 0.11, 'min_cluster_size': 20, 'min_samples': 8, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 18/18 [00:00<00:00, 385.13it/s]

Trial 255: DBCV=0.430, CCC=0.663
[I 2025-12-22 20:24:39,229] Trial 255 finished with values: [0.6627166111561849, 0.4298065634267075] and parameters: {'n_neighbors': 8, 'n_components': 7, 'min_dist': 0.02, 'min_cluster_size': 39, 'min_samples': 10, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 37/37 [00:00<00:00, 390.10it/s]

Trial 256: DBCV=0.632, CCC=0.492
[I 2025-12-22 20:24:50,701] Trial 256 finished with values: [0.4919992089458401, 0.6321634606261285] and parameters: {'n_neighbors': 28, 'n_components': 13, 'min_dist': 0.02, 'min_cluster_size': 6, 'min_samples': 12, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 300.13it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 257: DBCV=0.960, CCC=0.000
[I 2025-12-22 20:25:03,421] Trial 257 finished with values: [0.0, 0.9597176320525546] and parameters: {'n_neighbors': 42, 'n_components': 15, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 12, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 303.52it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 258: DBCV=0.958, CCC=0.000
[I 2025-12-22 20:25:14,694] Trial 258 finished with values: [0.0, 0.9577789552701905] and parameters: {'n_neighbors': 41, 'n_components': 8, 'min_dist': 0.03, 'min_cluster_size': 12, 'min_samples': 14, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 35/35 [00:00<00:00, 382.85it/s]

Trial 259: DBCV=0.530, CCC=0.568
[I 2025-12-22 20:25:25,857] Trial 259 finished with values: [0.5678371985406934, 0.5302878949936057] and parameters: {'n_neighbors': 20, 'n_components': 14, 'min_dist': 0.01, 'min_cluster_size': 15, 'min_samples': 10, 'cluster_selection_epsilon': 0.11}.

  0%|          | 0/86 [00:00<?, ?it/s]
 48%|████▊     | 41/86 [00:00<00:00, 405.41it/s]
100%|██████████| 86/86 [00:00<00:00, 382.91it/s]

Trial 260: DBCV=0.529, CCC=0.498
[I 2025-12-22 20:25:38,237] Trial 260 finished with values: [0.49806293063221047, 0.5290826949486717] and parameters: {'n_neighbors': 28, 'n_components': 15, 'min_dist': 0.02, 'min_cluster_size': 6, 'min_samples': 4, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 32/32 [00:00<00:00, 385.88it/s]

Trial 261: DBCV=0.554, CCC=0.572
[I 2025-12-22 20:25:48,264] Trial 261 finished with values: [0.5724078998514472, 0.5540753313816652] and parameters: {'n_neighbors': 11, 'n_components': 11, 'min_dist': 0.01, 'min_cluster_size': 19, 'min_samples': 12, 'cluster_selection_epsilon': 0.27}.

  0%|          | 0/50 [00:00<?, ?it/s]
100%|██████████| 50/50 [00:00<00:00, 390.95it/s]

Trial 262: DBCV=0.359, CCC=0.539
[I 2025-12-22 20:25:56,949] Trial 262 finished with values: [0.5389093140932817, 0.3588314234014367] and parameters: {'n_neighbors': 4, 'n_components': 2, 'min_dist': 0.2, 'min_cluster_size': 2, 'min_samples': 11, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 13/13 [00:00<00:00, 346.84it/s]

Trial 263: DBCV=0.323, CCC=0.495
[I 2025-12-22 20:26:09,142] Trial 263 finished with values: [0.49548095041610557, 0.3231512783947782] and parameters: {'n_neighbors': 35, 'n_components': 15, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 2, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 29/29 [00:00<00:00, 393.11it/s]

Trial 264: DBCV=0.624, CCC=0.498
[I 2025-12-22 20:26:20,789] Trial 264 finished with values: [0.49810052811821626, 0.6242315153423954] and parameters: {'n_neighbors': 34, 'n_components': 13, 'min_dist': 0.0, 'min_cluster_size': 6, 'min_samples': 14, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 13/13 [00:00<00:00, 347.81it/s]

Trial 265: DBCV=0.450, CCC=0.744
[I 2025-12-22 20:26:31,902] Trial 265 finished with values: [0.7437999306277374, 0.4504296445401238] and parameters: {'n_neighbors': 23, 'n_components': 13, 'min_dist': 0.02, 'min_cluster_size': 39, 'min_samples': 4, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 301.36it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 266: DBCV=0.824, CCC=0.000
[I 2025-12-22 20:26:41,700] Trial 266 finished with values: [0.0, 0.8240331210053526] and parameters: {'n_neighbors': 18, 'n_components': 2, 'min_dist': 0.12, 'min_cluster_size': 15, 'min_samples': 14, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 299.83it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 267: DBCV=0.940, CCC=0.000
[I 2025-12-22 20:26:54,056] Trial 267 finished with values: [0.0, 0.9404197970075725] and parameters: {'n_neighbors': 36, 'n_components': 15, 'min_dist': 0.14, 'min_cluster_size': 44, 'min_samples': 2, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 309.45it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 268: DBCV=0.939, CCC=0.000
[I 2025-12-22 20:27:05,217] Trial 268 finished with values: [0.0, 0.9385415748257162] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.1, 'min_cluster_size': 41, 'min_samples': 2, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 276.30it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 269: DBCV=0.898, CCC=0.000
[I 2025-12-22 20:27:16,273] Trial 269 finished with values: [0.0, 0.8976780270029143] and parameters: {'n_neighbors': 14, 'n_components': 15, 'min_dist': 0.27, 'min_cluster_size': 37, 'min_samples': 18, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/84 [00:00<?, ?it/s]
 50%|█████     | 42/84 [00:00<00:00, 419.75it/s]
100%|██████████| 84/84 [00:00<00:00, 397.30it/s]

Trial 270: DBCV=0.667, CCC=0.471
[I 2025-12-22 20:27:26,030] Trial 270 finished with values: [0.4710150074438087, 0.6665678673359317] and parameters: {'n_neighbors': 11, 'n_components': 2, 'min_dist': 0.08, 'min_cluster_size': 2, 'min_samples': 8, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 305.71it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 271: DBCV=0.959, CCC=0.000
[I 2025-12-22 20:27:38,589] Trial 271 finished with values: [0.0, 0.9593777563800193] and parameters: {'n_neighbors': 41, 'n_components': 15, 'min_dist': 0.02, 'min_cluster_size': 6, 'min_samples': 13, 'cluster_selection_epsilon': 0.15}.

100%|██████████| 1/1 [00:00<00:00, 276.30it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 272: DBCV=0.947, CCC=0.000
[I 2025-12-22 20:27:49,953] Trial 272 finished with values: [0.0, 0.9466422537018198] and parameters: {'n_neighbors': 41, 'n_components': 7, 'min_dist': 0.03, 'min_cluster_size': 15, 'min_samples': 13, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 34/34 [00:00<00:00, 381.95it/s]

Trial 273: DBCV=0.517, CCC=0.526
[I 2025-12-22 20:27:59,253] Trial 273 finished with values: [0.5260404086683127, 0.5167321219603105] and parameters: {'n_neighbors': 11, 'n_components': 2, 'min_dist': 0.08, 'min_cluster_size': 19, 'min_samples': 9, 'cluster_selection_epsilon': 0.06}.

  0%|          | 0/91 [00:00<?, ?it/s]
 45%|████▌     | 41/91 [00:00<00:00, 408.76it/s]
100%|██████████| 91/91 [00:00<00:00, 385.66it/s]

Trial 274: DBCV=0.566, CCC=0.446
[I 2025-12-22 20:28:09,592] Trial 274 finished with values: [0.446018614859117, 0.5660332838197564] and parameters: {'n_neighbors': 20, 'n_components': 2, 'min_dist': 0.16, 'min_cluster_size': 2, 'min_samples': 6, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 276.69it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 275: DBCV=0.933, CCC=0.000
[I 2025-12-22 20:28:21,682] Trial 275 finished with values: [0.0, 0.9328741462990177] and parameters: {'n_neighbors': 29, 'n_components': 15, 'min_dist': 0.12, 'min_cluster_size': 15, 'min_samples': 6, 'cluster_selection_epsilon': 0.01}.

  0%|          | 0/45 [00:00<?, ?it/s]
100%|██████████| 45/45 [00:00<00:00, 374.17it/s]

Trial 276: DBCV=0.373, CCC=0.472
[I 2025-12-22 20:28:32,540] Trial 276 finished with values: [0.4720674990718318, 0.3732894642679489] and parameters: {'n_neighbors': 28, 'n_components': 8, 'min_dist': 0.05, 'min_cluster_size': 8, 'min_samples': 1, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 236.34it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 277: DBCV=0.941, CCC=0.000
[I 2025-12-22 20:28:44,697] Trial 277 finished with values: [0.0, 0.9413077514338963] and parameters: {'n_neighbors': 40, 'n_components': 14, 'min_dist': 0.02, 'min_cluster_size': 39, 'min_samples': 10, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 1/1 [00:00<00:00, 268.04it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 278: DBCV=0.936, CCC=0.000
[I 2025-12-22 20:28:56,653] Trial 278 finished with values: [0.0, 0.9361362180852908] and parameters: {'n_neighbors': 39, 'n_components': 13, 'min_dist': 0.17, 'min_cluster_size': 44, 'min_samples': 10, 'cluster_selection_epsilon': 0.15}.

  0%|          | 0/99 [00:00<?, ?it/s]
 41%|████▏     | 41/99 [00:00<00:00, 408.49it/s]
100%|██████████| 99/99 [00:00<00:00, 400.62it/s]

Trial 279: DBCV=0.627, CCC=0.461
[I 2025-12-22 20:29:06,979] Trial 279 finished with values: [0.4611681487604724, 0.6271375252173537] and parameters: {'n_neighbors': 10, 'n_components': 8, 'min_dist': 0.03, 'min_cluster_size': 6, 'min_samples': 4, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 275.42it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 280: DBCV=0.947, CCC=0.000
[I 2025-12-22 20:29:18,600] Trial 280 finished with values: [0.0, 0.9467853622552014] and parameters: {'n_neighbors': 30, 'n_components': 13, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 14, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 30/30 [00:00<00:00, 381.24it/s]

Trial 281: DBCV=0.366, CCC=0.608
[I 2025-12-22 20:29:29,756] Trial 281 finished with values: [0.608460263083004, 0.3659874596737922] and parameters: {'n_neighbors': 34, 'n_components': 10, 'min_dist': 0.01, 'min_cluster_size': 19, 'min_samples': 2, 'cluster_selection_epsilon': 0.05}.

  0%|          | 0/86 [00:00<?, ?it/s]
 48%|████▊     | 41/86 [00:00<00:00, 407.40it/s]
100%|██████████| 86/86 [00:00<00:00, 389.20it/s]

Trial 282: DBCV=0.623, CCC=0.427
[I 2025-12-22 20:29:38,778] Trial 282 finished with values: [0.42737233565959554, 0.6225157565716672] and parameters: {'n_neighbors': 4, 'n_components': 2, 'min_dist': 0.08, 'min_cluster_size': 2, 'min_samples': 9, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 33/33 [00:00<00:00, 403.03it/s]

Trial 283: DBCV=0.539, CCC=0.650
[I 2025-12-22 20:29:49,615] Trial 283 finished with values: [0.6499348367386748, 0.5388212541336233] and parameters: {'n_neighbors': 28, 'n_components': 7, 'min_dist': 0.02, 'min_cluster_size': 15, 'min_samples': 10, 'cluster_selection_epsilon': 0.04}.

  0%|          | 0/80 [00:00<?, ?it/s]
100%|██████████| 80/80 [00:00<00:00, 389.69it/s]

Trial 284: DBCV=0.618, CCC=0.462
[I 2025-12-22 20:29:59,835] Trial 284 finished with values: [0.4615758459490319, 0.6178993972645361] and parameters: {'n_neighbors': 11, 'n_components': 6, 'min_dist': 0.01, 'min_cluster_size': 6, 'min_samples': 6, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 12/12 [00:00<00:00, 381.22it/s]

Trial 285: DBCV=0.450, CCC=0.750
[I 2025-12-22 20:30:10,316] Trial 285 finished with values: [0.7499971125918372, 0.4502518346975092] and parameters: {'n_neighbors': 18, 'n_components': 11, 'min_dist': 0.03, 'min_cluster_size': 42, 'min_samples': 12, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 278.90it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 286: DBCV=0.892, CCC=0.000
[I 2025-12-22 20:30:20,442] Trial 286 finished with values: [0.0, 0.8916334088785894] and parameters: {'n_neighbors': 20, 'n_components': 4, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 11, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 16/16 [00:00<00:00, 362.72it/s]

Trial 287: DBCV=0.470, CCC=0.671
[I 2025-12-22 20:30:31,416] Trial 287 finished with values: [0.6714636347139723, 0.47025894885680236] and parameters: {'n_neighbors': 25, 'n_components': 12, 'min_dist': 0.02, 'min_cluster_size': 37, 'min_samples': 7, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 17/17 [00:00<00:00, 386.79it/s]

Trial 288: DBCV=0.293, CCC=0.798
[I 2025-12-22 20:30:41,858] Trial 288 finished with values: [0.7979147509055905, 0.2934478209733887] and parameters: {'n_neighbors': 24, 'n_components': 6, 'min_dist': 0.02, 'min_cluster_size': 35, 'min_samples': 3, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 4/4 [00:00<00:00, 270.87it/s]

Trial 289: DBCV=0.209, CCC=0.951
[I 2025-12-22 20:30:53,274] Trial 289 finished with values: [0.9510346687302897, 0.20859619065721383] and parameters: {'n_neighbors': 28, 'n_components': 13, 'min_dist': 0.01, 'min_cluster_size': 44, 'min_samples': 4, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 1/1 [00:00<00:00, 285.70it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 290: DBCV=0.889, CCC=0.000
[I 2025-12-22 20:31:03,702] Trial 290 finished with values: [0.0, 0.8891316733686226] and parameters: {'n_neighbors': 39, 'n_components': 2, 'min_dist': 0.02, 'min_cluster_size': 44, 'min_samples': 6, 'cluster_selection_epsilon': 0.27}.

  0%|          | 0/76 [00:00<?, ?it/s]
100%|██████████| 76/76 [00:00<00:00, 396.62it/s]

Trial 291: DBCV=0.378, CCC=0.423
[I 2025-12-22 20:31:15,440] Trial 291 finished with values: [0.4230439699986321, 0.3779787418648606] and parameters: {'n_neighbors': 41, 'n_components': 9, 'min_dist': 0.02, 'min_cluster_size': 6, 'min_samples': 1, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 1/1 [00:00<00:00, 281.08it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 292: DBCV=0.883, CCC=0.000
[I 2025-12-22 20:31:25,325] Trial 292 finished with values: [0.0, 0.8826984743886789] and parameters: {'n_neighbors': 11, 'n_components': 7, 'min_dist': 0.21, 'min_cluster_size': 6, 'min_samples': 12, 'cluster_selection_epsilon': 0.04}.

  0%|          | 0/54 [00:00<?, ?it/s]
100%|██████████| 54/54 [00:00<00:00, 378.77it/s]

Trial 293: DBCV=0.615, CCC=0.511
[I 2025-12-22 20:31:36,349] Trial 293 finished with values: [0.5108817367197613, 0.6147098488091312] and parameters: {'n_neighbors': 28, 'n_components': 7, 'min_dist': 0.05, 'min_cluster_size': 8, 'min_samples': 7, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 12/12 [00:00<00:00, 344.60it/s]

Trial 294: DBCV=0.331, CCC=0.740
[I 2025-12-22 20:31:47,190] Trial 294 finished with values: [0.7396493379042787, 0.33086150160938177] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.02, 'min_cluster_size': 41, 'min_samples': 2, 'cluster_selection_epsilon': 0.01}.

  0%|          | 0/51 [00:00<?, ?it/s]
100%|██████████| 51/51 [00:00<00:00, 378.21it/s]

Trial 295: DBCV=0.652, CCC=0.483
[I 2025-12-22 20:31:56,260] Trial 295 finished with values: [0.483323254092097, 0.652167020974448] and parameters: {'n_neighbors': 4, 'n_components': 11, 'min_dist': 0.01, 'min_cluster_size': 2, 'min_samples': 12, 'cluster_selection_epsilon': 0.06}.

  0%|          | 0/55 [00:00<?, ?it/s]
100%|██████████| 55/55 [00:00<00:00, 379.96it/s]

Trial 296: DBCV=0.549, CCC=0.515
[I 2025-12-22 20:32:07,559] Trial 296 finished with values: [0.5146249176303233, 0.5492935555868489] and parameters: {'n_neighbors': 41, 'n_components': 8, 'min_dist': 0.03, 'min_cluster_size': 6, 'min_samples': 8, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 16/16 [00:00<00:00, 356.47it/s]

Trial 297: DBCV=0.374, CCC=0.743
[I 2025-12-22 20:32:17,047] Trial 297 finished with values: [0.7427225987378246, 0.37352560752543057] and parameters: {'n_neighbors': 7, 'n_components': 12, 'min_dist': 0.02, 'min_cluster_size': 37, 'min_samples': 13, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 33/33 [00:00<00:00, 387.32it/s]

Trial 298: DBCV=0.535, CCC=0.503
[I 2025-12-22 20:32:27,603] Trial 298 finished with values: [0.5031335818718594, 0.5354723504249896] and parameters: {'n_neighbors': 11, 'n_components': 15, 'min_dist': 0.02, 'min_cluster_size': 19, 'min_samples': 10, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 1/1 [00:00<00:00, 279.64it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 299: DBCV=0.884, CCC=0.000
[I 2025-12-22 20:32:38,054] Trial 299 finished with values: [0.0, 0.8841394054719498] and parameters: {'n_neighbors': 11, 'n_components': 14, 'min_dist': 0.14, 'min_cluster_size': 44, 'min_samples': 14, 'cluster_selection_epsilon': 0.24}.

In [7]:
df_descriptions = study.trials_dataframe()
df_descriptions.head()

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_cluster_selection_epsilon,params_min_cluster_size,params_min_dist,params_min_samples,params_n_components,params_n_neighbors,user_attrs_ccc_score,user_attrs_dbcv_score,user_attrs_n_clusters,user_attrs_outlier_ratio,system_attrs_NSGAIISampler:generation,state
0,0,0.000000,0.865779,2025-12-22 19:37:54.263051,2025-12-22 19:38:11.137953,0 days 00:00:16.874902,0.05,41,0.19,3,7,18,0.000000,0.865779,2,0.000000,0,COMPLETE
1,1,0.000000,0.838539,2025-12-22 19:38:11.139397,2025-12-22 19:38:20.830485,0 days 00:00:09.691088,0.01,42,0.14,7,2,17,0.000000,0.838539,2,0.000000,0,COMPLETE
2,2,0.000000,0.933301,2025-12-22 19:38:20.832546,2025-12-22 19:38:32.132921,0 days 00:00:11.300375,0.12,49,0.08,2,11,30,0.000000,0.933301,2,0.000000,0,COMPLETE
3,3,0.000000,0.935671,2025-12-22 19:38:32.134287,2025-12-22 19:38:43.534845,0 days 00:00:11.400558,0.05,39,0.11,17,9,41,0.000000,0.935671,2,0.000000,0,COMPLETE
4,4,0.415777,0.432808,2025-12-22 19:38:43.536584,2025-12-22 19:38:54.600035,0 days 00:00:11.063451,0.09,5,0.20,2,8,17,0.415777,0.432808,114,0.170149,0,COMPLETE

In [8]:
import joblib
# Save to a file
joblib.dump(study, "02_251222_multi_clusterdata_descriptions_Phi-4-mini-instruct.pkl")

['02_251222_multi_clusterdata_descriptions_Phi-4-mini-instruct.pkl']

In [9]:
df_descriptions.to_csv("02_251222_multi_clusterdata_descriptions_Phi-4-mini-instruct.csv", index=False)

In [10]:
import optuna.visualization as vis

fig = vis.plot_pareto_front(
    study,
    target_names=["CCC Score", "Number of Clusters"], # Names for Obj 0 and Obj 1
    include_dominated_trials=True  # Set to True to see all points, not just the best frontier
)

fig.update_layout(width=600, height=500)
fig.show()