Run the following command in the terminal:

sbatch --gpus=1 --gres=gpumem:10g --time=05:00:00 --mem-per-cpu=32g --wrap="jupyter nbconvert --to notebook --execute 02_251218_optimizing_number_of_clusters_Apertus-8B-Instruct.ipynb --inplace"

In [1]:
import os
import json
import pandas as pd

directory_path = "./251030_generated_descriptions_GPT5-nano"
data_list = []
# Iterate through all files in the directory
for filename in os.listdir(directory_path):
    if filename.endswith('.json'):
        file_path = os.path.join(directory_path, filename)
        with open(file_path, 'r', encoding='utf-8') as file:
            try:
                data = json.load(file)
                # Ensure it's a dict with 4 key-value pairs
                if isinstance(data, dict):
                    if data["data_point"] == "":
                        print(f"Skipping {filename}, data point empty")
                    
                        continue
                    data_list.append(data)
                else:
                    print(f"Skipping {filename}")
            except json.JSONDecodeError:
                print(f"Skipping {filename}: invalid JSON format.")
                
# Convert list of dicts to DataFrame
df = pd.DataFrame(data_list)
df.tail()

,question,original_source,data_group,data_point,reference_1,reference_2,description,references
2005,What is the meaning of eco-toxicity in relatio...,CPR 2024.pdf,essential environmental characteristics,eco-toxicity,CPR 2024.pdf,BAMB 2019.pdf,Eco-toxicity in relation to essential environm...,[{'text': 'ANNEX II Predetermined environmenta...
2006,What is the meaning of freshwater in relation ...,CPR 2024.pdf,essential environmental characteristics,freshwater,CPR 2024.pdf,CPR 2024.pdf,Eutrophication aquatic freshwater refers to on...,[{'text': 'ANNEX II Predetermined environmenta...
2007,What is the meaning of human toxicity cancerog...,CPR 2024.pdf,essential environmental characteristics,human toxicity cancerogenic,CPR 2024.pdf,BAMB 2019.pdf,Human toxicity cancerogenic in relation to ess...,[{'text': 'ANNEX II Predetermined environmenta...
2008,What is the meaning of human toxicity non-canc...,CPR 2024.pdf,essential environmental characteristics,human toxicity non-cancerogenic,CPR 2024.pdf,BAMB 2019.pdf,Human toxicity non-cancerogenic in relation to...,[{'text': 'ANNEX II Predetermined environmenta...
2009,What is the meaning of land use related impact...,CPR 2024.pdf,essential environmental characteristics,land use related impacts,CPR 2024.pdf,Kebede 2024.pdf,Land use related impacts in relation to essent...,[{'text': 'ANNEX II Predetermined environmenta...

In [2]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import make_scorer
from sentence_transformers import SentenceTransformer


model = SentenceTransformer('./cluster/scratch/svangelova')
description_embeddings = model.encode(df["description"])

In [3]:
import numpy as np
import pandas as pd
import logging
from collections.abc import Iterable
from scipy.sparse import csr_matrix
from scipy.spatial.distance import squareform
from typing import Optional, Union, Tuple


def select_topic_representation(
    ctfidf_embeddings,
    embeddings,
    use_ctfidf: bool = True,
    output_ndarray: bool = False,
):
    """Select the topic representation.

    Arguments:
        ctfidf_embeddings: The c-TF-IDF embedding matrix
        embeddings: The topic embedding matrix
        use_ctfidf: Whether to use the c-TF-IDF representation. If False, topics embedding representation is used, if it
                    exists. Default is True.
        output_ndarray: Whether to convert the selected representation into ndarray
    Raises
        ValueError:
            - If no topic representation was found
            - If c-TF-IDF embeddings are not a numpy array or a scipy.sparse.csr_matrix

    Returns:
        The selected topic representation and a boolean indicating whether it is c-TF-IDF.
    """

    def to_ndarray(array: Union[np.ndarray, csr_matrix]) -> np.ndarray:
        if isinstance(array, csr_matrix):
            return array.toarray()
        return array
    if use_ctfidf:
        if ctfidf_embeddings is None:
            repr_, ctfidf_used = embeddings, False
        else:
            repr_, ctfidf_used = ctfidf_embeddings, True
    else:
        if embeddings is None:
            repr_, ctfidf_used = ctfidf_embeddings, True
        else:
            repr_, ctfidf_used = embeddings, False

    return to_ndarray(repr_) if output_ndarray else repr_, ctfidf_used


def validate_distance_matrix(X, n_samples):
    """Validate the distance matrix and convert it to a condensed distance matrix
    if necessary.

    A valid distance matrix is either a square matrix of shape (n_samples, n_samples)
    with zeros on the diagonal and non-negative values or condensed distance matrix
    of shape (n_samples * (n_samples - 1) / 2,) containing the upper triangular of the
    distance matrix.

    Arguments:
        X: Distance matrix to validate.
        n_samples: Number of samples in the dataset.

    Returns:
        X: Validated distance matrix.

    Raises:
        ValueError: If the distance matrix is not valid.
    """
    # Make sure it is the 1-D condensed distance matrix with zeros on the diagonal
    s = X.shape
    if len(s) == 1:
        # check it has correct size
        n = s[0]
        if n != (n_samples * (n_samples - 1) / 2):
            raise ValueError("The condensed distance matrix must have " "shape (n*(n-1)/2,).")
    elif len(s) == 2:
        # check it has correct size
        if (s[0] != n_samples) or (s[1] != n_samples):
            raise ValueError("The distance matrix must be of shape " "(n, n) where n is the number of samples.")
        # force zero diagonal and convert to condensed
        np.fill_diagonal(X, 0)
        X = squareform(X)
    else:
        raise ValueError(
            "The distance matrix must be either a 1-D condensed "
            "distance matrix of shape (n*(n-1)/2,) or a "
            "2-D square distance matrix of shape (n, n)."
            "where n is the number of documents."
            "Got a distance matrix of shape %s" % str(s)
        )

    # Make sure its entries are non-negative
    if np.any(X < 0):
        raise ValueError("Distance matrix cannot contain negative values.")

    return X

In [4]:
import optuna
import hdbscan
import numpy as np
from umap import UMAP
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.vectorizers import ClassTfidfTransformer
from sklearn.datasets import fetch_20newsgroups
from scipy.cluster import hierarchy as sch
from scipy.cluster.hierarchy import linkage, cophenet
from scipy.spatial.distance import pdist
from hdbscan.validity import validity_index
from sklearn.metrics.pairwise import cosine_similarity

def calculate_ccc(topic_model, docs):
    # Hierarchical topics
    linkage_function = lambda x: sch.linkage(x, "ward", optimal_ordering=True)
    _distance_function = lambda x: 1 - cosine_similarity(x)
    
    hierarchical_topics = topic_model.hierarchical_topics(docs, 
                                                          linkage_function=linkage_function, 
                                                          distance_function=_distance_function, 
                                                          use_ctfidf=True)
    
    # Select topic embeddings
    use_ctfidf = True

    # Calculate distance
    embeddings = select_topic_representation(topic_model.c_tf_idf_, topic_model.topic_embeddings_, use_ctfidf)[0][
        topic_model._outliers :
    ]
    distance_function = lambda x: validate_distance_matrix(_distance_function(x), embeddings.shape[0])
    
    dists = distance_function(embeddings)
    linkage_matrix = linkage_function(dists)

    ccc_score, _ = cophenet(linkage_matrix, dists)

    if np.isnan(ccc_score):
        return 0.0

    return ccc_score


ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

def objective(trial, docs, embeddings):
    # --- Hyperparameters to Optimize ---
    
    # UMAP Parameters
    n_neighbors = trial.suggest_int('n_neighbors', 2, 50)
    n_components = trial.suggest_int('n_components', 2, 15)
    min_dist = trial.suggest_float("min_dist", 0.0, 0.3, step=0.01)
    
    # HDBSCAN Parameters
    min_cluster_size = trial.suggest_int('min_cluster_size', 2, 50)
    min_samples = trial.suggest_int('min_samples', 1, 20)
    cluster_selection_epsilon = trial.suggest_float("cluster_selection_epsilon", 0.0, 0.3, step=0.01)
    
    # --- Model Initialization ---
    
    umap_model = UMAP(
        n_neighbors=n_neighbors,
        n_components=n_components,
        min_dist=min_dist,
        metric='cosine',
        random_state=42,
        n_jobs=1 #important for reproducability
    )

    
    hdbscan_model = hdbscan.HDBSCAN(
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        cluster_selection_epsilon=cluster_selection_epsilon,
        metric="euclidean",  
        cluster_selection_method='eom'
    )
    
    topic_model = BERTopic(
        hdbscan_model=hdbscan_model,
        vectorizer_model=CountVectorizer(stop_words='english'),
        ctfidf_model=ctfidf_model, 
        umap_model=umap_model,
        calculate_probabilities=False
        )

    topic_model.fit(docs, embeddings)

    labels = topic_model.get_document_info(docs).Topic
    mask = labels != -1
    n_clusters = len(np.unique(labels[mask]))
    emb_umap = topic_model.umap_model.embedding_
    
    emb_masked = np.ascontiguousarray(emb_umap[mask], dtype=np.float64)
    labels_masked = np.ascontiguousarray(labels[mask], dtype=np.int32)

    dbcv_score = validity_index(emb_masked, labels_masked, metric='euclidean')
    ccc_score = calculate_ccc(topic_model, docs)

    
    # logging for visibility
    print(f"Trial {trial.number}: DBCV={dbcv_score:.3f}, CCC={ccc_score:.3f}")

    # ---- Outlier ratio (fraction of points labeled -1)
    outlier_ratio =  outlier_ratio = np.mean(labels == -1)

    # Store the custom metrics in Optuna
    trial.set_user_attr("dbcv_score", dbcv_score)
    trial.set_user_attr("ccc_score", ccc_score)
    trial.set_user_attr("outlier_ratio", outlier_ratio)
    trial.set_user_attr("n_clusters", n_clusters)

    # Create directory if it doesn't exist
    os.makedirs("optuna_models/GPT5-nano", exist_ok=True)
    
    # Save model (safely serialization)
    model_name = f"optuna_models/GPT5-nano/251222_trial_{trial.number}_model"
    topic_model.save(model_name, serialization="safetensors", save_ctfidf=True)

    return ccc_score, dbcv_score

In [5]:
# 2. Run Multi-Objective Optimization
# Note: 'directions' list matches the return tuple order (DBCV, CCC)
study = optuna.create_study(directions=['maximize', 'maximize'])

study.optimize(lambda trial: objective(trial, df["description"], description_embeddings), n_trials=300, show_progress_bar=True)

[I 2025-12-22 19:35:36,841] A new study created in memory with name: no-name-4febe27a-6167-4dec-b521-1854d0dfc847

  0%|          | 0/300 [00:00<?, ?it/s]

100%|██████████| 12/12 [00:00<00:00, 386.52it/s]

Trial 0: DBCV=0.501, CCC=0.523
[I 2025-12-22 19:35:55,056] Trial 0 finished with values: [0.5229477740854445, 0.5006954176258589] and parameters: {'n_neighbors': 42, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 28, 'min_samples': 17, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 1/1 [00:00<00:00, 284.09it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 1: DBCV=-0.456, CCC=0.000
[I 2025-12-22 19:36:05,322] Trial 1 finished with values: [0.0, -0.4558774357934434] and parameters: {'n_neighbors': 42, 'n_components': 2, 'min_dist': 0.2, 'min_cluster_size': 38, 'min_samples': 2, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 311.80it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 2: DBCV=0.455, CCC=0.000
[I 2025-12-22 19:36:15,839] Trial 2 finished with values: [0.0, 0.45531165298433485] and parameters: {'n_neighbors': 17, 'n_components': 12, 'min_dist': 0.21, 'min_cluster_size': 21, 'min_samples': 17, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 10/10 [00:00<00:00, 353.46it/s]

Trial 3: DBCV=0.261, CCC=0.554
[I 2025-12-22 19:36:25,831] Trial 3 finished with values: [0.5541940043320613, 0.26108480267696993] and parameters: {'n_neighbors': 34, 'n_components': 3, 'min_dist': 0.29, 'min_cluster_size': 38, 'min_samples': 17, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 11/11 [00:00<00:00, 329.39it/s]

Trial 4: DBCV=0.039, CCC=0.667
[I 2025-12-22 19:36:36,448] Trial 4 finished with values: [0.6668327420057855, 0.03944930463116496] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.03, 'min_cluster_size': 44, 'min_samples': 2, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 26/26 [00:00<00:00, 390.48it/s]

Trial 5: DBCV=0.258, CCC=0.513
[I 2025-12-22 19:36:47,126] Trial 5 finished with values: [0.5134429566486632, 0.2582753228550994] and parameters: {'n_neighbors': 33, 'n_components': 8, 'min_dist': 0.26, 'min_cluster_size': 24, 'min_samples': 3, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 13/13 [00:00<00:00, 361.36it/s]

Trial 6: DBCV=0.083, CCC=0.592
[I 2025-12-22 19:36:56,955] Trial 6 finished with values: [0.5919192972647154, 0.08251946198557131] and parameters: {'n_neighbors': 26, 'n_components': 3, 'min_dist': 0.08, 'min_cluster_size': 31, 'min_samples': 4, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 15/15 [00:00<00:00, 397.11it/s]

Trial 7: DBCV=0.188, CCC=0.556
[I 2025-12-22 19:37:06,982] Trial 7 finished with values: [0.5555764975053009, 0.18803082590433004] and parameters: {'n_neighbors': 21, 'n_components': 6, 'min_dist': 0.06, 'min_cluster_size': 31, 'min_samples': 5, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 10/10 [00:00<00:00, 352.47it/s]

Trial 8: DBCV=0.056, CCC=0.663
[I 2025-12-22 19:37:18,356] Trial 8 finished with values: [0.6626211970288176, 0.055878257341617] and parameters: {'n_neighbors': 25, 'n_components': 15, 'min_dist': 0.24, 'min_cluster_size': 44, 'min_samples': 2, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 7/7 [00:00<00:00, 298.95it/s]

Trial 9: DBCV=0.105, CCC=0.567
[I 2025-12-22 19:37:29,311] Trial 9 finished with values: [0.5666865672488719, 0.1049835412691129] and parameters: {'n_neighbors': 49, 'n_components': 6, 'min_dist': 0.18, 'min_cluster_size': 42, 'min_samples': 7, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 285.89it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 10: DBCV=0.386, CCC=0.000
[I 2025-12-22 19:37:39,509] Trial 10 finished with values: [0.0, 0.38559030011643314] and parameters: {'n_neighbors': 18, 'n_components': 8, 'min_dist': 0.06, 'min_cluster_size': 20, 'min_samples': 13, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 1/1 [00:00<00:00, 280.05it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 11: DBCV=0.113, CCC=0.000
[I 2025-12-22 19:37:50,263] Trial 11 finished with values: [0.0, 0.11339354971686397] and parameters: {'n_neighbors': 38, 'n_components': 5, 'min_dist': 0.14, 'min_cluster_size': 21, 'min_samples': 17, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 19/19 [00:00<00:00, 379.25it/s]

Trial 12: DBCV=0.289, CCC=0.562
[I 2025-12-22 19:38:00,016] Trial 12 finished with values: [0.5618006819037334, 0.28930289433046186] and parameters: {'n_neighbors': 18, 'n_components': 5, 'min_dist': 0.23, 'min_cluster_size': 25, 'min_samples': 10, 'cluster_selection_epsilon': 0.07}.

  0%|          | 0/123 [00:00<?, ?it/s]
 34%|███▍      | 42/123 [00:00<00:00, 415.28it/s]
100%|██████████| 123/123 [00:00<00:00, 393.61it/s][A

Trial 13: DBCV=0.386, CCC=0.488
[I 2025-12-22 19:38:11,799] Trial 13 finished with values: [0.48765767397926174, 0.3858392693085851] and parameters: {'n_neighbors': 24, 'n_components': 12, 'min_dist': 0.19, 'min_cluster_size': 5, 'min_samples': 2, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 34/34 [00:00<00:00, 401.14it/s]

Trial 14: DBCV=0.559, CCC=0.535
[I 2025-12-22 19:38:21,645] Trial 14 finished with values: [0.5354661691224221, 0.5591076901347867] and parameters: {'n_neighbors': 24, 'n_components': 4, 'min_dist': 0.21, 'min_cluster_size': 3, 'min_samples': 15, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 12/12 [00:00<00:00, 358.65it/s]

Trial 15: DBCV=0.283, CCC=0.604
[I 2025-12-22 19:38:32,047] Trial 15 finished with values: [0.6042046822811801, 0.2830228976724522] and parameters: {'n_neighbors': 48, 'n_components': 3, 'min_dist': 0.05, 'min_cluster_size': 46, 'min_samples': 6, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 2/2 [00:00<00:00, 218.20it/s]

Trial 16: DBCV=-0.213, CCC=0.827
[I 2025-12-22 19:38:42,102] Trial 16 finished with values: [0.8269448086205721, -0.21283075950423694] and parameters: {'n_neighbors': 31, 'n_components': 2, 'min_dist': 0.06, 'min_cluster_size': 14, 'min_samples': 14, 'cluster_selection_epsilon': 0.22}.

  0%|          | 0/41 [00:00<?, ?it/s]
100%|██████████| 41/41 [00:00<00:00, 399.14it/s]

Trial 17: DBCV=0.363, CCC=0.502
[I 2025-12-22 19:38:52,305] Trial 17 finished with values: [0.5015312935891324, 0.36320278545840323] and parameters: {'n_neighbors': 23, 'n_components': 6, 'min_dist': 0.23, 'min_cluster_size': 12, 'min_samples': 5, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 1/1 [00:00<00:00, 342.92it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 18: DBCV=-0.267, CCC=0.000
[I 2025-12-22 19:39:03,119] Trial 18 finished with values: [0.0, -0.2665048897112595] and parameters: {'n_neighbors': 48, 'n_components': 4, 'min_dist': 0.28, 'min_cluster_size': 21, 'min_samples': 10, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 9/9 [00:00<00:00, 399.48it/s]

Trial 19: DBCV=0.367, CCC=0.728
[I 2025-12-22 19:39:13,029] Trial 19 finished with values: [0.7276306510625382, 0.3672567615186126] and parameters: {'n_neighbors': 22, 'n_components': 6, 'min_dist': 0.2, 'min_cluster_size': 47, 'min_samples': 11, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 2/2 [00:00<00:00, 338.10it/s]

Trial 20: DBCV=-0.588, CCC=0.996
[I 2025-12-22 19:39:21,633] Trial 20 finished with values: [0.9962341298325342, -0.5883825625199656] and parameters: {'n_neighbors': 3, 'n_components': 7, 'min_dist': 0.26, 'min_cluster_size': 20, 'min_samples': 18, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 1/1 [00:00<00:00, 317.17it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 21: DBCV=0.311, CCC=0.000
[I 2025-12-22 19:39:32,640] Trial 21 finished with values: [0.0, 0.31096901887685197] and parameters: {'n_neighbors': 19, 'n_components': 14, 'min_dist': 0.03, 'min_cluster_size': 23, 'min_samples': 17, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 280.99it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 22: DBCV=0.394, CCC=0.000
[I 2025-12-22 19:39:44,001] Trial 22 finished with values: [0.0, 0.39399602700748737] and parameters: {'n_neighbors': 25, 'n_components': 14, 'min_dist': 0.12, 'min_cluster_size': 23, 'min_samples': 3, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 16/16 [00:00<00:00, 407.93it/s]

Trial 23: DBCV=0.227, CCC=0.558
[I 2025-12-22 19:39:54,557] Trial 23 finished with values: [0.5580071750737543, 0.22705969678410032] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.16, 'min_cluster_size': 27, 'min_samples': 7, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 15/15 [00:00<00:00, 371.22it/s]

Trial 24: DBCV=0.430, CCC=0.624
[I 2025-12-22 19:40:04,254] Trial 24 finished with values: [0.6237101683228657, 0.4297656211065318] and parameters: {'n_neighbors': 14, 'n_components': 7, 'min_dist': 0.09, 'min_cluster_size': 38, 'min_samples': 9, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 2/2 [00:00<00:00, 330.20it/s]

Trial 25: DBCV=0.620, CCC=0.827
[I 2025-12-22 19:40:14,804] Trial 25 finished with values: [0.8269448086205721, 0.6198184527308173] and parameters: {'n_neighbors': 18, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 12, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 1/1 [00:00<00:00, 316.29it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 26: DBCV=0.376, CCC=0.000
[I 2025-12-22 19:40:25,001] Trial 26 finished with values: [0.0, 0.3756502150264349] and parameters: {'n_neighbors': 19, 'n_components': 6, 'min_dist': 0.13, 'min_cluster_size': 23, 'min_samples': 16, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 1/1 [00:00<00:00, 307.50it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 27: DBCV=0.417, CCC=0.000
[I 2025-12-22 19:40:35,041] Trial 27 finished with values: [0.0, 0.4168959344350563] and parameters: {'n_neighbors': 19, 'n_components': 5, 'min_dist': 0.14, 'min_cluster_size': 22, 'min_samples': 18, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 40/40 [00:00<00:00, 404.62it/s]

Trial 28: DBCV=0.476, CCC=0.524
[I 2025-12-22 19:40:47,159] Trial 28 finished with values: [0.5241008897737635, 0.47644588090134754] and parameters: {'n_neighbors': 46, 'n_components': 14, 'min_dist': 0.09, 'min_cluster_size': 8, 'min_samples': 8, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 1/1 [00:00<00:00, 342.64it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 29: DBCV=0.107, CCC=0.000
[I 2025-12-22 19:40:57,029] Trial 29 finished with values: [0.0, 0.10672113244547] and parameters: {'n_neighbors': 13, 'n_components': 8, 'min_dist': 0.27, 'min_cluster_size': 19, 'min_samples': 9, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 1/1 [00:00<00:00, 329.27it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 30: DBCV=-0.266, CCC=0.000
[I 2025-12-22 19:41:06,046] Trial 30 finished with values: [0.0, -0.26588694244362754] and parameters: {'n_neighbors': 8, 'n_components': 3, 'min_dist': 0.24, 'min_cluster_size': 24, 'min_samples': 20, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 14/14 [00:00<00:00, 408.55it/s]

Trial 31: DBCV=0.064, CCC=0.574
[I 2025-12-22 19:41:16,561] Trial 31 finished with values: [0.5739708680533809, 0.06404944357140889] and parameters: {'n_neighbors': 33, 'n_components': 6, 'min_dist': 0.14, 'min_cluster_size': 38, 'min_samples': 1, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 10/10 [00:00<00:00, 400.77it/s]

Trial 32: DBCV=0.415, CCC=0.497
[I 2025-12-22 19:41:28,582] Trial 32 finished with values: [0.49683006612235076, 0.41527659598670374] and parameters: {'n_neighbors': 49, 'n_components': 14, 'min_dist': 0.06, 'min_cluster_size': 37, 'min_samples': 8, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 20/20 [00:00<00:00, 383.29it/s]

Trial 33: DBCV=0.282, CCC=0.551
[I 2025-12-22 19:41:38,369] Trial 33 finished with values: [0.5509913784699382, 0.2818559650735081] and parameters: {'n_neighbors': 14, 'n_components': 7, 'min_dist': 0.04, 'min_cluster_size': 35, 'min_samples': 4, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 6/6 [00:00<00:00, 379.03it/s]

Trial 34: DBCV=0.130, CCC=0.829
[I 2025-12-22 19:41:49,324] Trial 34 finished with values: [0.8288747580619553, 0.130336394484201] and parameters: {'n_neighbors': 47, 'n_components': 8, 'min_dist': 0.23, 'min_cluster_size': 28, 'min_samples': 12, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 11/11 [00:00<00:00, 337.82it/s]

Trial 35: DBCV=0.221, CCC=0.606
[I 2025-12-22 19:41:58,304] Trial 35 finished with values: [0.6058210839331477, 0.2207635230508129] and parameters: {'n_neighbors': 11, 'n_components': 3, 'min_dist': 0.27, 'min_cluster_size': 47, 'min_samples': 16, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 12/12 [00:00<00:00, 404.26it/s]

Trial 36: DBCV=0.135, CCC=0.651
[I 2025-12-22 19:42:08,869] Trial 36 finished with values: [0.6506261127947309, 0.13549090778189662] and parameters: {'n_neighbors': 28, 'n_components': 10, 'min_dist': 0.23, 'min_cluster_size': 49, 'min_samples': 1, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 11/11 [00:00<00:00, 403.74it/s]

Trial 37: DBCV=0.199, CCC=0.576
[I 2025-12-22 19:42:19,333] Trial 37 finished with values: [0.5761271244245975, 0.1986989962983741] and parameters: {'n_neighbors': 31, 'n_components': 8, 'min_dist': 0.22, 'min_cluster_size': 34, 'min_samples': 6, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 12/12 [00:00<00:00, 406.56it/s]

Trial 38: DBCV=0.354, CCC=0.534
[I 2025-12-22 19:42:29,399] Trial 38 finished with values: [0.5341428004990983, 0.35383517281102495] and parameters: {'n_neighbors': 32, 'n_components': 3, 'min_dist': 0.05, 'min_cluster_size': 36, 'min_samples': 17, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 24/24 [00:00<00:00, 387.89it/s]

Trial 39: DBCV=0.454, CCC=0.572
[I 2025-12-22 19:42:39,592] Trial 39 finished with values: [0.5717842193167653, 0.45437183990853636] and parameters: {'n_neighbors': 12, 'n_components': 14, 'min_dist': 0.06, 'min_cluster_size': 26, 'min_samples': 6, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 1/1 [00:00<00:00, 311.94it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 40: DBCV=0.372, CCC=0.000
[I 2025-12-22 19:42:48,937] Trial 40 finished with values: [0.0, 0.3722088232351835] and parameters: {'n_neighbors': 9, 'n_components': 5, 'min_dist': 0.09, 'min_cluster_size': 33, 'min_samples': 20, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 8/8 [00:00<00:00, 397.75it/s]

Trial 41: DBCV=0.444, CCC=0.536
[I 2025-12-22 19:42:58,514] Trial 41 finished with values: [0.5358978275472829, 0.44412342317464004] and parameters: {'n_neighbors': 12, 'n_components': 9, 'min_dist': 0.23, 'min_cluster_size': 42, 'min_samples': 16, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 223.58it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 42: DBCV=0.195, CCC=0.000
[I 2025-12-22 19:43:08,857] Trial 42 finished with values: [0.0, 0.19459486800532566] and parameters: {'n_neighbors': 28, 'n_components': 4, 'min_dist': 0.09, 'min_cluster_size': 17, 'min_samples': 17, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 11/11 [00:00<00:00, 397.60it/s]

Trial 43: DBCV=0.206, CCC=0.576
[I 2025-12-22 19:43:20,436] Trial 43 finished with values: [0.575841432785752, 0.20595295864533442] and parameters: {'n_neighbors': 42, 'n_components': 13, 'min_dist': 0.18, 'min_cluster_size': 36, 'min_samples': 4, 'cluster_selection_epsilon': 0.3}.

  0%|          | 0/47 [00:00<?, ?it/s]
100%|██████████| 47/47 [00:00<00:00, 380.62it/s]

Trial 44: DBCV=0.578, CCC=0.483
[I 2025-12-22 19:43:30,834] Trial 44 finished with values: [0.48275398610934434, 0.5778649190526197] and parameters: {'n_neighbors': 15, 'n_components': 12, 'min_dist': 0.0, 'min_cluster_size': 12, 'min_samples': 11, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 13/13 [00:00<00:00, 366.47it/s]

Trial 45: DBCV=0.479, CCC=0.597
[I 2025-12-22 19:43:41,460] Trial 45 finished with values: [0.596511665512992, 0.47885287905104107] and parameters: {'n_neighbors': 23, 'n_components': 12, 'min_dist': 0.19, 'min_cluster_size': 35, 'min_samples': 16, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 13/13 [00:00<00:00, 350.79it/s]

Trial 46: DBCV=0.419, CCC=0.582
[I 2025-12-22 19:43:52,688] Trial 46 finished with values: [0.5820536213498491, 0.4188256533195237] and parameters: {'n_neighbors': 31, 'n_components': 13, 'min_dist': 0.24, 'min_cluster_size': 32, 'min_samples': 10, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 285.42it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 47: DBCV=0.546, CCC=0.000
[I 2025-12-22 19:44:03,225] Trial 47 finished with values: [0.0, 0.5455092165232622] and parameters: {'n_neighbors': 24, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 23, 'min_samples': 14, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 1/1 [00:00<00:00, 283.28it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 48: DBCV=0.486, CCC=0.000
[I 2025-12-22 19:44:13,746] Trial 48 finished with values: [0.0, 0.4860855930057795] and parameters: {'n_neighbors': 13, 'n_components': 14, 'min_dist': 0.29, 'min_cluster_size': 14, 'min_samples': 9, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 30/30 [00:00<00:00, 396.96it/s]

Trial 49: DBCV=0.427, CCC=0.551
[I 2025-12-22 19:44:23,546] Trial 49 finished with values: [0.5513380904203965, 0.4269690522107388] and parameters: {'n_neighbors': 7, 'n_components': 15, 'min_dist': 0.08, 'min_cluster_size': 20, 'min_samples': 7, 'cluster_selection_epsilon': 0.05}.

  0%|          | 0/80 [00:00<?, ?it/s]
100%|██████████| 80/80 [00:00<00:00, 397.49it/s]

Trial 50: DBCV=0.589, CCC=0.546
[I 2025-12-22 19:44:33,604] Trial 50 finished with values: [0.5461910602747855, 0.5892781506931422] and parameters: {'n_neighbors': 12, 'n_components': 8, 'min_dist': 0.06, 'min_cluster_size': 6, 'min_samples': 7, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 13/13 [00:00<00:00, 361.76it/s]

Trial 51: DBCV=0.487, CCC=0.621
[I 2025-12-22 19:44:44,804] Trial 51 finished with values: [0.6211109212127164, 0.4867399218808389] and parameters: {'n_neighbors': 34, 'n_components': 12, 'min_dist': 0.19, 'min_cluster_size': 27, 'min_samples': 16, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 2/2 [00:00<00:00, 316.29it/s]

Trial 52: DBCV=0.382, CCC=0.824
[I 2025-12-22 19:44:56,823] Trial 52 finished with values: [0.8237886340582232, 0.38186986523611743] and parameters: {'n_neighbors': 31, 'n_components': 15, 'min_dist': 0.21, 'min_cluster_size': 14, 'min_samples': 15, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 8/8 [00:00<00:00, 388.18it/s]

Trial 53: DBCV=0.358, CCC=0.725
[I 2025-12-22 19:45:07,494] Trial 53 finished with values: [0.7254130140129472, 0.35811814342151155] and parameters: {'n_neighbors': 24, 'n_components': 12, 'min_dist': 0.3, 'min_cluster_size': 41, 'min_samples': 16, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 11/11 [00:00<00:00, 395.47it/s]

Trial 54: DBCV=0.254, CCC=0.475
[I 2025-12-22 19:45:18,823] Trial 54 finished with values: [0.474707301593453, 0.253751337151222] and parameters: {'n_neighbors': 28, 'n_components': 14, 'min_dist': 0.23, 'min_cluster_size': 39, 'min_samples': 1, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 1/1 [00:00<00:00, 285.17it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 55: DBCV=0.228, CCC=0.000
[I 2025-12-22 19:45:29,428] Trial 55 finished with values: [0.0, 0.22828904561662558] and parameters: {'n_neighbors': 31, 'n_components': 5, 'min_dist': 0.24, 'min_cluster_size': 22, 'min_samples': 10, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 1/1 [00:00<00:00, 281.14it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 56: DBCV=0.429, CCC=0.000
[I 2025-12-22 19:45:41,440] Trial 56 finished with values: [0.0, 0.4294904041122926] and parameters: {'n_neighbors': 38, 'n_components': 14, 'min_dist': 0.29, 'min_cluster_size': 21, 'min_samples': 8, 'cluster_selection_epsilon': 0.0}.

  0%|          | 0/42 [00:00<?, ?it/s]
100%|██████████| 42/42 [00:00<00:00, 377.19it/s]

Trial 57: DBCV=0.410, CCC=0.566
[I 2025-12-22 19:45:52,520] Trial 57 finished with values: [0.5661727278842494, 0.4104904517176549] and parameters: {'n_neighbors': 21, 'n_components': 14, 'min_dist': 0.28, 'min_cluster_size': 11, 'min_samples': 5, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 15/15 [00:00<00:00, 400.03it/s]

Trial 58: DBCV=0.233, CCC=0.519
[I 2025-12-22 19:46:02,112] Trial 58 finished with values: [0.5192735480792722, 0.23267500363662652] and parameters: {'n_neighbors': 13, 'n_components': 6, 'min_dist': 0.14, 'min_cluster_size': 38, 'min_samples': 2, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 1/1 [00:00<00:00, 288.11it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 59: DBCV=-0.266, CCC=0.000
[I 2025-12-22 19:46:11,222] Trial 59 finished with values: [0.0, -0.26588694244362754] and parameters: {'n_neighbors': 8, 'n_components': 3, 'min_dist': 0.24, 'min_cluster_size': 31, 'min_samples': 20, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 40/40 [00:00<00:00, 405.42it/s]

Trial 60: DBCV=0.476, CCC=0.524
[I 2025-12-22 19:46:23,465] Trial 60 finished with values: [0.5241008897737635, 0.47644588090134754] and parameters: {'n_neighbors': 46, 'n_components': 14, 'min_dist': 0.09, 'min_cluster_size': 8, 'min_samples': 8, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 19/19 [00:00<00:00, 403.82it/s]

Trial 61: DBCV=0.042, CCC=0.495
[I 2025-12-22 19:46:34,025] Trial 61 finished with values: [0.49473317211248335, 0.04172384080311952] and parameters: {'n_neighbors': 33, 'n_components': 6, 'min_dist': 0.14, 'min_cluster_size': 31, 'min_samples': 1, 'cluster_selection_epsilon': 0.18}.

  0%|          | 0/227 [00:00<?, ?it/s]
 18%|█▊        | 41/227 [00:00<00:00, 406.71it/s]
 37%|███▋      | 83/227 [00:00<00:00, 413.66it/s]
 55%|█████▌    | 125/227 [00:00<00:00, 405.72it/s]
 73%|███████▎  | 166/227 [00:00<00:00, 406.57it/s]
100%|██████████| 227/227 [00:00<00:00, 401.29it/s]

Trial 62: DBCV=0.535, CCC=0.419
[I 2025-12-22 19:46:47,582] Trial 62 finished with values: [0.4188386029387634, 0.5345395039885104] and parameters: {'n_neighbors': 24, 'n_components': 12, 'min_dist': 0.07, 'min_cluster_size': 2, 'min_samples': 2, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 9/9 [00:00<00:00, 397.54it/s]

Trial 63: DBCV=0.367, CCC=0.728
[I 2025-12-22 19:46:57,622] Trial 63 finished with values: [0.7276306510625382, 0.3672567615186126] and parameters: {'n_neighbors': 22, 'n_components': 6, 'min_dist': 0.2, 'min_cluster_size': 47, 'min_samples': 11, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 17/17 [00:00<00:00, 352.55it/s]

Trial 64: DBCV=0.467, CCC=0.473
[I 2025-12-22 19:47:06,236] Trial 64 finished with values: [0.4728099269912616, 0.4674824752643929] and parameters: {'n_neighbors': 3, 'n_components': 13, 'min_dist': 0.16, 'min_cluster_size': 36, 'min_samples': 4, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 1/1 [00:00<00:00, 287.40it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 65: DBCV=0.203, CCC=0.000
[I 2025-12-22 19:47:16,640] Trial 65 finished with values: [0.0, 0.2029890538992743] and parameters: {'n_neighbors': 31, 'n_components': 4, 'min_dist': 0.22, 'min_cluster_size': 23, 'min_samples': 6, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 10/10 [00:00<00:00, 389.15it/s]

Trial 66: DBCV=0.455, CCC=0.612
[I 2025-12-22 19:47:26,385] Trial 66 finished with values: [0.6120772459292829, 0.4552951878444649] and parameters: {'n_neighbors': 18, 'n_components': 5, 'min_dist': 0.09, 'min_cluster_size': 33, 'min_samples': 20, 'cluster_selection_epsilon': 0.2}.

  0%|          | 0/51 [00:00<?, ?it/s]
100%|██████████| 51/51 [00:00<00:00, 395.32it/s]

Trial 67: DBCV=0.522, CCC=0.503
[I 2025-12-22 19:47:37,679] Trial 67 finished with values: [0.502862901952827, 0.5215184446985172] and parameters: {'n_neighbors': 23, 'n_components': 14, 'min_dist': 0.09, 'min_cluster_size': 8, 'min_samples': 8, 'cluster_selection_epsilon': 0.27}.

  0%|          | 0/69 [00:00<?, ?it/s]
100%|██████████| 69/69 [00:00<00:00, 393.27it/s]

Trial 68: DBCV=0.620, CCC=0.477
[I 2025-12-22 19:47:47,882] Trial 68 finished with values: [0.47688130093898384, 0.6204276045689004] and parameters: {'n_neighbors': 14, 'n_components': 7, 'min_dist': 0.09, 'min_cluster_size': 3, 'min_samples': 9, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 10/10 [00:00<00:00, 342.40it/s]

Trial 69: DBCV=0.526, CCC=0.629
[I 2025-12-22 19:47:57,500] Trial 69 finished with values: [0.6291760493861621, 0.5255594195022195] and parameters: {'n_neighbors': 12, 'n_components': 9, 'min_dist': 0.06, 'min_cluster_size': 42, 'min_samples': 16, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 12/12 [00:00<00:00, 394.26it/s]

Trial 70: DBCV=0.418, CCC=0.570
[I 2025-12-22 19:48:05,794] Trial 70 finished with values: [0.5697528767424221, 0.4175081744750793] and parameters: {'n_neighbors': 3, 'n_components': 7, 'min_dist': 0.0, 'min_cluster_size': 47, 'min_samples': 18, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 28/28 [00:00<00:00, 397.69it/s]

Trial 71: DBCV=0.445, CCC=0.484
[I 2025-12-22 19:48:14,512] Trial 71 finished with values: [0.484039412207479, 0.4448098287544508] and parameters: {'n_neighbors': 7, 'n_components': 2, 'min_dist': 0.06, 'min_cluster_size': 20, 'min_samples': 14, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 10/10 [00:00<00:00, 359.70it/s]

Trial 72: DBCV=0.275, CCC=0.540
[I 2025-12-22 19:48:23,542] Trial 72 finished with values: [0.5396294622022642, 0.2754696317725523] and parameters: {'n_neighbors': 9, 'n_components': 5, 'min_dist': 0.09, 'min_cluster_size': 47, 'min_samples': 20, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 16/16 [00:00<00:00, 358.03it/s]

Trial 73: DBCV=0.402, CCC=0.539
[I 2025-12-22 19:48:33,914] Trial 73 finished with values: [0.5391097101726652, 0.40192731560802386] and parameters: {'n_neighbors': 21, 'n_components': 10, 'min_dist': 0.06, 'min_cluster_size': 31, 'min_samples': 5, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 8/8 [00:00<00:00, 314.12it/s]

Trial 74: DBCV=0.253, CCC=0.789
[I 2025-12-22 19:48:44,915] Trial 74 finished with values: [0.7887390543686826, 0.2532245573373515] and parameters: {'n_neighbors': 47, 'n_components': 8, 'min_dist': 0.19, 'min_cluster_size': 28, 'min_samples': 12, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 18/18 [00:00<00:00, 372.16it/s]

Trial 75: DBCV=0.362, CCC=0.539
[I 2025-12-22 19:48:54,697] Trial 75 finished with values: [0.5394902255016051, 0.361592662851167] and parameters: {'n_neighbors': 18, 'n_components': 5, 'min_dist': 0.06, 'min_cluster_size': 31, 'min_samples': 10, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 10/10 [00:00<00:00, 399.77it/s]

Trial 76: DBCV=0.298, CCC=0.539
[I 2025-12-22 19:49:05,776] Trial 76 finished with values: [0.5392127205052822, 0.2981114316803515] and parameters: {'n_neighbors': 42, 'n_components': 10, 'min_dist': 0.22, 'min_cluster_size': 28, 'min_samples': 17, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 1/1 [00:00<00:00, 304.53it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 77: DBCV=0.546, CCC=0.000
[I 2025-12-22 19:49:16,313] Trial 77 finished with values: [0.0, 0.5455092165232622] and parameters: {'n_neighbors': 24, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 23, 'min_samples': 7, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 12/12 [00:00<00:00, 362.24it/s]

Trial 78: DBCV=0.354, CCC=0.520
[I 2025-12-22 19:49:26,279] Trial 78 finished with values: [0.519644046771804, 0.35430099723250086] and parameters: {'n_neighbors': 18, 'n_components': 8, 'min_dist': 0.23, 'min_cluster_size': 25, 'min_samples': 10, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 11/11 [00:00<00:00, 399.88it/s]

Trial 79: DBCV=0.286, CCC=0.696
[I 2025-12-22 19:49:36,462] Trial 79 finished with values: [0.6963625893200925, 0.28554679544012074] and parameters: {'n_neighbors': 13, 'n_components': 14, 'min_dist': 0.29, 'min_cluster_size': 38, 'min_samples': 9, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 30/30 [00:00<00:00, 398.34it/s]

Trial 80: DBCV=0.344, CCC=0.511
[I 2025-12-22 19:49:47,115] Trial 80 finished with values: [0.5110077952069633, 0.344269004313106] and parameters: {'n_neighbors': 18, 'n_components': 13, 'min_dist': 0.06, 'min_cluster_size': 20, 'min_samples': 2, 'cluster_selection_epsilon': 0.17}.

  0%|          | 0/217 [00:00<?, ?it/s]
 19%|█▉        | 42/217 [00:00<00:00, 411.62it/s]
 39%|███▊      | 84/217 [00:00<00:00, 414.17it/s]
 58%|█████▊    | 126/217 [00:00<00:00, 407.22it/s]
 77%|███████▋  | 167/217 [00:00<00:00, 400.71it/s]
100%|██████████| 217/217 [00:00<00:00, 397.54it/s]

Trial 81: DBCV=0.466, CCC=0.447
[I 2025-12-22 19:49:59,284] Trial 81 finished with values: [0.44707275942746894, 0.4661304791175142] and parameters: {'n_neighbors': 24, 'n_components': 2, 'min_dist': 0.19, 'min_cluster_size': 3, 'min_samples': 2, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 11/11 [00:00<00:00, 334.76it/s]

Trial 82: DBCV=-0.041, CCC=0.512
[I 2025-12-22 19:50:09,916] Trial 82 finished with values: [0.5118879629447867, -0.040945891836110505] and parameters: {'n_neighbors': 33, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 46, 'min_samples': 1, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 12/12 [00:00<00:00, 396.34it/s]

Trial 83: DBCV=0.440, CCC=0.631
[I 2025-12-22 19:50:20,505] Trial 83 finished with values: [0.6310111521675892, 0.440478140973481] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.03, 'min_cluster_size': 44, 'min_samples': 13, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 1/1 [00:00<00:00, 314.60it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 84: DBCV=0.053, CCC=0.000
[I 2025-12-22 19:50:29,847] Trial 84 finished with values: [0.0, 0.0532993899658744] and parameters: {'n_neighbors': 7, 'n_components': 9, 'min_dist': 0.23, 'min_cluster_size': 42, 'min_samples': 7, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 11/11 [00:00<00:00, 394.44it/s]

Trial 85: DBCV=0.497, CCC=0.665
[I 2025-12-22 19:50:41,669] Trial 85 finished with values: [0.6650363030982795, 0.4966300794531555] and parameters: {'n_neighbors': 42, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 28, 'min_samples': 16, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 15/15 [00:00<00:00, 395.06it/s]

Trial 86: DBCV=0.500, CCC=0.570
[I 2025-12-22 19:50:52,943] Trial 86 finished with values: [0.5704561541133327, 0.49953137468515885] and parameters: {'n_neighbors': 31, 'n_components': 13, 'min_dist': 0.05, 'min_cluster_size': 32, 'min_samples': 10, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 9/9 [00:00<00:00, 344.06it/s]

Trial 87: DBCV=0.353, CCC=0.695
[I 2025-12-22 19:51:03,556] Trial 87 finished with values: [0.6951238022589503, 0.3527588997949729] and parameters: {'n_neighbors': 28, 'n_components': 10, 'min_dist': 0.23, 'min_cluster_size': 42, 'min_samples': 8, 'cluster_selection_epsilon': 0.11}.

  0%|          | 0/107 [00:00<?, ?it/s]
 39%|███▉      | 42/107 [00:00<00:00, 419.66it/s]
100%|██████████| 107/107 [00:00<00:00, 399.89it/s][A

Trial 88: DBCV=0.540, CCC=0.470
[I 2025-12-22 19:51:14,157] Trial 88 finished with values: [0.47005947683872634, 0.5396750918689147] and parameters: {'n_neighbors': 13, 'n_components': 10, 'min_dist': 0.27, 'min_cluster_size': 3, 'min_samples': 4, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 40/40 [00:00<00:00, 405.95it/s]

Trial 89: DBCV=0.522, CCC=0.505
[I 2025-12-22 19:51:25,232] Trial 89 finished with values: [0.5050503575801575, 0.5219870885226306] and parameters: {'n_neighbors': 49, 'n_components': 6, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 12, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 15/15 [00:00<00:00, 402.59it/s]

Trial 90: DBCV=0.292, CCC=0.519
[I 2025-12-22 19:51:33,569] Trial 90 finished with values: [0.5194141666022788, 0.2916004862135788] and parameters: {'n_neighbors': 3, 'n_components': 10, 'min_dist': 0.23, 'min_cluster_size': 49, 'min_samples': 1, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 10/10 [00:00<00:00, 391.89it/s]

Trial 91: DBCV=0.151, CCC=0.514
[I 2025-12-22 19:51:42,585] Trial 91 finished with values: [0.5144593720080639, 0.15132431702431728] and parameters: {'n_neighbors': 11, 'n_components': 2, 'min_dist': 0.19, 'min_cluster_size': 35, 'min_samples': 16, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 9/9 [00:00<00:00, 392.45it/s]

Trial 92: DBCV=0.275, CCC=0.608
[I 2025-12-22 19:51:53,667] Trial 92 finished with values: [0.6077818616397407, 0.27470301357841226] and parameters: {'n_neighbors': 48, 'n_components': 7, 'min_dist': 0.05, 'min_cluster_size': 46, 'min_samples': 6, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 2/2 [00:00<00:00, 209.26it/s]

Trial 93: DBCV=-0.155, CCC=0.846
[I 2025-12-22 19:52:04,749] Trial 93 finished with values: [0.8460159746515313, -0.1550695234156332] and parameters: {'n_neighbors': 42, 'n_components': 6, 'min_dist': 0.24, 'min_cluster_size': 12, 'min_samples': 10, 'cluster_selection_epsilon': 0.06}.

  0%|          | 0/63 [00:00<?, ?it/s]
100%|██████████| 63/63 [00:00<00:00, 396.92it/s]

Trial 94: DBCV=0.553, CCC=0.501
[I 2025-12-22 19:52:14,451] Trial 94 finished with values: [0.5008226769732184, 0.5534970155877369] and parameters: {'n_neighbors': 8, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 9, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 13/13 [00:00<00:00, 399.33it/s]

Trial 95: DBCV=0.162, CCC=0.468
[I 2025-12-22 19:52:24,034] Trial 95 finished with values: [0.46804489157052326, 0.16161030155931985] and parameters: {'n_neighbors': 18, 'n_components': 3, 'min_dist': 0.21, 'min_cluster_size': 25, 'min_samples': 10, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 11/11 [00:00<00:00, 396.58it/s]

Trial 96: DBCV=0.473, CCC=0.619
[I 2025-12-22 19:52:35,704] Trial 96 finished with values: [0.6190525538369971, 0.473152037387945] and parameters: {'n_neighbors': 36, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 34, 'min_samples': 12, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 14/14 [00:00<00:00, 404.90it/s]

Trial 97: DBCV=0.342, CCC=0.615
[I 2025-12-22 19:52:46,080] Trial 97 finished with values: [0.6149813023959516, 0.34170416106522755] and parameters: {'n_neighbors': 24, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 30, 'min_samples': 11, 'cluster_selection_epsilon': 0.18}.

100%|██████████| 13/13 [00:00<00:00, 405.74it/s]

Trial 98: DBCV=0.513, CCC=0.569
[I 2025-12-22 19:52:56,791] Trial 98 finished with values: [0.5690945314581467, 0.5128832608469318] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.03, 'min_cluster_size': 38, 'min_samples': 19, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 23/23 [00:00<00:00, 388.38it/s]

Trial 99: DBCV=0.053, CCC=0.532
[I 2025-12-22 19:53:07,394] Trial 99 finished with values: [0.5317059260987637, 0.053246750848126904] and parameters: {'n_neighbors': 34, 'n_components': 6, 'min_dist': 0.14, 'min_cluster_size': 27, 'min_samples': 1, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 9/9 [00:00<00:00, 336.03it/s]

Trial 100: DBCV=0.394, CCC=0.690
[I 2025-12-22 19:53:17,873] Trial 100 finished with values: [0.6899811982165328, 0.39388920015258444] and parameters: {'n_neighbors': 18, 'n_components': 12, 'min_dist': 0.11, 'min_cluster_size': 47, 'min_samples': 11, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 9/9 [00:00<00:00, 399.29it/s]

Trial 101: DBCV=0.291, CCC=0.650
[I 2025-12-22 19:53:27,574] Trial 101 finished with values: [0.6495732743149698, 0.29113264670013705] and parameters: {'n_neighbors': 15, 'n_components': 6, 'min_dist': 0.2, 'min_cluster_size': 41, 'min_samples': 11, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 8/8 [00:00<00:00, 333.11it/s]

Trial 102: DBCV=0.450, CCC=0.756
[I 2025-12-22 19:53:39,354] Trial 102 finished with values: [0.7558245824140537, 0.45012846035372706] and parameters: {'n_neighbors': 49, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 47, 'min_samples': 11, 'cluster_selection_epsilon': 0.25}.

  0%|          | 0/63 [00:00<?, ?it/s]
100%|██████████| 63/63 [00:00<00:00, 392.92it/s]

Trial 103: DBCV=0.582, CCC=0.450
[I 2025-12-22 19:53:49,373] Trial 103 finished with values: [0.4504232787595654, 0.5818691726241629] and parameters: {'n_neighbors': 8, 'n_components': 14, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 9, 'cluster_selection_epsilon': 0.19}.

  0%|          | 0/51 [00:00<?, ?it/s]
100%|██████████| 51/51 [00:00<00:00, 382.13it/s]

Trial 104: DBCV=0.510, CCC=0.504
[I 2025-12-22 19:54:00,648] Trial 104 finished with values: [0.5042892749377593, 0.5100694319864155] and parameters: {'n_neighbors': 23, 'n_components': 14, 'min_dist': 0.07, 'min_cluster_size': 6, 'min_samples': 8, 'cluster_selection_epsilon': 0.27}.

100%|██████████| 9/9 [00:00<00:00, 400.58it/s]

Trial 105: DBCV=0.339, CCC=0.711
[I 2025-12-22 19:54:10,666] Trial 105 finished with values: [0.7114637873227562, 0.3386501794988148] and parameters: {'n_neighbors': 22, 'n_components': 6, 'min_dist': 0.3, 'min_cluster_size': 42, 'min_samples': 11, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 8/8 [00:00<00:00, 333.27it/s]

Trial 106: DBCV=0.286, CCC=0.717
[I 2025-12-22 19:54:21,086] Trial 106 finished with values: [0.7169332924397389, 0.28581700897516255] and parameters: {'n_neighbors': 42, 'n_components': 4, 'min_dist': 0.18, 'min_cluster_size': 44, 'min_samples': 17, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 9/9 [00:00<00:00, 401.80it/s]

Trial 107: DBCV=0.363, CCC=0.632
[I 2025-12-22 19:54:30,428] Trial 107 finished with values: [0.6315637955669686, 0.36345663699057273] and parameters: {'n_neighbors': 12, 'n_components': 5, 'min_dist': 0.27, 'min_cluster_size': 33, 'min_samples': 20, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 2/2 [00:00<00:00, 316.73it/s]

Trial 108: DBCV=0.079, CCC=0.824
[I 2025-12-22 19:54:41,265] Trial 108 finished with values: [0.8243195397671446, 0.07860479637128946] and parameters: {'n_neighbors': 31, 'n_components': 8, 'min_dist': 0.21, 'min_cluster_size': 14, 'min_samples': 15, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 23/23 [00:00<00:00, 390.10it/s]

Trial 109: DBCV=0.460, CCC=0.542
[I 2025-12-22 19:54:53,442] Trial 109 finished with values: [0.5421575769878619, 0.4597545470133661] and parameters: {'n_neighbors': 42, 'n_components': 15, 'min_dist': 0.3, 'min_cluster_size': 14, 'min_samples': 15, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 22/22 [00:00<00:00, 386.67it/s]

Trial 110: DBCV=0.487, CCC=0.552
[I 2025-12-22 19:55:03,799] Trial 110 finished with values: [0.5516452423295481, 0.4872068784506502] and parameters: {'n_neighbors': 18, 'n_components': 11, 'min_dist': 0.07, 'min_cluster_size': 24, 'min_samples': 12, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 2/2 [00:00<00:00, 314.30it/s]

Trial 111: DBCV=0.223, CCC=0.681
[I 2025-12-22 19:55:13,020] Trial 111 finished with values: [0.6812978980331023, 0.22323766099330355] and parameters: {'n_neighbors': 7, 'n_components': 6, 'min_dist': 0.2, 'min_cluster_size': 20, 'min_samples': 10, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 13/13 [00:00<00:00, 391.43it/s]

Trial 112: DBCV=0.457, CCC=0.636
[I 2025-12-22 19:55:22,426] Trial 112 finished with values: [0.63649165333815, 0.45703092876926654] and parameters: {'n_neighbors': 7, 'n_components': 13, 'min_dist': 0.16, 'min_cluster_size': 36, 'min_samples': 14, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 2/2 [00:00<00:00, 280.88it/s]

Trial 113: DBCV=0.375, CCC=0.827
[I 2025-12-22 19:55:33,417] Trial 113 finished with values: [0.8269448086205721, 0.3745176040941119] and parameters: {'n_neighbors': 18, 'n_components': 14, 'min_dist': 0.24, 'min_cluster_size': 2, 'min_samples': 14, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 10/10 [00:00<00:00, 394.54it/s]

Trial 114: DBCV=0.409, CCC=0.578
[I 2025-12-22 19:55:44,018] Trial 114 finished with values: [0.577525809741622, 0.4090564810576363] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.03, 'min_cluster_size': 47, 'min_samples': 11, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 40/40 [00:00<00:00, 407.04it/s]

Trial 115: DBCV=0.513, CCC=0.564
[I 2025-12-22 19:55:54,463] Trial 115 finished with values: [0.5638416902219625, 0.5130355952001855] and parameters: {'n_neighbors': 13, 'n_components': 14, 'min_dist': 0.04, 'min_cluster_size': 14, 'min_samples': 9, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 10/10 [00:00<00:00, 353.80it/s]

Trial 116: DBCV=0.100, CCC=0.732
[I 2025-12-22 19:56:04,885] Trial 116 finished with values: [0.7319323096011922, 0.09989313121596259] and parameters: {'n_neighbors': 49, 'n_components': 3, 'min_dist': 0.29, 'min_cluster_size': 38, 'min_samples': 9, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 28/28 [00:00<00:00, 392.75it/s]

Trial 117: DBCV=0.472, CCC=0.542
[I 2025-12-22 19:56:13,955] Trial 117 finished with values: [0.5419752968008134, 0.47249435190655165] and parameters: {'n_neighbors': 7, 'n_components': 8, 'min_dist': 0.05, 'min_cluster_size': 26, 'min_samples': 7, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 16/16 [00:00<00:00, 396.79it/s]

Trial 118: DBCV=0.396, CCC=0.535
[I 2025-12-22 19:56:23,627] Trial 118 finished with values: [0.5354138319243138, 0.3963006463022253] and parameters: {'n_neighbors': 12, 'n_components': 8, 'min_dist': 0.06, 'min_cluster_size': 30, 'min_samples': 7, 'cluster_selection_epsilon': 0.12}.

  0%|          | 0/76 [00:00<?, ?it/s]
100%|██████████| 76/76 [00:00<00:00, 395.66it/s]

Trial 119: DBCV=0.539, CCC=0.429
[I 2025-12-22 19:56:34,352] Trial 119 finished with values: [0.4291623901277742, 0.5392049435902924] and parameters: {'n_neighbors': 24, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 2, 'min_samples': 7, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 1/1 [00:00<00:00, 280.26it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 120: DBCV=0.242, CCC=0.000
[I 2025-12-22 19:56:45,817] Trial 120 finished with values: [0.0, 0.24178493677650967] and parameters: {'n_neighbors': 46, 'n_components': 9, 'min_dist': 0.09, 'min_cluster_size': 23, 'min_samples': 8, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 15/15 [00:00<00:00, 408.57it/s]

Trial 121: DBCV=0.430, CCC=0.624
[I 2025-12-22 19:56:55,517] Trial 121 finished with values: [0.6237101683228657, 0.4297656211065318] and parameters: {'n_neighbors': 14, 'n_components': 7, 'min_dist': 0.09, 'min_cluster_size': 38, 'min_samples': 9, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 2/2 [00:00<00:00, 308.22it/s]

Trial 122: DBCV=0.620, CCC=0.827
[I 2025-12-22 19:57:06,066] Trial 122 finished with values: [0.8269448086205721, 0.6198184527308173] and parameters: {'n_neighbors': 18, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 12, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 27/27 [00:00<00:00, 385.15it/s]

Trial 123: DBCV=0.583, CCC=0.533
[I 2025-12-22 19:57:17,013] Trial 123 finished with values: [0.5334190805204904, 0.5829302673211298] and parameters: {'n_neighbors': 31, 'n_components': 11, 'min_dist': 0.21, 'min_cluster_size': 14, 'min_samples': 15, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 10/10 [00:00<00:00, 391.85it/s]

Trial 124: DBCV=0.371, CCC=0.703
[I 2025-12-22 19:57:27,038] Trial 124 finished with values: [0.7026172864337324, 0.3707184991077919] and parameters: {'n_neighbors': 22, 'n_components': 6, 'min_dist': 0.2, 'min_cluster_size': 34, 'min_samples': 11, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 12/12 [00:00<00:00, 403.06it/s]

Trial 125: DBCV=0.298, CCC=0.667
[I 2025-12-22 19:57:37,361] Trial 125 finished with values: [0.6670288030288231, 0.29780651207876097] and parameters: {'n_neighbors': 23, 'n_components': 8, 'min_dist': 0.14, 'min_cluster_size': 35, 'min_samples': 7, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 10/10 [00:00<00:00, 401.48it/s]

Trial 126: DBCV=0.409, CCC=0.578
[I 2025-12-22 19:57:47,968] Trial 126 finished with values: [0.577525809741622, 0.4090564810576363] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.03, 'min_cluster_size': 44, 'min_samples': 11, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 20/20 [00:00<00:00, 412.26it/s]

Trial 127: DBCV=0.374, CCC=0.503
[I 2025-12-22 19:57:58,865] Trial 127 finished with values: [0.5030341588776711, 0.37398098778795197] and parameters: {'n_neighbors': 47, 'n_components': 6, 'min_dist': 0.19, 'min_cluster_size': 28, 'min_samples': 8, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 12/12 [00:00<00:00, 407.04it/s]

Trial 128: DBCV=0.433, CCC=0.659
[I 2025-12-22 19:58:10,803] Trial 128 finished with values: [0.6591400343694611, 0.4333773569231882] and parameters: {'n_neighbors': 47, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 28, 'min_samples': 12, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 11/11 [00:00<00:00, 400.99it/s]

Trial 129: DBCV=0.510, CCC=0.584
[I 2025-12-22 19:58:21,465] Trial 129 finished with values: [0.5836583947184455, 0.5096872922523433] and parameters: {'n_neighbors': 23, 'n_components': 12, 'min_dist': 0.06, 'min_cluster_size': 35, 'min_samples': 16, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 15/15 [00:00<00:00, 402.59it/s]

Trial 130: DBCV=0.280, CCC=0.495
[I 2025-12-22 19:58:31,251] Trial 130 finished with values: [0.4947654495058349, 0.28016033234423365] and parameters: {'n_neighbors': 12, 'n_components': 11, 'min_dist': 0.06, 'min_cluster_size': 42, 'min_samples': 4, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 8/8 [00:00<00:00, 332.38it/s]

Trial 131: DBCV=0.058, CCC=0.704
[I 2025-12-22 19:58:42,062] Trial 131 finished with values: [0.7038074687905704, 0.0577701777862611] and parameters: {'n_neighbors': 22, 'n_components': 13, 'min_dist': 0.16, 'min_cluster_size': 47, 'min_samples': 4, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 2/2 [00:00<00:00, 326.47it/s]

Trial 132: DBCV=0.507, CCC=0.827
[I 2025-12-22 19:58:53,091] Trial 132 finished with values: [0.8269448086205721, 0.5068141784410313] and parameters: {'n_neighbors': 24, 'n_components': 12, 'min_dist': 0.07, 'min_cluster_size': 2, 'min_samples': 16, 'cluster_selection_epsilon': 0.04}.

  0%|          | 0/121 [00:00<?, ?it/s]
 35%|███▍      | 42/121 [00:00<00:00, 413.03it/s]
100%|██████████| 121/121 [00:00<00:00, 397.46it/s][A

Trial 133: DBCV=0.433, CCC=0.402
[I 2025-12-22 19:59:04,807] Trial 133 finished with values: [0.4016696226409753, 0.43271040953042916] and parameters: {'n_neighbors': 24, 'n_components': 11, 'min_dist': 0.07, 'min_cluster_size': 2, 'min_samples': 2, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 12/12 [00:00<00:00, 328.09it/s]

Trial 134: DBCV=0.281, CCC=0.606
[I 2025-12-22 19:59:15,712] Trial 134 finished with values: [0.6055239297308654, 0.2808863085125143] and parameters: {'n_neighbors': 48, 'n_components': 6, 'min_dist': 0.05, 'min_cluster_size': 46, 'min_samples': 6, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 24/24 [00:00<00:00, 383.45it/s]

Trial 135: DBCV=0.566, CCC=0.470
[I 2025-12-22 19:59:26,807] Trial 135 finished with values: [0.4698657950743144, 0.5655086572588772] and parameters: {'n_neighbors': 25, 'n_components': 14, 'min_dist': 0.19, 'min_cluster_size': 14, 'min_samples': 19, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 14/14 [00:00<00:00, 405.45it/s]

Trial 136: DBCV=0.308, CCC=0.628
[I 2025-12-22 19:59:37,243] Trial 136 finished with values: [0.6283340966885, 0.30767975562035005] and parameters: {'n_neighbors': 15, 'n_components': 14, 'min_dist': 0.29, 'min_cluster_size': 38, 'min_samples': 3, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 1/1 [00:00<00:00, 288.84it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 137: DBCV=0.310, CCC=0.000
[I 2025-12-22 19:59:48,275] Trial 137 finished with values: [0.0, 0.3099550404734933] and parameters: {'n_neighbors': 24, 'n_components': 12, 'min_dist': 0.06, 'min_cluster_size': 2, 'min_samples': 17, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 8/8 [00:00<00:00, 397.61it/s]

Trial 138: DBCV=0.361, CCC=0.759
[I 2025-12-22 19:59:59,256] Trial 138 finished with values: [0.7589903251947203, 0.3607351618582871] and parameters: {'n_neighbors': 47, 'n_components': 8, 'min_dist': 0.25, 'min_cluster_size': 44, 'min_samples': 12, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 9/9 [00:00<00:00, 391.66it/s]

Trial 139: DBCV=0.247, CCC=0.719
[I 2025-12-22 20:00:09,897] Trial 139 finished with values: [0.7185418798220536, 0.246816155287595] and parameters: {'n_neighbors': 24, 'n_components': 12, 'min_dist': 0.29, 'min_cluster_size': 38, 'min_samples': 9, 'cluster_selection_epsilon': 0.0}.

  0%|          | 0/42 [00:00<?, ?it/s]
100%|██████████| 42/42 [00:00<00:00, 398.08it/s]

Trial 140: DBCV=0.539, CCC=0.498
[I 2025-12-22 20:00:19,558] Trial 140 finished with values: [0.4978100339789562, 0.5394428185300085] and parameters: {'n_neighbors': 12, 'n_components': 6, 'min_dist': 0.11, 'min_cluster_size': 12, 'min_samples': 10, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 37/37 [00:00<00:00, 395.16it/s]

Trial 141: DBCV=0.388, CCC=0.530
[I 2025-12-22 20:00:29,443] Trial 141 finished with values: [0.5303509773969717, 0.38751625941532014] and parameters: {'n_neighbors': 13, 'n_components': 10, 'min_dist': 0.27, 'min_cluster_size': 12, 'min_samples': 4, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/239 [00:00<?, ?it/s]
 18%|█▊        | 42/239 [00:00<00:00, 412.72it/s]
 35%|███▌      | 84/239 [00:00<00:00, 404.16it/s]
 52%|█████▏    | 125/239 [00:00<00:00, 400.03it/s]
 69%|██████▉   | 166/239 [00:00<00:00, 403.68it/s]
100%|██████████| 239/239 [00:00<00:00, 400.70it/s]

Trial 142: DBCV=0.536, CCC=0.445
[I 2025-12-22 20:00:43,320] Trial 142 finished with values: [0.44462442308593847, 0.535678447966965] and parameters: {'n_neighbors': 24, 'n_components': 13, 'min_dist': 0.07, 'min_cluster_size': 2, 'min_samples': 2, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 16/16 [00:00<00:00, 401.48it/s]

Trial 143: DBCV=0.381, CCC=0.591
[I 2025-12-22 20:00:51,836] Trial 143 finished with values: [0.5907160348756667, 0.38080324949251804] and parameters: {'n_neighbors': 4, 'n_components': 7, 'min_dist': 0.09, 'min_cluster_size': 38, 'min_samples': 9, 'cluster_selection_epsilon': 0.05}.

100%|██████████| 10/10 [00:00<00:00, 406.97it/s]

Trial 144: DBCV=0.418, CCC=0.631
[I 2025-12-22 20:01:02,555] Trial 144 finished with values: [0.6309426897969116, 0.4178119328207328] and parameters: {'n_neighbors': 42, 'n_components': 6, 'min_dist': 0.24, 'min_cluster_size': 41, 'min_samples': 16, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 282.67it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 145: DBCV=0.079, CCC=0.000
[I 2025-12-22 20:01:13,308] Trial 145 finished with values: [0.0, 0.07940501997656399] and parameters: {'n_neighbors': 38, 'n_components': 4, 'min_dist': 0.26, 'min_cluster_size': 3, 'min_samples': 18, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 28/28 [00:00<00:00, 400.60it/s]

Trial 146: DBCV=0.535, CCC=0.534
[I 2025-12-22 20:01:25,364] Trial 146 finished with values: [0.5340683320283007, 0.5352877300282599] and parameters: {'n_neighbors': 46, 'n_components': 14, 'min_dist': 0.14, 'min_cluster_size': 8, 'min_samples': 14, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 10/10 [00:00<00:00, 348.52it/s]

Trial 147: DBCV=0.322, CCC=0.611
[I 2025-12-22 20:01:36,050] Trial 147 finished with values: [0.6108623534141717, 0.3219587522150131] and parameters: {'n_neighbors': 38, 'n_components': 8, 'min_dist': 0.2, 'min_cluster_size': 47, 'min_samples': 12, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 2/2 [00:00<00:00, 354.74it/s]

Trial 148: DBCV=-0.361, CCC=0.888
[I 2025-12-22 20:01:46,580] Trial 148 finished with values: [0.8875719781734257, -0.36086612487439373] and parameters: {'n_neighbors': 24, 'n_components': 8, 'min_dist': 0.19, 'min_cluster_size': 27, 'min_samples': 2, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 14/14 [00:00<00:00, 410.77it/s]

Trial 149: DBCV=0.231, CCC=0.546
[I 2025-12-22 20:01:57,271] Trial 149 finished with values: [0.5457559492019699, 0.23062909215054347] and parameters: {'n_neighbors': 47, 'n_components': 5, 'min_dist': 0.19, 'min_cluster_size': 28, 'min_samples': 11, 'cluster_selection_epsilon': 0.12}.

  0%|          | 0/63 [00:00<?, ?it/s]
100%|██████████| 63/63 [00:00<00:00, 408.45it/s]

Trial 150: DBCV=0.553, CCC=0.501
[I 2025-12-22 20:02:07,008] Trial 150 finished with values: [0.5008226769732184, 0.5534970155877369] and parameters: {'n_neighbors': 8, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 9, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 316.62it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 151: DBCV=0.598, CCC=0.000
[I 2025-12-22 20:02:18,441] Trial 151 finished with values: [0.0, 0.5981918865712935] and parameters: {'n_neighbors': 25, 'n_components': 14, 'min_dist': 0.16, 'min_cluster_size': 14, 'min_samples': 19, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 1/1 [00:00<00:00, 319.57it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 152: DBCV=0.310, CCC=0.000
[I 2025-12-22 20:02:29,502] Trial 152 finished with values: [0.0, 0.3099550404734933] and parameters: {'n_neighbors': 24, 'n_components': 12, 'min_dist': 0.06, 'min_cluster_size': 23, 'min_samples': 16, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 1/1 [00:00<00:00, 321.87it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 153: DBCV=0.485, CCC=0.000
[I 2025-12-22 20:02:39,891] Trial 153 finished with values: [0.0, 0.4853705130618536] and parameters: {'n_neighbors': 12, 'n_components': 14, 'min_dist': 0.24, 'min_cluster_size': 31, 'min_samples': 14, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 17/17 [00:00<00:00, 413.43it/s]

Trial 154: DBCV=0.481, CCC=0.612
[I 2025-12-22 20:02:50,779] Trial 154 finished with values: [0.6119505546046078, 0.48075268668101895] and parameters: {'n_neighbors': 22, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 28, 'min_samples': 12, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 13/13 [00:00<00:00, 410.74it/s]

Trial 155: DBCV=0.405, CCC=0.627
[I 2025-12-22 20:03:00,789] Trial 155 finished with values: [0.6271536024439879, 0.40479211772331947] and parameters: {'n_neighbors': 22, 'n_components': 6, 'min_dist': 0.23, 'min_cluster_size': 28, 'min_samples': 11, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 7/7 [00:00<00:00, 296.94it/s]

Trial 156: DBCV=0.368, CCC=0.609
[I 2025-12-22 20:03:12,933] Trial 156 finished with values: [0.6089557854817766, 0.3675630503081026] and parameters: {'n_neighbors': 49, 'n_components': 14, 'min_dist': 0.18, 'min_cluster_size': 47, 'min_samples': 9, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 276.45it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 157: DBCV=0.322, CCC=0.000
[I 2025-12-22 20:03:22,164] Trial 157 finished with values: [0.0, 0.32229771978145005] and parameters: {'n_neighbors': 7, 'n_components': 8, 'min_dist': 0.21, 'min_cluster_size': 14, 'min_samples': 19, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 32/32 [00:00<00:00, 415.77it/s]

Trial 158: DBCV=0.554, CCC=0.550
[I 2025-12-22 20:03:30,987] Trial 158 finished with values: [0.5500122783483254, 0.5539898213607953] and parameters: {'n_neighbors': 4, 'n_components': 12, 'min_dist': 0.05, 'min_cluster_size': 2, 'min_samples': 16, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 9/9 [00:00<00:00, 407.44it/s]

Trial 159: DBCV=0.290, CCC=0.693
[I 2025-12-22 20:03:41,789] Trial 159 finished with values: [0.693018347607356, 0.28989792284000887] and parameters: {'n_neighbors': 24, 'n_components': 12, 'min_dist': 0.3, 'min_cluster_size': 41, 'min_samples': 11, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 9/9 [00:00<00:00, 400.31it/s]

Trial 160: DBCV=0.390, CCC=0.581
[I 2025-12-22 20:03:52,543] Trial 160 finished with values: [0.5812781948622866, 0.38971976182362184] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.03, 'min_cluster_size': 38, 'min_samples': 12, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 2/2 [00:00<00:00, 212.13it/s]

Trial 161: DBCV=0.375, CCC=0.827
[I 2025-12-22 20:04:03,729] Trial 161 finished with values: [0.8269448086205721, 0.3745176040941119] and parameters: {'n_neighbors': 18, 'n_components': 14, 'min_dist': 0.24, 'min_cluster_size': 12, 'min_samples': 7, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/81 [00:00<?, ?it/s]
100%|██████████| 81/81 [00:00<00:00, 410.42it/s]

Trial 162: DBCV=0.527, CCC=0.467
[I 2025-12-22 20:04:14,156] Trial 162 finished with values: [0.4672470296910324, 0.5268029414857501] and parameters: {'n_neighbors': 18, 'n_components': 8, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 7, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 26/26 [00:00<00:00, 414.69it/s]

Trial 163: DBCV=0.495, CCC=0.486
[I 2025-12-22 20:04:24,622] Trial 163 finished with values: [0.4864315158340578, 0.49471463980521485] and parameters: {'n_neighbors': 31, 'n_components': 6, 'min_dist': 0.21, 'min_cluster_size': 14, 'min_samples': 15, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 342.76it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 164: DBCV=0.243, CCC=0.000
[I 2025-12-22 20:04:35,867] Trial 164 finished with values: [0.0, 0.2433705292075694] and parameters: {'n_neighbors': 40, 'n_components': 6, 'min_dist': 0.18, 'min_cluster_size': 25, 'min_samples': 12, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 227.79it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 165: DBCV=-0.038, CCC=0.000
[I 2025-12-22 20:04:47,051] Trial 165 finished with values: [0.0, -0.03813326160459919] and parameters: {'n_neighbors': 47, 'n_components': 6, 'min_dist': 0.25, 'min_cluster_size': 21, 'min_samples': 12, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 1/1 [00:00<00:00, 214.72it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 166: DBCV=0.164, CCC=0.000
[I 2025-12-22 20:04:57,617] Trial 166 finished with values: [0.0, 0.16445724612460794] and parameters: {'n_neighbors': 22, 'n_components': 7, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 18, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/69 [00:00<?, ?it/s]
100%|██████████| 69/69 [00:00<00:00, 403.26it/s]

Trial 167: DBCV=0.499, CCC=0.457
[I 2025-12-22 20:05:07,991] Trial 167 finished with values: [0.4572439782761767, 0.49949294875944594] and parameters: {'n_neighbors': 13, 'n_components': 12, 'min_dist': 0.3, 'min_cluster_size': 3, 'min_samples': 7, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 34/34 [00:00<00:00, 401.74it/s]

Trial 168: DBCV=0.479, CCC=0.488
[I 2025-12-22 20:05:18,528] Trial 168 finished with values: [0.48784452394180944, 0.4790311790850859] and parameters: {'n_neighbors': 42, 'n_components': 4, 'min_dist': 0.04, 'min_cluster_size': 14, 'min_samples': 9, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 2/2 [00:00<00:00, 251.22it/s]

Trial 169: DBCV=-0.361, CCC=0.888
[I 2025-12-22 20:05:29,051] Trial 169 finished with values: [0.8875719781734257, -0.36086612487439373] and parameters: {'n_neighbors': 24, 'n_components': 8, 'min_dist': 0.19, 'min_cluster_size': 27, 'min_samples': 2, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 14/14 [00:00<00:00, 401.63it/s]

Trial 170: DBCV=0.391, CCC=0.579
[I 2025-12-22 20:05:39,402] Trial 170 finished with values: [0.5794709677535378, 0.3906431900299697] and parameters: {'n_neighbors': 28, 'n_components': 8, 'min_dist': 0.29, 'min_cluster_size': 28, 'min_samples': 12, 'cluster_selection_epsilon': 0.12}.

  0%|          | 0/50 [00:00<?, ?it/s]
100%|██████████| 50/50 [00:00<00:00, 403.00it/s]

Trial 171: DBCV=0.596, CCC=0.503
[I 2025-12-22 20:05:49,162] Trial 171 finished with values: [0.503314200438202, 0.5960483552035464] and parameters: {'n_neighbors': 12, 'n_components': 8, 'min_dist': 0.06, 'min_cluster_size': 6, 'min_samples': 11, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 10/10 [00:00<00:00, 399.07it/s]

Trial 172: DBCV=0.342, CCC=0.646
[I 2025-12-22 20:06:00,703] Trial 172 finished with values: [0.6455579855361365, 0.342188856689985] and parameters: {'n_neighbors': 45, 'n_components': 12, 'min_dist': 0.16, 'min_cluster_size': 38, 'min_samples': 16, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 11/11 [00:00<00:00, 404.54it/s]

Trial 173: DBCV=0.251, CCC=0.617
[I 2025-12-22 20:06:11,190] Trial 173 finished with values: [0.6172167476411049, 0.250598591776134] and parameters: {'n_neighbors': 31, 'n_components': 6, 'min_dist': 0.2, 'min_cluster_size': 34, 'min_samples': 10, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 27/27 [00:00<00:00, 398.20it/s]

Trial 174: DBCV=0.583, CCC=0.533
[I 2025-12-22 20:06:22,161] Trial 174 finished with values: [0.5334190805204904, 0.5829302673211298] and parameters: {'n_neighbors': 31, 'n_components': 11, 'min_dist': 0.21, 'min_cluster_size': 13, 'min_samples': 15, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 7/7 [00:00<00:00, 384.03it/s]

Trial 175: DBCV=0.440, CCC=0.742
[I 2025-12-22 20:06:33,078] Trial 175 finished with values: [0.7420950093269939, 0.43993956339779483] and parameters: {'n_neighbors': 49, 'n_components': 6, 'min_dist': 0.07, 'min_cluster_size': 48, 'min_samples': 18, 'cluster_selection_epsilon': 0.06}.

  0%|          | 0/80 [00:00<?, ?it/s]
100%|██████████| 80/80 [00:00<00:00, 405.27it/s]

Trial 176: DBCV=0.589, CCC=0.546
[I 2025-12-22 20:06:43,137] Trial 176 finished with values: [0.5461910602747855, 0.5892781506931422] and parameters: {'n_neighbors': 12, 'n_components': 8, 'min_dist': 0.06, 'min_cluster_size': 6, 'min_samples': 7, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 15/15 [00:00<00:00, 358.38it/s]

Trial 177: DBCV=0.244, CCC=0.579
[I 2025-12-22 20:06:53,041] Trial 177 finished with values: [0.5794919199031323, 0.24417927256986977] and parameters: {'n_neighbors': 31, 'n_components': 2, 'min_dist': 0.06, 'min_cluster_size': 32, 'min_samples': 14, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 7/7 [00:00<00:00, 384.55it/s]

Trial 178: DBCV=0.132, CCC=0.754
[I 2025-12-22 20:07:03,928] Trial 178 finished with values: [0.7543479422506917, 0.1316403812493862] and parameters: {'n_neighbors': 46, 'n_components': 6, 'min_dist': 0.14, 'min_cluster_size': 34, 'min_samples': 14, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 13/13 [00:00<00:00, 340.91it/s]

Trial 179: DBCV=0.418, CCC=0.606
[I 2025-12-22 20:07:15,190] Trial 179 finished with values: [0.6063392237876389, 0.4176387293758889] and parameters: {'n_neighbors': 31, 'n_components': 13, 'min_dist': 0.18, 'min_cluster_size': 32, 'min_samples': 10, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 10/10 [00:00<00:00, 360.07it/s]

Trial 180: DBCV=0.275, CCC=0.632
[I 2025-12-22 20:07:24,912] Trial 180 finished with values: [0.6320571954429244, 0.2747510664973961] and parameters: {'n_neighbors': 24, 'n_components': 3, 'min_dist': 0.3, 'min_cluster_size': 41, 'min_samples': 16, 'cluster_selection_epsilon': 0.26}.

100%|██████████| 1/1 [00:00<00:00, 275.78it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 181: DBCV=0.554, CCC=0.000
[I 2025-12-22 20:07:34,309] Trial 181 finished with values: [0.0, 0.5538935285684794] and parameters: {'n_neighbors': 6, 'n_components': 12, 'min_dist': 0.19, 'min_cluster_size': 2, 'min_samples': 16, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 10/10 [00:00<00:00, 395.77it/s]

Trial 182: DBCV=0.524, CCC=0.592
[I 2025-12-22 20:07:45,811] Trial 182 finished with values: [0.5924963616455835, 0.5239833745917518] and parameters: {'n_neighbors': 49, 'n_components': 11, 'min_dist': 0.03, 'min_cluster_size': 38, 'min_samples': 19, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 20/20 [00:00<00:00, 403.98it/s]

Trial 183: DBCV=0.596, CCC=0.513
[I 2025-12-22 20:07:54,298] Trial 183 finished with values: [0.5127414067690325, 0.5959827304994888] and parameters: {'n_neighbors': 3, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 10, 'min_samples': 18, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 34/34 [00:00<00:00, 422.08it/s]

Trial 184: DBCV=0.534, CCC=0.452
[I 2025-12-22 20:08:05,843] Trial 184 finished with values: [0.4524724138337207, 0.5336116278307134] and parameters: {'n_neighbors': 46, 'n_components': 11, 'min_dist': 0.16, 'min_cluster_size': 2, 'min_samples': 14, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/107 [00:00<?, ?it/s]
 39%|███▉      | 42/107 [00:00<00:00, 412.40it/s]
100%|██████████| 107/107 [00:00<00:00, 397.16it/s][A

Trial 185: DBCV=0.540, CCC=0.470
[I 2025-12-22 20:08:16,464] Trial 185 finished with values: [0.47005947683872634, 0.5396750918689147] and parameters: {'n_neighbors': 13, 'n_components': 10, 'min_dist': 0.27, 'min_cluster_size': 3, 'min_samples': 4, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/42 [00:00<?, ?it/s]
100%|██████████| 42/42 [00:00<00:00, 398.75it/s]

Trial 186: DBCV=0.539, CCC=0.498
[I 2025-12-22 20:08:26,094] Trial 186 finished with values: [0.4978100339789562, 0.5394428185300085] and parameters: {'n_neighbors': 12, 'n_components': 6, 'min_dist': 0.11, 'min_cluster_size': 12, 'min_samples': 10, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 1/1 [00:00<00:00, 317.77it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 187: DBCV=-0.109, CCC=0.000
[I 2025-12-22 20:08:35,453] Trial 187 finished with values: [0.0, -0.10943776538648417] and parameters: {'n_neighbors': 8, 'n_components': 8, 'min_dist': 0.18, 'min_cluster_size': 44, 'min_samples': 7, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 40/40 [00:00<00:00, 405.51it/s]

Trial 188: DBCV=0.534, CCC=0.549
[I 2025-12-22 20:08:44,967] Trial 188 finished with values: [0.5494297436859864, 0.5341453734062058] and parameters: {'n_neighbors': 8, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 12, 'min_samples': 10, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 9/9 [00:00<00:00, 401.58it/s]

Trial 189: DBCV=0.353, CCC=0.716
[I 2025-12-22 20:08:56,050] Trial 189 finished with values: [0.7160910355411665, 0.3526234648262114] and parameters: {'n_neighbors': 42, 'n_components': 10, 'min_dist': 0.19, 'min_cluster_size': 49, 'min_samples': 10, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 1/1 [00:00<00:00, 236.97it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 190: DBCV=0.379, CCC=0.000
[I 2025-12-22 20:09:06,203] Trial 190 finished with values: [0.0, 0.3792612596382956] and parameters: {'n_neighbors': 24, 'n_components': 4, 'min_dist': 0.21, 'min_cluster_size': 23, 'min_samples': 14, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 34/34 [00:00<00:00, 404.71it/s]

Trial 191: DBCV=0.559, CCC=0.535
[I 2025-12-22 20:09:16,108] Trial 191 finished with values: [0.5354661691224221, 0.5591076901347867] and parameters: {'n_neighbors': 24, 'n_components': 4, 'min_dist': 0.21, 'min_cluster_size': 3, 'min_samples': 15, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 13/13 [00:00<00:00, 400.34it/s]

Trial 192: DBCV=0.410, CCC=0.653
[I 2025-12-22 20:09:26,846] Trial 192 finished with values: [0.6527490758317319, 0.4099156611802877] and parameters: {'n_neighbors': 24, 'n_components': 12, 'min_dist': 0.04, 'min_cluster_size': 41, 'min_samples': 16, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 3/3 [00:00<00:00, 268.50it/s]

Trial 193: DBCV=0.330, CCC=0.763
[I 2025-12-22 20:09:36,267] Trial 193 finished with values: [0.7629932933856507, 0.33047107717967056] and parameters: {'n_neighbors': 8, 'n_components': 8, 'min_dist': 0.18, 'min_cluster_size': 22, 'min_samples': 9, 'cluster_selection_epsilon': 0.3}.

100%|██████████| 14/14 [00:00<00:00, 409.35it/s]

Trial 194: DBCV=0.471, CCC=0.515
[I 2025-12-22 20:09:46,861] Trial 194 finished with values: [0.5153075050738103, 0.47100042125908353] and parameters: {'n_neighbors': 23, 'n_components': 12, 'min_dist': 0.1, 'min_cluster_size': 35, 'min_samples': 16, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 17/17 [00:00<00:00, 406.51it/s]

Trial 195: DBCV=0.523, CCC=0.561
[I 2025-12-22 20:09:55,993] Trial 195 finished with values: [0.5606935233829072, 0.5233715449009069] and parameters: {'n_neighbors': 6, 'n_components': 12, 'min_dist': 0.11, 'min_cluster_size': 29, 'min_samples': 17, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 38/38 [00:00<00:00, 407.60it/s]

Trial 196: DBCV=0.591, CCC=0.477
[I 2025-12-22 20:10:06,151] Trial 196 finished with values: [0.47712784279883447, 0.5906059249797305] and parameters: {'n_neighbors': 11, 'n_components': 14, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 15, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 14/14 [00:00<00:00, 406.11it/s]

Trial 197: DBCV=0.269, CCC=0.574
[I 2025-12-22 20:10:17,723] Trial 197 finished with values: [0.5739284414699762, 0.26929736260593456] and parameters: {'n_neighbors': 47, 'n_components': 12, 'min_dist': 0.11, 'min_cluster_size': 28, 'min_samples': 12, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 23/23 [00:00<00:00, 391.97it/s]

Trial 198: DBCV=0.519, CCC=0.614
[I 2025-12-22 20:10:27,083] Trial 198 finished with values: [0.6144406042388725, 0.5191612541506162] and parameters: {'n_neighbors': 7, 'n_components': 13, 'min_dist': 0.16, 'min_cluster_size': 28, 'min_samples': 12, 'cluster_selection_epsilon': 0.24}.

100%|██████████| 2/2 [00:00<00:00, 311.52it/s]

Trial 199: DBCV=0.309, CCC=0.824
[I 2025-12-22 20:10:38,071] Trial 199 finished with values: [0.8240623356293533, 0.30892144315173437] and parameters: {'n_neighbors': 18, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 17, 'min_samples': 12, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 17/17 [00:00<00:00, 404.56it/s]

Trial 200: DBCV=0.523, CCC=0.561
[I 2025-12-22 20:10:47,183] Trial 200 finished with values: [0.5606935233829072, 0.5233715449009069] and parameters: {'n_neighbors': 6, 'n_components': 12, 'min_dist': 0.11, 'min_cluster_size': 29, 'min_samples': 17, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 2/2 [00:00<00:00, 275.14it/s]

Trial 201: DBCV=0.620, CCC=0.827
[I 2025-12-22 20:10:58,097] Trial 201 finished with values: [0.8269448086205721, 0.6198184527308173] and parameters: {'n_neighbors': 18, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 14, 'min_samples': 15, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 12/12 [00:00<00:00, 405.40it/s]

Trial 202: DBCV=0.462, CCC=0.520
[I 2025-12-22 20:11:09,888] Trial 202 finished with values: [0.520499442517307, 0.4622397103816323] and parameters: {'n_neighbors': 42, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 28, 'min_samples': 15, 'cluster_selection_epsilon': 0.08}.

  0%|          | 0/90 [00:00<?, ?it/s]
 47%|████▋     | 42/90 [00:00<00:00, 417.70it/s]
100%|██████████| 90/90 [00:00<00:00, 401.75it/s]

Trial 203: DBCV=0.622, CCC=0.489
[I 2025-12-22 20:11:19,810] Trial 203 finished with values: [0.4890345620569363, 0.6219924501863642] and parameters: {'n_neighbors': 12, 'n_components': 4, 'min_dist': 0.06, 'min_cluster_size': 3, 'min_samples': 7, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 20/20 [00:00<00:00, 406.47it/s]

Trial 204: DBCV=0.596, CCC=0.513
[I 2025-12-22 20:11:28,314] Trial 204 finished with values: [0.5127414067690325, 0.5959827304994888] and parameters: {'n_neighbors': 3, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 20, 'min_samples': 18, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 17/17 [00:00<00:00, 380.03it/s]

Trial 205: DBCV=0.518, CCC=0.472
[I 2025-12-22 20:11:38,926] Trial 205 finished with values: [0.47211488124507106, 0.5179522703988056] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.03, 'min_cluster_size': 28, 'min_samples': 19, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 35/35 [00:00<00:00, 415.95it/s]

Trial 206: DBCV=0.581, CCC=0.491
[I 2025-12-22 20:11:47,674] Trial 206 finished with values: [0.49093984395795265, 0.5805575426112953] and parameters: {'n_neighbors': 3, 'n_components': 13, 'min_dist': 0.05, 'min_cluster_size': 20, 'min_samples': 10, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 10/10 [00:00<00:00, 404.81it/s]

Trial 207: DBCV=0.398, CCC=0.576
[I 2025-12-22 20:11:58,836] Trial 207 finished with values: [0.5759430980209737, 0.3976792767928413] and parameters: {'n_neighbors': 34, 'n_components': 12, 'min_dist': 0.19, 'min_cluster_size': 36, 'min_samples': 14, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 2/2 [00:00<00:00, 352.00it/s]

Trial 208: DBCV=0.620, CCC=0.827
[I 2025-12-22 20:12:09,506] Trial 208 finished with values: [0.8269448086205721, 0.6198184527308173] and parameters: {'n_neighbors': 18, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 12, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/80 [00:00<?, ?it/s]
100%|██████████| 80/80 [00:00<00:00, 396.92it/s]

Trial 209: DBCV=0.346, CCC=0.426
[I 2025-12-22 20:12:20,391] Trial 209 finished with values: [0.426332377600209, 0.34624627847980427] and parameters: {'n_neighbors': 24, 'n_components': 7, 'min_dist': 0.21, 'min_cluster_size': 3, 'min_samples': 3, 'cluster_selection_epsilon': 0.3}.

  0%|          | 0/52 [00:00<?, ?it/s]
100%|██████████| 52/52 [00:00<00:00, 386.04it/s]

Trial 210: DBCV=0.511, CCC=0.542
[I 2025-12-22 20:12:30,823] Trial 210 finished with values: [0.5419198449201924, 0.5113100361748061] and parameters: {'n_neighbors': 15, 'n_components': 12, 'min_dist': 0.06, 'min_cluster_size': 12, 'min_samples': 5, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 14/14 [00:00<00:00, 373.08it/s]

Trial 211: DBCV=0.470, CCC=0.548
[I 2025-12-22 20:12:42,773] Trial 211 finished with values: [0.5481824621179742, 0.469784262746283] and parameters: {'n_neighbors': 46, 'n_components': 14, 'min_dist': 0.11, 'min_cluster_size': 29, 'min_samples': 17, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 1/1 [00:00<00:00, 256.55it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 212: DBCV=0.457, CCC=0.000
[I 2025-12-22 20:12:54,863] Trial 212 finished with values: [0.0, 0.45675598716991933] and parameters: {'n_neighbors': 42, 'n_components': 14, 'min_dist': 0.24, 'min_cluster_size': 14, 'min_samples': 19, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 28/28 [00:00<00:00, 398.00it/s]

Trial 213: DBCV=0.587, CCC=0.552
[I 2025-12-22 20:13:04,410] Trial 213 finished with values: [0.5521774165342047, 0.5871218043909705] and parameters: {'n_neighbors': 12, 'n_components': 8, 'min_dist': 0.07, 'min_cluster_size': 20, 'min_samples': 16, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 8/8 [00:00<00:00, 407.26it/s]

Trial 214: DBCV=0.424, CCC=0.701
[I 2025-12-22 20:13:14,839] Trial 214 finished with values: [0.7014661864371355, 0.4236263202028899] and parameters: {'n_neighbors': 31, 'n_components': 6, 'min_dist': 0.21, 'min_cluster_size': 48, 'min_samples': 18, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 20/20 [00:00<00:00, 415.41it/s]

Trial 215: DBCV=0.493, CCC=0.543
[I 2025-12-22 20:13:26,910] Trial 215 finished with values: [0.5434256887495807, 0.4925930931572423] and parameters: {'n_neighbors': 46, 'n_components': 14, 'min_dist': 0.2, 'min_cluster_size': 16, 'min_samples': 14, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 1/1 [00:00<00:00, 283.30it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 216: DBCV=0.425, CCC=0.000
[I 2025-12-22 20:13:38,188] Trial 216 finished with values: [0.0, 0.4245981653938292] and parameters: {'n_neighbors': 23, 'n_components': 14, 'min_dist': 0.19, 'min_cluster_size': 14, 'min_samples': 15, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 40/40 [00:00<00:00, 419.67it/s]

Trial 217: DBCV=0.513, CCC=0.564
[I 2025-12-22 20:13:48,607] Trial 217 finished with values: [0.5638416902219625, 0.5130355952001855] and parameters: {'n_neighbors': 13, 'n_components': 14, 'min_dist': 0.04, 'min_cluster_size': 14, 'min_samples': 9, 'cluster_selection_epsilon': 0.12}.

  0%|          | 0/43 [00:00<?, ?it/s]
100%|██████████| 43/43 [00:00<00:00, 404.99it/s]

Trial 218: DBCV=0.584, CCC=0.480
[I 2025-12-22 20:13:58,895] Trial 218 finished with values: [0.48049666630207594, 0.5835052361827546] and parameters: {'n_neighbors': 12, 'n_components': 14, 'min_dist': 0.06, 'min_cluster_size': 2, 'min_samples': 15, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 2/2 [00:00<00:00, 252.91it/s]

Trial 219: DBCV=0.514, CCC=0.827
[I 2025-12-22 20:14:10,170] Trial 219 finished with values: [0.8269448086205721, 0.514285200469584] and parameters: {'n_neighbors': 22, 'n_components': 14, 'min_dist': 0.2, 'min_cluster_size': 17, 'min_samples': 11, 'cluster_selection_epsilon': 0.29}.

100%|██████████| 28/28 [00:00<00:00, 399.32it/s]

Trial 220: DBCV=0.316, CCC=0.554
[I 2025-12-22 20:14:19,974] Trial 220 finished with values: [0.5539639886733778, 0.31628221811438945] and parameters: {'n_neighbors': 14, 'n_components': 7, 'min_dist': 0.24, 'min_cluster_size': 24, 'min_samples': 9, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 1/1 [00:00<00:00, 293.97it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 221: DBCV=0.129, CCC=0.000
[I 2025-12-22 20:14:31,363] Trial 221 finished with values: [0.0, 0.12928324564020222] and parameters: {'n_neighbors': 25, 'n_components': 14, 'min_dist': 0.06, 'min_cluster_size': 22, 'min_samples': 16, 'cluster_selection_epsilon': 0.22}.

  0%|          | 0/70 [00:00<?, ?it/s]
100%|██████████| 70/70 [00:00<00:00, 403.00it/s]

Trial 222: DBCV=0.555, CCC=0.487
[I 2025-12-22 20:14:41,471] Trial 222 finished with values: [0.4870601692238848, 0.5554839181596865] and parameters: {'n_neighbors': 11, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 9, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 33/33 [00:00<00:00, 398.35it/s]

Trial 223: DBCV=0.652, CCC=0.497
[I 2025-12-22 20:14:49,981] Trial 223 finished with values: [0.49715456828145854, 0.6516199437844129] and parameters: {'n_neighbors': 3, 'n_components': 11, 'min_dist': 0.0, 'min_cluster_size': 10, 'min_samples': 19, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 9/9 [00:00<00:00, 402.79it/s]

Trial 224: DBCV=0.367, CCC=0.728
[I 2025-12-22 20:14:59,956] Trial 224 finished with values: [0.7276306510625382, 0.3672567615186126] and parameters: {'n_neighbors': 22, 'n_components': 6, 'min_dist': 0.2, 'min_cluster_size': 44, 'min_samples': 11, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 9/9 [00:00<00:00, 401.84it/s]

Trial 225: DBCV=0.445, CCC=0.710
[I 2025-12-22 20:15:11,608] Trial 225 finished with values: [0.7100324364217889, 0.4452778781779402] and parameters: {'n_neighbors': 31, 'n_components': 15, 'min_dist': 0.2, 'min_cluster_size': 47, 'min_samples': 11, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 2/2 [00:00<00:00, 337.71it/s]

Trial 226: DBCV=0.404, CCC=0.825
[I 2025-12-22 20:15:21,326] Trial 226 finished with values: [0.8249446208630905, 0.4042942595679105] and parameters: {'n_neighbors': 11, 'n_components': 8, 'min_dist': 0.23, 'min_cluster_size': 2, 'min_samples': 15, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 1/1 [00:00<00:00, 324.59it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 227: DBCV=-0.277, CCC=0.000
[I 2025-12-22 20:15:32,033] Trial 227 finished with values: [0.0, -0.276786021313452] and parameters: {'n_neighbors': 47, 'n_components': 3, 'min_dist': 0.25, 'min_cluster_size': 3, 'min_samples': 15, 'cluster_selection_epsilon': 0.13}.

100%|██████████| 31/31 [00:00<00:00, 397.62it/s]

Trial 228: DBCV=0.592, CCC=0.478
[I 2025-12-22 20:15:42,357] Trial 228 finished with values: [0.4784674072359487, 0.5918940998602963] and parameters: {'n_neighbors': 18, 'n_components': 11, 'min_dist': 0.3, 'min_cluster_size': 2, 'min_samples': 16, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 9/9 [00:00<00:00, 401.64it/s]

Trial 229: DBCV=0.412, CCC=0.640
[I 2025-12-22 20:15:52,744] Trial 229 finished with values: [0.6398322693883363, 0.4122920777254947] and parameters: {'n_neighbors': 30, 'n_components': 8, 'min_dist': 0.1, 'min_cluster_size': 42, 'min_samples': 16, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 20/20 [00:00<00:00, 409.08it/s]

Trial 230: DBCV=0.572, CCC=0.603
[I 2025-12-22 20:16:01,387] Trial 230 finished with values: [0.6030362926895455, 0.5722407554241242] and parameters: {'n_neighbors': 4, 'n_components': 10, 'min_dist': 0.05, 'min_cluster_size': 32, 'min_samples': 16, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 2/2 [00:00<00:00, 338.17it/s]

Trial 231: DBCV=-0.114, CCC=0.846
[I 2025-12-22 20:16:12,445] Trial 231 finished with values: [0.8458483776196606, -0.11355351049809652] and parameters: {'n_neighbors': 34, 'n_components': 7, 'min_dist': 0.21, 'min_cluster_size': 14, 'min_samples': 15, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 15/15 [00:00<00:00, 409.09it/s]

Trial 232: DBCV=0.546, CCC=0.526
[I 2025-12-22 20:16:22,145] Trial 232 finished with values: [0.5258351915190904, 0.546213461849406] and parameters: {'n_neighbors': 12, 'n_components': 9, 'min_dist': 0.11, 'min_cluster_size': 29, 'min_samples': 16, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 2/2 [00:00<00:00, 326.74it/s]

Trial 233: DBCV=0.079, CCC=0.824
[I 2025-12-22 20:16:33,011] Trial 233 finished with values: [0.8243195397671446, 0.07860479637128946] and parameters: {'n_neighbors': 31, 'n_components': 8, 'min_dist': 0.21, 'min_cluster_size': 14, 'min_samples': 15, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 7/7 [00:00<00:00, 397.05it/s]

Trial 234: DBCV=0.474, CCC=0.734
[I 2025-12-22 20:16:44,834] Trial 234 finished with values: [0.7338564685306357, 0.47407791126662885] and parameters: {'n_neighbors': 42, 'n_components': 14, 'min_dist': 0.22, 'min_cluster_size': 50, 'min_samples': 15, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 9/9 [00:00<00:00, 404.01it/s]

Trial 235: DBCV=0.348, CCC=0.597
[I 2025-12-22 20:16:55,240] Trial 235 finished with values: [0.5974048546820045, 0.34849043728965595] and parameters: {'n_neighbors': 31, 'n_components': 6, 'min_dist': 0.3, 'min_cluster_size': 48, 'min_samples': 15, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 10/10 [00:00<00:00, 356.11it/s]

Trial 236: DBCV=-0.068, CCC=0.686
[I 2025-12-22 20:17:04,530] Trial 236 finished with values: [0.6864658254332991, -0.06788926502164994] and parameters: {'n_neighbors': 12, 'n_components': 4, 'min_dist': 0.19, 'min_cluster_size': 47, 'min_samples': 2, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 1/1 [00:00<00:00, 325.22it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 237: DBCV=0.202, CCC=0.000
[I 2025-12-22 20:17:15,633] Trial 237 finished with values: [0.0, 0.20232271350894743] and parameters: {'n_neighbors': 42, 'n_components': 6, 'min_dist': 0.24, 'min_cluster_size': 12, 'min_samples': 19, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 29/29 [00:00<00:00, 418.42it/s]

Trial 238: DBCV=0.629, CCC=0.517
[I 2025-12-22 20:17:24,356] Trial 238 finished with values: [0.5169995765156347, 0.6291463250173898] and parameters: {'n_neighbors': 4, 'n_components': 12, 'min_dist': 0.18, 'min_cluster_size': 10, 'min_samples': 16, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 2/2 [00:00<00:00, 218.74it/s]

Trial 239: DBCV=0.518, CCC=0.827
[I 2025-12-22 20:17:34,895] Trial 239 finished with values: [0.8269448086205721, 0.5181670785183855] and parameters: {'n_neighbors': 18, 'n_components': 11, 'min_dist': 0.21, 'min_cluster_size': 2, 'min_samples': 15, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 13/13 [00:00<00:00, 407.76it/s]

Trial 240: DBCV=0.457, CCC=0.636
[I 2025-12-22 20:17:44,235] Trial 240 finished with values: [0.63649165333815, 0.45703092876926654] and parameters: {'n_neighbors': 7, 'n_components': 13, 'min_dist': 0.16, 'min_cluster_size': 36, 'min_samples': 14, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 2/2 [00:00<00:00, 274.15it/s]

Trial 241: DBCV=0.358, CCC=0.825
[I 2025-12-22 20:17:55,153] Trial 241 finished with values: [0.8245950852855517, 0.35754999155179634] and parameters: {'n_neighbors': 24, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 3, 'min_samples': 10, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 2/2 [00:00<00:00, 279.82it/s]

Trial 242: DBCV=-0.068, CCC=0.845
[I 2025-12-22 20:18:05,960] Trial 242 finished with values: [0.8452825497597842, -0.06785121364052056] and parameters: {'n_neighbors': 34, 'n_components': 6, 'min_dist': 0.2, 'min_cluster_size': 14, 'min_samples': 11, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 2/2 [00:00<00:00, 318.85it/s]

Trial 243: DBCV=0.321, CCC=0.825
[I 2025-12-22 20:18:16,879] Trial 243 finished with values: [0.8251043134062207, 0.32131092451776755] and parameters: {'n_neighbors': 24, 'n_components': 11, 'min_dist': 0.21, 'min_cluster_size': 3, 'min_samples': 15, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 14/14 [00:00<00:00, 410.44it/s]

Trial 244: DBCV=0.497, CCC=0.597
[I 2025-12-22 20:18:28,027] Trial 244 finished with values: [0.5972047280226169, 0.49737159411889786] and parameters: {'n_neighbors': 34, 'n_components': 12, 'min_dist': 0.2, 'min_cluster_size': 27, 'min_samples': 11, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 2/2 [00:00<00:00, 213.84it/s]

Trial 245: DBCV=-0.317, CCC=0.859
[I 2025-12-22 20:18:38,249] Trial 245 finished with values: [0.8594599311336539, -0.3169512777351452] and parameters: {'n_neighbors': 34, 'n_components': 2, 'min_dist': 0.06, 'min_cluster_size': 14, 'min_samples': 16, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 36/36 [00:00<00:00, 395.86it/s]

Trial 246: DBCV=0.493, CCC=0.519
[I 2025-12-22 20:18:48,114] Trial 246 finished with values: [0.5190473452287307, 0.49342677153330033] and parameters: {'n_neighbors': 14, 'n_components': 7, 'min_dist': 0.15, 'min_cluster_size': 14, 'min_samples': 9, 'cluster_selection_epsilon': 0.12}.

  0%|          | 0/73 [00:00<?, ?it/s]
100%|██████████| 73/73 [00:00<00:00, 399.98it/s]

Trial 247: DBCV=0.339, CCC=0.569
[I 2025-12-22 20:18:59,647] Trial 247 finished with values: [0.5685687914296531, 0.3386088953077268] and parameters: {'n_neighbors': 49, 'n_components': 8, 'min_dist': 0.07, 'min_cluster_size': 8, 'min_samples': 2, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 29/29 [00:00<00:00, 398.95it/s]

Trial 248: DBCV=0.554, CCC=0.514
[I 2025-12-22 20:19:10,161] Trial 248 finished with values: [0.513763450788376, 0.5537078349107809] and parameters: {'n_neighbors': 31, 'n_components': 6, 'min_dist': 0.06, 'min_cluster_size': 14, 'min_samples': 15, 'cluster_selection_epsilon': 0.06}.

  0%|          | 0/67 [00:00<?, ?it/s]
100%|██████████| 67/67 [00:00<00:00, 397.00it/s]

Trial 249: DBCV=0.552, CCC=0.485
[I 2025-12-22 20:19:20,829] Trial 249 finished with values: [0.48495972840555046, 0.551712188726389] and parameters: {'n_neighbors': 18, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 9, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 230.81it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 250: DBCV=-0.448, CCC=0.000
[I 2025-12-22 20:19:30,705] Trial 250 finished with values: [0.0, -0.44820848972597954] and parameters: {'n_neighbors': 24, 'n_components': 2, 'min_dist': 0.19, 'min_cluster_size': 41, 'min_samples': 10, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 1/1 [00:00<00:00, 284.05it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 251: DBCV=0.252, CCC=0.000
[I 2025-12-22 20:19:40,943] Trial 251 finished with values: [0.0, 0.25239650811765624] and parameters: {'n_neighbors': 24, 'n_components': 4, 'min_dist': 0.18, 'min_cluster_size': 20, 'min_samples': 18, 'cluster_selection_epsilon': 0.08}.

  0%|          | 0/31 [00:00<?, ?it/s]
100%|██████████| 31/31 [00:00<00:00, 221.12it/s]

Trial 252: DBCV=0.640, CCC=0.436
[I 2025-12-22 20:19:49,546] Trial 252 finished with values: [0.4364313328428677, 0.6399706313768437] and parameters: {'n_neighbors': 3, 'n_components': 8, 'min_dist': 0.0, 'min_cluster_size': 20, 'min_samples': 19, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 2/2 [00:00<00:00, 319.41it/s]

Trial 253: DBCV=0.336, CCC=0.824
[I 2025-12-22 20:20:00,661] Trial 253 finished with values: [0.8239054413706746, 0.33568625679981867] and parameters: {'n_neighbors': 24, 'n_components': 12, 'min_dist': 0.16, 'min_cluster_size': 14, 'min_samples': 16, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 35/35 [00:00<00:00, 402.41it/s]

Trial 254: DBCV=0.659, CCC=0.427
[I 2025-12-22 20:20:09,506] Trial 254 finished with values: [0.42659425964038566, 0.6587026554227777] and parameters: {'n_neighbors': 4, 'n_components': 12, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 16, 'cluster_selection_epsilon': 0.19}.

100%|██████████| 9/9 [00:00<00:00, 394.37it/s]

Trial 255: DBCV=0.227, CCC=0.702
[I 2025-12-22 20:20:19,836] Trial 255 finished with values: [0.7019078877657456, 0.2265647159090308] and parameters: {'n_neighbors': 23, 'n_components': 8, 'min_dist': 0.19, 'min_cluster_size': 43, 'min_samples': 7, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 29/29 [00:00<00:00, 398.72it/s]

Trial 256: DBCV=0.569, CCC=0.550
[I 2025-12-22 20:20:29,663] Trial 256 finished with values: [0.5502913888507102, 0.5688694222130438] and parameters: {'n_neighbors': 12, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 6, 'min_samples': 16, 'cluster_selection_epsilon': 0.16}.

100%|██████████| 16/16 [00:00<00:00, 342.77it/s]

Trial 257: DBCV=0.545, CCC=0.668
[I 2025-12-22 20:20:38,053] Trial 257 finished with values: [0.6682011397999937, 0.5452769309872646] and parameters: {'n_neighbors': 3, 'n_components': 8, 'min_dist': 0.18, 'min_cluster_size': 10, 'min_samples': 18, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 11/11 [00:00<00:00, 348.89it/s]

Trial 258: DBCV=0.300, CCC=0.525
[I 2025-12-22 20:20:49,259] Trial 258 finished with values: [0.5249498731133323, 0.3003699436201878] and parameters: {'n_neighbors': 49, 'n_components': 7, 'min_dist': 0.26, 'min_cluster_size': 20, 'min_samples': 18, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 14/14 [00:00<00:00, 408.83it/s]

Trial 259: DBCV=0.194, CCC=0.528
[I 2025-12-22 20:20:59,889] Trial 259 finished with values: [0.5278592916128445, 0.19432916671367176] and parameters: {'n_neighbors': 49, 'n_components': 4, 'min_dist': 0.03, 'min_cluster_size': 38, 'min_samples': 7, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 37/37 [00:00<00:00, 402.23it/s]

Trial 260: DBCV=0.616, CCC=0.555
[I 2025-12-22 20:21:08,809] Trial 260 finished with values: [0.5547565862219159, 0.616414321313765] and parameters: {'n_neighbors': 4, 'n_components': 13, 'min_dist': 0.05, 'min_cluster_size': 2, 'min_samples': 16, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 28/28 [00:00<00:00, 396.76it/s]

Trial 261: DBCV=0.557, CCC=0.529
[I 2025-12-22 20:21:18,867] Trial 261 finished with values: [0.5293639718357428, 0.5569615744628577] and parameters: {'n_neighbors': 11, 'n_components': 14, 'min_dist': 0.01, 'min_cluster_size': 22, 'min_samples': 15, 'cluster_selection_epsilon': 0.08}.

  0%|          | 0/59 [00:00<?, ?it/s]
100%|██████████| 59/59 [00:00<00:00, 399.45it/s]

Trial 262: DBCV=0.549, CCC=0.480
[I 2025-12-22 20:21:29,009] Trial 262 finished with values: [0.4803470845599103, 0.54855652412928] and parameters: {'n_neighbors': 18, 'n_components': 6, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 11, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 16/16 [00:00<00:00, 374.65it/s]

Trial 263: DBCV=0.481, CCC=0.556
[I 2025-12-22 20:21:39,713] Trial 263 finished with values: [0.5562441960077538, 0.4813245988873859] and parameters: {'n_neighbors': 18, 'n_components': 14, 'min_dist': 0.21, 'min_cluster_size': 26, 'min_samples': 11, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/41 [00:00<?, ?it/s]
100%|██████████| 41/41 [00:00<00:00, 397.84it/s]

Trial 264: DBCV=0.530, CCC=0.545
[I 2025-12-22 20:21:50,015] Trial 264 finished with values: [0.5454382735382094, 0.5300852841255034] and parameters: {'n_neighbors': 12, 'n_components': 14, 'min_dist': 0.06, 'min_cluster_size': 14, 'min_samples': 7, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 2/2 [00:00<00:00, 340.61it/s]

Trial 265: DBCV=-0.317, CCC=0.859
[I 2025-12-22 20:22:00,372] Trial 265 finished with values: [0.8594599311336539, -0.3169512777351452] and parameters: {'n_neighbors': 34, 'n_components': 2, 'min_dist': 0.06, 'min_cluster_size': 14, 'min_samples': 16, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 11/11 [00:00<00:00, 359.91it/s]

Trial 266: DBCV=0.476, CCC=0.618
[I 2025-12-22 20:22:11,884] Trial 266 finished with values: [0.6175838494794966, 0.4762719455528121] and parameters: {'n_neighbors': 49, 'n_components': 11, 'min_dist': 0.06, 'min_cluster_size': 38, 'min_samples': 16, 'cluster_selection_epsilon': 0.25}.

100%|██████████| 11/11 [00:00<00:00, 361.09it/s]

Trial 267: DBCV=0.433, CCC=0.567
[I 2025-12-22 20:22:22,512] Trial 267 finished with values: [0.5671299789993811, 0.4326971522220367] and parameters: {'n_neighbors': 23, 'n_components': 12, 'min_dist': 0.25, 'min_cluster_size': 35, 'min_samples': 17, 'cluster_selection_epsilon': 0.18}.

  0%|          | 0/63 [00:00<?, ?it/s]
100%|██████████| 63/63 [00:00<00:00, 409.80it/s]

Trial 268: DBCV=0.593, CCC=0.508
[I 2025-12-22 20:22:32,781] Trial 268 finished with values: [0.5084484818397299, 0.5934909207333958] and parameters: {'n_neighbors': 14, 'n_components': 11, 'min_dist': 0.09, 'min_cluster_size': 3, 'min_samples': 9, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 11/11 [00:00<00:00, 404.09it/s]

Trial 269: DBCV=0.385, CCC=0.603
[I 2025-12-22 20:22:42,867] Trial 269 finished with values: [0.6031141274215367, 0.38473711754494194] and parameters: {'n_neighbors': 18, 'n_components': 9, 'min_dist': 0.19, 'min_cluster_size': 29, 'min_samples': 12, 'cluster_selection_epsilon': 0.04}.

100%|██████████| 11/11 [00:00<00:00, 409.83it/s]

Trial 270: DBCV=0.465, CCC=0.544
[I 2025-12-22 20:22:54,470] Trial 270 finished with values: [0.5439766337302729, 0.46497243998550447] and parameters: {'n_neighbors': 49, 'n_components': 12, 'min_dist': 0.03, 'min_cluster_size': 38, 'min_samples': 19, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 40/40 [00:00<00:00, 405.49it/s]

Trial 271: DBCV=0.513, CCC=0.564
[I 2025-12-22 20:23:04,946] Trial 271 finished with values: [0.5638416902219625, 0.5130355952001855] and parameters: {'n_neighbors': 13, 'n_components': 14, 'min_dist': 0.04, 'min_cluster_size': 14, 'min_samples': 9, 'cluster_selection_epsilon': 0.09}.

  0%|          | 0/66 [00:00<?, ?it/s]
100%|██████████| 66/66 [00:00<00:00, 394.81it/s]

Trial 272: DBCV=0.572, CCC=0.525
[I 2025-12-22 20:23:15,078] Trial 272 finished with values: [0.5251494641410055, 0.5718876337599017] and parameters: {'n_neighbors': 14, 'n_components': 7, 'min_dist': 0.16, 'min_cluster_size': 3, 'min_samples': 9, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 35/35 [00:00<00:00, 404.09it/s]

Trial 273: DBCV=0.491, CCC=0.584
[I 2025-12-22 20:23:23,871] Trial 273 finished with values: [0.5837452223527304, 0.49064906120822405] and parameters: {'n_neighbors': 7, 'n_components': 3, 'min_dist': 0.16, 'min_cluster_size': 14, 'min_samples': 12, 'cluster_selection_epsilon': 0.01}.

100%|██████████| 10/10 [00:00<00:00, 351.00it/s]

Trial 274: DBCV=0.252, CCC=0.546
[I 2025-12-22 20:23:35,275] Trial 274 finished with values: [0.5456423316564437, 0.2516253874025828] and parameters: {'n_neighbors': 44, 'n_components': 11, 'min_dist': 0.03, 'min_cluster_size': 44, 'min_samples': 7, 'cluster_selection_epsilon': 0.07}.

100%|██████████| 2/2 [00:00<00:00, 336.07it/s]

Trial 275: DBCV=0.464, CCC=0.827
[I 2025-12-22 20:23:46,152] Trial 275 finished with values: [0.8269448086205721, 0.46359863160494524] and parameters: {'n_neighbors': 22, 'n_components': 11, 'min_dist': 0.13, 'min_cluster_size': 17, 'min_samples': 11, 'cluster_selection_epsilon': 0.21}.

  0%|          | 0/45 [00:00<?, ?it/s]
100%|██████████| 45/45 [00:00<00:00, 394.04it/s]

Trial 276: DBCV=0.293, CCC=0.485
[I 2025-12-22 20:23:57,535] Trial 276 finished with values: [0.4849065723696361, 0.2926826945765101] and parameters: {'n_neighbors': 24, 'n_components': 14, 'min_dist': 0.19, 'min_cluster_size': 14, 'min_samples': 2, 'cluster_selection_epsilon': 0.12}.

  0%|          | 0/66 [00:00<?, ?it/s]
100%|██████████| 66/66 [00:00<00:00, 398.23it/s]

Trial 277: DBCV=0.600, CCC=0.424
[I 2025-12-22 20:24:08,168] Trial 277 finished with values: [0.42427636323028023, 0.6002747525307219] and parameters: {'n_neighbors': 12, 'n_components': 14, 'min_dist': 0.06, 'min_cluster_size': 2, 'min_samples': 9, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 12/12 [00:00<00:00, 373.32it/s]

Trial 278: DBCV=0.489, CCC=0.611
[I 2025-12-22 20:24:18,823] Trial 278 finished with values: [0.6112988387675299, 0.48921665808609394] and parameters: {'n_neighbors': 34, 'n_components': 8, 'min_dist': 0.06, 'min_cluster_size': 38, 'min_samples': 19, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 2/2 [00:00<00:00, 239.28it/s]

Trial 279: DBCV=0.130, CCC=0.834
[I 2025-12-22 20:24:28,775] Trial 279 finished with values: [0.8336582592350268, 0.12962594939806082] and parameters: {'n_neighbors': 8, 'n_components': 14, 'min_dist': 0.24, 'min_cluster_size': 2, 'min_samples': 9, 'cluster_selection_epsilon': 0.06}.

100%|██████████| 37/37 [00:00<00:00, 403.21it/s]

Trial 280: DBCV=0.566, CCC=0.480
[I 2025-12-22 20:24:37,476] Trial 280 finished with values: [0.47974825903651547, 0.5657769289893093] and parameters: {'n_neighbors': 3, 'n_components': 13, 'min_dist': 0.05, 'min_cluster_size': 20, 'min_samples': 6, 'cluster_selection_epsilon': 0.23}.

100%|██████████| 20/20 [00:00<00:00, 372.19it/s]

Trial 281: DBCV=0.448, CCC=0.570
[I 2025-12-22 20:24:46,787] Trial 281 finished with values: [0.5703150953716284, 0.44769563352418634] and parameters: {'n_neighbors': 7, 'n_components': 11, 'min_dist': 0.11, 'min_cluster_size': 38, 'min_samples': 6, 'cluster_selection_epsilon': 0.24}.

  0%|          | 0/63 [00:00<?, ?it/s]
100%|██████████| 63/63 [00:00<00:00, 408.39it/s]

Trial 282: DBCV=0.593, CCC=0.508
[I 2025-12-22 20:24:57,100] Trial 282 finished with values: [0.5084484818397299, 0.5934909207333958] and parameters: {'n_neighbors': 14, 'n_components': 11, 'min_dist': 0.09, 'min_cluster_size': 3, 'min_samples': 9, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 14/14 [00:00<00:00, 382.46it/s]

Trial 283: DBCV=0.372, CCC=0.507
[I 2025-12-22 20:25:07,091] Trial 283 finished with values: [0.507270312504547, 0.3718418802758203] and parameters: {'n_neighbors': 34, 'n_components': 2, 'min_dist': 0.06, 'min_cluster_size': 35, 'min_samples': 16, 'cluster_selection_epsilon': 0.22}.

100%|██████████| 1/1 [00:00<00:00, 319.25it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 284: DBCV=0.482, CCC=0.000
[I 2025-12-22 20:25:17,651] Trial 284 finished with values: [0.0, 0.48150093741809585] and parameters: {'n_neighbors': 22, 'n_components': 7, 'min_dist': 0.26, 'min_cluster_size': 20, 'min_samples': 18, 'cluster_selection_epsilon': 0.03}.

100%|██████████| 2/2 [00:00<00:00, 332.64it/s]

Trial 285: DBCV=-0.361, CCC=0.888
[I 2025-12-22 20:25:28,126] Trial 285 finished with values: [0.8875719781734257, -0.36086612487439373] and parameters: {'n_neighbors': 24, 'n_components': 8, 'min_dist': 0.19, 'min_cluster_size': 27, 'min_samples': 2, 'cluster_selection_epsilon': 0.0}.

100%|██████████| 26/26 [00:00<00:00, 387.64it/s]

Trial 286: DBCV=0.559, CCC=0.499
[I 2025-12-22 20:25:36,956] Trial 286 finished with values: [0.49908915996685504, 0.5590683347599217] and parameters: {'n_neighbors': 4, 'n_components': 12, 'min_dist': 0.01, 'min_cluster_size': 20, 'min_samples': 17, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 1/1 [00:00<00:00, 282.41it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 287: DBCV=0.153, CCC=0.000
[I 2025-12-22 20:25:45,917] Trial 287 finished with values: [0.0, 0.1530194613856733] and parameters: {'n_neighbors': 4, 'n_components': 12, 'min_dist': 0.24, 'min_cluster_size': 10, 'min_samples': 19, 'cluster_selection_epsilon': 0.21}.

100%|██████████| 2/2 [00:00<00:00, 220.69it/s]

Trial 288: DBCV=-0.268, CCC=0.823
[I 2025-12-22 20:25:56,360] Trial 288 finished with values: [0.8230300901503328, -0.26757351543659735] and parameters: {'n_neighbors': 31, 'n_components': 4, 'min_dist': 0.21, 'min_cluster_size': 13, 'min_samples': 15, 'cluster_selection_epsilon': 0.09}.

100%|██████████| 10/10 [00:00<00:00, 403.07it/s]

Trial 289: DBCV=0.373, CCC=0.497
[I 2025-12-22 20:26:06,301] Trial 289 finished with values: [0.49705169310026015, 0.37273933251026986] and parameters: {'n_neighbors': 24, 'n_components': 5, 'min_dist': 0.21, 'min_cluster_size': 38, 'min_samples': 16, 'cluster_selection_epsilon': 0.02}.

100%|██████████| 16/16 [00:00<00:00, 372.29it/s]

Trial 290: DBCV=0.421, CCC=0.593
[I 2025-12-22 20:26:18,275] Trial 290 finished with values: [0.5932801740963034, 0.4209696654134451] and parameters: {'n_neighbors': 47, 'n_components': 14, 'min_dist': 0.23, 'min_cluster_size': 28, 'min_samples': 11, 'cluster_selection_epsilon': 0.1}.

100%|██████████| 2/2 [00:00<00:00, 316.16it/s]

Trial 291: DBCV=0.668, CCC=0.827
[I 2025-12-22 20:26:29,215] Trial 291 finished with values: [0.8269448086205721, 0.6681129992924271] and parameters: {'n_neighbors': 18, 'n_components': 14, 'min_dist': 0.15, 'min_cluster_size': 8, 'min_samples': 14, 'cluster_selection_epsilon': 0.2}.

100%|██████████| 1/1 [00:00<00:00, 344.67it/s]
/cluster/home/svangelova/Pre-demolition audits/env/lib/python3.11/site-packages/scipy/cluster/hierarchy.py:1715: RuntimeWarning:

invalid value encountered in scalar divide

Trial 292: DBCV=0.019, CCC=0.000
[I 2025-12-22 20:26:39,071] Trial 292 finished with values: [0.0, 0.018887378853162235] and parameters: {'n_neighbors': 8, 'n_components': 14, 'min_dist': 0.18, 'min_cluster_size': 38, 'min_samples': 9, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 23/23 [00:00<00:00, 416.71it/s]

Trial 293: DBCV=0.360, CCC=0.534
[I 2025-12-22 20:26:48,625] Trial 293 finished with values: [0.5344110049836993, 0.36032443414273946] and parameters: {'n_neighbors': 12, 'n_components': 8, 'min_dist': 0.02, 'min_cluster_size': 28, 'min_samples': 6, 'cluster_selection_epsilon': 0.11}.

100%|██████████| 29/29 [00:00<00:00, 388.33it/s]

Trial 294: DBCV=0.552, CCC=0.576
[I 2025-12-22 20:26:58,243] Trial 294 finished with values: [0.5755404472282917, 0.5518942355961435] and parameters: {'n_neighbors': 12, 'n_components': 7, 'min_dist': 0.21, 'min_cluster_size': 14, 'min_samples': 16, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 15/15 [00:00<00:00, 404.36it/s]

Trial 295: DBCV=0.625, CCC=0.628
[I 2025-12-22 20:27:06,743] Trial 295 finished with values: [0.6281671083304605, 0.6245457433673551] and parameters: {'n_neighbors': 3, 'n_components': 13, 'min_dist': 0.06, 'min_cluster_size': 34, 'min_samples': 18, 'cluster_selection_epsilon': 0.08}.

100%|██████████| 21/21 [00:00<00:00, 410.93it/s]

Trial 296: DBCV=0.269, CCC=0.556
[I 2025-12-22 20:27:17,090] Trial 296 finished with values: [0.5556816496003355, 0.2686373812993618] and parameters: {'n_neighbors': 18, 'n_components': 11, 'min_dist': 0.18, 'min_cluster_size': 27, 'min_samples': 2, 'cluster_selection_epsilon': 0.12}.

100%|██████████| 2/2 [00:00<00:00, 342.04it/s]

Trial 297: DBCV=0.091, CCC=0.846
[I 2025-12-22 20:27:28,188] Trial 297 finished with values: [0.8461300517742921, 0.09139580812183298] and parameters: {'n_neighbors': 29, 'n_components': 11, 'min_dist': 0.24, 'min_cluster_size': 13, 'min_samples': 15, 'cluster_selection_epsilon': 0.09}.

  0%|          | 0/79 [00:00<?, ?it/s]
100%|██████████| 79/79 [00:00<00:00, 421.86it/s]

Trial 298: DBCV=0.622, CCC=0.454
[I 2025-12-22 20:27:37,489] Trial 298 finished with values: [0.4540620938095162, 0.6224790900285488] and parameters: {'n_neighbors': 8, 'n_components': 4, 'min_dist': 0.18, 'min_cluster_size': 2, 'min_samples': 9, 'cluster_selection_epsilon': 0.17}.

100%|██████████| 20/20 [00:00<00:00, 406.72it/s]

Trial 299: DBCV=0.536, CCC=0.508
[I 2025-12-22 20:27:45,904] Trial 299 finished with values: [0.5076213382965743, 0.5357827006654664] and parameters: {'n_neighbors': 3, 'n_components': 11, 'min_dist': 0.04, 'min_cluster_size': 24, 'min_samples': 18, 'cluster_selection_epsilon': 0.21}.

In [6]:
df_descriptions = study.trials_dataframe()
df_descriptions.head()

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_cluster_selection_epsilon,params_min_cluster_size,params_min_dist,params_min_samples,params_n_components,params_n_neighbors,user_attrs_ccc_score,user_attrs_dbcv_score,user_attrs_n_clusters,user_attrs_outlier_ratio,system_attrs_NSGAIISampler:generation,state
0,0,0.522948,0.500695,2025-12-22 19:35:36.852208,2025-12-22 19:35:55.056691,0 days 00:00:18.204483,0.23,28,0.22,17,14,42,0.522948,0.500695,13,0.365174,0,COMPLETE
1,1,0.000000,-0.455877,2025-12-22 19:35:55.058261,2025-12-22 19:36:05.322750,0 days 00:00:10.264489,0.27,38,0.20,2,2,42,0.000000,-0.455877,2,0.026866,0,COMPLETE
2,2,0.000000,0.455312,2025-12-22 19:36:05.324867,2025-12-22 19:36:15.839822,0 days 00:00:10.514955,0.09,21,0.21,17,12,17,0.000000,0.455312,2,0.000000,0,COMPLETE
3,3,0.554194,0.261085,2025-12-22 19:36:15.841630,2025-12-22 19:36:25.831557,0 days 00:00:09.989927,0.13,38,0.29,17,3,34,0.554194,0.261085,11,0.424378,0,COMPLETE
4,4,0.666833,0.039449,2025-12-22 19:36:25.833088,2025-12-22 19:36:36.448418,0 days 00:00:10.615330,0.24,44,0.03,2,8,34,0.666833,0.039449,12,0.129851,0,COMPLETE

In [7]:
import joblib
# Save to a file
joblib.dump(study, "02_251222_multi_clusterdata_descriptions_GPT5-nano.pkl")

['02_251222_multi_clusterdata_descriptions_GPT5-nano.pkl']

In [8]:
df_descriptions.to_csv("02_251222_multi_clusterdata_descriptions_GPT5-nano.csv", index=False)

In [9]:
import optuna.visualization as vis

fig = vis.plot_pareto_front(
    study,
    target_names=["CCC Score", "Number of Clusters"], # Names for Obj 0 and Obj 1
    include_dominated_trials=True  # Set to True to see all points, not just the best frontier
)

fig.update_layout(width=600, height=500)
fig.show()